### ISSUE TITLE
Conversions: "mi" not considered a unit, should be!

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1006]
@elohmrow can you fix this?

https://duckduckgo.com/?q=2km+to+mi

**Comment by MrChrisW** [comment]
@moollaza I've lodged a PR that should resolve this [#8](https://github.com/elohmrow/Convert-Pluggable/pull/8)

**Comment by moollaza** [comment]
@MrChrisW wonderful! Thanks a lot :smiley:

**Comment by elohmrow** [comment]
@moollaza it's in there now and uploaded to cpan as C::P-0.027

**Comment by moollaza** [comment]
@elohmrow thanks a lot!

**Comment by killerfish** [comment]
This looks good to close, great work guys
