### ISSUE TITLE
JS Keycodes: getting keycodes via an input field

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/zeroclickinfo-goodies#1013]
I was just looking for some JS keycodes and thought an IA might be useful.

I saw there was already one that is [waiting to be released](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/414), but it only offers results for "keycode tab" and similar.

I was thinking it could be pretty cool to handle queries like "javascript keycodes" and display a textbox like on [this page](http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes), where you press a key and get an instant response. That should be fairly easy to do with some front-end JS.

I don't mind taking this on if you think it's a good idea.

**Comment by mintsoft** [comment]
Sounds cool! Feel free to extend the one that's there :+1:

**Comment by mintsoft** [comment]
@andrey-p Only thing would be; if it's got JS in it for interaction (i.e. like https://duckduckgo.com/?q=timer&ia=timer or https://duckduckgo.com/?q=stopwatch&ia=stopwatch ) then it should be a spice (https://github.com/duckduckgo/zeroclickinfo-spice) rather than a Goodie

**Comment by killerfish** [comment]
As per conversation [here] (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/781), we are to put on hold any goodies with input fields, till custom templates are supported.

**Comment by andrey-p** [comment]
@killerfish Hmm, how about Spice IAs? (see @mintsoft's comment above)

**Comment by killerfish** [comment]
@andrey-p Yea, we can opt for a spice in the meantime, you can go ahead with that, we can always port it as a goodie later on when its possible ^^
