### ISSUE TITLE
Square root of 25 answer is confusing

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#1019]
It's not very clear! 

![image](https://cloud.githubusercontent.com/assets/978048/6320932/ca5de5c2-bae3-11e4-8abd-d1ca87e90f26.png)

Raised from: https://duck.co/forum/thread/12316/square-root-and-other-math-questions

https://duck.co/ia/view/calc_roots

**Comment by moollaza** [comment]
I'm not sure why we have the extra stuff in parens, but I think we should remove it for now. It may also be simplest to use words until we have better support for displaying math (perhaps via MathJax?)

i.e. "square root of 25 = 5", "4th root of 25 = 2.23606797749979"

**Comment by moollaza** [comment]
Looks like this one also needs to be converted to use a structured answer. That way the font will be larger and the parsed query can be re-iterated below as we do for the Calulator IA

**Comment by kfloey** [comment]
@moollaza @mintsoft
>I'm not sure why we have the extra stuff in parens

The stuff in the parens is the square root in simplest form.  You might want to leave it for more complicated answers like the one below, and remove it for exact answers like "square root of 25."

![screenshot from 2015-02-24 14 21 54](https://cloud.githubusercontent.com/assets/9901144/6357199/8fd638b6-bc30-11e4-9f5a-90ddf7f2e99b.png)

**Comment by kfloey** [comment]
I can fix this one, just need to know what you thought about my earlier statement above ^^^

**Comment by moollaza** [comment]
@kfloey I think for now we can remove the simplification, because it's not very clear what it means.

We're currently investigating Goodies that are candidates for the new Goodie Templates, so I'll mention this one to the team. Hopefully we can find a template/design that makes things more obvious here.

@kfloey if you wouldn't mind switching this to a structured answer while you're at it, that would be awesome.

**Comment by mintsoft** [comment]
@kfloey @moollaza I like the simplest form reduction personall, what if it was changed to something like: `root(40) = 2 * root(10) ~ 6.324555`

**Comment by kfloey** [comment]
@moollaza I will get working on that
@mintsoft I agree. I like the reduction and there should be a better way to format it.

Also, I might have found another bug.  If the query is "negative square root of 9" it returns the inverse of the result. 3 becomes 1/3.  I'm not sure that would be the desired or intended answer.

![screenshot from 2015-02-26 09 35 49](https://cloud.githubusercontent.com/assets/9901144/6393755/dd72f878-bd9a-11e4-988a-8c4b9c359f6d.png)

**Comment by moollaza** [comment]
@kfloey that definitely seems like a bug. It should be `-3`

http://www.wolframalpha.com/input/?i=negative%20square%20root%20of%20nine

**Comment by kfloey** [comment]
pull request has been submitted: #1024 

I  still need to fix the negative square root bug though

**Comment by aleksandar-todorovic** [comment]
@kfloey Any update on this?

**Comment by kfloey** [comment]
@aleksandar-todorovic Yep, the changes have been merged and is currently live.  You can check it out at https://duckduckgo.com/?q=square+root+of+25&ia=answer

**Comment by aleksandar-todorovic** [comment]
It seems that the negative square root bug is also fixed ([source](https://duckduckgo.com/?q=negative+square+root+of+25&ia=answer)).

Seems like this issue should be closed now.

**Comment by mintsoft** [comment]
Thanks for the prompt @aleksandar-todorovic
