### ISSUE TITLE
Conversions: Add support for cubits

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#1020]
Not currently a supported unit, however it's been requested: https://duck.co/forum/thread/12316/square-root-and-other-math-questions

------
IA Page: https://duck.co/ia/view/conversions

**Comment by altern8tif** [comment]
@mintsoft I think this requires changes to the Convert::Pluggable module right?  All the units seem to be retrieve via that.

**Comment by mintsoft** [comment]
@altern8tif That is correct!

**Comment by pjhampton** [comment]
Closing for now.
