### ISSUE TITLE
Calculator doesn't work with some valid queries

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-goodies#1026]
e.g. 

Search for "(0.4e^(0))*cos(0)"

https://duck.co/ia/view/calculator

**Update:** See https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1026#issuecomment-76492136

**Comment by jagtalon** [comment]
`cos` and `e` should work https://duckduckgo.com/?q=cos(e)&ia=answer but this specific query doesn't.

**Comment by mintsoft** [comment]
Actually `(e ^ (0)) * cos(0)` works: https://duckduckgo.com/?q=(e%5E(0))*cos(0)&ia=answer

**Comment by puskin94** [comment]
I was reading the code trying to figure out the problem and I have a doubt: Why `[0-9 \. ,]*` instead of `/\d+\.?\d*/` ?

**Comment by mintsoft** [comment]
@puskin94 In mainland Europe numbers are formatted as `1.234,00`; in other cultures `1 000 000` is used instead of `1,000,000`

**Comment by puskin94** [comment]
@mintsoft I think the problem is here ( line 122 )
`my ($amount, $from, $alt_amount, $to) = ($1, $2, $3, $4 || '');`
`$amount` will be cutted if it contains spaces... right?
