### ISSUE TITLE
Pi: Make it work with π

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1037]
Such as "60 digits of π"

https://duck.co/ia/view/pi

**Comment by marianosimone** [comment]
Strangely enough, there's a test to support this (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Pi.t#L20), but it seems like when it's running on the server, it's not matching.

Might be related to encodings?

**Comment by mintsoft** [comment]
@marianosimone You're right, although there isn't a specific test for queries of this pattern; personally I assumed it wasn't implemented because it isn't tested!

Fixing the problem might be as simple as adding `use utf8;` into the `.pm` and the `.t` !
