### ISSUE TITLE
GuitarChords: Regex for chord check needs to be tightened

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1039]
Just noticed a couple edge cases that should be addressed.

The regex only checks for "min" or "maj" but doesn't use word boundaries so "guitar chord fminute" would trigger the IA and show the "F Minor" chord.

https://moollaza.duckduckgo.com/?q=guitar+chord+fminute&ia=answer

Worse is that we don't check for any letters or words after the matched chord name, e.g. "minor" or "major" as a word *after* the chord name, so "guitar chord f minor" actually show an F Major chord. This is a false positive which is really bad! 

Similalry "Guitar chord finder" shows an "F" chord because we matched on "guitar chord f". We need to add word boundaries.

https://moollaza.duckduckgo.com/?q=guitar+chord+f+minor
https://moollaza.duckduckgo.com/?q=guitar+chord+finder&ia=answer

/cc @jagtalon @mintsoft @charles-l

**Comment by charles-l** [comment]
Yep, that definitely needs fixed. From a workflow standpoint, should I just submit another pull request or reopen the initial pull request?

**Comment by mintsoft** [comment]
@charles-l can you open another PR?

**Comment by charles-l** [comment]
OK, see PR #1042
