### ISSUE TITLE
Tips: Could also respond to tax

### ISSUE THREAD

**Issue by mattr555** [duckduckgo/zeroclickinfo-goodies#1044]
"7% tax on $35.99" seems like a reasonable query to me.

-- http://duck.co/ia/view/tips

**Comment by moollaza** [comment]
:+1:

**Comment by sagarhani** [comment]
I would like to fix this. Tell me where exactly the code for this IA present. 
Difficult to find it. :unamused:

**Comment by gaulrobe** [comment]
PR for this in #3208
