### ISSUE TITLE
Pi: Convert to Info Template and add more digits

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1046]
Add more digits to Pi! https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Pi.pm#L24

------
IA Page: https://duck.co/ia/view/pi

**Comment by puskin94** [comment]
@jagtalon Hei, as @moollaza suggested, this IA will wait for more digits until the new Goodie template is not complete!

**Comment by jagtalon** [comment]
@puskin94 ah, noted!

**Comment by aleksandar-todorovic** [comment]
Just for the reference, the current IA is limited to 400 digits.

Also, is there any proposition on the new limit?

**Comment by mintsoft** [comment]
@aleksandar-todorovic anything that doesn't affect the performance of the IA entirely. I.e; if it was actually computing 1000000 digits then I think we'd probably have an issue :)

**Comment by aleksandar-todorovic** [comment]
@mintsoft I have a very basic knowledge in the syntax, so correct me if I'm wrong, but by looking at the `Pi.pm` file, it seems to me like it's not actually computing anything. Instead, this goodie seems to have a pre-made list of 400 digits currently. I think it just outputs the amount of digits specified while triggering the goodie.

**Comment by mintsoft** [comment]
@aleksandar-todorovic Exactly; so you can make the number arbitrarily large without any real issue. I was just saying that if the approach was changed to compute rather than essentially just sub-stringing then we'd probably *have* to enforce a timelimit

**Comment by Owlree** [comment]
I noticed that the IA can't event display the current 400 digits.

![Screenshot of pi IA](http://i.imgur.com/Vi6UeQc.jpg)
