### ISSUE TITLE
ColorCodes: Improve triggering, should support "#ccc to rgb"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1048]
https://duck.co/ideas/idea/5047/better-triggering-for-color-conversion-instant-ans

We should support queries of the form, "X to Y", for each of the various colour code formats:

- "#ccc to rgb"
- "#ccc to hsl"
- "#ccc to cmyk
- etc.

https://duck.co/ia/view/color_codes

**Comment by mintsoft** [comment]
@moollaza do you think we want a more targeted output here or just to make it trigger the same answer on more queries?

**Comment by moollaza** [comment]
@mintsoft I think the current IA is good enough, as it answers all/each of those queries.

@abeyang any thoughts on that? I'm not sure if we want to change the design or add anything to the IA for those kinds of queries.
