### ISSUE TITLE
base64: Change to `start` trigger

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-goodies#1051]
https://duckduckgo.com/?q=python+base64&ia=answer 
https://twitter.com/mistydemeo/status/573933169654681603

-- http://duck.co/ia/view/base64

**Comment by dogweather** [comment]
Getting started on this one.

**Comment by mintsoft** [comment]
Cool @dogweather If you run into any problems make a PR at any point and we can help out!

**Comment by dogweather** [comment]
Ok, I'm ready for feedback on my PR: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1059

**Comment by mintsoft** [comment]
Fixed by @dogweather in #1059
