### ISSUE TITLE
Bring back the "mirror" IA

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/zeroclickinfo-goodies#1073]
Not sure if this is possible anymore and if it's practical to bring it back, but we should update the "mirror" IA (https://i.imgur.com/tkUK3FN.png) for the new format and design.

**Comment by moollaza** [comment]
It's already done :) https://duckduckgo.com/?q=mirror+text+hello&ia=answer

**Comment by javathunderman** [comment]
@moollaza It's still not triggering like it used to (i.e. mirror folder doesn't work anymore), but I think it's for the better...

**Comment by moollaza** [comment]
@javathunderman you're correct, we had to make the trigger more explicit to prevent false-positive results like the one in your picture.
