### ISSUE TITLE
MD5, Base64: Triggers should be more strict

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1074]
Noticed some false positives today: 
- [convert image to base64](https://duckduckgo.com/?q=convert+image+to+base64&ia=answer)
- [md5 program for windows](https://duckduckgo.com/?q=md5+program+for+windows&ia=answer)

We need to make sure the triggers for these IA's capture the user's intent

------
IA Page: https://duck.co/ia/view/md5

**Comment by puskin94** [comment]
@moollaza what about trigger only expressions between `"` or `'` ? Because we can convert `md5 "program for windows"` too

**Comment by moollaza** [comment]
Potentially, but I think we can solve this by making a unified crypto IA that does the work on the frontend

**Comment by puskin94** [comment]
@moollaza how to chech in the frontend if the query is 'general' or about an encryption? However, this afternoon I will work on this

**Comment by jagtalon** [comment]
@moollaza @puskin94 maybe one solution is to get this triggering if it's at the beginning. What do you think?

**Comment by jagtalon** [comment]
Kinda like Slack's slash commands https://api.slack.com/slash-commands

**Comment by orzechow** [comment]
I'd appreciate better triggering too.
Today I've searched for a files sha1 sum to double check my download (`sha1 cm-10.1.1-maguro.zip`).
The instant answer was rather misleading, since my first thought was: "oh nice, how does duckduckgo know that?"
It turned out (as you know) it's the hash of the string, not the file. But that's not what a user would expect it to be.

**Comment by orzechow** [comment]
This applies to all hash algorithms of course.

**Comment by edgesince84** [comment]
@orzechow with my little knowledge of this topic, I think you nailed it -- it's the hash of the string, not the file, and that's not what people expect.

**Comment by GuiltyDolphin** [comment]
@edgesince84 @orzechow Perhaps this should be clarified in the answer? `md5 hash of string: X`?

**Comment by orzechow** [comment]
Yes, the answer should be clarified.
Though, I'd prefer an explicit trigger as proposed by @puskin94 :
* `sha1 cm-10.1.1-maguro.zip` does not trigger
* `sha1 "cm-10.1.1-maguro.zip"` does trigger

**Comment by edgesince84** [comment]
hey @orzechow I wanted to see if you wanted to work on addressing this issue - I'd love to see a fix go live! 

If you'd rather work on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by orzechow** [comment]
Hey edgesince84,

I might have a look at this, though I'm not familiar with the duckduckgo code, API or anything yet.
But I'm on holidays until end of August, so don't expect changes until then ;)

Cheers!

**Comment by edgesince84** [comment]
thanks for letting me know, @orzechow --  enjoy your holiday!  When you're back, feel free to ask any questions you might have on the forum or [Slack](https://quackslack.herokuapp.com/).
