### ISSUE TITLE
Duplicated Markdown cheatsheet on IA index?

### ISSUE THREAD

**Issue by ngzhian** [duckduckgo/zeroclickinfo-goodies#1090]
There seems to be a duplicated entry on the IA index:

![dup](https://cloud.githubusercontent.com/assets/1749303/6994172/2ef884ec-dadd-11e4-8927-7c3c10843782.PNG)

https://duck.co/ia

**Comment by moollaza** [comment]
@ngzhian good catch! We accidentally created the first MardownCheatSheet page with the wrong id so we needed to make a new one to replace it.

I've changed the milestone of the incorrect page to `deprecated` so you won't see it in the index. We'll remove it later.

**Comment by moollaza** [comment]
https://duck.co/ia/view/markdown_cheatsheet

**Comment by mintsoft** [comment]
@moollaza same is true of BPMToMs

**Comment by moollaza** [comment]
@mintsoft thanks! I deprecated the incorrect page.
