### ISSUE TITLE
CalcRoots: IA should also use "sqrt" trigger

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1096]
E.g. ```sqrt 169```

**Comment by moollaza** [comment]
I think this will cause some conflicts with the Calculator Goodie? We're about to make some major improvements to the calculator though (using a new source for calculations) which should deprecate some of the niche calculation Goodies.

**Comment by tagawa** [comment]
OK, that sounds like a better long-term solution. Thanks.
