### ISSUE TITLE
Random characters show up in uppercase goodie

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/zeroclickinfo-goodies#1097]
I don't know if this is a thing that's been around for a while, but when you try to use punctuation with the uppercase IA (at least with an apostrophe), it prints out these sorts of characters in the IA description. 

![image](https://cloud.githubusercontent.com/assets/6887325/7036842/479f38a6-dd67-11e4-9cae-8c84c14cb022.png)

**Comment by mintsoft** [comment]
@javathunderman That's because the input is being `html_enc`'d I believe this is being tolerated until the Goodie Templates are completed. @moollaza ?

**Comment by moollaza** [comment]
Yup I believe @jagtalon is gonna take a peek into the internal templates we're using for the basic `structured_answer` -- I think we plan to keep them around for the foreseeable future.

**Comment by javathunderman** [comment]
@mintsoft @moollaza Hey, any updates on this?

**Comment by moollaza** [comment]
We've been discussing these "autotemplate" Goodie's recently. I think many of them can be converted to use the new "full" templates, but we still need to fix the auto-templates so that we're not showing escaped HTML on the SERP.

**Comment by moollaza** [comment]
Closing. More discussion in #1099
