### ISSUE TITLE
FlipText: Non-ASCII characters get escaped so they look weird

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1099]
![screen shot 2015-04-09 at 10 55 42 am](https://cloud.githubusercontent.com/assets/81969/7069500/2369028c-dea7-11e4-9d7e-7bcbf8a24bb9.png)

Query: "flip text /sɹoqɥƃıǝu‾sɹıɐʇsdn‾sǝuoʎɹǝʌǝ/4ɥʍʍ⇂Ɛ/sʇuǝɯɯoɔ/soǝpıʌ/ɹ/ɯoɔ˙ʇıppǝɹ˙ʍʍʍ//:dʇʇɥ"

**Comment by moollaza** [comment]
@jagtalon I believe this is requires an internal fix? We should probably update our template to not escape the contents and make sure we HTML encode the `input` internally so dev's don't have to worry.

**Comment by jagtalon** [comment]
@moollaza cool--will see what I can do on our end.

**Comment by zachthompson** [comment]
Just a quick test in duckpan shows that, within the goodie, the values are the same regardless of whether the query was upside down or not:
```
input: http://duckduckgo.com/?q=result
result: ʇʃnsǝɹ=b¿/ɯoɔ˙oƃʞɔnpʞɔnp//:dʇʇɥ
input_enc: http://duckduckgo.com/?q=result
result enc: &#x287;&#x283;ns&#x1DD;&#x279;=b&iquest;/&#x26F;o&#x254;&#x2D9;o&#x183;&#x29E;&#x254;np&#x29E;&#x254;np//:d&#x287;&#x287;&#x265;

input: ʇʃnsǝɹ=b¿/ɯoɔ˙oƃʞɔnpʞɔnp//:dʇʇɥ
result: http://duckduckgo.com/?q=result
input_enc: &#x287;&#x283;ns&#x1DD;&#x279;=b&iquest;/&#x26F;o&#x254;&#x2D9;o&#x183;&#x29E;&#x254;np&#x29E;&#x254;np//:d&#x287;&#x287;&#x265;
result enc: http://duckduckgo.com/?q=result
```
Particularly look at the encoded versions of the upside down text which are the same.  Somewhere we are already encoding the input by default.  So this only shows up where html_enc actually does something and it encodes twice.

Removing html_enc on the input fixes this.

**Comment by zachthompson** [comment]
@moollaza we also saw this with Mönchengladbach as input when looking at the utf8 stuff.
