### ISSUE TITLE
Conversions: "light year in mm" returns "mm in light years"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1102]
However, "light year in millimetres" returns the correct result

**Comment by mintsoft** [comment]
o.0 not sure how that's happening!

**Comment by marianosimone** [comment]
this happens also with other queries like:

- light year in m
- light year in cm
- light year in millimeter

But does NOT happen when there's a specific number before the "light year" or the other unit is in plural:

- 1 light year in m
- light year in mms

I'm working on a solution that might fix all the cases
