### ISSUE TITLE
Percent calculation looks wrong

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-goodies#1109]
![cfdwcdz](https://cloud.githubusercontent.com/assets/127263/7235255/fb522dac-e75a-11e4-8391-4f796c890f64.png)
![1tan1jp](https://cloud.githubusercontent.com/assets/127263/7235256/fb539976-e75a-11e4-9a4f-02a11d12d622.png)

https://twitter.com/dsokol/status/590150769103474689?refsrc=email&s=11

**Comment by MrChrisW** [comment]
Ping @puskin94 creator of [PercentOf](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/PercentOf.pm) :smile: 

Correct result: $28.87 
5/100 = 0.05 | $577.40*0.05 = 28.87
