### ISSUE TITLE
Unicode: Improve triggering, move to structured_answer and template

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1110]
A user was trying to trigger this IA with the query "unicode lsquo" and was unsuccessful.

This IA should be updated so any valid representation of a unicode entity should trigger the IA and show the other implementations.

The result of ["html &lsquo;"](https://duckduckgo.com/?q=html+%26lsquo%3B&ia=answer) is a step in the right direction, except we should show the result for: ["unicode left single quotation mark"](https://duckduckgo.com/?q=unicode+left+single+quotation+mark&ia=answer) (or something similar)

The code for this Goodie could also use a revamp. The static hashes should be moved to a YAML file and loaded from the share dir so the code is cleaner and the hashes are more easy to update and work with.

If we can relax the trigger even more for this it would be great, e.g. "left single quote" should be an alias for "left single quotation mark" -- users aren't likely to be that verbose :)

---

IA Page: https://duck.co/ia/view/unicode

**Comment by cosimo** [comment]
Tried to understand which "static hashes" could be moved out, but found none. Can you please clarify?

**Comment by moollaza** [comment]
@cosimo apologies for the confusion, I think I was talking about the EmcodeHTMLEntities IA: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/HTMLEntitiesEncode.pm
