### ISSUE TITLE
FedEx: Tracking link needs to be updated -- currently leads to "page has moved"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1111]
https://duckduckgo.com/?q=fedex+9241990100130206401644&ia=answer

Clicking the link we provide sends the user to a page which states:

```
Moved Permanently

The document has moved here.
```

We need to be sending them to:
https://www.fedex.com/apps/fedextrack/?action=track&tracknumbers=9241990100130206401644&action=track

**Comment by stevenmg** [comment]
I'll work on this. I don't think it will take much time.

**Comment by moollaza** [comment]
:+1:
