### ISSUE TITLE
YAML Loading should be done with `LoadFile`

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1114]
There's no need for us to be `slurp`ing the file content into a string. YAML exports a `LoadFile` function which can be used to simplify things:

```perl
use YAML::XS qw(LoadFile);
...
my $file = LoadFile share("myfile.txt");
```

**Comment by mintsoft** [comment]
:+1:

**Comment by altern8tif** [comment]
@moollaza This is good to close?

**Comment by mintsoft** [comment]
Yup, there's no yaml slurping in the repo
