### ISSUE TITLE
Conversions: Support “feet and inches” syntax

### ISSUE THREAD

**Issue by ticky** [duckduckgo/zeroclickinfo-goodies#1118]
As it stands, it only supports either [whole](https://duckduckgo.com/?q=5'+in+cm&ia=answer) or [decimal](https://duckduckgo.com/?q=5.5+feet+in+cm&ia=answer) feet. Queries such as [5'7" in cm](https://duckduckgo.com/?q=5'7"+in+cm) don’t produce results.

Likewise, it’d be useful to be able to convert in the other direction; [173cm in feet](https://duckduckgo.com/?q=173cm+in+feet&ia=answer) produces an answer in decimal feet. [173cm in feet and inches](https://duckduckgo.com/?q=173cm+in+feet+and+inches) produces no answer.

As someone who doesn’t use feet and inches regularly myself, but often interacts with people who do, it would be handy to be able to use DuckDuckGo to quickly convert.

**Comment by MrChrisW** [comment]
Hi @grapegravity, thanks for the suggestions! 

To summarise you'd like the following queries to trigger the [Calculator Goodie](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm) and perform a conversion.

+ 5'7" in cm
+ 173cm in feet and inches

I've included some examples of these triggers to help with development.
![selection_382](https://cloud.githubusercontent.com/assets/5282264/7315778/46a5f55e-eaa3-11e4-9047-681bad593c30.png)

Two possible ways of displaying feet and inches?
![selection_384](https://cloud.githubusercontent.com/assets/5282264/7315781/4b98b8e4-eaa3-11e4-920e-1fa9d9c7ef71.png)
![selection_383](https://cloud.githubusercontent.com/assets/5282264/7315782/4bf2620e-eaa3-11e4-92b8-5eaf5aa53d94.png)
