### ISSUE TITLE
Minecraft: JSON formatting & Image display

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-goodies#1124]
Two issues with the Minecraft IA. 

~~1. Quotes (`"`) in the [JSON data file](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/minecraft/crafting-guide.json) (`description`) only need to be escaped with a single backslash `\`~~ - Fixed
1. The image is being cut off due to `max-width: none` set on `c-info__img` - Internal

Example:
![selection_400](https://cloud.githubusercontent.com/assets/5282264/7450935/26092f0a-f27d-11e4-9dbf-b11844fb2826.png)

Link: https://duckduckgo.com/?q=compass+minecraft&ia=minecraft

------
IA Page: https://duck.co/ia/view/minecraft

**Comment by MrChrisW** [comment]
@moollaza I'm unable to fix image issue as this is an internal issue with the template styles?
I'm happy to add some hacky CSS however I know you like to fix the templates if there's an issue.

**Comment by moollaza** [comment]
@MrChrisW I'll make an issue for the images but I think it's expected/tolerated on smaller screens. The images on my monitor and macbook are OK until the dev tools reduces the height.

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@MrChrisW with regards to the unicode, lets just replace it with decimal numbers. I.e. 1½  -> 1.5

**Comment by MrChrisW** [comment]
@moollaza :+1:

**Comment by MrChrisW** [comment]
@moollaza On screens smaller then 634px the  `max-width` value for `.c-info__img-wrap `  is set to `180px` which results in the cropped image.

This media query sets the  `max-width to `220px` on larger height screens, hence you don't see a problem on your awesomely big screen :laughing:

````css
@media only screen and (min-width: 634px) and (min-height: 634px) {
    .c-info__img-wrap {
    height: 150px;
    line-height: 150px;
    max-width: 220px;
}
````

**Comment by moollaza** [comment]
Looks like it's an internal issue (happens elsewhere) I'll make an issue for the design team
