### ISSUE TITLE
Conversions: Support query oz to ml (absence of `fl`)

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-goodies#1125]
IA: https://duck.co/ia/view/conversions

Support the query `oz in ml`

Currently the following query works [32 fl oz to ml](https://duckduckgo.com/?q=32+fl+oz+to+ml&ia=answer) however [32 oz to ml](https://duckduckgo.com/?q=32+oz+in+ml) does not. Conversions should assume `fl` if `ml` is specified with `oz`

Originally reported here: https://github.com/duckduckgo/zeroclickinfo-spice/issues/1828 by @yegg

**Comment by mintsoft** [comment]
Hmm, the easiest way to implement this is to probably massage the input rather than fixing it in Conversions

**Comment by MrChrisW** [comment]
@mintsoft Do you mean something [like this](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/f3937f38f64287ad21152ab4371a9c06a6d73abe/lib/DDG/Goodie/Conversions.pm#L80-L83)?  or am I on the wrong track? :wink:

**Comment by mintsoft** [comment]
@MrChrisW something similar yeah

**Comment by mintsoft** [comment]
Fixed by @MrChrisW in #1127
