### ISSUE TITLE
Calculator: auto-focus text field on click

### ISSUE THREAD

**Issue by malbin** [duckduckgo/zeroclickinfo-goodies#1128]
after performing a calculation (https://duckduckgo.com/?q=5%2B5&ia=answer) when clicking the result it should auto-focus the cursor back in the text field so that you don't need to reselect it to perform additional calculations

------
IA Page: http://duck.co/ia/view/calculator

**Comment by MrChrisW** [comment]
This should be happening already as on [line 158](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm#L158) we use `document.x.q.focus();` to focus the search input, however testing revels this doesn't actually focus.

Testing `$("#search_form_input").focus();` also fails... Investigating.

**Comment by moollaza** [comment]
The interactive calculator has been released, this is now resolved.
