### ISSUE TITLE
Conversions: More significant digits, support "lightyear" as unit

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1132]
Originally posted on Duck.co, https://duck.co/ideas/idea/5237/1-lightyear-3-1e16-feet-unit-conversion-can-be
- We should show a few more significant digits when giving the result
- We should support "lightyear(s)" as a valid unit (this may need to be updated in Convert::Pluggable)

---

IA Page: http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
Quick update: Google only provides 4 SF these days; so I'll probably switch conversions to return 5 🤣
