### ISSUE TITLE
Guitar Chords: Use less ambiguous filenames (so letter casing isn't an issue)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1143]
I just cheked out the repo on my MacBook and it seems that the OS is having a hard time distinguishing the filenames because they are identical apart from the letter casing: ie `A#m7` vs `A#M7`. We should switch to use "Major" and "Minor" in the filenames so letter casing isn't an issue which leaves to room for problems :)

Open to other suggestions, but nearly-identical filenames sounds like something we should aim to avoid anyways.

**Alternatively**, there's an [initial PR that moves this IA towards using pure HTML](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1023) which is now a viable option as Goodie templates exist. That route would mean we wouldn't need to maintain all these images in the repo, which would be awesome.

*Note*: The original submitter hasn't responded in a while, so I believe it's up for grabs if someone wants to finish it.

------

IA Page: http://duck.co/ia/view/guitar_chords

**Comment by charles-l** [comment]
Oops, sorry for not responding promptly. I didn't realize this bug was created. I'll be sure to look into it soon.

**Comment by charles-l** [comment]
The pure HTML version actually is IMO cleaner (less generated crap in the git repo), so I'll look into finishing that one up if the original submitter doesn't reply.

**Comment by moollaza** [comment]
It's no problem @charles-l. The original creator hasn't replied in a while so you're welcome to pick it up and finish it up. I'd love to get those image assets out of the repo ;)

**Comment by moollaza** [comment]
@charles-l would you be able to fix the filenames for now? It's starting to cause problems for devs with OS's that aren't case sensitive (like Mac OS!)

Let's use "minor" and "major" in the names and keep them all lowercased.

**Comment by charles-l** [comment]
@moollaza OK, I'll look into fixing it within the week.

**Comment by charles-l** [comment]
@moollaza made the PR: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1265

**Comment by moollaza** [comment]
@charles-l thanks a lot!

**Comment by jagtalon** [comment]
Fixed in #1265
