### ISSUE TITLE
Password: Implement minimum password length

### ISSUE THREAD

**Issue by KK4OXJ** [duckduckgo/zeroclickinfo-goodies#1145]
The password generator is giving incorrect reports about password strength: 

![screenshot-6](https://cloud.githubusercontent.com/assets/7751418/7760300/3205050e-ffe8-11e4-8a74-df012e3b1d00.png)

I'm pretty sure a one character long password isn't "high strength". 

IA: https://duck.co/ia/view/password

**Comment by SamHH** [comment]
It appears to be simply echoing the strength of password you requested. If you ask for low strength, it will always display the strength as low, irrespective of length or actual strength. The same is true of average and high strength.

**Comment by KK4OXJ** [comment]
@SamHH Ah, I see. It still doesn't seem like it should say that a one character long password is strong, but it makes sense now :)

**Comment by mintsoft** [comment]
@SamHH @KK4OXJ That's exactly what it does, however the output is probably too terse which just causes confusion!

**Comment by moollaza** [comment]
@KK4OXJ @SamHH @mintsoft perhaps we should ensure a more sane minimum number of character for a password. I think at least 5 or 10 is good?

I can't imagine anyone needing a 1, 2, or 3 letter password?

**Comment by KK4OXJ** [comment]
@moollaza 8 is generally the recommended shortest length for a password, and it's in between 5 and 10. Maybe make that the default?

**Comment by moollaza** [comment]
@KK4OXJ sounds good to me! :+1:

**Comment by altern8tif** [comment]
Anyone working on this?  Otherwise, will try my hand at Perl programming for once :grimacing:

**Comment by mintsoft** [comment]
@altern8tif looks like no-one so go for it!
