### ISSUE TITLE
Independence Day: Convert to icon template, display country flag

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1148]
This Goodies should converted to use the [Icon template group](https://duck.co/duckduckhack/templates_overview#icon-template-group) and should display the flag for the given country.

The result should look like this:

![independence-day-v1 1-belgium](https://cloud.githubusercontent.com/assets/873785/7800796/12d754d0-02e9-11e5-9ae2-c15e874b2eb6.jpg)
![independence-day-v1 1-romania](https://cloud.githubusercontent.com/assets/873785/7800797/12dc719a-02e9-11e5-9680-8ce6e6d5555a.jpg)

**Note:** We'll likely need to use `Locale::Country` to get the 2 letter Country Code and pass that along to the `data` property. We'll then retrieve the country code in a new JavaScript file, that we can use to determine the icon size (based on whether or not we're dealing with a mobile device) and build the URL for the icon asset we need to show using `DDG.settings.region.getSmallIconURL` and `DDG.settings.region.getLargeconURL`

------
IA Page: http://duck.co/ia/view/independence_day

**Comment by cskksc** [comment]
@moollaza I've started working on this. This is what I have so far.
![img](https://cloud.githubusercontent.com/assets/5201497/8463204/45b22594-2056-11e5-83cf-fcbc5f09585c.png)

But how do we decide if its a mobile device ? And btw the large icon url doesn't look so bad on a phone. Also I am using the 'icon' template group, but how do I force it to use the 'detail' template, i.e it shouldn't display "Showing 1 items" and so on. It works fine on a phone.

**Comment by moollaza** [comment]
@cskksc you're off to a great start, but seeing as we're dealing with a single result, you'll want to use the detail view, instead of a tile view. Disabling the `item` template will solve this and should make the IA to look the way it does in my picture:

```js
templates:
  group: 'icon',
  item: false,
  ...
}
```

>But how do we decide if its a mobile device 

There will be a global js variable, `is-mobile` set to true when the device is considered mobile.

If you search for that variable name, you should see plenty of examples in the repo ;)

**Comment by cskksc** [comment]
Thanks. Probably should've done some more digging. :smile:
