### ISSUE TITLE
Convert old cheat sheet Instant Answers to JSON

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1155]
We've moved some of the cheat sheets to JSON, and they look a lot better as a result. See https://duckduckgo.com/?q=tmux+cheatsheet&ia=cheatsheet and https://duckduckgo.com/?q=vim+cheatsheet&ia=cheatsheet to see the swanky new UI. They now live in https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/cheat_sheets, and we could use your help to convert these too:

- [x] [Crontab](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/crontab_cheat_sheet)
- [x] [Emacs](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/emacs_cheat_sheet)
- [x] [Gimp](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/gimp_cheat_sheet)
- [x] [DuckDuckGo Shortcuts](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/DdgShortcuts.pm)

The documentation is currently in https://github.com/duckduckgo/duckduckgo-documentation/pull/247, but should be live in duck.co/duckduckhack once it gets merged.

**P.S.** Docs are live! https://duck.co/duckduckhack/goodie_cheat_sheets

**Comment by dronov** [comment]
I would like to tackle this if nobody else has picked this up before I finish https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1150

**Comment by zekiel** [comment]
@dronov  please do! That would be great!

**Comment by kbhat95** [comment]
In the meantime, can I tackle Gimp?

**Comment by mintsoft** [comment]
@kbhat95 absolutely!

**Comment by kbhat95** [comment]
One issue I've come across:
* Some sections, like ```Tools```, have subsections like ```File``` and ```Context``` (see [here](https://duckduckgo.com/?q=gimp+cheatsheet&t=canonical&ia=answer)). How do I deal with subsections using the current JSON template?
