### ISSUE TITLE
CheatSheets: Switch CSS3 to JavaScript/jQuery

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1157]
I mistakenly used CSS3 selectors, and didn't realize they won't work with IE8!

We'll need to change my CSS which hides row 4+ of the first 2 sections displayed to JavaScript.

**Comment by moollaza** [comment]
@spentacular -- I figured this issue might interest you?

**Comment by spentacular** [comment]
Yea, I can definitely take a swing at it!

**Comment by spentacular** [comment]
Hey @moollaza I'm not quite sure how to inject the JS into the page. Is there an easy way to do that? 

Also, sorry I didn't get to you sooner, pulled something in my back, so I've been taking it easy the past couple days.

**Comment by jagtalon** [comment]
Fixed by #1288
