### ISSUE TITLE
pounds in dollars

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-goodies#1170]
http://duck.co/ia/view/conversions

Got a note on twitter that we're not converting in the form

X pounds in dollars

https://twitter.com/vectorvitale/status/605771245599064064/photo/1

**Comment by mintsoft** [comment]
@yegg I'm reopening this as: https://github.com/duckduckgo/zeroclickinfo-spice/issues/1883 as it's on the XE Spice rather than the conversions goodie
