### ISSUE TITLE
Convert simple structured_answer Goodies to full templates

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1171]
There are many Goodies which use the simpler form of Goodie templating ("auto templating") which works when the Goodie returns a 3-property `structured_anwer` which contains the `input`, `operation` and `result`.

Now that we have fully fledged templating support, many of these Goodies, especially the ones that return HTML should be converted to use the "full" template system. In many cases switching to the Text template group will likely suffice, but in others we may benefit from using other built-in templates, which will allow for more complex results.

BTW, converting many of these should be fairly simple and easy for newcomers!

**Comment by mintsoft** [comment]
@moollaza do you think it'd be worth having an example of a before and after from a simple one?

**Comment by moollaza** [comment]
Closing. Nearly all of them have been converted now. There are in-progress PR's to replace the remaining Goodies.
