### ISSUE TITLE
USPS: Make sure the query only contains the package number when matching

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1175]
If we match on the regex pattern of a number, it should be the only thing in the query.

![37346365253153_eur_to_us_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/8016243/ef9672ca-0bae-11e5-816d-66a81478c9ea.png)

**Comment by mintsoft** [comment]
@moollaza Abandoned?

**Comment by moollaza** [comment]
whoops!

**Comment by mintsoft** [comment]
Fixed by @marianosimone in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1199
