### ISSUE TITLE
Calculator: Add support for advanced calculations

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1187]
Add the ability to solve e.g. `10!`, `20nCr8`, etc. as well as equations.

Suggestion source: https://duck.co/forum/thread/13748/calculator-improvements

---

IA Page: https://duck.co/ia/view/calculator

**Comment by mintsoft** [comment]
@tagawa 20nCr8 should probably be handled by: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Combination.pm already I think

**Comment by moollaza** [comment]
We're currently contemplating how we want the calculator to work. There is a Spice PR which will bring a API powered calculator from Symbolab.com it *could* be used for just about all calculations, but we need to keep a backend (Perl) calculator for the /html and /lite versions of the site.

The current calculator isn't very modular and so we've created several niche "calculation" IA's which I'd like to avoid.

As @mintsoft knows, we have a similar problem with handling conversions.

One idea I had was to leverage Math.js and Node as it supports both Math and Conversions, and it's extensible.

**Comment by tagawa** [comment]
Thanks for the comments @mintsoft and @moollaza. I agree, there's practically no limit to the features/complications that could be added so a re-think is probably best.

**Comment by mintsoft** [comment]
* Factorial is implemented in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927
* Equation handling is solved by the spice
* nCr is handled by Combinations.pm

**Comment by mintsoft** [comment]
@tagawa I think this can be closed once #1927 is merged?

**Comment by tagawa** [comment]
@mintsoft Agree, and if there are any further requests they can be individual new issues.

**Comment by moollaza** [comment]
Closing.

The new calculator supports factorials.

nCr can be added to the Combination IA. (Will make a new issues)

Equations are handled by the Symbolab Spice.
