### ISSUE TITLE
Conversions: Add support for ml to cups

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-goodies#1188]
It would be great to get coverage on ml to cups. For example: 750ml to cups

In addition, 'ml to ounces' does not trigger whereas 'ml to oz does'

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by kbhat95** [comment]
I'd like to work on this.

Just to clarify: new units will have to go into [Convert-Pluggable](https://github.com/elohmrow/Convert-Pluggable), right?

**Comment by kbhat95** [comment]
The cup has been added as a unit into Convert-Pluggable; this should be good to go, I suppose. :)

**Comment by mintsoft** [comment]
@kbhat95 previously we needed to update `dist.ini` to the latest version. I'd also probably add a or 2 test into `Conversions.t` as it'll help if we do ever convert it to use a different module etc!

**Comment by mintsoft** [comment]
@kbhat95 Just noticed this : https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1189/files :+1:  !
