### ISSUE TITLE
Images link in Color Codes IA goes to an empty results page 

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-goodies#1204]
Can we fix this to link to a page with the appropriate results?

https://duckduckgo.com/?q=%23de5833&t=osx&ia=answer - if you click on the images link you are directed to this page...

![screen shot 2015-06-24 at 10 04 14 am](https://cloud.githubusercontent.com/assets/7061920/8336333/89bafe0e-1a58-11e5-877b-0c1e494045ee.png)

**Edit:**
Solution is described in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1204#issuecomment-115824272. Should be a matter of adding a slash before the `#`.

------
IA Page: http://duck.co/ia/view/color_codes

**Comment by mintsoft** [comment]
@chrismorast Hmm, it works for me? 
![image](https://cloud.githubusercontent.com/assets/978048/8339364/c9a40690-1aae-11e5-94ab-e33b8eb26c1f.png)

**Comment by moollaza** [comment]
@chrismorast it worked for me as well on OSX, FF. Do you have an ad blocker running? (I can't see one...).

I saw the grey tiles for a second, and then immediately after all the images loaded. Please try again and let us know!

**Comment by gokul1794** [comment]
Works on Ubuntu Chrome with Adblocker!

**Comment by jagtalon** [comment]
Was able to replicate. Only happens on Safari. URL has to be:

http://labs.tineye.com/multicolr/#colors=de5833;weights=100;

And not:

http://labs.tineye.com/multicolr#colors=de5833;weights=100;

**Comment by chrismorast** [comment]
Sorry for the late reply here - and thanks for looking into it @mintsoft , @gokul1794 , @moollaza & @jagtalon ! and thanks for the fix @altern8tif and @mintsoft ! Working for me now :relieved:
