### ISSUE TITLE
Dice: 6 times 3d6

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-goodies#1231]
"Why I cannot roll few dices few times? I cannot write 6 times 3d6 to get skill points roll."

https://twitter.com/mikolajhalber/status/616965696426258432?refsrc=email&s=11

---

IA Page:  http://duck.co/ia/view/dice

**Comment by loganom** [comment]
@zekiel will look into this at the weekend.

**Comment by loganom** [comment]
"this weekend".. I totally spaced on this issue with everything else going on. 

To be clear, the suggestion here is that the user would like to be able to type "6 times 3d6" and the expected result would be 6 multiplied by the sum of the 3 dice rolls?

**Comment by GuiltyDolphin** [comment]
@loganom If it is for a skills-point roll I imagine it would be 6 sums of 3d6 (or clearly displaying 6 separate rolls of 3 dice).

**Comment by cngarrison** [comment]
I made some progress on this, but haven't had time to get back to complete it. Incomplete fix has been pushed to https://github.com/cngarrison/zeroclickinfo-goodies/tree/dice-multi-roll. Not creating a PR for unfinished changes. Feel free to continue with my changes, or start over again. :-)

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
