### ISSUE TITLE
crontab says "at this freq." and then gives two points, not a frequency

### ISSUE THREAD

**Issue by nospampleasemam** [duckduckgo/zeroclickinfo-goodies#124]
http://duckduckgo.com/?q=crontab+0+0+*+*+*+%2Fusr%2Fbin%2Fnice+-n+15+%2Fusr%2Flocal%2Fddg%2Fsysadmin%2Flog%2Flogrotate_ubuntu.sh

**Comment by mintsoft** [comment]
Fixed by @W25 in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/885
