### ISSUE TITLE
Calculator does not support multiplication symbol

### ISSUE THREAD

**Issue by Asherehsa** [duckduckgo/zeroclickinfo-goodies#1243]
The calculator solves 3 * 3 (three asterisk three) and 3 x 3 (three ex three) but not when you use the proper multiplication symbol 3 × 3

**Comment by RomainLG** [comment]
Dammit, I've been trying but I'm not sure you can use the plaintext symbol, maybe I should use it's encoding numbers 

https://en.wikipedia.org/wiki/Multiplication_sign#In_computer_software

Anyway, who types it that way into their browsers?! ^^'

**Comment by Sloff** [comment]
Hi @mintsoft, I think this issue can be closed as it was resolved in #1264

**Comment by mintsoft** [comment]
@Sloff It was indeed; thanks for reminded me
