### ISSUE TITLE
CheatSheets: Update JSON files to newest syntax

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1250]
We've published slightly updated documentation for cheat sheets. Existing cheat sheets now need to be updated to make sure everything is correct.

The biggest change we've made is that we've decided to ditch the plus (`+`) between keys.

```
//bad
[Ctrl] + [Alt] + [Delete]

//good
[Ctrl]  [Alt]  [Delete]
```

------

Similarly, successive key presses should be separated with a comma (`,`):

```
//bad
[Ctrl] then [Alt] then [Delete]

//good
[Ctrl],  [Alt],  [Delete]
```

---

There are also new updated for show alternative keys and alternative shortcuts. More details can be found in the documentation: https://duck.co/duckduckhack/goodie_cheat_sheets

**Comment by sagarhani** [comment]
@moollaza looks like there are many cheat sheets with bad syntax. I'll update the JSON file for [vim cheat sheet](https://duckduckgo.com/?q=vim+cheat+sheet&ia=cheatsheet) and [gimp cheat sheet](https://duckduckgo.com/?q=gimp+cheat+sheet&ia=cheatsheet) :+1:

**Comment by RomainLG** [comment]
@moollaza , what about alternative keys? Is `[0] or [Insert]` ok?

**Comment by sagarhani** [comment]
@RomainLG  That is fine I guess. :+1: 
And I have already updated the JSON file for almost all IAs gimp, vim, blender, gnome-keyboard, mac-keyboard, I'll push all these in a while.
@RomainLG If you are interested, check if I had missed any other IAs and please work on it.

**Comment by RomainLG** [comment]
Apparently some other files contain `+` :

* coffee-script
* coffeescript
* duckduckgo
* gnome-keyboard
* mac-keyboard 

If it isn't fixed by tomorrow I'll do it.

**Comment by moollaza** [comment]
@sagarhani @RomainLG as the docs mention, alternatives should be handled by creating two separate k-v pairs, and then let the descriptions indicate that they're alternatives.

For sub-alternatives, they should be wrapped in parenthesis `()`, and separated with slashes `/`

**Comment by RomainLG** [comment]
@moollaza thanks for answering.

It's all explained [at the end of this page](https://duck.co/duckduckhack/goodie_cheat_sheets) and there's going to be some changes in most of the files I think...
