### ISSUE TITLE
Dice: Support for "Roll 2 dices" or "Roll two dice"

### ISSUE THREAD

**Issue by RomainLG** [duckduckgo/zeroclickinfo-goodies#1255]
On the instant answer "dice":

Keyword: "roll 2 dice" works, although I'm seeing blank rectangles but that's supposedly my browser unicode support that is lacking (latest chrome).

![image](https://cloud.githubusercontent.com/assets/13045542/8548918/121f1658-24c8-11e5-9081-f66acca6c9c3.png)

I would have supported ***"roll 2 dices"*** too. Dices is an accepted word of the [dictionary](http://www.thefreedictionary.com/dices), albeit less common than dice.

***"Roll two dice"*** doesn't work either.

-----
IA Page: https://duck.co/ia/view/dice

**Comment by moollaza** [comment]
@abeyang @thm should we ask the community to make some dice icons for us so we don't need to bother with unicode support across browsers?

**Comment by abeyang** [comment]
@moollaza here you go: http://cl.ly/3j0s1F1B121P (with thanks to @chrismorast)

**Comment by abeyang** [comment]
--the above is 36x36; here it is at 24x24, just in case: http://cl.ly/0f2X1C1p0I2k
