### ISSUE TITLE
Title of vim cheat sheet Instant Answer

### ISSUE THREAD

**Issue by sagarhani** [duckduckgo/zeroclickinfo-goodies#1278]
Look at any cheat sheet - [gimp](https://duckduckgo.com/?q=gimp+cheat+sheet&ia=cheatsheet), [blender](https://duckduckgo.com/?q=blender+cheat+sheet&ia=cheatsheet), [harry potter spells](https://duckduckgo.com/?q=harry+potter+spells+cheat+sheet&ia=cheatsheet), [gnome keyboard](https://duckduckgo.com/?q=gnome+keyboard+cheat+sheet&ia=cheatsheet), and all others.
The title of the result page will be - cheat_sheet_name at DuckDuckGo
Example [1] : Title of gimp cheat sheet is - gimp cheat sheet at DuckDuckGo
Example [2] : Title of blender cheat sheet is - blender cheat sheet at DuckDuckGo

But, for [vim cheat sheet](https://duckduckgo.com/?q=vim+cheat+sheet&ia=cheatsheet) the title is - vim cheat sheet (Software) at DuckDuckGo 

The word (Software) is appended. :frowning:

**Comment by Sloff** [comment]
The word (Software) is also only appended with the keyword "cheat sheet", but not with "cheatsheet" or any of the other triggers.

For example:
[Cheatsheet](https://duckduckgo.com/?q=vim+cheatsheet&ia=cheatsheet)
[Command](https://duckduckgo.com/?q=vim+command&ia=cheatsheet)

**Comment by sagarhani** [comment]
@Sloff, Yes. Good find. :+1: 
Actually, the word (Software) shouldn't be appended to any of the triggers.

**Comment by moollaza** [comment]
@jdorweiler any idea what's setting the page title here? I assume this was based on previous metadata? The category is no long set to Software though, so I'm guessing this is just a result of caching?

**Comment by jdorweiler** [comment]
@moollaza good question.  I'm not sure where that's coming from but I don't think it's caching.

**Comment by iambibhas** [comment]
This is very weird.
