### ISSUE TITLE
TimezoneConverter: Improve triggering

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1279]
Originally reported on Duck.co: https://duck.co/ideas/idea/6047/time-zone-conversion-triggering

---

"7:00 p.m. ET to PT" doesn't return the IA though "7:00 PM EDT to PDT" does.

Other queries that should trigger the Time Zones conversion but don't are:
- "7:00 pm eastern to pacific"
- "7:00 PM ET to PT"
- "7:00 pm ET in pacific"
- "7:00 pm EDT in pacific"

---

IA Page:  http://duck.co/ia/view/timezone_converter

**Comment by checkaayush** [comment]
@moollaza I'd like to take it up. Any cues?

**Comment by mintsoft** [comment]
@checkaayush looking at: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/TimezoneConverter.pm it's probably that there's no definition for "ET" or "PT" in the dates role's timezone list: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/GoodieRole/Dates.pm#L64
