### ISSUE TITLE
Replace legacy "url escape" image with newer Cheat Sheet

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1282]
We currently show an image in the results for the query [url escape](https://duckduckgo.com/?q=url+escape).

We should showcase this information with a cheat sheet instead. Let's ditch the image!

**Comment by gokul1794** [comment]
@moollaza I made a cheatsheet for the url escape, but the `url escape` triggers the URLEncode IA as `url escape` as one of the triggers, What to do?

**Comment by mintsoft** [comment]
@gokul1794 It's probably best to guard the `handle` on the urlencode to just `return` if the remainder matches `/cheat[\s]?sheet/`. If you open a PR with the cheatsheet on we can check out the triggering of them all together :)

**Comment by gokul1794** [comment]
@mintsoft I will make a PR and then can you can help me out?
