### ISSUE TITLE
TimezoneConverter: wrong MSK timezone

### ISSUE THREAD

**Issue by sjoubert** [duckduckgo/zeroclickinfo-goodies#1286]
The MSK (Moscow Time) is wrongly configured to UTC+4 while it should be UTC+3

This makes all conversion involving MSK to be off by one hour.
Example: https://duckduckgo.com/?q=0+MSK+in+UTC

See the following links for references:
https://en.wikipedia.org/wiki/Moscow_Time
http://www.timeanddate.com/time/zones/msk

**Comment by moollaza** [comment]
@sjoubert thanks a lot for reporting!

I feel like this is a good reason to leverage the TimeAndDate API for thse kinds of queries rather than trying to maintain a static Goodie which can clearly become outdated!
