### ISSUE TITLE
DaysBetween: Dates should be able to infer year

### ISSUE THREAD

**Issue by bjtitus** [duckduckgo/zeroclickinfo-goodies#1301]
When I first tried to use this IA, I attempted to search for "days between 7/17 and 8/20" but nothing came up. I expect it to default to the current year. Most date calculations will be for the current year so it is tedious to have to type out the year.

There may be more to do here with year inference (checking if one of the dates has a year specified and inferring the other one to be in the same year) but there may be too much magic in that.

---

IA Page:  http://duck.co/ia/view/days_between

**Comment by mintsoft** [comment]
@bjtitus Something similar is implemented currently, however it requires unambiguous date formatting. https://duckduckgo.com/?q=days+between+17+July+and+18+Aug&t=vivaldi&ia=answer

I'll have a look about how the year defaults and ambiguous date handling is currently implemented, as it might essentially already do this, however Days Between is blocking it up

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
