### ISSUE TITLE
DaysBetween: Dates should accept short year format

### ISSUE THREAD

**Issue by bjtitus** [duckduckgo/zeroclickinfo-goodies#1302]
Dates should be able to be specified using a short form where possible:

"7/20/15" = 7/20/2015
"7/20/96" = 7/20/1996

It looks like this may need to be an addition to date handling in [Dates.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/GoodieRole/Dates.pm)

------
IA Page:  http://duck.co/ia/view/days_between

**Comment by mintsoft** [comment]
@bjtitus I believe this should already be implemented? https://duckduckgo.com/?q=days+between+7%2F20%2F2015+and+8%2F20%2F2015&t=vivaldi&ia=answer
