### ISSUE TITLE
DatesRole could be made location aware for formats

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#1327]
Lo,

A comment by @abeyang has reminded me about something I wanted to extend the dates role for.

Essentially date formats that put the month at the front are uniquely North American; therefore I think it would be sensible to make the datesrole location-aware and prefer `05/20/2014` or `Jan, 01 2014` for US; but `20/05/2014` or `20th May 2014`. Especially for ambiguous formats (`02/05/2014`) this would be beneficial.

So, What do people think? Good idea, bad idea?

**Comment by abeyang** [comment]
@mintsoft I dig this -- I was starting a conversation about this internally as well. Only thing I would add (if this isn't already there) is an easy way to shift between certain formats. So, maybe default would be `mmm d, yyyy` (like `Jan 1, 2015`), but it can just as easily become `M d, yyyy`

**Comment by mintsoft** [comment]
Yeah I was thinking of having two or three templates,
`short` which would be '20/10/2014' or '01/20/2014'
'medium' which would be '01 Jun 2014' or 'Jun 1, 2014'
'long' which would be '1st January 2014' or 'January 1, 2014'

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
