### ISSUE TITLE
TimezoneConverter: detect user timezone

### ISSUE THREAD

**Issue by Petethegoat** [duckduckgo/zeroclickinfo-goodies#1334]
"12:30pm EDT" should find the user's timezone, and automatically convert it to that.

------
IA Page:  http://duck.co/ia/view/timezone_converter

**Comment by zekiel** [comment]
thanks for filing @Petethegoat  This could probably use a pass on triggering e.g. things like this work https://duckduckgo.com/?q=12%3A30pm+EDT+to+paris+time&ia=time
