### ISSUE TITLE
Regex Cheat Sheet: black titles in black theme

### ISSUE THREAD

**Issue by lightonflux** [duckduckgo/zeroclickinfo-goodies#1347]
If you use the dark theme and expand the regex cheat sheet view all the heading are black, which is less than stellar because of the low contrast:

[Image](https://i.imgur.com/M7syFxx.png)

------
IA Page:  http://duck.co/ia/view/regex_cheat_sheet

**Comment by moollaza** [comment]
@lightonflux thanks for reporting. We have already fixed this in the repo and will be releasing the fix very soon (today hopefully!)
