### ISSUE TITLE
DuckDuckGo Shortcuts: 

### ISSUE THREAD

**Issue by ishankhare07** [duckduckgo/zeroclickinfo-goodies#1355]
add a new shortcut for focusing back on the search bar

------
IA Page:  http://duck.co/ia/view/duckduckgo_cheat_sheet

**Comment by moollaza** [comment]
@ishankhare07 we actually do have the shortcut for focusing on the search bar. You need to click the expand icon first and then you'll see it :+1:

**Comment by ishankhare07** [comment]
@moollaza i must have missed it out
for those who might come later to this issue searching for a similar functionality
the shortcut is `/` or `h`
