### ISSUE TITLE
Binary: Goodie can use ISO-8859-1 encoding. Should always be UTF-8

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/zeroclickinfo-goodies#1356]
https://twitter.com/xowap/status/626706181097156608?refsrc=email&s=11

---

IA Page:  http://duck.co/ia/view/binary

**Comment by moollaza** [comment]
@nilnilnil can you explain what the expected output should be here? I'm a little confused...

**Comment by mintsoft** [comment]
@moollaza in utf8 é is two bytes and comes out like: `11000011 ‭10101001‬`

**Comment by moollaza** [comment]
@mintsoft aah, thanks for clarifying :+1:
