### ISSUE TITLE
emacs cheat sheet typo

### ISSUE THREAD

**Issue by synbit** [duckduckgo/zeroclickinfo-goodies#1361]
Hello,

I think that should be `M->` instead, please see below:

![emacscheatsheettypo](https://cloud.githubusercontent.com/assets/13200096/9060895/ceec062c-3aaf-11e5-8f1b-062df0b3e0f5.png)

**Comment by Sloff** [comment]
Has been fixed in #1310

**Comment by mintsoft** [comment]
@sloff yes! I knew it rung a bell when I saw it.
