### ISSUE TITLE
Morse: Reign in triggering

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1376]
A recently added "More Code Cheat Sheet" was created which brought to light a triggering issue with this IA. After speaking with the team, we agreed that the trigger "morse code" is too broad for this IA and should be reigned in.

I believe we should change the trigger for this IA to something more along the lines of "more code for" and "to morse code". This would allow queries like "<phrase> to morse code" and "more code for <phrase>" to trigger this IA. These kinds of queries clearly indicate an intention to convert a given phrase into more code.

Additionally, we should also update the morse code cheat sheet's `description` to mention that this IA exists and users can search "x to morse code" in order to convert something into morse code

------
IA Page:  http://duck.co/ia/view/morse

**Comment by jagtalon** [comment]
Fixed in #1537
