### ISSUE TITLE
Conversions: without "Convert" it takes the exact opposit of what you need

### ISSUE THREAD

**Issue by roelleor** [duckduckgo/zeroclickinfo-goodies#1385]
Example: BTU to KwH gives the amount of BTU in 1 KwH. When using the longer syntax, e.g. "Convert BTU to KwH", everything goes fine. Btw, thanks for developing this, its great!

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
@roelleor thanks for raising this; we've had a few other issues raised around this exact thing recently.

**Comment by mintsoft** [comment]
@moollaza I was just looking into this; there's quite a lot of tidying up around ambiguity handling I want to do, however: how is the new all-singing-all-dancing clientside-conversions thingy going along? I'm happy to kick this around and sort it out, but only of it's actually worth doing!

**Comment by mintsoft** [comment]
related: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1102
