### ISSUE TITLE
Calculator: Switch Math::BigInt to use GMP when available for increased performance

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1389]
If we switch our usages of `Math::BigInt` and `bigint` to `Math::BigInt try => "GMP"` It will allow us to use GMP when available (meaning production) but fallback to a slower pure Perl implementation otherwise (for devs that don't have GMP installed).

This should be updated wherever we're using BigInt.

------
IA Page: https://duck.co/ia/view/calculator

**Comment by rfdrake** [comment]
"try" doesn't require a dependency.  If GMP isn't installed it won't use it, but it will use it if it's there.  If anything you might add it to a "recommends" section of your makefile.

You might use Math::BigInt try => 'GMP, Pari' to try both XS modules.  The one drawback being that if there are any bugs in either library then you've increased the chances of hitting them in your library.

You should also make sure you're doing this for BigFloat and other Math::Big libraries that support it.

**Comment by moollaza** [comment]
@rfdrake thanks for the input!

>"try" doesn't require a dependency. If GMP isn't installed it won't use it, but it will use it if it's there.

That's exactly the point I was trying to get across -- I guess I wasn't very clear though?

>You should also make sure you're doing this for BigFloat and other Math::Big libraries that support it.

Good point! I'll check if we're using any other Math::Big libraries.

**Comment by moollaza** [comment]
Looks like we're only using `Math::BigInt` in a couple places right now...

**Comment by moollaza** [comment]
We'll be deprecating the Perl backend shortly in favour of the new frontend. This will no longer be an issue.
