### ISSUE TITLE
Calculator: shows results when searching for a phone number

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#1393]
When looking up a phone number I get a calculator result.  

------
IA Page:  http://duck.co/ia/view/calculator

**Comment by mintsoft** [comment]
@jdorweiler Do you have an example of the format? UK phone numbers don't seem to do it!

**Comment by jdorweiler** [comment]
@mintsoft sorry!  Here's a US phone example https://duckduckgo.com/?q=555-555-5555&t=canonical&ia=answer

**Comment by wongalvis** [comment]
I don't think it's easy to differentiate searching for a phone number and entering a formula in the query.
There could be a suggestion link above the search results "Looking for a calculation?" (or something like that) and expands to display the Goodie when it's clicked.

**Comment by moollaza** [comment]
@wongalvis I think it's OK to bail on queries that match a North American phone number regex like:

```perl
/^\(?\d{3}\)?-\d{3}-\d{4}$/
```

If there's no spaces and 10 digits, its almost certainly a phone number. The user can adjust the query or add "calculate" or `=` to the query to ensure the calculator picks it up.

Not that it matters much, but for comparison, Google and Bing handle it this way. Interestingly Yahoo shows their calculator for queries that match that regex.

**Comment by jagtalon** [comment]
Or you can https://metacpan.org/pod/Number::Phone
