### ISSUE TITLE
Conversions: Auto-conversion to "fl oz" doesn't work with "liters"

### ISSUE THREAD

**Issue by Dhekke** [duckduckgo/zeroclickinfo-goodies#1396]
In line 80 of [Conversions.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm#L80) there's a hack for automatically interpreting "oz" as "fl oz" if the query contains "ml".

It works perfectly, but it'd be nice if the same worked for other units of volume, but especially liters.

Here's one example: https://duckduckgo.com/?q=convert+2+liters+to+oz

---

IA Page:  http://duck.co/ia/view/conversions

**Comment by moollaza** [comment]
@Dhekke thanks a lot for submitting this!

Could you list out examples of other assumptions/inferences we should make? That way we can have someone implement them!

**Comment by Dhekke** [comment]
@moollaza Sure, I could give it a shot. Ideally, all units of volume should make 'oz' be interpreted as 'fl oz' but I think that's a pretty huge goal.

I did some digging and these (I think!) are the units of volume that are already accepted by the script:
- liter (l)
- mililiter (ml)
- gallon
- pint
- quart
- fluid ounce (fl oz)

So 'oz'/'ounces' should be interpreted as fluid ounces for:

- liter (l)
- gallon
- pint
- quart

I also found out that the abbreviated names for pint (pt) and quart (qt) are not currently accepted. But that's another issue altogether.

Thanks!

**Comment by MrChrisW** [comment]
Something like this should do (untested)
````perl
s/(oz|ounces)/fl oz/ if(/ml|gallons?|pints?|quarts?|liters?|l/ && not /fl oz/);
````
It also looks like the abbreviations for gallon isn't accepted `gal or gals`, may need to create an issue over at https://github.com/elohmrow/Convert-Pluggable/issues
