### ISSUE TITLE
Cheat Sheets: Add spacing around Parentheses and Slashes in Alternatives

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1407]
We decide to add some padding around the alternative keys. We should updated all Goodies so that alternatives like `([A]/[B]/[C])` are spaced out to look like this: `( [A] / [B] / [C] )`.

This can done manually, but a small find+sed script should be able to handle it as well :smile: 

Any takers?

**Comment by cskksc** [comment]
@moollaza I'd like to get started on this. I'll submit a PR soon.
