### ISSUE TITLE
Rankine temperature conversion is incorrect

### ISSUE THREAD

**Issue by ahstro** [duckduckgo/zeroclickinfo-goodies#1413]
As of now, `10 rankine in fahrenheit`  outputs `-441.670 °F`, when, according to this conversion, `[°F] = [°R] − 459.67`, found [here](https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature), it should equal `-449.67`.
I searched through both [`Conversions.pm`](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm) and the imported [`Convert::Pluggable`](https://github.com/elohmrow/Convert-Pluggable), but just when I thought I found the right place in the latter, I realized that the [conversion process](https://github.com/elohmrow/Convert-Pluggable/blob/master/lib/Convert/Pluggable.pm#L46) seemed correct.

I'm baffled and Perl is not my primary, nor secondary, language, so I'm going to leave this issue here. Also, CC @elohmrow, since you created the conversion module, although I'm not sure that's where the problem lies.

**Comment by elohmrow** [comment]
i will look in a bit - thanks!

**Comment by elohmrow** [comment]
i've taken a peek - and it seems *very* odd.  F<=>R is actually the *easiest* of the conversions in that set, but it simply is not working.  tracing it out, running new tests, changing the code (it really needs updating, and i had started to, but there does not seem to be much call for it) - nothing.  i'll have to look again, or, perhaps someone else copied on here might see it?

**Comment by seisfeld** [comment]
Dunno if that helps, but Celsius to Rakine also gives wrong answer (-263.150 °C but should give -267.5944444 °C).

Source to double check: https://converterin.com/temperature/rankine-scale-to-celsius-degrees.html

**Comment by elohmrow** [comment]
yeah its just rankine ... basically the way I implemented it is fahrenheit is base, every unit turns first to fahrenheit, then gets converted.

so since R<=>F is not working, no rankine conversions will :(

/bda

**Comment by seisfeld** [comment]
This looks like a rounding or precision error. The answer is exactly off by -0.8 F per 1 R:

DDG: 1 R -> -457.870 F
Correct: -458.67 F
Difference: -0.8

DDG: 10 R -> -441.670 F
Correct: -449.67 F
Difference: -8

**Comment by elohmrow** [comment]
@seisfeld *very nice* catch!<br />
i am very busy for the next 20 hrs or so ... if you would like to submit a patch, i'll fold it in.  either way, i'll try to put up a new version to CPAN within 24 hours.<br />

**Comment by seisfeld** [comment]
@elohmrow I'd love to submit a patch but i lack Perl skills. ;) Am glad i could help a little with the search for the issue though. I'm really keen to finally see what it exactly was.

**Comment by elohmrow** [comment]
@seisfeld well, i will plug something in as soon as i can ... i didn't even make the comparisons, since it's such a simple calculation.  you found the pattern, and it probably solves the problem.

**Comment by phylum** [comment]
@elohmrow I investigated the problem but was only able to figure out that the code tries to convert everything to Kelvin instead of Rankine while stating that it's converted to Rankine.  I'll continue to research the issue and if you have an idea of where in the code to look it'd be greatly appreciated.

**Comment by elohmrow** [comment]
@phylum - you'll want to look at 'sub convert_temperatures' and '@temperature' - for temperature conversions, everything is first turned in to a base temperature (Fahrenheit), then from that base temperature to whatever was asked for.  the current calculation looks correct to me - something sinister is happening that hasn't been tracked down yet.

**Comment by elohmrow** [comment]
@ahstro @seisfeld @phylum ~ I have a fix for this now.  I will push it up here asap, and notify you all when it's done.

**Comment by seisfeld** [comment]
@elohmrow Cool! What was it?

**Comment by elohmrow** [comment]
@seisfeld ~ the regex for temperatures was off - some times, when it encountered an alias for 'rankine', it captured on 'kelvin' ... so i made the regex more clear.

**Comment by elohmrow** [comment]
@ahstro @seisfeld @phylum fixed in 306c551046b06d6aede637ede8472669ee5d394f

**Comment by elohmrow** [comment]
@moollaza ~ if you are still using this, please switch your C::P to v0.030, where this issue is fixed.

**Comment by moollaza** [comment]
>@moollaza ~ if you are still using this, please switch your C::P to v0.030, where this issue is fixed.

@elohmrow thanks, will do!
