### ISSUE TITLE
Cheat Sheets: Need to encode angle brackets "<", ">" inside code blocks

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1414]
Looks like the Emacs Cheat Sheet is slightly broken now. The "Search and Replace" section contains a key with `[<replace-string>]` in it. The angle brackets aren't being encoded and so a `<replace-string></replace-string>` element is being created on the page.

https://duckduckgo.com/?q=emacs+cheat+sheet&t=ffab&ia=cheatsheet&iax=1

-----
IA Page: https://duck.co/ia/view/cheat_sheets

**Comment by mintsoft** [comment]
@moollaza Isn't this `html_enc` rather than escape?

**Comment by moollaza** [comment]
> @moollaza Isn't this html_enc rather than escape?

@mintsoft whoops. You're totally right. Updated the phrasing :+1: Thanks!

**Comment by mattr555** [comment]
Also observed this on the bash cheat sheet:

![screenshot - 08292015 - 09 08 16 am](https://cloud.githubusercontent.com/assets/4411471/9562014/8299e096-4e2d-11e5-8fc5-0f9e78972059.png)
