### ISSUE TITLE
Factorial: Move integration into Calculator.pm; Calculate factorial with Math::BigInt bfac()

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1418]
We recently merged a new Factorial Goodie. The current implementation works, but really this functionality should be a part of the existing Calculator Goodie.

As well. the current implementation uses a naive method of calculating the Factorial using recursion via `List::Util::reduce`. This should definitely be switched to use `Math::BigInt`'s `bfac()` method.

This will enable us to calculate considerably larger values, however we need to wrap this logic in an `alarm` (or similar) so that we don't spend more than 1s calculating extremely large numbers.

Alternatively we could enforce a reasonable upper limit on the highest input we're willing to accept. Maybe 10,000? or something smaller, like 1000?

Any Perl experts out there interested in tackling this one?

---

IA Page: https://duck.co/ia/view/calculator

**Comment by jagtalon** [comment]
For the limiting the execution to 1s check out https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm#L121

**Comment by mintsoft** [comment]
Implementation in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927 uses `bfac`

**Comment by pjhampton** [comment]
Closing as this is no longer applicable
