### ISSUE TITLE
Vim Cheat Sheet: Should be triggered on "vi"

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1420]
This should be triggered on "vi cheat sheet", not just "vim cheat sheet", etc.

------
IA Page:  http://duck.co/ia/view/vim_cheat_sheet

**Comment by seisfeld** [comment]
There is actually a separate Vi Cheat Sheet already. It was merged to master by @moollaza a couple days ago: https://github.com/duckduckgo/zeroclickinfo-goodies/commit/fba090a37a3e6e358d4c84dde6e90724664ca42e It's just not live in production yet.

**Comment by tagawa** [comment]
Thanks @seisfeld, that'll do nicely.
