### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by marzig76** [duckduckgo/zeroclickinfo-goodies#1421]
Converting bytes to larger orders of magnitude doesn't work properly.  For instance 8,000,000,000 bytes is showing up at 8GB, when in reality, it's 7.45058GB

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by marzig76** [comment]
A gigabyte is really 1,073,741,824 bytes (1024*1024*1024)

**Comment by mintsoft** [comment]
@marzig76 thanks for the report; conversion of binary prefixes is also supported currently: https://duckduckgo.com/?q=8000000000+bytes+in+gibibytes&t=debian&ia=answer

**Comment by mintsoft** [comment]
Reference: https://en.wikipedia.org/wiki/Binary_prefix

**Comment by marzig76** [comment]
@mintsoft 

I guess it's debatable.. The 4th sentence in the link you provided says "gigabyte customarily means 1073741824 bytes."

The wiki page you provided link also links to the JEDEC memory standards which is what I was referring to:

"The specification cites three prefixes as follows:
    kilo (K): A multiplier equal to 1024 (210).
    mega (M): A multiplier equal to 1048576 (220 or K2, where K = 1024).
    giga (G): A multiplier equal to 1073741824 (230 or K3, where K = 1024)."

https://en.wikipedia.org/wiki/JEDEC_memory_standards#Unit_prefixes_for_semiconductor_storage_capacity

I just think this standard is much more frequently used.. But it is useful to know that I can use the "gibi" prefix.. Thanks for pointing that out..

**Comment by moollaza** [comment]
@marzig76 @mintsoft are we agreed then? Shall I close this and mark it as tolerated? I think seeing as we offer the Gibibyte conversion this is OK.

Perhaps we should add a "more at" link to the relevant wiki page for the converted to unit in the future so it's clear what unit we're using?

**Comment by marzig76** [comment]
Yea, that's fine.  You can close it out.
