### ISSUE TITLE
XCode Cheat Sheet: Use ⌘ instead of "Command"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1433]
It might look nicer to use ⌘ instead of "Command" in the cheat sheet.

![screen shot 2015-08-25 at 8 18 17 am](https://cloud.githubusercontent.com/assets/81969/9466307/e7153018-4b01-11e5-948a-1117e77835f8.png)

**Comment by seisfeld** [comment]
I implemented this change on #1434 for everyone to review.

**Comment by jagtalon** [comment]
Fixed by @seisfeld in #1434
