### ISSUE TITLE
IA for converting from binary -> decimal

### ISSUE THREAD

**Issue by jgkamat** [duckduckgo/zeroclickinfo-goodies#1435]
Right now, there seems to be the [base goodie](https://duck.co/ia/view/base) for converting decimal -> any base, and the [binary goodie](https://duck.co/ia/view/binary), which converts any base into binary. 

I want to work on a goodie to type '1001 in decimal' (or maybe just '1001') and have a IA that gives back 9. I'm not sure if this functionality should be added to the base/binary goodies or create a new (frombinary?) goodie.

This goodie would have to deal somehow to determine if an input was unsigned or two's compliment (I think unsigned should be the default, but two's compliment should be accessible via adjusting your query).

Example query: https://duckduckgo.com/?q=01010001+in+decimal
Desired IA: 81

Feedback would be appreciated! Thanks!

**Comment by mintsoft** [comment]
@jgkamat Sounds good on the whole; I'd probably try and extend the `base` goodie at the moment as it's something which can be easily from the regex inplace. 

I would expect the input to be regarded as unsigned, unless I explicitly say signed: `101001 signed in decimal` for example. Although inside the output, it should state this so the user is able to understand how it's been parsed.

If you need any help with any implementation details, open a PR and myself/someone else from the community will swing in to help!

**Comment by jgkamat** [comment]
Sure thing, I'll try to find time to work on this over the next couple of weeks. I'll try and modify the base goodie first, but If I can't find a way to do that, I'll create a new goodie.

Thanks! :smile:
