### ISSUE TITLE
 CSS Cleanup: Remove any ie8 Specific CSS (IE8 no longer supported!)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1445]
Now that we no longer support IE8, we can remove any legacy CSS written for backwards compatibility :)

Looks like there's not too much...

```
$ ack "ie8"
share/goodie/frequency_spectrum/frequency_spectrum.css
2:.ie8-display-none {

lib/DDG/Goodie/FrequencySpectrum.pm
639:<!--[if lte IE 8]><div class="ie8-display-none">
```

This IA should really be converted to use a builtin template. Given the custom UI, its OK to use the `base` tempate ;)

**Comment by mintsoft** [comment]
:tada: !
