### ISSUE TITLE
TimezoneConverter: Some results are "too" friendly

### ISSUE THREAD

**Issue by fardelian** [duckduckgo/zeroclickinfo-goodies#1451]
I tried to convert "5 AM EDT" to my time zone and I got "Noon EEST". It took me a while to notice the word because I was looking for a HH:MM time stamp. Please always give the exact time as the main text and use smaller text for the more friendly "noon".

![image](https://cloud.githubusercontent.com/assets/507634/9556739/aaaeb03c-4ddf-11e5-88da-c30c4b53e7b7.png)

---

IA Page:  http://duck.co/ia/view/timezone_converter

**Comment by moollaza** [comment]
@fardelian thanks for the feedback! If you're interested in fixing this yourself, the code is all open source!

**Comment by mintsoft** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/TimezoneConverter.pm :)

**Comment by tossj** [comment]
@moollaza Can I be assigned this task?
