### ISSUE TITLE
Cheat Sheets Terminal Template: Long text causes columns to overlap

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1457]
Looks like we'll need to adjust our CSS a bit to prevent this.

/cc @alohaas 

![duckduckhack](https://cloud.githubusercontent.com/assets/873785/9561731/0df8b6e8-4e20-11e5-9d48-39de028e12e3.png)

**Comment by alohaas** [comment]
Yuck! I can take care of this @moollaza

**Comment by moollaza** [comment]
@alohaas thanks a lot! :+1:
