### ISSUE TITLE
RandomNumber: bounds are ignored if lower bound is 0

### ISSUE THREAD

**Issue by null-minus-null** [duckduckgo/zeroclickinfo-goodies#1466]
When the lower bound is zero, the upper bound is ignored and instead of the expected integer, a float between 0 and 1 is generated.

Example links:
* [random 0 100](http://ddg.gg/?q=random+0+100)
* [random 0 10000](http://ddg.gg/?q=random+0+10000)

------
IA Page:  http://duck.co/ia/view/random_number

**Comment by loganom** [comment]
I'll look at this.

**Comment by mintsoft** [comment]
closed by @loganom in #1490
