### ISSUE TITLE
Support for multiple sourceNames in metadata in cheatsheets

### ISSUE THREAD

**Issue by anistark** [duckduckgo/zeroclickinfo-goodies#1468]
Many a times we take from multiple sources references and yet the cheatsheet format only has space for one alone. It should be able to render multiple sources in metadata object for cheatsheet goodies.

------
IA Page: https://duck.co/ia/view/cheat_sheets

**Comment by gautamkrishnar** [comment]
:+1: good suggestion

This can be implemented by giving a '+' icon next to the source link and giving a new link as name "even more",

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
