### ISSUE TITLE
ColorCodes: Problem with #000000

### ISSUE THREAD

**Issue by leowzukw** [duckduckgo/zeroclickinfo-goodies#1473]
We have some trouble with color #000000. See https://duckduckgo.com/?q=%23000000&ia=answer

Complementary and Analogous color are strange.

------
IA Page:  http://duck.co/ia/view/color_codes

**Comment by mintsoft** [comment]
@leowzukw is it the complementary and analogous colours?

**Comment by leowzukw** [comment]
@mintsoft Yes it is (I updated my issue since that)

**Comment by mintsoft** [comment]
Ah Yes, I know about this. It's any colour that's greyscale (i.e. 000 -> fff). Would you prefer the section be hidden?

**Comment by leowzukw** [comment]
Yes why not.

**Comment by moollaza** [comment]
@chrismorast @abeyang thoughts? Should we hide the complementary/analogous sections when they're the same as the searched colour?

**Comment by mintsoft** [comment]
@moollaza I've implemented it to hide the section whenever there's no hue or saturation. In these situations there's essentially there's no "colour" value to calculate any complements from
