### ISSUE TITLE
Support for active links in cheat sheets

### ISSUE THREAD

**Issue by alohaas** [duckduckgo/zeroclickinfo-goodies#1476]
cc: @bsstoner @sdougbrown @moollaza @mintsoft @abeyang 
I was about to dive into creating the [nodejs tutorials cheat sheet](https://duck.co/ideas/idea/6178/getting-started-with-nodejs) when I realized that it would be so nice to be able to add active links to cheat sheets. This functionality currently does not exist.

I can think of two approaches to this:
1. Create a 'links' template where either the key or value could be specified as an href value.
2. Allow inline links to be added to any cheat sheet key or value in a quasi-markdown type way...

What are your thoughts on these options?

**Comment by jagtalon** [comment]
:+1: I think this sounds good!

**Comment by mintsoft** [comment]
I think 1 is my preference, it's more declarative and means that if we wish to render links differently in the future (i.e. with icons or something) then we can

**Comment by mintsoft** [comment]
Also https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1454 will be an awesome fit for this when this is implemented.

**Comment by moollaza** [comment]
@alohaas I think that both 1 and 2 could be implemented, but 2 is more difficult.

I think going with a dedicated "Links" template works for now, but ultimately we may want to be able to allow links in the keys/values of other templates (or at least the `vals`)

**Comment by bsstoner** [comment]
:+1: Good idea!

**Comment by alohaas** [comment]
Thanks for the feedback everyone!
I'd like to take a first pass at this by modifying the reference sheet template a little so that the key will render as a link and we can go from there...

**Comment by alohaas** [comment]
@moollaza / @mintsoft @bsstoner 

See the attached images for an idea of my implementation. I'm ready for a PR if it looks good. Since I've got a new Cheat Sheet as well as an enhancement, I was thinking I could break the PR into two PRs, though maybe that's overkill...what would you prefer? I'll fill out the IA submission either way!

<img width="1312" alt="screen shot 2015-08-29 at 5 14 02 pm" src="https://cloud.githubusercontent.com/assets/4480279/9564342/01409e50-4e72-11e5-9056-94ab78c5403c.png">
<img width="1047" alt="screen shot 2015-08-29 at 5 16 08 pm" src="https://cloud.githubusercontent.com/assets/4480279/9564344/05273682-4e72-11e5-8e6e-c239e4a40a25.png">

**Comment by mintsoft** [comment]
Cool; so this is basically the 'meta-cheatsheet' idea, a kind of table of contents for links. LGTm

**Comment by alohaas** [comment]
Yeah! A limitation of the current implementation is that you loose the description text since both the key and val are dedicated to building the link. As a first pass, it works great!

Could make a cheat sheet cheat sheet for sure :)

**Comment by gautamkrishnar** [comment]
:+1: a must have feature..

**Comment by alohaas** [comment]
@moollaza I'd like to dig back into this if possible.
Has there been further discussion about implementation, specifically if there should be a third key/val pair in each object for the sections to specify an href?

**Comment by abeyang** [comment]
@alohaas visually, I think what you have there is fine for now. Internally (and separately), we are working on ways to better display links (both active and visited states), so we'll update this once we figure that out. Thanks!

**Comment by abeyang** [comment]
^ cc @moollaza

**Comment by alohaas** [comment]
@abeyang thanks for the feedback!
