### ISSUE TITLE
Mac keyboard cheat sheet: Rename to "Apple Mac OS Cheat Sheet"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1498]
The following should be changed as well:

- `id`: change to `apple_mac_os_cheat_sheet` (to match or other Operating System Cheat Sheets)
- `name`: change to `Apple OS X`
- `description`: update to specify which versions of Mac OS this applies to
- filename: changed to `apple-mac-os.json`
- `aliases`: add `osx`, `os x`, `mac`, `apple mac`, etc...

------
IA Page:  http://duck.co/ia/view/mac_keyboard_cheat_sheet

**Comment by gautamkrishnar** [comment]
@moollaza  shall i work on it?

**Comment by seisfeld** [comment]
@moollaza I dunno what policy is in place when an issue is going to be closed. But i was tempted a couple times now to fix this myself, every time i see this in the overview although its already fixed in #1506 :smile:

**Comment by gautamkrishnar** [comment]
@seisfeld Hehehe sorry for that :smile: 
@moollaza can you close this issue?

**Comment by mintsoft** [comment]
@seisfeld normally they're closed as soon as the fix is merged into master. Sometimes they get missed  so if you spot any just ping someone and we can close it :)
