### ISSUE TITLE
Conversions: Rounding too generous

### ISSUE THREAD

**Issue by abrahimladha** [duckduckgo/zeroclickinfo-goodies#1517]
I feel like the rounding is way too generous. For example:
"1.3mm to m" returns "0.001 meters"

---

IA Page:  http://duck.co/ia/view/conversions

**Comment by moollaza** [comment]
@abrahimladha can you clarify what you'd expect to see instead?

**Comment by abrahimladha** [comment]
IMHO 1.3mm should have converted to 0.0013m instead, and Its really all to do with how many significant digits are displayed. I got a physics homework question incorrect because I didn't know my metric conversions eh heh heh. 

I found a similiar issue here https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1132 by you about significant digits. 

I don't think its that hard. It looks as simple as this https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm#L109 and lower. 
I think I will try to fix it and submit a pull request.

**Comment by GuiltyDolphin** [comment]
@mintsoft @abadojack What's the situation with this? The response is still the same so it is still relevant.

**Comment by mintsoft** [comment]
@GuiltyDolphin I'm just holding off on this atm until I get the templated version merged https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2044 so I can finish the interactive

**Comment by GuiltyDolphin** [comment]
@mintsoft Got it.
