### ISSUE TITLE
Conversions: Add support for "microgram" abbreviation

### ISSUE THREAD

**Issue by SarahTehCat** [duckduckgo/zeroclickinfo-goodies#1523]
If you want to convert between `microgram` and another unit, you have to type out "microgram".

So, for example, if you searched `50 μg to mg`, [instant answers wouldn't work](http://i.imgur.com/4TI7VxV.png?1); but if you searched for `50 micrograms to mg`, [it'd work just fine](http://i.imgur.com/99xyBoN.png?1).

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
Apologies for the delay @SarahTehCat ! This is absolutely do-able :+1: and should be pretty easy. If you're interested in doing it yourself at all, the code is all open source (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm)! Although I believe this will probably require alterations in Convert::Pluggable (https://github.com/elohmrow/Convert-Pluggable)

cc @elohmrow

**Comment by SarahTehCat** [comment]
No worries. I would've preferred a sooner reply, but I know this is a community, and thus volunteer, support thingy, so it happens. :)

Anyway, I would love to do it myself, but I'm only still a beginner in code. I'm still learning. ;)

**Comment by elohmrow** [comment]
@mintsoft plz let me know if anything needs to be changed in C::P to maintain compatible.
