### ISSUE TITLE
Add dns.watch DNS servers to public_dns

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/zeroclickinfo-goodies#1524]
Recently came across https://dns.watch which provides DNS servers/resolvers without any kind of censorship etc. Can we add them to the public_dns goodie?

![screenshot from 2015-09-05 23 52 50](https://cloud.githubusercontent.com/assets/357253/9700679/3c725eb6-5429-11e5-9d2a-fe0690396c9f.png)

**Comment by mintsoft** [comment]
@iambibhas Just chuck them into: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/public_dns/providers.yml 

Easy as!

**Comment by iambibhas** [comment]
@mintsoft will do as soon as I fix this problem with setting up duckpan https://github.com/duckduckgo/p5-app-duckpan/issues/270
