### ISSUE TITLE
Cheat Sheets: "Show More" underline color

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#1531]
The 'Show More' link has blue underline that shows up on either side of the text after clicking it:

![screen shot 2015-09-08 at 3 48 20 pm](https://cloud.githubusercontent.com/assets/126358/9745644/2feff10c-5641-11e5-8e10-ff6e75bd9c99.png)

------
IA Page:  http://duck.co/ia/view/vim_cheat_sheet

**Comment by seisfeld** [comment]
What Browser on what OS do you see this? I'm running Safari 7.1.8 on OS X 10.9.5 and it looks okay:

<img width="725" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9606362/9756735/ad2418e2-56dc-11e5-9e99-f05a6528c625.png">

**Comment by moollaza** [comment]
Can confirm I'm seeing it on Chrome, OSX. @bsstoner @sdougbrown any ideas what could be doing this? Seems almost like a browser bug? If you change the CSS for the element, and then switch it back, the problem goes away, like the browser needs to re-draw things.

**Comment by Jedidiah** [comment]
I can see it in Chrome too, I think you're correct about it need to redraw; 

If you add `text-shadow: transparent 0 0 0;` to `.chomp--link__mr` and `.chomp--link__ls` makes the issue go away, as does making them inline-block rather than inline.

**Comment by bsstoner** [comment]
Why don't we have the same issue with that link in the other non-cheatsheet IA's? i.e. https://duckduckgo.com/?q=duckduckgo&ia=about

**Comment by Jedidiah** [comment]
Maybe something todo with the animated transition when you expand the cheatsheet. The about DDG pane just opens instantly.

**Comment by altern8tif** [comment]
Is this still a problem?  I'm running Chrome 46 on OSX and the problem seems to have gone away.

**Comment by bsstoner** [comment]
@altern8tif Thanks, you're right, this doesn't seem to be an issue anymore, closing.
