### ISSUE TITLE
Photoshop cheat sheet: delete selections

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#1548]
Selections section doesn't exist
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/photoshop.json#L16

------
IA Page:  http://duck.co/ia/view/photoshop_cheat_sheet

**Comment by seisfeld** [comment]
This is also fixed in #1549 so this one can also be closed.

**Comment by mintsoft** [comment]
Thanks for the fix & reminder @seisfeld

**Comment by seisfeld** [comment]
Your're welcome. :)
