### ISSUE TITLE
Relative Cost of Living IA

### ISSUE THREAD

**Issue by epik** [duckduckgo/zeroclickinfo-goodies#1551]
If I search "Relative Cost of Living Paoli, PA" (or other places that don't seem to be in Expatistan's database) it shows the Cost of Living index for LA.  The IA seems like it needs a catch if the location is not in the database to not show or something like that.

**Comment by mintsoft** [comment]
@epik Thanks for the report, however this is on the wrong repo; however I've mirrored the issue request in the right place:
