### ISSUE TITLE
Password: Hard to trigger

### ISSUE THREAD

**Issue by b1ake** [duckduckgo/zeroclickinfo-goodies#1565]
It would great to expand the triggering for this IA. I couldn't figure out how to trigger it until I found the IA page, which a random user probably wouldn't do.

Some queries I tried:

- generate password
- generate strong password
- generate random password
- password generator
- random password generator
- random strong password
- random password 16 characters
- create random password

-----
IA Page: https://duck.co/ia/view/password

**Comment by moollaza** [comment]
@b1ake these are great suggestions, and should be fairly easy to handle :+1:

**Comment by b1ake** [comment]
Nice!
