### ISSUE TITLE
Zodiac: Switch to Icon template, use new icons

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1595]
Similar to the Chinese Zodiac Goodie, this IA should now be converted to use the Icon template, and should use the new icons we've made:

The icons can be found here: http://cl.ly/0p303X0N1B1k

The icons should use the background colours outlined in the image below. 

**Note** Remember to set the background colour using our `elClass` property and the `bg-clr--XXXX` named classes.

**More details here:** https://duck.co/duckduckhack/templates_reference#directly-specifying-classes

![overview](https://cloud.githubusercontent.com/assets/873785/9993846/023127de-6048-11e5-87d0-b765690fbeb2.png)

**Comment by thm** [comment]
@moollaza sorry, I forgot to include those! That would be:
Water = $blue-light
Earth = $green
Fire = $red
Air = $grey

**Comment by Mailkov** [comment]
@mollaza @thm 
In your zip file there are two errors: file named Aquarius is instead Gemini and file named Gemini is not present.

**Comment by moollaza** [comment]
> In your zip file there are two errors: file named Aquarius is instead Gemini and file named Gemini is not present.

@Mailkov apologies! @thm can you send me the Gemini icon?

**Comment by thm** [comment]
@moollaza @Mailkov My bad, here's the updated set: http://cl.ly/0p303X0N1B1k

**Comment by Mailkov** [comment]
@moollaza Let me know if it is okay.
