### ISSUE TITLE
CurrencyIn: The currency in Poland is the Polish zÅoty (PLN)

### ISSUE THREAD

**Issue by arty-name** [duckduckgo/zeroclickinfo-goodies#1599]
If you search for "[what is the currency of poland](https://duckduckgo.com/?q=what+is+the+currency+of+poland&t=canonical&ia=answer)" the answer will be "The currency in Poland is the Polish zÅoty (PLN)", while it should be "The currency in Poland is the Polish złoty (PLN)"

IA Page:  http://duck.co/ia/view/currency_in

**Comment by arty-name** [comment]
![ddg-pln](https://cloud.githubusercontent.com/assets/133055/10041331/d796600a-61e3-11e5-8882-5b4ff92bced6.png)

**Comment by moollaza** [comment]
@arty-name thanks a lot for bringing this to our attention!

@Alchymista would you be free to investigate and fix this?
