### ISSUE TITLE
USPS: Should be triggering on "9536100030904162000148"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1621]
Currently, we're showing the FedEx IA which is incorrect:

https://duckduckgo.com/?q=9536100030904162000148&t=ffab&ia=answer

-----
IA Page: https://duck.co/ia/view/usps

**Comment by tagawa** [comment]
Same thing for these numbers, as reported on Twitter:
9361289877758119544505 9361289877737147963793 9361289877737147566833 9361289877724130267143 9361289877737145829022

**Comment by tekkub** [comment]
:bear: :heart: :feet:

**Comment by zekiel** [comment]
closeing per https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2845
