### ISSUE TITLE
Pull Request Template: Remove XP requirement?

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/zeroclickinfo-goodies#1625]
Seeing as XP has been unsupported for more than a year now, and that Microsoft has ditched IE, I think we should update the PR template to reflect those changes (add Edge rather than IE, delete all XP requirements).

**Comment by gautamkrishnar** [comment]
@javathunoderman  I think it need not to be removed. I had added windows 10 in my PR's..

@moollaza @mintsoft  what do you think about this? :smiley:

**Comment by javathunderman** [comment]
@gautamkrishnar thanks for the PR! 

@moollaza @mintsoft Can you weigh in?

**Comment by moollaza** [comment]
We're going to be removing the

**Comment by moollaza** [comment]
We're going to be updating these and removing them from the PR Template as it's now covered in the IA Pages, but I guess this is fine for now.

**Comment by gautamkrishnar** [comment]
:+1:
