### ISSUE TITLE
Rust Language Object Types Cheat Sheet: Switch to Reference template

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1626]
This should look much better with the Reference template!

------
IA Page:  http://duck.co/ia/view/rust_types_cheat_sheet

**Comment by gautamkrishnar** [comment]
@moollaza changed :+1:  :smile:

**Comment by gautamkrishnar** [comment]
@mintsoft i think this can be now closed!
