### ISSUE TITLE
infomation button is missing

### ISSUE THREAD

**Issue by sagarhani** [duckduckgo/zeroclickinfo-goodies#1629]
Information button is missing in [html cheat sheet](https://duckduckgo.com/?q=html+cheat+sheet&ia=cheatsheet&iax=1).

-----
IA Page: https://duck.co/ia/view/html_cheat_sheet

**Comment by moollaza** [comment]
@sagarhani thanks -- looks like there's no dev associated with the IA page. I'll update it

**Comment by moollaza** [comment]
Added in the dev. Should update with the next release & deploy.
