### ISSUE TITLE
Finish up 2048 Game, implement new design

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1637]
A while ago a PR for a new 2048 Game Goodie was started but eventually was abandoned: #1036 

We'd love to see this one go live, and we're hoping someone from the community is willing to help complete this Instant Answer.

We have a new design that needs to be implemented, which can be seen here:
![2048 - v2e](https://cloud.githubusercontent.com/assets/873785/13266001/eff40d7c-da43-11e5-8d16-487556bf7dce.jpg)

The color scheme isn't final, but it's a good start. Once a PR is made we'll work with you to refine the colours.

_More importantly though_, we **need** someone to refactor the JS code here. It's not fast/efficient (unnecessary looping), or well organized (heavily nested) and incorrectly implements event listeners (it doesn't relinquish control when needed).

If someone out there with has a good understanding of JavaScript, jQuery and Events is interested in tackling this please let us know!

**Comment by Roysten** [comment]
I would like to take a stab at this one. I already started working on it ;)

**Comment by moollaza** [comment]
IA is now live
