### ISSUE TITLE
Conversions: Year to Days should be accurate

### ISSUE THREAD

**Issue by CallMeLaNN** [duckduckgo/zeroclickinfo-goodies#1672]
Conversion years to days should not simply multiply by 356. We should include the fraction (remember we have leap year).

E.g.
DuckDuckGo: 5years to days = 1825 (365*5)
Manual calc 365.25*5 = 1826.25
More accurate = 1,826.2125
It supposed to show at least 1826 without the decimal place.

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
@CallMeLaNN Thanks for the report. 

We deliberately made the decision to use exactly 12 months and 365 days per year within Conversions (Conversation starts at: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/356#issuecomment-38604913). Essentially this is a for a few reasons:
* 5 years can mean a variety of durations depending on *which* 5 years it is we're discussing. For example 1st Jan 1897 -> 1st Jan 1902 was 1825 days, whilst 1st Jan 1997 -> 1st Jan 2002 was 1826.
* A year as a duration has a variety of definitions, in most Astronomical systems it refers to `365.25*86400` seconds exactly (a Julian Year)
* Similiarly for 'orbital' years, it could be either the Sidereal (365.256363004 days, where a day is 86400 seconds) or Tropical (365.242190402 days)

We're happy to re-evaluate this it appears confusing to users however.

cc @jagtalon @moollaza @elohmrow

**Comment by moollaza** [comment]
@mintsoft I'm with you. If we get more complaints we can change this, but I think this is fair.

For reference Google and WolframAlpha handle it this way as well. Interestingly Bing gives a decimal answer.
