### ISSUE TITLE
Currency Cheat Sheet: Add currency symbols to content

### ISSUE THREAD

**Issue by nemeth** [duckduckgo/zeroclickinfo-goodies#1690]
Because the Cheat Sheet Goodie allows ['symbols'](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/CheatSheets.pm#L23) as a trigger word the search term ['currency symbols'](https://duckduckgo.com/?q=currency+symbols) will display the currency cheat sheet, which - unfortunately- doesn't contain any symbol for the listed currencies. This behaviour might be confusing for the user.

-----
IA Page: https://duck.co/ia/view/currency_cheat_sheet

**Comment by amitdev** [comment]
Submitted pull request #1806.

**Comment by moollaza** [comment]
@amitdev thanks for making a PR. For future reference, if you put `Fixes #1806` in the description of your PR it will automatically ensure the issue is closed when the PR is merged, and make a note here that the issue was mentioned in your PR :+1:
