### ISSUE TITLE
CheatSheets: CheatSheets.pm should force lowercasing of aliases to ensure they always work

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1695]
We've updated the documentation to tell developers that they should only use lowercase letters, but we should also ensure that the `getAliases` function forces the aliases to be lower-cased so that everything still works and developers don't get frustrated.

We should probably print a warning if an uppercase alias is detected. We already do this in DuckPAN for any Spice/Goodies that have uppercase trigger words defined.

Here's the line that needs to be fixed: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/CheatSheets.pm#L49

**Comment by nemeth** [comment]
I made changes in  #1710.
Is [this the warning](https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/DDG.pm#L97) what you mean, @moollaza?

**Comment by moollaza** [comment]
@nemeth yup, that's the warning I was referring to :+1:

**Comment by moollaza** [comment]
I forgot that we were working on https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1668. This is probably the best place to put in a warning for uppercase aliases (also, uppercases in the keys like `metadata`, `sections`, etc.

**Comment by nemeth** [comment]
oh, thanks to point that PR! I'll take a look at it

**Comment by GuiltyDolphin** [comment]
@moollaza #2281 Has a test for uppercase characters in aliases; feel free to comment any other test suggestions there.

**Comment by GuiltyDolphin** [comment]
@moollaza Fixed in #2281 as the test was made critical - so aliases can no longer contain uppercase characters.
