### ISSUE TITLE
FontAwesome CheatSheet

### ISSUE THREAD

**Issue by soleo** [duckduckgo/zeroclickinfo-goodies#1696]
Would be nice to have a cheatsheet for FontAwesome in DDG as IA. 

Search query should be `fontawesome cheatsheet`

Display a list of icon names from fontawesome like https://fortawesome.github.io/Font-Awesome/cheatsheet/

Icon Name can be found in https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml

**Comment by moollaza** [comment]
@soleo thanks for posting this. It's best to post new IA ideas on the [Ideas Forum](https://duck.co/ideas) though, as we suggest developers go look there for new/unclaimed ideas.

**Comment by vikashvverma** [comment]
I will work on this.

**Comment by vikashvverma** [comment]
If we want to display this then we need to update the CSS (use content property) for few icons to be displayed in search.

I am working on that.

@moollaza Should I go ahead with this? Do you have any other suggestion?

**Comment by moollaza** [comment]
@vikashvverma this will require a new template, that displays icons, and will require internal changes to allow you to load the FontAwesome CSS

I would suggest you start with a new template that allows for an image to be defined, or a css class to be given, for an icon to be displayed. Let's see where that lands us and we can go from there.

**Comment by pjhampton** [comment]
Seems this is being taken forward here: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2256
