### ISSUE TITLE
Guitar Chords Goodie is suboptimal in dark theme

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#1699]
Lo,

I thought there was an issue for this already, and I think it's already being fixed:

![image](https://cloud.githubusercontent.com/assets/978048/10767029/1bf1acec-7cd2-11e5-9cd3-fdb8a7a0f88a.png)

Related: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1303

------
IA Page: https://duck.co/ia/view/chord_diagrams

**Comment by moollaza** [comment]
Ugh, this is bad. I don't think I had noticed this before, but once #1303 is finished this should be addressed.

**Comment by nalinbhardwaj** [comment]
@mintsoft Made a PR: #4083
