### ISSUE TITLE
SunInfo: feature request: change location

### ISSUE THREAD

**Issue by emilecantin** [duckduckgo/zeroclickinfo-goodies#1720]
I'd like to add "in MyCity" to search for sunrise / sunset times in a specific city (not my location).

------
IA Page:  http://duck.co/ia/view/sun_info

**Comment by moollaza** [comment]
@emilecantin searching by city is already supported, however we don't yet have support for most cities. Right now because of how things are setup you can only search for the sunrise in a country or a capital city.

https://duckduckgo.com/?q=sunrise+in+australia&ia=answer
