### ISSUE TITLE
Dice: Does not roll if "d" comes after math sign

### ISSUE THREAD

**Issue by willhopkins** [duckduckgo/zeroclickinfo-goodies#1742]
@loganom: 9+2d6 is not parsed as dice, while 2d6+9 is.

------
IA Page:  http://duck.co/ia/view/dice

**Comment by loganom** [comment]
Hi @willhopkins, I'm not sure if 9+2d6 was originally considered.

Would you expect to have seen two separate series of dice rolls? ie. 9d6 and then 2d6? or would you have expected to see 11d6?

**Comment by willhopkins** [comment]
Solid question. I would have expected it to be parsed as 2d6+9, but I see why that might be challenging. I guess my assumption here is that I interpret anything not in dice notation as a modifier to be added to the dice total.

**Comment by loganom** [comment]
I definitely think that it's an issue that the dice IA is not being triggered. Now i'm just wondering what we should be parsing it as. I think that your expectation is appropriate, but i'm also wondering if others may think that they would be getting two separate dice rolls.

@moollaza ?

**Comment by loganom** [comment]
Nice catch @willhopkins

**Comment by mintsoft** [comment]
@loganom you're right that it's not triggering Dice.pm for this case. The regex here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Dice.pm#L103 will prevent it from matching. 

It looks pretty trivial to alter the Regex to support this query however.

**Comment by willhopkins** [comment]
If you guys want a pull request, happy to contribute it this weekend.

**Comment by loganom** [comment]
@willhopkins If you have interest, that sounds good. If no one has picked it up in a week or so, i'll take care of it.

**Comment by willhopkins** [comment]
@loganom I'm pursuing it now.

Full disclosure: I work for Google, so I need to make sure I follow any internal rules before submitting code, and make sure the patch will be accepted by DDG as well.

**Comment by moollaza** [comment]
> and make sure the patch will be accepted by DDG as well.

@willhopkins hey there! I'd be happy to accept your PR :smiley: Thanks for the interest in DuckDuckHack, and for contributing!

**Comment by maxau** [comment]
I researched this as my first potential contribution and have an *untested* version working similar to how the current version of Dice behaves when the "d" or "w" are in front of the plus (+).  

Based on this [Wikipedia article on dice notation](https://en.wikipedia.org/wiki/Dice_notation), the current behavior is expected:
>To this basic notation, an additive modifier can be appended, yielding expressions of the form,
>AdX+B. The plus is sometimes replaced by a minus sign ("−") to indicate subtraction. B is a 
>number to be added to the sum of the rolls. So, 1d20-10 would indicate a roll of a single 20-sided 
>die with 10 being subtracted from the result.

The article also mentions a **multiplier** which I may add (although I first need to follow up on protocol) after tests for this modification are finished:
>In some games, the above notation is expanded to allow for a multiplier, as in AdX×C or C×dX, where:
>
>**×** denotes multiplication, and can be replaced by "/" or "÷" for division.
>**C** is a natural number (1 if omitted).

**Comment by willhopkins** [comment]
I need to drop this. Good luck to @maxau and the others with the patch!

**Comment by netoeuler** [comment]
Is @maxau fix this? If not, I can try.

**Comment by netoeuler** [comment]
Is this really a bug? In this Wikipedia link say that the regex of sum is AdX+B, if 9+2d6 were valid the regex would be (AdX+B | B+AdX).
