### ISSUE TITLE
ResistorColors: More at link is broken

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-goodies#1751]
@HackOrQuack 

------
IA Page:  http://duck.co/ia/view/resistor_colors

**Comment by jagtalon** [comment]
Links to resistor colors seem to be working. @mintsoft @moollaza verify?

<img width="1552" alt="screen shot 2015-11-14 at 1 30 42 am" src="https://cloud.githubusercontent.com/assets/81969/11162433/5e9cc5ea-8a6f-11e5-82b0-0d58694bd87e.png">

**Comment by mintsoft** [comment]
@jagtalon works for me too

**Comment by mintsoft** [comment]
@chrismorast any more information you could offer? I've checked a few different values etc and it's working consistently for me

**Comment by chrismorast** [comment]
yeah, seems to be working now for me as well. As always, thanks for looking into it @mintsoft !
