### ISSUE TITLE
Conversions: Cups not triggering on production

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1754]
For example this query doesn't trigger a conversion:
https://duckduckgo.com/?q=4+cups+in+quarts

Although cups seem to be in the upstream code:
https://github.com/elohmrow/Convert-Pluggable/blob/33c0275e0b358ac841b4a10a3915dc18b1cb6307/lib/Convert/Pluggable.pm

**Comment by mintsoft** [comment]
@tagawa I've just checked this and the goodie fires correctly, however it doesn't in production!

![image](https://cloud.githubusercontent.com/assets/978048/11192742/ad87bd7c-8c9a-11e5-95d1-568689a8b1e9.png)


@moollaza @jagtalon I can't debug this any further from here; it looks like a live-only problem!

**Comment by moollaza** [comment]
@mintsoft I suspect our version of Convert::Pluggable is behind in production. Will make a task
