### ISSUE TITLE
goodie proposal: gms of sugar in teaspoons.

### ISSUE THREAD

**Issue by hemanth** [duckduckgo/zeroclickinfo-goodies#1761]
@moollaza A new proposal to show gms of sugar in teaspoons.

For example:

![screen shot 2015-11-14 at 19 57 46](https://cloud.githubusercontent.com/assets/18315/11163993/01d10b00-8b0a-11e5-83e9-fbe8382aeee2.png)

What say?

This time I shall do a local setup and be uber fast ;)

Update: the values are from [webmd](http://www.webmd.com/food-recipes/sugar-shockers-foods-surprisingly-high-in-sugar)

**Comment by moollaza** [comment]
@hemanth seems like this kind of query should be handled by our existing conversions Instant Answer -- I would suggest you investigate improving that one. Support for kitchen measurement units may need to be added to `Convert::Pluggable` first though

**Comment by hemanth** [comment]
@moollaza Cool, I didn't noticed the [Conversions](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm) goodie, will improve the same.

BTW is there any setup script to set this up locally? Or do I just `cpan App::DuckPAN` clone the repo and do a `duckpan server`? Last time I was stuck with codio that hindered the velocity.

What's with `zeroclickinfo-spice` ?

**Comment by moollaza** [comment]
@hemanth yes you can install Duckpan locally: https://github.com/duckduckgo/p5-app-duckpan#installing-duckpan-locally

Spice is for API powered Instant Answers. You can read all about them and walk through tutorials in our docs.

We actually have a beta version of the docs available if you'd like to try them out: https://talsraviv.gitbooks.io/duckduckhackdocs/content/

**Comment by hemanth** [comment]
Sweet! Thanks.

**Comment by hemanth** [comment]
@moollaza Did a setup on my VM, where can find the source of [this](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm#L29) is it an external deps? (Doesn't seem line, grep could find it for me)

**Comment by mintsoft** [comment]
@hemanth It's on cpan: https://metacpan.org/pod/Convert::Pluggable

**Comment by hemanth** [comment]
@mintsoft Cool, hmm so I must do a PR to `Convert::Pluggable`.

**Comment by GuiltyDolphin** [comment]
@mintsoft @hemanth Conversions is fully-local now, so we should re-evaluate the situation, with the likely outcome of being able to implement this locally.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
