### ISSUE TITLE
Cheat Sheet export

### ISSUE THREAD

**Issue by arwk** [duckduckgo/zeroclickinfo-goodies#1762]
It would be cool if you could export or print Cheat Sheets, for example formatted to fit a DIN A4 page.
A possibility to download the Cheat Sheet as pdf would be great either.
I tried to print the vi Cheat Sheet but the design didn't adjust to fit the page.
![vi-print-screenshot](https://cloud.githubusercontent.com/assets/14203899/11165586/cf992ec4-8b13-11e5-8aef-91a59c8a8fe3.png)

---
IA Page: https://duck.co/ia/view/cheat_sheets

**Comment by moollaza** [comment]
@arwk thanks for the suggestion -- I've never considered printing our IA's before.

Taking a screenshot should work though? Firefox (and I assume most other browsers) have a method of screenshotting the whole page (not just what's visible).

You could crop them -- or build a tool to query the page, and take a screenshot of just the Cheat Sheet's `<div>`

**Comment by arwk** [comment]
I admit that its not very common to print search results :wink:
Thanks for your hint of screenshotting the whole page, I never used such a function, but I'll give it a try!
Additionally it would be possible to build a small tool to parse the .json Cheat Sheet files to create a .pdf with LaTeX or something similar..

**Comment by moollaza** [comment]
> Additionally it would be possible to build a small tool to parse the .json Cheat Sheet files to create a .pdf with LaTeX or something similar..

@arwk that sounds like something the community should be able to tackle, using the GitHub API on their own!

**Comment by moollaza** [comment]
@duckduckgo/community-leaders what do you think of this idea?

I feel it's something anyone in the community would be welcome to build -- DDG doesn't need to own or maintain it.

@tagawa shall we tweet about the idea?

**Comment by mintsoft** [comment]
@moollaza sounds like a good idea, definitely feels like a community thing

**Comment by javathunderman** [comment]
@moollaza Yeah, this sounds great. Having an irl copy of a CheatSheet would be really useful.

**Comment by codenirvana** [comment]
@moollaza Good idea :+1:

**Comment by gautamkrishnar** [comment]
Yes! A really useful feature :+1:

**Comment by preemeijer** [comment]
:+1:

**Comment by tagawa** [comment]
This is a great idea. One approach is to do it as a web app (e.g. using gh-pages), for example:
1. Get the list of cheat sheets using the [GitHub API](https://api.github.com/repos/duckduckgo/zeroclickinfo-goodies/contents/share/goodie/cheat_sheets/json)
2. Get the ```download_url``` from the API feed
3. Use [PDF.js](https://mozilla.github.io/pdf.js/) or similar to convert the JSON to PDF
4. Celebrate!

**Comment by gautamkrishnar** [comment]
@tagawa sounds great! It will be one of our topics for the January hackathon which will be held on January 2016 by duckduckhack community kochi.
http://www.meetup.com/Quack-Hack-Kochi/

**Comment by tagawa** [comment]
@gautamkrishnar Cool. Shall I assign it to you so that we don't get duplicate PRs?

**Comment by gautamkrishnar** [comment]
@tagava Yup, sure.... :+1: :Smiley:

**Comment by tagawa** [comment]
Hah, looks like I can't assign it anyway! Nevermind, if people see this thread they can see that you plan to work on it. Thanks @gautamkrishnar, and let us know if you (or the devs at the meetup) need any help.

**Comment by gautamkrishnar** [comment]
@tagawa Yup... :smile: We will be happy to hack on it :smile:

**Comment by arwk** [comment]
How is the status of this feature?

**Comment by gautamkrishnar** [comment]
Sorry its not implemented yet...  @arwk can you work on it?
@GuiltyDolphin  what's your thought on this?

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Hmm... We could probably include a button to export the cheat sheet as a PDF, but I'm not 100% sure about the formatting.

@zachthompson Any thoughts?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
