### ISSUE TITLE
Calculator: Basic functions not recognized

### ISSUE THREAD

**Issue by airon90** [duckduckgo/zeroclickinfo-goodies#1765]
See the example:

`exp(0) - log(e) + sqrt(9) / tan(45°)` 

The result should be 1 - 1 + 3 / 1 = 3

Instead [no answer is returned](https://duckduckgo.com/?q=exp%280%29+-+log%28e%29+%2B+sqrt%289%29+%2F+tan%2845°%29)

The goody lacks of support to the following notations:
- [`exp(x)`](https://duckduckgo.com/?q=exp%283%29) ([`e^x`](https://duckduckgo.com/?q=e^3) is already supported) 
- [`TrigonometricalFunction(x°)`](https://duckduckgo.com/?q=sin%2845°%29) ([support to radians](%28https://duckduckgo.com/?q=sin%28pi%29%29) is already in the code)
- [`atan(x)`](https://duckduckgo.com/?q=atan%281%29) / [`arctan(x)`](https://duckduckgo.com/?q=arctan%281%29) (same with asin/arcsin and acos/arccos)
- [`HyperbolicTrigonometricalFunction(x)`](https://duckduckgo.com/?q=sinh%280%29) (`sinh`/`sh`, `cosh`/`ch`, `tanh`/`th`, `arcsinh`/`asinh`, `arccosh`/`acosh` and `arctanh`/`atanh`)

---

IA Page: http://duck.co/ia/view/calculator

**Comment by moollaza** [comment]
Looks like this is handled properly by the new API backed calculator. However `log` needs to be `ln`:

https://duckduckgo.com/?q=calculate+exp%280%29+-+ln%28e%29+%2B+sqrt%289%29+%2F+tan%2845%C2%B0%29&t=ffab&ia=calculator

I believe all the other functions are also handled by that calculator

**Comment by moollaza** [comment]
@Airon90 would you like to try more equations and get back to us? I can let the Symbolab team know if they're missing anything we think is necessary.

**Comment by Airon90** [comment]
Thank you very much! Now that I know that for advanced calculator I need to type "calculate" before the query I'm happier :)
I will try Symbolab as I just fell in love with it. If something doesn't work on DDG I will report it.
Thank you for your answer!
PS: I study mathematics at the University of Milan and in university we use ```log``` instead of ```ln``` ;) It is just a notation problem :)

**Comment by moollaza** [comment]
@Airon90 we could update the IA to replace `log` with `ln` in the query so your syntax would work :+1:

**Comment by Airon90** [comment]
I don't think that it should be replaced, as ln(x) equals to log_e(x).
I think that maybe a [calculator cheat sheet](https://duckduckgo.com/?q=calculator+cheat%20sheet) would be useful. Moreover a cheat sheet for every IA would be useful to understand every implemented functions. Don't you? :)

**Comment by moollaza** [comment]
>Moreover a cheat sheet for every IA would be useful to understand every implemented functions. Don't you? :)

I think that'd be overkill. The idea behind the IA Pages is that we should provide quality descriptions and example queries so users will understand how to use Instant Answers. Ideally they shouldn't require too specific a syntax, but in some cases it's a little hard to avoid

**Comment by GuiltyDolphin** [comment]
@moollaza, @Airon90, @mintsoft - see PR #1927 in which I have implemented some of this functionality and aim to add much more soon.

**Comment by mintsoft** [comment]
All suggested functionality is implemented in : https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927
