### ISSUE TITLE
Add support to complex number

### ISSUE THREAD

**Issue by Airon90** [duckduckgo/zeroclickinfo-goodies#1766]
* Multiplication: ```(a + ib)(x + iy)``` → ``ax - by + i(bx + ay)``` 
* Real part:  ```a + ib``` → ```a```
* Imaginary part:  ```a + ib``` → ```b```
* [Conjugate](https://en.wikipedia.org/wiki/Complex_conjugate):  ```a + ib``` → ```a - ib```
* Division: ```(a + ib)/(c + id)``` = ```(ac - bd)/(c²+d²) + i (bc - ad)/(c²+d²)```

----

IA Page: http://duck.co/ia/view/calculator

**Comment by moollaza** [comment]
@Airon90 we have a new "Advanced Calculator" that should be able to handle these queries. The triggering is limited right now while we evaluate it, but if you start a query with `calculate <equation>` it should work!

**Comment by Airon90** [comment]
Thank you! So I have to type "calculate" to trigger the advanced calculator. Moreover I didn't know about Symbolab. Are you going to merge Symbolab into calculator? Thank you again!

**Comment by moollaza** [comment]
We're working on relaxing the trigger so the Perl calculator can fallback onto the Symbolab calculator. For now it requires the "calculate"  or "solve" trigger words.

We can't merge the code, but I hope to merge the frontend eventually so it looks uniform
