### ISSUE TITLE
Language cheat sheets should be triggered with the keyword "phrases"

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1770]
In other words, instead of having to type "german phrases cheat sheet", the IA should be triggered with only "german phrases".

**Comment by GuiltyDolphin** [comment]
Hey @tagawa, we can do this as of #2170! Check it out: https://duckduckgo.com/?q=german+phrases&t=ftas&ia=cheatsheet
