### ISSUE TITLE
Differential needed in example

### ISSUE THREAD

**Issue by Airon90** [duckduckgo/zeroclickinfo-goodies#1774]
Hi,
I saw the [first example of Symbolab](https://duck.co/ia/view/symbolab) and mathematically is incorrect because there isn't its differential in the integral: 

[```compute integral of x^2```](https://duckduckgo.com/?q=compute%20integral%20of%20x%5E2&ia=calculator) should be [```compute integral of x^2 dx```](https://duckduckgo.com/?q=compute+integral+of+x^2+dx&ia=calculator) as [```compute integral of x^2 dy```  is different](https://duckduckgo.com/?q=compute+integral+of+x^2+dy&ia=calculator)

**Comment by mintsoft** [comment]
Thanks for the report @Airon90 as this is a spice (uses an API) I've moved this issue to the Spice Repo: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2290
