### ISSUE TITLE
Description missing in IRC cheat sheet

### ISSUE THREAD

**Issue by sagarhani** [duckduckgo/zeroclickinfo-goodies#1776]
Description is missing in [IRC cheat sheet](https://duckduckgo.com/?q=IRC+cheat+sheet&ia=cheatsheet).
@moollaza Shall I add it ?

**Comment by codenirvana** [comment]
@sagarhani There are many cheat sheets without description, This is because the description added at the time of PR is  redundant or not describe about the cheat sheet well. 

If you have a better description that describes what the cheat sheet is doing than you must add :smile:

**Comment by sagarhani** [comment]
Oh Yes!
Now, I noticed that there are several other cheat sheets which don't have description.

**Comment by moollaza** [comment]
@sagarhani it would be nice to have descriptions for all the Cheat Sheets.

If you run `t/CheatSheets/CheatSheetsJSON.t` you'll see all the warnings for Cheat Sheets without descriptions
