### ISSUE TITLE
Automated screenshot for cheatsheet 

### ISSUE THREAD

**Issue by jophab** [duckduckgo/zeroclickinfo-goodies#1783]
#1758 this cheatsheet I changed the template type to 'keyboard' from 'reference' .But stills the new automated screen shot shows it in reference template.
But when we check the beta its in keyboard template

**Comment by gautamkrishnar** [comment]
@moollaza i think this feature need to be limited as daxtheduck is spmming pr with automated screenshots( probably one per commit )

What about changing the trigger as a command by mentioning daxtheduck in pr just like:
' @daxtheduck screenshot '

**Comment by moollaza** [comment]
@jophab thanks for reporting, we'll look into this
/cc @jdorweiler 

@gautamkrishnar right now I think it's OK -- we can remove any extra/unnecessary pictures from the conversation if that's what you're concerned with. The idea is that it gives a picture of the changes as new commits are pushed.

**Comment by moollaza** [comment]
I'm going to close this and create an internal task for the team to investigate the photo not showing the actual changes

**Comment by jdorweiler** [comment]
Thanks.  I'll look into the screenshots not being correct.  I could have it remove all the previous screenshot comments too.  That way a PR only has a single one.
