### ISSUE TITLE
Frequency Spectrum: Convert to use templates + JS

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1786]
Now that Goodies have access to templates, JS and CSS they should no longer generate and return HTML strings.

This IA is particularly bad because it also injects JS into the HTML. It should instead use templates and a separate JS file to handle modifying the DOM. It's also important that the JS fires using our `onShow()` event so that the timing is correct and we know the DOM is ready.

**Comment by Mailkov** [comment]
@moollaza I'm working on this

**Comment by moollaza** [comment]
Excellent :+1:
