### ISSUE TITLE
Re-implement ASCII Table Cheat Sheet

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#1789]
This is a pretty old internal instant answer and it needs to be moved as an open source goodie to match the "modern" look that we have. https://duckduckgo.com/?q=ascii+table&t=ffab

**Comment by jagtalon** [comment]
Another option for the look, you could use something similar to https://duckduckgo.com/?q=shruggie+and+friends&t=ffab&ia=shruggie

**Comment by moollaza** [comment]
I don't think we have a great way of doing this yet...

See my comment in #1788

**Comment by pjhampton** [comment]
We'll continue this here: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3991
