### ISSUE TITLE
CheatSheets: Java cheatsheet overlap on wide screens

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/zeroclickinfo-goodies#1816]
I'm not sure if this is just the Java cheatsheet or not, but I couldn't reproduce with other cheatsheets. I guess something to do with the line length here?

![screenshot_2015-11-25_16-03-02](https://cloud.githubusercontent.com/assets/1431577/11402390/8a7e54de-938f-11e5-80b1-af08ed53bbcc.png)

https://duck.co/ia/view/java_cheat_sheet

**Comment by moollaza** [comment]
Thanks for pointing this out! 

I didn't see all that HTML in there, but it shouldn't be there!

**Comment by moollaza** [comment]
My planned parser changes will fix this when the `<br>` are replaced with `/n`

**Comment by tagawa** [comment]
Seems to be OK now. Can anyone confirm?

**Comment by moollaza** [comment]
@tagawa uh-oh it looks like it hasn't been fixed!

@duckduckgo/duckduckhack-contributors would someone like to fix this? We need to remove the `<br>` tags in the HTML and replace them with `\n`. Likewise the multiple spaces in the string can be replaced with `\t` which will be converted to `&nbsp;&nbsp;&nbsp;&nbsp;` when the IA is displayed.

This is a super easy, but important fix!

**Comment by MoriTanosuke** [comment]
I will try to fix this.

**Comment by MoriTanosuke** [comment]
Sorry for the noise, I didn't know that Github would add commits on my repositories branch to this issue...

I tried to fix the issues mentioned by @moollaza, someone please have a look if I got everything right.

**Comment by moollaza** [comment]
@MoriTanosuke the fixes look pretty good. Please make a Pull Request so we can test them on Beta!
