### ISSUE TITLE
FedEx: Overlap with USPS tracking ID 

### ISSUE THREAD

**Issue by atomic1fire** [duckduckgo/zeroclickinfo-goodies#1828]
https://www.reddit.com/r/duckduckgo/comments/3uheyl/searching_for_usps_tracking_always_suggests_to/

https://duckduckgo.com/?q=9361289879010710383692&ia=answer

   Someone on reddit is having problems with a USPS tracking ID showing up as Fedex. 

Seems to work if you include USPS, but it's coming in as a Fedex ID. Maybe it's an overlapping tracking number?

---

IA Page:  http://duck.co/ia/view/fed_ex

**Comment by mintsoft** [comment]
Related: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/370 https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1621

**Comment by sumsted** [comment]
Saw this on reddit... I noticed this bug as well. The number given in the bug 93.... doesn't appear to be an overlapping fedex tracking number or what would be called smartpost. It doesn't pass the fedex tests but does pass the usps tests. I have a little experience identifying tracking numbers and lend a hand to look over the logic if you need it.

I just read bug 370, it refers to smarpost. You can actually look those up at either service though the availability of scans is different for each. Defect 1621 looks to be the same as this one.

**Comment by Xeddicus** [comment]
Bug is happening still it seems, same workaround required: add usps.

**Comment by moollaza** [comment]
Hey guys,  thanks for the feedback. We're currently building a unified package tracking instant answer using an API which will solve this problem.

**Comment by bsstoner** [comment]
Here's another example that was just reported where it's USPS tracking number but we're detecting it as FedEx: 9361289681090104850693

**Comment by moollaza** [comment]
Our new Package Tracking Spice is able to detect the carrier...but it's triggering requires the word "package", "tracking", etc.

We can replace several of the Package tracking Goodies, such as Fedex and USPS with the Spice if we adjust the triggers to also trigger on any/all of the courier tracking number patterns.

**Comment by bsstoner** [comment]
There has been A LOT of user complaints about this. What do we need to do to get it fixed?

These are all complaints from the past 2 weeks:

**9361289673090238917898**
[https://duckduckgo.com/?q=9361289673090238917898&kp=1&kad=wt_WT&kl=wt-wt&t=ffab](https://duckduckgo.com/?q=9361289673090238917898&kp=1&kad=wt_WT&kl=wt-wt&t=ffab)
_"Why does DDG return a link to FedEx when a USPS tracking number is input? i'm going back to Google until you folks get your defecation in configuration"_

**RB667864089RU usps**
[https://duckduckgo.com/?q=RB667864089RU%20usps&kp=1&kad=wt_WT&kl=us-en](https://duckduckgo.com/?q=RB667864089RU%20usps&kp=1&kad=wt_WT&kl=us-en)
_"BAD SEARCH RESULTS FOR TRACKING WITH ALL TRACKING NUMBERS - YOU NUMBSKULLS HAD IT WORKING LAST MONTH BUT NOW ITS FUCKED UP!"_

**9361289673090238917898**
[https://duckduckgo.com/?q=9361289673090238917898&kp=1&kad=wt_WT&kl=us-en](https://duckduckgo.com/?q=9361289673090238917898&kp=1&kad=wt_WT&kl=us-en)
_"What the fuck did you guys do? entering a USPS, UPS, or FedEx tracking number *used* to work, but now the results are FUCKED UP!!!!"_

**9361289676090263812691**
[https://duckduckgo.com/?q=9361289676090263812691&kp=-1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=9361289676090263812691&kp=-1&kad=wt_WT&kl=wt-wt)
_"Tracking code is USPS not Fedex"_

**9361289683090128318351**
[https://duckduckgo.com/?q=9361289683090128318351&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=9361289683090128318351&kp=1&kad=wt_WT&kl=wt-wt)
_"This is a USPS tracking number, not a FedEx one"_

**9361289683090130819020**
[https://duckduckgo.com/?q=9361289683090130819020&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=9361289683090130819020&kp=1&kad=wt_WT&kl=wt-wt)
_"Not FedEx, USPS"_

**Comment by bsstoner** [comment]
Can we fix the issue now without rebuilding the entire IA?

**Comment by mintsoft** [comment]
@bsstoner We can probably get away with it, I think what's happening is that there's a path in the FedEx IA which doesn't do any checksumming etc, for queries with a number > 9 digits (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/FedEx.pm#L37) which is presumably tripping up the USPS IA. 

I have no idea why that's there, if you take it out then the tests fail. However the tests are asserting on 22 digits numbers; so why can't we limit the input to 22 digits? I'm not convinced that the tests cover well enough here for me to remove it. Also being non-US I've not seen enough FedEx parcels for me to "know" if it's correct or not. According to: http://www.trackingmore.com/usps-tracking.html?utm_source=20161006_vanessa the USPS doesn't handle 22 character codes. So if we limit the FedEx to 22 chars, it'll get it out of the way of the USPS IA.

**Comment by bsstoner** [comment]
I'm on board with trying that.

**Comment by mintsoft** [comment]
@jagtalon If I remember correctly you were involved in the very first version of the FedEx/USPS; do you have any recollection as to why the first regex is there?

**Comment by moollaza** [comment]
> Can we fix the issue now without rebuilding the entire IA?

If we just port the regex triggers to the package tracking spice, the API will take care of figuring out the courier, and providing the correct information.

We just need to give the API the tracking number, it will do the rest.

I added "package" to each of those urls above to trigger the Spice and it got the right answer for all of them..

![9361289683090130819020_package_at_duckduckgo_and_9361289676090263812691_package_at_duckduckgo_and_9361289673090238917898_package_at_duckduckgo_and_rb667864089ru_package_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/22723029/13f43784-ed89-11e6-95c1-727e65124072.png)

**Comment by bsstoner** [comment]
Nice, that looks way better too! Can we switch over to that IA? Any blockers that I can help with?

**Comment by bsstoner** [comment]
**9400115901670883620130**
[https://duckduckgo.com/?q=9400115901670883620130](https://duckduckgo.com/?q=9400115901670883620130)
_Comment: This is a USPS shipping code. Only showing link toFedex._

**Comment by pjhampton** [comment]
Closing this. Described here: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3973
