### ISSUE TITLE
LaserShip: Regex trigger needs anchors to limit triggering

### ISSUE THREAD

**Issue by vanR** [duckduckgo/zeroclickinfo-goodies#1836]
Hi,

A DDG search for a LaserShip Tracking number in the form "1LS12345678999999999", results in a truncated tracking ID link link like so http://lasership.com/track/LS12345678 (no leading "1" truncated to 8 trailing digits).  This shortened URL results in a LaserShip validation error, "So sorry, the tracking number could not be located ...", whereas the full form, http://lasership.com/track/1LS12345678999999999 displays expected results.

------
IA Page:  http://duck.co/ia/view/laser_ship

**Comment by moollaza** [comment]
@vanR thanks for pointing this out!

It looks like the regex trigger for lasership needs to be adjusted as it's simply capturing the middle portion of the match. It needs to include anchors (`/^...$/`) so it only captures the shorter version, and needs to be adjusted to also capture longer versions.

Are you interested in fixing this?

**Comment by jonk1993** [comment]
Hi I included anchors so query "1LS12345678999999999" would not trigger the LaserShip IA, but I'm confused as to what you mean by "needs to be adjust to also capture longer versions." It seems like a typical LaserShip tracking number consists of two alphabet letters followed by eight digits. Is there a longer version this IA should capture?
