### ISSUE TITLE
Some triggering words not working for cheatsheet of 8086

### ISSUE THREAD

**Issue by jophab** [duckduckgo/zeroclickinfo-goodies#1841]
#1794 #1777 The only triggering word that triggers the cheatsheet is "cheat sheet".Others are not working.I am attaching screenshots too.
![4](https://cloud.githubusercontent.com/assets/13940974/11532362/6878ab7e-9929-11e5-8a75-797390a9a70e.png)
![6png](https://cloud.githubusercontent.com/assets/13940974/11532365/68946116-9929-11e5-83b5-6f18009de101.png)
![7](https://cloud.githubusercontent.com/assets/13940974/11532363/688a7c6e-9929-11e5-9752-ba69616b02a9.png)
![8](https://cloud.githubusercontent.com/assets/13940974/11532364/68915764-9929-11e5-8ae5-c00e32bcddb2.png)

**Comment by jophab** [comment]
Even 'cheatsheet','help' is not working.
But they are working  for other cheat sheets. Is there some problems ?

**Comment by jophab** [comment]
@mintsoft  @moollaza

**Comment by mintsoft** [comment]
@moollaza Just confirmed this; looks like a similiar problem that we had with the eclipse cheatsheet:

![cheatsheet](https://cloud.githubusercontent.com/assets/978048/11599853/1cce6364-9ac1-11e5-8eaf-230758b405f5.png)

**Comment by jophab** [comment]
@jdorweiler @moollaza 
I think this is a problem for cheatsheets with names as numbers.
same problem arises with 8085 cheatsheet
please checkout
https://beta.duckduckgo.com/?q=8085+cheatsheet

**Comment by moollaza** [comment]
Thanks guys. Will take a look today

**Comment by moollaza** [comment]
Found the bug. Working on a fix right now...

**Comment by moollaza** [comment]
Fixed here: https://moollaza.duckduckgo.com/?q=8086+symbols&ia=cheatsheet&iax=1

**Comment by jophab** [comment]
@moollaza :+1:
