### ISSUE TITLE
Cheat Sheets (Controller): Need to ensure aliases don't match existing cheat sheet names, or aliases

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1844]
CheatSheets.t (or similar) should test that the aliases for each cheat sheet don't match the name of an existing cheat sheet, or the aliases of an existing cheat sheet.

Names and aliases must be unique across cheat sheets.

For example `ubuntu.json` had `"aliases" : [ "ubuntu unity" ]`, while there was already an `ubuntu-unity.json` cheat sheet.

This caused ambiguity in triggering and so the tests failed randomly (depending which Cheat Sheet triggered).

------
IA Page:  http://duck.co/ia/view/cheat_sheets

**Comment by harisphnx** [comment]
Can't we add this check in the `continuous-integration/travis-ci/pr`. It will check through all the cheatsheets to check if the new one has any conflicting aliases, or there can be a list of all currently being used aliases also to check from.

**Comment by navneetzz** [comment]
we should ass this check in the continuous-integration/travis-ci/pr . By the way it should the task of developer to check the IA prorperly

**Comment by moollaza** [comment]
@harisphnx @navneetzz if CheatSheet.t is updated, then Travis will run the test :+1:

**Comment by harisphnx** [comment]
@moollaza, Tell me if any help is needed. :)

**Comment by moollaza** [comment]
@harisphnx @navneetzz if you guys would like to tackle the updates you're welcome to :+1:

**Comment by navneetzz** [comment]
@moollaza Ya I would like to
Say what we I can to do

**Comment by vCillusion** [comment]
Can't we have multiple IA being triggered by same query displayed with one being active?
