### ISSUE TITLE
Beta IA showing incorrect cheatsheet

### ISSUE THREAD

**Issue by jophab** [duckduckgo/zeroclickinfo-goodies#1848]
#1823 beta is showing c cheatsheet instead of c++ cheat sheet.
There are c and c++ cheatsheets in ia testing.Examples of both are showing c cheat sheet

![err](https://cloud.githubusercontent.com/assets/13940974/11552790/8e1d7cb2-99ae-11e5-9672-999dbd02bfb7.png)

**Comment by jophab** [comment]
@moollaza

**Comment by mintsoft** [comment]
@jophab If the query string is URLEncoded then it works correctly: https://beta.duckduckgo.com/?q=C%2B%2B+cheatsheet&ia=cheatsheet

Did you click a link that took you to that page?

**Comment by mintsoft** [comment]
@moollaza @jophab Just seen the link (https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1823#issuecomment-161338947) I'm guessing it's a Dax/Github integration issue. I'm not sure this is the right place for this as an issue but I also don't know where's best to put it!

**Comment by moollaza** [comment]
@mintsoft @jophab definitely seems like an encoding issue :+1: 

/cc @jdorweiler -- feel free to close this if you want to track it elsewhere!

**Comment by jdorweiler** [comment]
@jophab thanks, I'll get this fixed.

**Comment by jophab** [comment]
@jdorweiler can you check #1841 too

**Comment by jdorweiler** [comment]
@jophab I'll ask @moollaza.  I think he is working on that.

**Comment by jophab** [comment]
Okayy.. :+1:
