### ISSUE TITLE
Lower case Conversion goodie?

### ISSUE THREAD

**Issue by hemanth** [duckduckgo/zeroclickinfo-goodies#1849]
```
Detected potential UPPERCASE triggers in the following instant answers. If yours is listed, check it out! Only lowercase will work.
[
    [0] "DDG::Goodie::Conversions"
]
```

**Comment by mintsoft** [comment]
@hemanth That's due to a slight issue with Conversions and triggers. Technically conversions requires  that the triggers are case sensitive (i.e. S means siemens, whilst s means seconds); there isn't currently a 'good' way of dealing with this however

**Comment by hemanth** [comment]
Hmm, true, there won't be 'good' way unless we can predict what the user meant, say if the query is like: `60S in mins` we need to assume that the user meant second and not siemens.

**Comment by mintsoft** [comment]
We are currently evaluating new approaches for Conversions including a javascript implementation which would be interactive etc. I'd probably suggest ignoring this for now until we decide on the approach that we'll be taking

**Comment by hemanth** [comment]
:+1:
