### ISSUE TITLE
FR: caniuse goodie.

### ISSUE THREAD

**Issue by hemanth** [duckduckgo/zeroclickinfo-goodies#1854]
I am planning for a new goodie, `caniuse` that could be both a spice and a normal on, how do i decide?

It would be nice if we could use node modules for spices

//cc @moollaza @mintsoft

**Comment by mintsoft** [comment]
If caniuse has a JSON API then a spice would be the answer. If they don't then another way of getting the information is required. Sometimes people write scrapers to output yaml and then use a goodie to handle the display and triggering of it.

**Comment by hemanth** [comment]
There is no JSON API as such but the closest is [this](https://github.com/Fyrd/caniuse/blob/master/data.json) we can't use node module in spices yet?

**Comment by moollaza** [comment]
We have an existing CanIUse Fathead which could be updated. 

I suppose if you really wanted you could have it use the node module to provide all the info needed instead of scraping the website.

Fathead is ideal for this kind of info.

**Comment by moollaza** [comment]
A supplementary Spice could be used if they have a json search endpoint, but there's no way for it to use a node module right now.

**Comment by hemanth** [comment]
Was asking because there is this [caniuse](https://www.npmjs.com/package/caniuse-api) which internal uses `caniuse-db` the link I had mentioned [above](https://github.com/Fyrd/caniuse/blob/master/data.json) is there an alternative to have the endpoint available on of the DDG API servers?

I missed looking into FatHead, will check that out.

**Comment by hemanth** [comment]
Oh cool, [caniuse](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/share/fathead/caniuse)!

BTW I tried searching for `caniuse fetch`, before creating that issue, it did not return anything for `caniuse fetch`

 :+1:

**Comment by moollaza** [comment]
>Was asking because there is this caniuse which internal uses caniuse-db the link I had mentioned above is there an alternative to have the endpoint available on of the DDG API servers?

@hemanth no we don't have a way to expose a node module as an API. 

If that JSON file covers all the content on CanIUse then making a Fathead out of the JSON should be fairly simple.

---

Alternatively, you could reach out to CanIUse to see if they plan to expose a search API?
