### ISSUE TITLE
POTUS: Should not trigger for "vice president of the united states"

### ISSUE THREAD

**Issue by Pawtiko** [duckduckgo/zeroclickinfo-goodies#1863]
@numbertheory 
Searching for "vice president of the united states" triggers this instant answer, giving the incorrect output of Barack Obama

------
IA Page:  http://duck.co/ia/view/potus

**Comment by jophab** [comment]
Its because the potus is triggered if the query contain the substrings "president of the united states"
or "president of the us"
![image](https://cloud.githubusercontent.com/assets/13940974/11647415/ae14a68e-9d8d-11e5-9ed1-67bbcbe249a3.png)

**Comment by hemanth** [comment]
It would nice to fix the [RE](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/POTUS.pm#L33) to have a beings with check.

**Comment by mintsoft** [comment]
@hemanth should be as simple as adding a `^` to the front

**Comment by hemanth** [comment]
@mintsoft Yes, I am aware of that, giving a chance to the person who reported to do a PR ;)

**Comment by moollaza** [comment]
Looks like this still needs fixing @hemanth, care to fix it?

**Comment by hemanth** [comment]
@moollaza Sure, what the expected triggers here? In the [RE](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/POTUS.pm#L31-L34) 
just a beings with for `who\s+(is|was)\s+the\s+` is enough?

**Comment by moollaza** [comment]
The triggers are OK, but we shouldn't just be stripping out expected query parts. We need to ensure that the whole query matches our regex:

```perl
handle query_lc => sub {
  return unless m/^(?:who (?:is|was) the )?(?:potus|president of the (?:us|united states|usa)) (\d+)?/;
  ...
```

Something like that...

We should add tests to ensure this.

**Comment by moollaza** [comment]
I would also just use `triggers any => "potus", "president ... ";`

**Comment by hemanth** [comment]
```perl
return unless my ($tense, $index, $text) = $_ =~ ^(?:who (?:is|was) the )?(\d+(?:st|nd|rd|th))?(?:potus|president of the (?:us|united states|usa)) ?(\d+)?$
```
Something like ^ and then fetch the required index from `@presidents` ?

**Comment by moollaza** [comment]
@hemanth sure -- not sure you need to capture anything besides the index though.

We can derive `is/was` from if it's not the current president.

**Comment by hemanth** [comment]
> "Sorry, no hit for your instant answer"

Well with the modified R.E I see ^ missing something?

**Comment by moollaza** [comment]
@hemanth use `warn` -- you'll see it printed in DuckPAN's server output

**Comment by hemanth** [comment]
Use `use warn;` but it's not triggering instant answer for any of the valid phrases: `POTUS` et.al
