### ISSUE TITLE
Cheat Sheets (Controller): 

### ISSUE THREAD

**Issue by Abledsoul** [duckduckgo/zeroclickinfo-goodies#1870]
------
IA Page:  http://duck.co/ia/view/cheat_sheets

**Comment by moollaza** [comment]
@abledsoul did you mean to add something to this? Is there a bug you found? 

Please close if not.

**Comment by Abledsoul** [comment]
Sorry, still learning. :)

**Comment by moollaza** [comment]
@Abledsoul no problem!

If you need anything, the DuckDuckHack community and DDG Staff (including myself!) are available on Slack to answer any questions you may have. If you'd like to join us there please send an email to quackslack@duckduckgo.com.
