### ISSUE TITLE
Lowercase: Should ignore input that's only numerical

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1871]
https://duckduckgo.com/?q=lowercase+1235&t=ffab&ia=answer

We should ignore input that only has numbers. We should probably not show a result if the output === input actually?

------
IA Page:  http://duck.co/ia/view/lowercase

**Comment by GuiltyDolphin** [comment]
If someone queried `lowercase 123`, wouldn't that be very indicative that they want the IA to show? I would vote for keeping lowercase for these (especially where result = input), it is a very cheap call afterall - being a single Perl sub-routine. Adding these checks would make the Goodie file more verbose, I feel.

**Comment by moollaza** [comment]
@GuiltyDolphin thanks for chiming in!

Unfortunately just because someone searches `lowercase X` doesn't mean they intended to trigger the IA. We typically don't show anything if we have nothing useful to show, so for this IA, if the result is the same as the input, I would argue it's better to show *nothing*, than show something that's potentially unwanted or unnecessary to show.

In general, this also gives other IA's a chance to show something useful. The worst case being we don't show anything, which is better than showing something unwanted or wrong.

Looking at the autocomplete results for "lowercase" it's clear that most, or even ***all***, of the popular queries aren't actually looking to modify a string, which is a relevancy issue that these kinds of IA's (query modifiers) face in general:

![drake_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/11760271/2a3354b8-a063-11e5-9f4f-fe45dd286b9f.png)

**Comment by GuiltyDolphin** [comment]
@moollaza Good points! I was thinking of lowercase more as an imperative command than an adjective! With your points in mind I agree with your initial statement of only having lowercase trigger with non-lowercase input. 

Brings up an interesting point with the `uppercase` Goodie though, although the searches seem a lot less common:

![screenshot from 2015-12-12 10 49 53](https://cloud.githubusercontent.com/assets/8598426/11761537/aa8e7b50-a0be-11e5-8f79-8294476516a8.png)
