### ISSUE TITLE
UnicodeFuzzySearch: Not triggering on live server

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1882]
@konr 

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/UnicodeFuzzySearch.pm seems to be ignored &mdash; the example queries don't work:

https://duckduckgo.com/?q=unicode+2665
https://duckduckgo.com/?q=unicode+black+heart

**Comment by tagawa** [comment]
Strange, seems like it's working in DuckPAN server but not the live or beta servers.

**Comment by cosimo** [comment]
Doesn't seem to be related to DDG::Goodie::Unicode, rather DDG::Goodie::UnicodeFuzzySearch.

**Comment by tagawa** [comment]
Thanks @cosimo - I've updated the title and description. As it's only an issue on the live server it may be a platform bug rather than IA issue.

**Comment by moollaza** [comment]
@tagawa FuzzySearch isn't live, we disabled it a while ago because there were bugs. It hasn't been deployed to beta either so it only works locally, in DuckPAN right now.

There are some issues that need resolving. 


> https://duck.co/ia/view/unicode_fuzzy_search

**Comment by tagawa** [comment]
Ah, got it. Thanks @moollaza
