### ISSUE TITLE
Apple Mac OS Cheat Sheet IA page link not working

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#1896]
@moollaza 
IA Page:  http://duck.co/ia/view/apple_mac_os_cheat_sheet
The Front-End Files link in IA Page is not working as the json file is renamed...  its returning  404.
Need to replace that with the new link.
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/apple-mac-os.json

**Comment by tagawa** [comment]
cc @MariagraziaAlastra

**Comment by moollaza** [comment]
@gautamkrishnar thanks -- I believe this is a known issue, I'm not sure if the Platform Team has a fix ready yet.

**Comment by gautamkrishnar** [comment]
:+1:

**Comment by preemeijer** [comment]
Hello, the link is working now. Is this fixed or is there still something that needs to be done internally?
Greetings, Paul

**Comment by gautamkrishnar** [comment]
yes @preemeijer good find :+1:

**Comment by gautamkrishnar** [comment]
@MariagraziaAlastra

**Comment by preemeijer** [comment]
@gautamkrishnar I was just going through the issues and what needs to be done. 
Hopefully this issue can be closed. Let's wait and see :smile:

**Comment by GuiltyDolphin** [comment]
Seems fixed. :wink:
