### ISSUE TITLE
`aspect ratio` instant answer is not being triggered?

### ISSUE THREAD

**Issue by hemanth** [duckduckgo/zeroclickinfo-goodies#1899]
^

**Comment by marianosimone** [comment]
@hemanth what query is not working for you? I see it working just fine

<img width="724" alt="screen shot 2015-12-15 at 1 58 55 pm" src="https://cloud.githubusercontent.com/assets/104916/11825466/05c72432-a334-11e5-9b53-8615e9e55e3f.png">

**Comment by altern8tif** [comment]
Same here.  Working just fine.

**Comment by hemanth** [comment]
:+1:
