### ISSUE TITLE
Add additional color calculator triggers

### ISSUE THREAD

**Issue by hunterlang** [duckduckgo/zeroclickinfo-goodies#190]
red: \d{0,4} green: \d{0,4} blue: \d{0,4}

etc.

------
IA Page:  https://duck.co/ia/view/color_codes

**Comment by javathunderman** [comment]
@moollaza Is there anything else to do for this?

**Comment by moollaza** [comment]
@javathunderman I don't believe the trigger mentioned above has been added yet

**Comment by javathunderman** [comment]
@moollaza Will try at this, but I suggest someone else tackle this as well in case I break something...

**Comment by javathunderman** [comment]
Yep, way too complex for me. Any other takers?

**Comment by mintsoft** [comment]
I can pick this up as I'm already messing with the ColorCodes goodie, however I'll definitely do it as a separate PR from the current one!

**Comment by javathunderman** [comment]
ping @mintsoft

**Comment by mintsoft** [comment]
Whoa, I totally forgot about this

**Comment by zekiel** [comment]
@Mailkov is this something you'd like to handle?
