### ISSUE TITLE
Bitsum: Hamming weight result is confusing

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#1902]
@kste 

The Hamming weight output is the same as the search query which doesn't seem correct. E.g. the [Hamming weight for 11101 is 4](https://en.wikipedia.org/wiki/Hamming_weight) but the IA says 11101.

------
IA Page:  http://duck.co/ia/view/bitsum

**Comment by moollaza** [comment]
@tagawa I'm not seeing that? I'm getting a hamming weight of 9 for 11101 (it defaults to base 10)

https://duckduckgo.com/?q=bitsum+11101&t=ffab&ia=answer

**Comment by moollaza** [comment]
We may want to have it accept and default to binary though? And have it indicate the base it used for the input

**Comment by tagawa** [comment]
I was looking at the sub-heading. It says "Hamming Weight: 11101" (under the "9"). Maybe it's the layout that's confusing. And yes, indicate the base would be helpful.

**Comment by rushikesh90** [comment]
I think hamming weight is not the operation here, instead it is bitsum or bitcount.

**Comment by moollaza** [comment]
@tagawa I understand now what was confusing you. The subtitle is meant to indicate that what you're seeing is the `Hamming Weight:` for the input `11101`. The result of the given operation for the given input is displayed as the title, `9`.

We may need to adjust the subtitle phrasing...

**Comment by tagawa** [comment]
Thanks. That fix looks good to me.
