### ISSUE TITLE
'list' as triggering  word for cheat sheet.

### ISSUE THREAD

**Issue by jophab** [duckduckgo/zeroclickinfo-goodies#1905]
Shall we add the word 'list ' as  triggering word for cheat sheet.
It will be helpful in case of IAs which list something.
for eg : #1884 

---

IA Page: https://duck.co/ia/view/cheat_sheets

**Comment by jophab** [comment]
@moollaza  @jdorweiler  @tagawa

**Comment by moollaza** [comment]
@jophab thanks for the suggestion. I'd like to hold off on adding more triggers to cheat sheets for now. We'll be revisiting our approach to triggering cheat sheets in the new year to ensure they're triggering as well as possible.

**Comment by gautamkrishnar** [comment]
@jophab that could be a good idea.

**Comment by gautamkrishnar** [comment]
@moollaza I think, We must add some more trigger words like:-
* help
* quickstart
* jumpstart

**Comment by vCillusion** [comment]
I would like to add one more thing can we include some additional metadata for categorization. See the following case.
Example: Trigger for language lets say 'Javascript' 
Query : javascript syntax -> should display the cheatsheet

**Comment by tagawa** [comment]
Perhaps this can be closed, thanks to #2170 ?

**Comment by GuiltyDolphin** [comment]
@tagawa I've left this one open for now as I haven't actually added a `list` trigger yet. It's not quite clear *where* it would make sense, and could easily lead to massive overtriggering (`python list` -> `python cheat sheet`). Perhaps this is something we could look into further if we improve the integration of metadata and cheat sheets.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
