### ISSUE TITLE
Convert Markdown CheatSheet to new format, add support for GitHub Flavored MD

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1906]
We have an existing "Markdown Cheat Sheet" that doesn't actually trigger for the query "Markdown Cheat Sheet" because it is implemented as a Perl Goodie that triggers on specific markdown elements:

https://duckduckgo.com/?q=markdown+header&t=ffab&ia=answer

We should probably have a JSON Cheat Sheet for Markdown. As mentioned in https://github.com/duckduckgo/zeroclickinfo-fathead/issues/167 we should also support "GitHub Flavoured Markdown". It could be a separate Cheat sheet or combined into the new Markdown Cheat Sheet

**Comment by gautamkrishnar** [comment]
I will create a cheatsheet for markdown syntax.  :+1:

**Comment by gautamkrishnar** [comment]
@moollaza shall i have to create separate JSON file for GHFM ?

**Comment by moollaza** [comment]
> shall i have to create separate JSON file for GHFM ?
@gautamkrishnar sure
