### ISSUE TITLE
Periodic Table: Provide Atomic Mass for queries containing the name or "periodic table"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1914]
Queries for atomic elements by name, e.g. "Helium", "Lathanum" should show the atomic mass instead of repeating the full name.

Suggested on Duck.co here: https://duck.co/ideas/idea/6804/show-all-information-in-periodic-table-goodie

----

Also it looks like "periodic table" isn't a trigger for this IA and I think it should be added. Queries like https://duckduckgo.com/?q=periodic+table+he&t=ffab should also show the element name and mass.

We may need to update the design to always allow for the atomic mass /cc @abeyang 

/cc @zblair 

------
IA Page:  http://duck.co/ia/view/periodic_table

**Comment by amitdev** [comment]
This looks easy - does the following format look good? If so, I can raise a PR.
![he](https://cloud.githubusercontent.com/assets/969139/12008978/a718d344-ac8a-11e5-9150-748e39dcc53d.png)

**Comment by mintsoft** [comment]
@amitdev Looks cool

**Comment by amitdev** [comment]
Submitted PR #1973.
