### ISSUE TITLE
Calculator: Operation for `fact()` should be "factorial"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1917]
When computing only the factorial of a number, regardless of the query, we should show the operation as "factorial" instead of "fact"

i.e. it should look like this:

![fact_3__at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/11887351/621092c2-a501-11e5-92f1-c233cc581898.png)

---

IA Page:  http://duck.co/ia/view/calculator

**Comment by mintsoft** [comment]
This is being tackled in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927

**Comment by fzzr-** [comment]
* `42!`
* `42 factorial`

Is it possible to do so?

**Comment by GuiltyDolphin** [comment]
@fzzr- The first, yes. But the second no - not at the moment. @mintsoft I should be able to add `X factorial` as a post-factor modifier if desired - what do you think?

**Comment by fzzr-** [comment]
I think that it is necessary to handle not only specific mathematical queries, but also human lingual. Then:

* `X!` is cool
* `X factorial` is optional but cool too

Such as `sin X` or `the sine of X` or more complicated `the sine of 45 minus the factorial of 42` - that will be really great but it hard in impl.

**Comment by fzzr-** [comment]
Remember [AppleScript](https://developer.apple.com/library/mac/documentation/AppleScript/Conceptual/AppleScriptX/Concepts/work_with_as.html#//apple_ref/doc/uid/TP40001568-BABEBGCF)!
There we can say many possible variants for semantically one expression:

```applescript
set myList to {"Problem", "There was a problem", "Bummer"}
-- simple variant:
set theChoice to item 2 of myList
-- beauty and more lingual variant:
set theChoice to second item of myList
return theChoice
```

**Comment by GuiltyDolphin** [comment]
@fzzr- I use a full parser for the calculator. We simply add terms to the grammar.

There are certain forms, such as `to the power...`, which are supported - but more are to come in the future. Again, this will likely be implemented on the interactive branch though.

**Comment by fzzr-** [comment]
Also mb. support `√` Square Root symbol?
(`U+221A` / `E2 88 9A`)
