### ISSUE TITLE
Add support for newline in cheatsheet

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#1920]
`\n` Must be parsed as a newline in cheatsheet key values

**Comment by gautamkrishnar** [comment]
#1908 @moollaza

**Comment by mintsoft** [comment]
IIRC It is parsed as such, it's just that browsers ignore insignificant whitespace; I'm guessing that the desired behaviour is to actually output `<br/>` or something similar when the cheatsheet engine encounters a newline?

**Comment by gautamkrishnar** [comment]
@mintsoft  Ya the `\n` must be parsed as a `<br/>`
It will makes the   writing of programming cheatsheets easier...
for example we can use:
```   
key:"var x;\n x=2;"
val:"Declare and initialize"
```
For real `\n` we can use double escape sequence: `\\n`

**Comment by moollaza** [comment]
I already have a PR in progress for this. I need to carefully review what IA's it will affect though which is why I haven't merged it yet.

See #1167

**Comment by gautamkrishnar** [comment]
Yes. As it is a work in progress, i will close this right now

**Comment by GuiltyDolphin** [comment]
I'll re-open this until it is fixed - it is still a valid issue AFAIK.

**Comment by moollaza** [comment]
Fixed in #2627

**Comment by moollaza** [comment]
@gautamkrishnar take a look at this now in DuckPAN -- newlines are working :+1:

**Comment by gautamkrishnar** [comment]
Hey cool :candy:
