### ISSUE TITLE
URLEncode: URL percent-encode shows HTML entities in input field

### ISSUE THREAD

**Issue by rugk** [duckduckgo/zeroclickinfo-goodies#1930]
@nishanths 
Let's take this example:
https://duckduckgo.com/?q=url+encode+https%3A%2F%2Fduckduckgo.com%2F%3Fq%3D%C3%A4&ia=answer
![urlencode](https://cloud.githubusercontent.com/assets/11966684/11920669/0478e214-a776-11e5-83ad-e6f6b5899fae.PNG)

At the bottom you can see this:
> URL percent-encode: https://duckduckgo.com/?q=&auml;

However what is "URL percent-encode"? AFAIK the first - big - text shown is [percent encoded](https://en.wikipedia.org/wiki/Percent-encoding) (there are also many % in it :wink:) and the thing below is just HTML (text) encoding, which has nothing to do with each other, because the html entities (how they are called) *must not* be used in the URL.

------
IA Page:  http://duck.co/ia/view/urlencode

**Comment by nishanths** [comment]
@rugk Good point. The result and input are HTML encoded before being rendered—perhaps for security reasons—from this commit onward: https://github.com/duckduckgo/zeroclickinfo-goodies/commit/53ffe0c3b61dbc23e423dd7b3661330b5ec4b243.

cc @mwmiller @jagtalon Thoughts on removing the `html_enc` call?

**Comment by rugk** [comment]
> perhaps for security reasons

Yeah, we don't want XSS attacks either... :laughing:

**Comment by rugk** [comment]
Also `'` is displayed differently: `&#39;`

**Comment by mintsoft** [comment]
@nishanths The `html_enc` call can go now that it's templated; previously it was required to prevent XSS, however now the templates do the encoding for us.

**Comment by mintsoft** [comment]
Also fixed in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1960
