### ISSUE TITLE
URLEncode: Does not encode all reserved characters correctly

### ISSUE THREAD

**Issue by rugk** [duckduckgo/zeroclickinfo-goodies#1931]
@nishanths 

These are not encoded:
https://duckduckgo.com/?q=url+encode+*-.&ia=answer

However they [could be](http://www.w3schools.com/tags/ref_urlencode.asp) encoded, but I don't know whether it is required or not. It seems Browsers and other things (like PHPs `urlencode`) handle this differently.

**Edit:** At least `*` is a reservated character which must be encoded [according to Wikipedia](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) and it's also done by `urlencode`, but not by Firefox and Chrome/Chromium either as it seems ([test site](http://www.w3schools.com/tags/ref_urlencode.asp)).
So who is right?

------
IA Page:  http://duck.co/ia/view/urlencode

**Comment by rugk** [comment]
BTW I've just copied all of the reservated characters from wikipedia (`! # $ & ' ( ) * + , / : ; = ? @ [ ]` and ran them through your [encoding answer](https://duckduckgo.com/?q=url+encode+!+%23+%24+%26+%27+%28+%29+*+%2B+%2C+%2F+%3A+%3B+%3D+%3F+%40+[+]&ia=answer) and there are more which are not encoded correctly - both by Browsers and your answer:

**Comment by nishanths** [comment]
Thanks for noting this! There was a similar discussion during the development of this IA. The encoding module that was picked matched JavaScript's `encodeURIComponent()` function.

However, this behavior may not always be the right one to use all the time. This [SO answer](http://stackoverflow.com/a/3608791/3309046), though JavaScript, explains the difference between encodeURI() and encodeURIComponent(), and how to pick the correct function for the situation.

<img width="439" alt="screen shot 2015-12-20 at 5 42 46 pm" src="https://cloud.githubusercontent.com/assets/6028224/11920941/84482caa-a741-11e5-9320-85a310b3644d.png">

**Comment by rugk** [comment]
BTW I updated my previous replies in case you did not saw.

So okay, encodeURIComponent and encodeURI are different and the answer should look like encodeURIComponent. However the issue here is that it does not encode all reserved characters.

So this is what we have to try:
![reschar](https://cloud.githubusercontent.com/assets/11966684/11920997/ab8ff8ba-a77d-11e5-9b8f-bf81052f609b.PNG)

And interestingly Firefox' JS implementation does not encode the same characters. (I wonder why...)
So may this be the correct behaviour?

**Comment by mintsoft** [comment]
According to the documentation for the module that's used (`URI::Escape`) it should encode all characters specified as reserved by RFC 3986: http://search.cpan.org/~ether/URI-1.69/lib/URI/Escape.pm#DESCRIPTION

**Comment by moollaza** [comment]
Just checking in guys, is this now fixed? I see the Encode IA was updated + converted

**Comment by mintsoft** [comment]
@moollaza AFAIK it should have been fixed in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1960
