### ISSUE TITLE
URLDecode: Does not correctly decode German umlauts

### ISSUE THREAD

**Issue by rugk** [duckduckgo/zeroclickinfo-goodies#1932]
`äöü` [encoded](https://duckduckgo.com/?q=url+encode+%C3%A4%C3%B6%C3%BC&ia=answer) are `%C3%A4%C3%B6%C3%BC`

Try it: https://duckduckgo.com/?q=url+decode+%25C3%25A4%25C3%25B6%25C3%25BC&ia=answer
It returns this: `Ã¤Ã¶Ã¼`

------
IA Page:  http://duck.co/ia/view/urldecode

**Comment by mintsoft** [comment]
Looks like when this IA was converted to accept UTF-8 we should have switched to using `uri_escape_utf8` (http://search.cpan.org/~ether/URI-1.69/lib/URI/Escape.pm)

**Comment by cngarrison** [comment]
I'm writing some failing tests now, and then I'll have a look at implementing a fix, or I'll ask some UTF8 questions if I get stuck.

**Comment by mintsoft** [comment]
@rugk I think this is slightly misleading as I think `äöü` is `%E4%F6%FC`
