### ISSUE TITLE
Rubiks Cube Patterns: Show all patterns for "rubics cube patterns", add images to results

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#1934]
I just came across this website: http://ruwix.com/the-rubiks-cube/rubiks-cube-patterns-algorithms/

which showcases visuals for many patterns. We should try and borrow these images (with permission from the website ideally) or find others that are freely available, or make our own (/cc @thm @abeyang thoughts?)

Then, we can show those images along with the results to improve them.

For the query "rubics cube patterns", we could do a tile-view highlighting pictures of each pattern with the name. Clicking the tile could potentially show more info, or send you to a the above website.

------
IA Page:  http://duck.co/ia/view/rubiks_cube_patterns

**Comment by moollaza** [comment]
BTW, this is an archived page of the original source, which seems to have no gone offline: http://archive.is/aHic4

**Comment by Mailkov** [comment]
I'm working on this

**Comment by Mailkov** [comment]
@moollaza What do you think about this slash pattern of rubik's cube? I make it as SVG too

![rubiks-slash](https://cloud.githubusercontent.com/assets/10259499/11940074/7f688a96-a826-11e5-93f0-0a1631fdae0f.png)

**Comment by moollaza** [comment]
@Mailkov that looks awesome, potentially a little too bright/bold, but otherwise looking good

**Comment by Mailkov** [comment]
@moollaza What do you think about this? 
![rubiks-slash2](https://cloud.githubusercontent.com/assets/10259499/11978950/bb2a6490-a98f-11e5-9aed-6b67e3e91d13.png)

**Comment by moollaza** [comment]
:+1: Much better

**Comment by mintsoft** [comment]
@moollaza @Mailkov not to be petty, however I think the perspective is off? The cube doesn't look like a cube to me
