### ISSUE TITLE
C++ Strings Cheat Sheet: 

### ISSUE THREAD

**Issue by czipperz** [duckduckgo/zeroclickinfo-goodies#1983]
@gohar94 

Can this be triggered with `string` as well as `strings`?  The name of the class is `string` so I would assume someone would look for `cpp string help`, which doesn't display this cheat sheet.

------
IA Page:  http://duck.co/ia/view/cpp_strings_cheat_sheet

**Comment by gautamkrishnar** [comment]
:+1:

**Comment by czipperz** [comment]
Thanks

**Comment by czipperz** [comment]
PR:
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1999#event-505072743
