### ISSUE TITLE
Minecraft: should support alternate names for items.

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/zeroclickinfo-goodies#1988]
Item names are too hard to guess. They should have alternate names or should be stored with the most common term. 'shovel' for example, isn't in the item list, but rather stored in the plural form as 'shovels'. Some people may say "how to craft shovels" whereas others might prefer "how to craft a shovel". I doubt anyone will guess "Jack-O-Lantern".

@engvik 

------
IA Page:  http://duck.co/ia/view/minecraft

**Comment by cngarrison** [comment]
@moollaza  Are there any IAs that use word stemming in the handler? Is there a standard method for handling alternate trigger terms?

**Comment by jagtalon** [comment]
@cngarrison I don't think there is one at the moment.

**Comment by jomo** [comment]
There are some common item names [here](https://github.com/sk89q/WorldEdit/blob/7945b5ce25005df91ed9937ff97497c77f0933d5/worldedit-core/src/main/java/com/sk89q/worldedit/blocks/ItemType.java).

**Comment by jagtalon** [comment]
Thanks, @jomo!

**Comment by ecounysis** [comment]
@jagtalon I can look at this.

**Comment by engvik** [comment]
I didn't know this was still open. Please do, @ecounysis :)

**Comment by ecounysis** [comment]
I committed a change to my copy of the repo.  Here is a link to the
changeset:
https://github.com/ecounysis/zeroclickinfo-goodies/commit/f4636a5d5edea696670c2cc0fbd474c3557ef6ab

Please look at it and see if it is a reasonable approach. Also, if it is a
reasonable approach, should I submit a pull request now, or wait until all
the recipes have had a regex added?


started adding a regex value to some of the recipes in crafting-guide.json

used
https://github.com/sk89q/WorldEdit/blob/7945b5ce25005df91ed9937ff97497c77f0933d5/worldedit-core/src/main/java/com/sk89q/worldedit/blocks/ItemType.java
as a guide
Goodie matches recipe on the regex, if it exists. If the regex does not
exist it matches on the recipe name (as it has been doing).
This commit does not include regexes for all recipes. It is just a start.
It will take several weeks for me to add them all.

**Comment by engvik** [comment]
Sorry for the late reply!

This seems like an reasonable approach to me :smile: Wait with opening a PR until all of them are added.

Thanks and let me know if there's anything!

**Comment by 122131** [comment]
@ecounysis Are you still working on this? 
Because if you want I can help! 😄

**Comment by ecounysis** [comment]
@122131 that would be great
