### ISSUE TITLE
404 in Front-End Files link

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#2000]
https://duck.co/ia/view/cpp_strings_cheat_sheet

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Yeah, it's pointing to `c++-strings.json`, it should be pointing at `cpp-strings.json`.

**Comment by gautamkrishnar** [comment]
The correct link is:
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-strings.json

**Comment by moollaza** [comment]
@gautamkrishnar thanks for reporting, I'll speak with the team about how we can fix this. It’s a known issue affecting several pages...

**Comment by russellholt** [comment]
the file needs to be named after the IA id so this link relationship can be made

**Comment by MrChrisW** [comment]
@russellholt Name or ID ? https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-strings.json#L2-L3

**Comment by moollaza** [comment]
@MrChrisW currently the id and filename need to match. 

e.g `cpp-srtrings.json` => `cpp_strings_cheat_sheet`; `foo.json` => `foo_cheat_sheet`

**Comment by mayank7** [comment]
@moollaza Links are also broken in responses in DuckDuckGo, I fixed it in #2383

**Comment by gautamkrishnar** [comment]
it is fixed
