### ISSUE TITLE
USPS: should be triggering on 9361289878910710378432

### ISSUE THREAD

**Issue by joecabrera** [duckduckgo/zeroclickinfo-goodies#2008]
USPS should be triggering on 9361289878910710378432, instead search results only suggest Fedex

------
IA Page:  http://duck.co/ia/view/usps

**Comment by moollaza** [comment]
@joecabrera thanks for reporting this!

This issue should be addressed by the in-development, Package Tracking Spice Instant Answer which will cover several couriers in a single Instant Answer

**Comment by zekiel** [comment]
closing per https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2845 and https://github.com/duckduckgo/zeroclickinfo-spice/pull/2430

**Comment by zekiel** [comment]
@joecabrera The PR by Mailkov (above) seems to be covering your issue. It's not live yet but it IS on beta: https://beta.duckduckgo.com/?q=shipping+status+9361289878910710378432&ia=answer
