### ISSUE TITLE
Zodiac: Dates for the Zodiacs

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2009]
Hey all!

I'm working on internalizing the `Zodiac` Goodie because its dependencies cause a few issues.

I'm mostly sorted - but some of the tests are failing due to a few differences between the dates that I've used and those used by the dependency.

I've used [Wikipedia](https://en.wikipedia.org/wiki/Zodiac) as a source, and I've found some other sites that have agreed with it - but also some that have disagreed.

It's not always clear which year the Zodiac is for, and it seems that the dates can shift slightly?

Regardless, I've looked at the two main alternatives on CPAN: `Zodiac::Tiny` and `DateTime::Event::Zodiac` (the one that is currently used) and they both hardcode their dates - as have I.

Does anyone know a better source than Wikipedia for this? Or even, does anyone _know_ the correct dates?

I'd jut like to mention that I don't do astrology.

@duckduckgo/community-leaders

------ 

IA Page:  https://duck.co/ia/view/zodiac

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin Hope this helps:
http://www.psychicguild.com/horoscopes_explained.php

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Thanks - I've already seen that one and it conflicts with Wikipedia, specifically on Aquarius (18th Feb vs 19th Feb for end). Do you know if that is a particularly reliable source?

**Comment by gautamkrishnar** [comment]
Because of leap years, time zone differences and other factors, the exact day and time when the Sun changes signs varies from year to year. 

There's some tools for finding correct Zodiac sign:
http://www.astroica.com/western-astrology/zodiac.php
https://www.horoscope.com/us/games/calculator/game-zodiac-sign-finder.aspx

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin  i am still not sure about the reliability of this source. 
as specified in the article:
If you were born on the first or last day of a Sun sign, in astrological terms you were born on a cusp. If that's the case, you will probably benefit from reading your own Sun sign and the Sun sign that ends or begins right before or after your date of birth. For example, if your birth date is 22 December, your Sun sign is Capricorn, but you probably have some Sagittarian traits as well.

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar That second page seems to only base it on days and months (as I have). It seems they are all based on the start of Aries, so leap years shouldn't come into play (none of them start/end near the end of Feb). Time zone should also not affect it if it is based on days/months.

Wikipedia mentions... "vernal equinox in UT always falling either on 20 or 21 March in the period of 1797 to 2043, falling on 19 March in 1796 the last time and in 2044 the next" - I'll have a bit more of a look into this and see if I can get the times of the equinox.

**Comment by mintsoft** [comment]
@GuiltyDolphin It might be worth asking @n0mady as they wrote the goodie originally and may be able to lend a hand with specialist knowledge

**Comment by GuiltyDolphin** [comment]
@mintsoft They don't seem to be on Slack and their GitHub profile doesn't display any (public) activity for about a year. Not sure how easy it'll be to get hold of them.

**Comment by mintsoft** [comment]
@GuiltyDolphin They've probably got an email by my '@' mentioning them in the previous comment. If they're available then they might swing in.

**Comment by GuiltyDolphin** [comment]
@mintsoft Alrighty!

It seems the Goodie was based on the dates for 2011 (via the package used). I've made a PR using those dates, which seem to be agreed upon by various sites.

It may be possible to implement a more robust system using the `Astro::Utils` package with its `calculate_equinox` function - or we could just update it every few years ;)

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
