### ISSUE TITLE
Paleo Ingredient Check: 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-goodies#2014]
more example queries plz
------

@javathunderman   can you add some more example queries to the ia page? 

IA Page:  http://duck.co/ia/view/paleo_ingredient_check

**Comment by javathunderman** [comment]
@zekiel on it!

**Comment by javathunderman** [comment]
@zekiel Added some but let me know if I should add more. :+1:

**Comment by javathunderman** [comment]
@zekiel think this can be closed

**Comment by zekiel** [comment]
thanks! updated the live view
