### ISSUE TITLE
CheatSheets: Several Cheat Sheets have "missing" sections

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2015]
Looking at the output of `$ prove t/CheatSheets/CheatSheetsJSON.t`

It's clear that several Cheat Sheet are missing sections that are defined. This is usually caused when there are spelling/casing differences between the actual section title and the section as it's mention in the `section_order` list.

---

I think this "bug" should probably throw an actual  error (instead of a warn) so that Travis fails and developers are aware of the problem?

@duckduckgo/community-leaders -- any thoughts?

**Comment by GuiltyDolphin** [comment]
@moollaza It seems to be an issue with casing? For example, in the `php` cheat sheet, changing it from `php array functions` to `Php array functions` causes the warning to go away.

**Comment by gautamkrishnar** [comment]
@moollaza Yup i agree with @GuiltyDolphin 
I will make some PR's to fix this issues on cheatsheet JSON files.

**Comment by moollaza** [comment]
>Do we normalize the section_order sections to proper case? 

Nope. I had set it up to do a pretty naive check. It simply loops over the `section_order` and grabs `sections[section_name]` -- so if the casing differs it will fail. The test operates in the same way.

We could definitely force a normalized casing. 

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/cheat_sheets.js#L13
