### ISSUE TITLE
Redis Cheat Sheet: Add in essential HLL and Geo commands

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2017]
In light of https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1614#commitcomment-15116972 we should add in the essential HLL and Geo commands for Redis to round out the content here.

/cc @seisfeld 

------
IA Page:  http://duck.co/ia/view/redis_cheat_sheet

**Comment by gautamkrishnar** [comment]
i am on it

**Comment by seisfeld** [comment]
@gautamkrishnar Seems you broke the json with all the reformatting. Looks there is closing brackets in the wrong spot.

**Comment by gautamkrishnar** [comment]
@seisfeld ok thanks. I will; fix it :)
