### ISSUE TITLE
Shell cheat sheet: ambiguous or incorrect

### ISSUE THREAD

**Issue by mbionchi** [duckduckgo/zeroclickinfo-goodies#2022]
The file in question is:
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/shell.json
If this cheat sheet is for bash (as the source URL implies), then the Variables section is incorrect.  Otherwise it's just ambiguous what shell language the cheat sheet is for.

**Comment by MrChrisW** [comment]
Hi @mbionchi ! 

Which variable are you referring to ? They look correct to me. Do you mean the wording? "Shell" should be "Bash"?

Variables: 

+ $0             #Name of this shell script itself.
+ $1             #Value of first command line parameter (similarly $2, $3, etc)
+ $#             #In a shell script, the number of command line parameters.
+ $*             #All of the command line parameters.
+ $-             #Options given to the shell.
+ $?             #Return the exit status of the last command.
+ $$             #Process id of script (really id of the shell running the script)

Thanks

**Comment by mbionchi** [comment]
Hey @MrChrisW,

I meant the Variables section, not Builtin Variables.  Here it is:
```
"Variables": [
    {
        "key": "$hello = \"Hello World\"",
        "val": "Initialize a variable"
    },
    {
        "key": "$hello = \"1 2 3 4 5\"",
        "val": "Initialize a list"
    }
],
```
`$var = "val"` is not the way you assign variables in bash.  If the cheat sheet is about bash, it should be changed to `HELLO="Hello World"` or possibly merged with the existing bash cheat sheets, e.g. bash.json or shell-variables.json.

**Comment by MrChrisW** [comment]
@mbionchi Your absolutely right. 

I'm not actually sure why there's a "bash" cheetsheet and a "shell" cheatsheet when the original source link points to `bash cheatsheet`. 

Either way the correct way to perform a variable assignment in both a POSIX shell and Bash is `HELLO="Hello World"`

I'm in favor of removing the shell cheatsheet completely and possibly improving the bash cheatsheet with the "Conditionals" and "Loop" sections of this sheet. 

Are you interested in lodging a PR to remove the `shell.json` file and updating the bash cheatsheet?

**Comment by mbionchi** [comment]
Yes, absolutely.  I'll start working on it.
