### ISSUE TITLE
Title of css cheat sheet instant answer

### ISSUE THREAD

**Issue by sagarhani** [duckduckgo/zeroclickinfo-goodies#2028]
Check out [CSS cheat sheet](https://duckduckgo.com/?q=css+cheat+sheet&ia=cheatsheet) instant answer. It has an extra word (software) appended.

**Comment by gautamkrishnar** [comment]
@moollaza

**Comment by moollaza** [comment]
@sagarhani thanks for reporting -- it doesn't look like this affects any other queries, it make be some cached artifact of the old cheat sheet. I think it's safe to ignore for now.

@gautamkrishnar FWIF I get notifications for every issue/comment, so mentioning me doesn't do much more ;)
