### ISSUE TITLE
Markdown cheat sheet doesn't have contributor info 

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#2030]
https://duck.co/ia/view/markdown_cheat_sheet
My name not found :wink:  in both ia page and cheatsheet.page

https://duckduckgo.com/?q=Markdown+Cheat+Sheet&ia=answer
![screenshot 146](https://cloud.githubusercontent.com/assets/8397274/12221843/8a4fa4bc-b7d0-11e5-99d0-82f4cf1204a0.png)

**Comment by gautamkrishnar** [comment]
@moollaza

**Comment by moollaza** [comment]
Fixed! It should reflect on the SERP soon.

Thanks @gautamkrishnar
