### ISSUE TITLE
CalendarToday: Multi language support

### ISSUE THREAD

**Issue by cemiarni** [duckduckgo/zeroclickinfo-goodies#2034]
---

IA Page:  http://duck.co/ia/view/calendar_today

**Comment by moollaza** [comment]
@cemiarni Thanks for your suggestion and welcome to DuckDuckHack!

We have plans to localize our Instant Answers in the future, but nothing is expected to change soon. 

For now I will mark this as tolerated, but as mentioned, it's something we hope to do eventually!

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
