### ISSUE TITLE
Conversions: After 14 decimals places, scientific notation no longer used?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2041]
This behaviour seems like a bug?

Lower limit (6 0's): https://duckduckgo.com/?q=3000+km+to+m&t=ffab&ia=answer

https://duckduckgo.com/?q=30000+km+to+m&t=ffab&ia=answer

Upper limit? (14 0's): https://duckduckgo.com/?q=300000000000+km+to+m&t=ffab&ia=answer

https://duckduckgo.com/?q=3000000000000+km+to+m&t=ffab&ia=answer

/cc @mintsoft 

-----
IA Page: https://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
o.0 that's weird it might be the numbers role that's doing that, I'll investigate

@GuiltyDolphin did you see anything similar to this with the Calculator rewrite?

**Comment by GuiltyDolphin** [comment]
@mintsoft Uhh... I had a few issues with `NumberStyle` throughout, but I don't think this is `NumberStyle` - I'm pretty sure this is in `Conversions` (I've found a few offending lines).
