### ISSUE TITLE
Metadata in template for goodies & spices

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/zeroclickinfo-goodies#2042]
Currently, the new docs don't have any information on Topics and on Categories, but the template in the goodie and spice repositories are directing devs to documentation pages on those two things that no longer exists. Working on a fix that will just remove these comments. If possible, we could create a new page on that GitBook and add info on topics and categories.

**Comment by MrChrisW** [comment]
Metadata including Topics and Categories was removed from all repository's as part of #2277 &  #1756

The topics and categories section doesn't exist in the templates anymore

+ https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/template/lib/DDG/Goodie/Example.pm 
+ https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/template/lib/DDG/Spice/Example.pm

It's possible the `https://duck.co/duckduckhack/` links should be updated to `docs.duckduckhack.com` within the templates

**Comment by moollaza** [comment]
> It's possible the https://duck.co/duckduckhack/ links should be updated to docs.duckduckhack.com within the template

@MrChrisW good catch!

**Comment by MrChrisW** [comment]
Fixed in 

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2050
https://github.com/duckduckgo/zeroclickinfo-spice/pull/2409

**Comment by javathunderman** [comment]
Nice @MrChrisW
