### ISSUE TITLE
Bengali Cheat Sheet: Add pronunciation for each phrase

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2054]
@birajkarmakar 

------
IA Page:  http://duck.co/ia/view/bengali_cheat_sheet

**Comment by birajkarmakar** [comment]
Hi @tagawa 

Initially when I did code pronunciation was there https://github.com/birajkarmakar/zeroclickinfo-goodies/commit/22a24a89721bbb0cf7c620190e298d36fc611e1c 
Later I have changed the file as per new cheatsheet template called language. But pronounciation is still there https://github.com/birajkarmakar/zeroclickinfo-goodies/commit/ecd8652bf4ec3e27a426e4462ebeb89e461576d2 in "trn" section.

**Comment by tagawa** [comment]
Ah, I see. Maybe something's wrong with the template parser. Perhaps @moollaza knows.

**Comment by moollaza** [comment]
@tagawa @birajkarmakar the `template_type` is incorrect. It should be `language`

**Comment by tagawa** [comment]
D'oh! I should have spotted that. https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2062 should fix it.

**Comment by birajkarmakar** [comment]
awesome!
