### ISSUE TITLE
ResistorColors: URL is changed.

### ISSUE THREAD

**Issue by Hoaas** [duckduckgo/zeroclickinfo-goodies#2055]
@HackOrQuack The IA links to [http://resisto.rs/5.1](http://resisto.rs/5.1), but the new URL is [http://resisto.rs/#5.1](http://resisto.rs/#5.1).

------
IA Page:  http://duck.co/ia/view/resistor_colors

**Comment by moollaza** [comment]
@Hoaas thanks for reporting this! Would you be interested in fixing the link?

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/ResistorColors.pm#L177
