### ISSUE TITLE
DateMath.pm could/should handle time too?

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#2056]
I feel that queries such as `123456789 seconds ago` should work and be handled by probably `DateMath.pm`

I guess the location will be needed to do timezone adjustments etc

-----
https://duck.co/ia/view/date_math

**Comment by GuiltyDolphin** [comment]
@mintsoft It seems the package being used can handle down to nanoseconds - I'll check it out.
