### ISSUE TITLE
Lua Language Cheat Sheet: Incorrect else if Statement

### ISSUE THREAD

**Issue by viluon** [duckduckgo/zeroclickinfo-goodies#2071]
@lxndio 
The else if statement in Lua is noted as `elseif`, not `else if`.
![](http://puu.sh/mybi9/75954a1eb3.png)
------
IA Page:  http://duck.co/ia/view/lua_cheat_sheet

**Comment by lxndio** [comment]
Will be fixed as soon as possible.
