### ISSUE TITLE
Private network IA: No "i" icon is displayed

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2087]
Should be visible and link to https://duck.co/ia/view/private_network

**Comment by iamshubh22** [comment]
@tagawa I would like to work on this.

**Comment by tagawa** [comment]
Thanks for offering @iamshubh22 but I think this can only be fixed internally by staff.

**Comment by iamshubh22** [comment]
Ok.

**Comment by altern8tif** [comment]
Resolved.  Good to close.

**Comment by tagawa** [comment]
Looks good - thank you.
