### ISSUE TITLE
Frequency Spectrum: move embedded JS to .js file

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/zeroclickinfo-goodies#2088]
writing JS to the page from the perl module isn't needed since template and javascript support has been added to goodies.

 see http://docs.duckduckhack.com/frontend-reference/setting-goodie-display.html

------
IA Page:  http://duck.co/ia/view/frequency_spectrum

**Comment by moollaza** [comment]
This has actually being taken care of in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1916

**Comment by yash14123** [comment]
How should we go about fixing this?
