### ISSUE TITLE
Feature request: Interactive keyboard image for cheat sheets

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2091]
Suggestion from a dedicated DuckDuckGo user via Twitter:

"Make keyboard shortcut cheat sheets interactive with an image of a keyboard that responds (e.g. lights up) when particular keys are pressed.

Also mousing over a shortcut would light up corresponding keys. i.e. “^-L [get lyrics]” = control key & L-key light up.

The idea’s not necessarily useful, but cool. It could be useful wit an actual LED keyboard & API feedback extension for 3rd party or default in OSX."

------
 
IA Page: https://duck.co/ia/view/cheat_sheets
https://twitter.com/CogDisNoi/status/690152476561936384

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
