### ISSUE TITLE
Feature request: Detect user's platform for keyboard shortcut cheat sheets

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2096]
Keyboard shortcut cheat sheets should detect whether the user is on a Mac or PC, showing the correct keystrokes for that platform (and perhaps give the user the ability to override).

From a comment on Twitter: https://twitter.com/aarchel822/status/689442091299012608

**Comment by aarond12** [comment]
The PHP code $_SERVER["HTTP_USER_AGENT"] can easily be used to determine whether the user is on a Mac or PC. In ASP.NET, use Request.ServerVariables("HTTP_USER_AGENT"). 

I might suggest using [Command ⌘] when designating the Apple key and [Option ⌥] when designating the ALT key. Those characters are U+2318 and U+2325 respectively.

The idea of being able to show the other platform's keystrokes is outstanding! :+1:

**Comment by moollaza** [comment]
>The PHP code $_SERVER["HTTP_USER_AGENT"] can easily be used to determine whether the user is on a Mac or PC. In ASP.NET, use Request.ServerVariables("HTTP_USER_AGENT").

@aarond12 thanks -- we're using Perl + JS though. We'd need to figure this out client side in the JS.

I think handling this is also dependent on us handle cheat sheets for different OS's in a standardized way.

Right now we have a few Cheat Sheets that are OS specific and have specific keys.

In some cases, the Linux and Apple shortcuts may be the exact same, and only require changing `Ctrl` to `Cmd` in the UI.

In other cases, I imagine the shortcuts are different and switching keys won't work. For those cases we need to have a naming convention for the files so we know which ones to load.

e.g.`sublime_text_win.json`, `sublime_text_mac.json` and `sublime_text_linux.json` 

Alternatively, we could define all OS specific variations in one file and we could load the correct keys/values as needed.

I'd like to hear the community's thoughts on this. This is project which should be able to be carried out entirely in the open by the community!

/cc @duckduckgo/community-leaders 

I'd like to hear

**Comment by GuiltyDolphin** [comment]
@moollaza Maybe we could have a directory? E.g, `sublime_text/` which then has `linux.json`, `mac.json` etc... Would help prevent crowding the `json/` directory.

**Comment by aarond12** [comment]
In JavaScript, the object "navigator.userAgent" returns the user agent string. Parsing that for "Win" or "Mac" should be pretty easy.

**Comment by gautamkrishnar** [comment]
@tagawa Good suggestion :+1: 
@GuiltyDolphin yes. I agree with you. The JSON folder is already crowded nah :smile:.
@moollaza  i think, defining all OS specific variations in one file is also a good idea. I think it will make parsing more easier.

**Comment by Jedidiah** [comment]
I will quite often lookup shortcuts from my phone/tablet whilst working on the desktop, I'm not sure we can always assume the device the user is on is the device they're interested in the shortcuts for, I certainly wouldn't prevent them viewing alternate sets.

**Comment by altern8tif** [comment]
@Jedidiah would it be better to have sub-tabs for each operating system then?  We could still detect the userAgent and open the relevant Mac/Windows/Linux tab by default...

**Comment by GuiltyDolphin** [comment]
@altern8tif Oooh... I like it! :+1:

If we don't already have one, a template for tabs would be pretty amazing.

**Comment by altern8tif** [comment]
@GuiltyDolphin depending on how we implement it, that'll make things much more tidy as well... And we may not need to include "Mac", "Linux", "Windows" as trigger words anymore

**Comment by GuiltyDolphin** [comment]
@altern8tif Maybe a more general detection - the `CheatSheet` Goodie could detect those and automatically have the tab for whichever OS as default if it exists?

**Comment by altern8tif** [comment]
@GuiltyDolphin :+1:

**Comment by Jedidiah** [comment]
@altern8tif That sounds great :+1:  good idea defaulting to the current OS too.

**Comment by moollaza** [comment]
>@moollaza Maybe we could have a directory? E.g, sublime_text/ which then has linux.json, mac.json etc... Would help prevent crowding the json/ directory.

@GuiltyDolphin good idea! That should work

@Jedidiah @altern8tif I think the design team had a mockup at some point that included a dropdown. Even if they didn't, it's a standard element we plan to bring to IA's for you to modify them on the UI (e.g. change the sorting of tiles)

So yes, ideally we'd detect the OS and show it, but provide a way to switch to another version of the cheat sheet.

**Comment by jagtalon** [comment]
@moollaza we have standard ways of checking the OS / browser, and I wonder if that would be useful:

https://v.usetapes.com/Qk8Lo6j1r6

**Comment by fzzr-** [comment]
>we have standard ways of checking the OS

`DDG.device.is... : Bool`

1. IMO we need catch standard keywords in request like `win`/`(mac|os[\s-]*x)`/`.nix`;
2. If OS-keyword not found we have to show something like tab or button like a one on my _super_ screenshot. This is for fast switch if OS doesn't suggested in request.

![screen shot 2016-03-14 at 20 10 19](https://cloud.githubusercontent.com/assets/888526/13752736/3ab67ce0-ea21-11e5-8d44-333beaee8e5e.png)

**Comment by GuiltyDolphin** [comment]
@fzzr- There are a few issues we have to deal with:

1. Detecting which OS the user is on. Using a sensible procedures to determine which OS to use otherwise (including defaults).

2. Detecting which *cheat sheet* should be displayed for *each* operating system. This would mean introducing a standard way of declaring the OS for a cheat sheet. Not all cheat sheets would have an OS associated with them. (Potentially we could do this by having a single cheat sheet which could declare shortcuts for multiple OSes).

3. Displaying the cheat sheet and allowing the user to switch between cheat sheets in a manner that is consistent with the general style of IAs.

4. Basically make sure that *everything* works *all* of the time (we don't want to be displaying Windows cheat sheets to Mac power users, do we?).

So yeah, it's not as simple as *just* peering at the query - though that would be an obvious thing to do when detecting which OS they want. We might also want to consider other, more obscure OSes, or even generic maps.

**Comment by fzzr-** [comment]
That's great.

But if I understand all correctly there's one "but":

>we don't want to be displaying Windows cheat sheets to Mac power users, do we?

We need to correlate _keywords (mac / osx / win / etc) in query_ and _user's OS_ and prioritise its. I mean what we have to use _user's OS_ only if we don't have mentioned OS in query.

For example I'm on OS X asking DDG with query:

* `Sublime Cheat Sheet` ⇒ I need sheet for my OS;
* `Sublime Cheat Sheet Win` ⇒ I need sheet for windows.

**Comment by GuiltyDolphin** [comment]
@fzzr- As mentioned previously, user preferences (and query) should be high in determining which OS to use. Obviously searching for `X cheat sheet for Mac` should display the Mac cheat sheet. I was referring more to the case where we have the ability to display the correct cheat sheet, but display the wrong one; this is a case we want to avoid.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
