### ISSUE TITLE
Feature request: Support line breaks in cheat sheets

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2097]
For example being able to include code such as:
```
switch control expression {
  case pattern 1:
    statements
  case pattern 2 where condition:
    statements
  case pattern 3 where condition, pattern 4 where condition:
    statements
  default:
    statements
}
```
Suggestion by @gautamkrishnar

**Comment by gautamkrishnar** [comment]
:+1:

**Comment by moollaza** [comment]
I have #1920 -- just need to test it for breakage...

**Comment by vikashvverma** [comment]
I have observed this too in a few cheat sheets:

![2](https://cloud.githubusercontent.com/assets/915277/12725468/df3cacc6-c938-11e5-8439-e1865591abb8.gif)


![1](https://cloud.githubusercontent.com/assets/915277/12725469/df664e0a-c938-11e5-92b9-733b3251b609.gif)


@moollaza Adding following to regex fixed the issue.
                                                                                                                                                 
                .replace(/&lt;/g, "<")                                                                                                                                                       
                .replace(/&gt;/g, ">")  

See below : 

![2 2](https://cloud.githubusercontent.com/assets/915277/12725704/f77f563e-c939-11e5-9386-98515c6ea5a1.gif)



![1 1](https://cloud.githubusercontent.com/assets/915277/12725597/85ed4274-c939-11e5-808f-80cafd507863.gif)
