### ISSUE TITLE
atom cheatsheet not triggering

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#2108]
as mentioned in #1933 atom cheatsheet is not triggering. even triggers specified in the ia page is not working.
ia page link: https://duck.co/ia/view/atom_cheat_sheet
cc: @moollaza

**Comment by navneetzz** [comment]
@gautamkrishnar atom cheat sheet is working, it's fine. Try it now

**Comment by navneetzz** [comment]
@gautamkrishnar @moollaza atom cheat sheet is working, but just this aliases are not working for it - "atom for windows", "atom for linux", "linux atom", "windows atom"

**Comment by jophab** [comment]
@gautamkrishnar  @navneetzz @moollaza 
The cheatsheet you see the one for mac.
The one I made for windows and linux is not working.

**Comment by moollaza** [comment]
The new IA hasn't been deployed yet, I needed to keep the status set to live. It all works as expected on Beta.
