### ISSUE TITLE
GTA Vice City cheat sheet: No "i" icon is displayed

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2114]
This means the info box can't opened.

---
IA: https://duck.co/ia/view/gta_vice_city_cheat_sheet

**Comment by iamshubh22** [comment]
@tagawa  I would like to work on this.

**Comment by tagawa** [comment]
Thanks for offering @iamshubh22 but I think this can only be fixed internally by staff.

**Comment by iamshubh22** [comment]
@tagawa Ok.

**Comment by altern8tif** [comment]
Seems to be resolved.

![screen shot 2016-02-09 at 12 26 01 am](https://cloud.githubusercontent.com/assets/5793364/12891717/bebe275a-cec3-11e5-8e45-1c98d5fd3f49.png)

**Comment by tagawa** [comment]
Looks good - thank you.
