### ISSUE TITLE
Conversions: Add support for ping, Taiwanese unit of area commonly used in real estate listings.

### ISSUE THREAD

**Issue by heycam** [duckduckgo/zeroclickinfo-goodies#2125]
@mintsoft 

See https://en.wikipedia.org/wiki/Taiwanese_units_of_measurement

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by moollaza** [comment]
@heycam Thanks for contributing and welcome to DuckDuckHack!

I'll get this deployed to Beta for some testing. I expect this is fine though :+1: 

/cc @mintsoft
