### ISSUE TITLE
Tracking number being attached to wrong carrier

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#216]
92748926998277553042762371 should be UPS instead of USPS.

https://duckduckgo.com/?q=92748926998277553042762371

https://duck.co/ia/view/usps

**Comment by javathunderman** [comment]
@jagtalon Has this been resolved? I did a search and the error seems to still pop up.

**Comment by javathunderman** [comment]
@moollaza @jagtalon Best this IA be removed from DDG until this is fixed!

**Comment by mintsoft** [comment]
@javathunderman I think this is actually pretty minor, it's certainly been outstanding for quite a while!

**Comment by javathunderman** [comment]
Related: #370 and #1621

**Comment by zekiel** [comment]
There are several tracking number issues for USPS, UPS, FedEx, etc. To sumstead's point in #370, I'm not sure there's a great resolution here, besides someone taking over all the package trackers to diff their bugs. https://github.com/duckduckgo/zeroclickinfo-goodies/issues/370#issuecomment-164145845 

Anyone is welcome to reopen and attack this issue individually but I'm going to attempt closing these and creating 1 big issue for combining them in some intelligent way and sorting out the triggering. Maybe that's just a triggering handler we create and use in package tracker IAs.

**Comment by zekiel** [comment]
Here's the issue https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2845 
Here's the PR to fix it: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2430
