### ISSUE TITLE
Adding spices name in hindi share/goodie/cheat_sheets/json/language/hindi.json

### ISSUE THREAD

**Issue by shahbaz17** [duckduckgo/zeroclickinfo-goodies#2180]
eg. Cinnamon - दालचीनी (Dalchini)

**Comment by swapagarwal** [comment]
#2179 Just putting it here for reference.

**Comment by moollaza** [comment]
Closing this. Explanation over here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2179#issuecomment-177551844

@shahbaz17 FWIW you don't need to make an issue before making a pull request :+1:
