### ISSUE TITLE
Html cheat sheet : Display format is rough and JSON not correct

### ISSUE THREAD

**Issue by navneetzz** [duckduckgo/zeroclickinfo-goodies#2216]
![html2](https://cloud.githubusercontent.com/assets/11630812/12819283/7eccaf72-cb80-11e5-8026-f9e82b63f6f6.png)

There is lot of space left. If arranged properly it can be avoided.

The way cheat sheet is displayed is ODD and it's JSON file contains extra spaces
 https://duckduckgo.com/?q=html+cheat+sheet&ia=cheatsheet&iax=1

**Comment by GuiltyDolphin** [comment]
@navneetzz Can you elaborate? What do you mean by 'odd'?

**Comment by navneetzz** [comment]
@GuiltyDolphin 
There is lot of space left. If arranged properly it can be avoided.

**Comment by moollaza** [comment]
@navneetzz thanks for pointing this out and fixing. FWIW I think the extra space at the bottom is fine. There's definitely more pressing issues to deal with in Spice and Goodies -- wanna try tackling some of those next?

**Comment by navneetzz** [comment]
@moollaza yep I will work on them
