### ISSUE TITLE
 Bit torrent Cheat sheet: cheat sheet doesn't display

### ISSUE THREAD

**Issue by gvanwaelvelde** [duckduckgo/zeroclickinfo-goodies#2225]
When typing "bit torrent cheat sheet" into DuckDuckGo's beta server search box, the IA doesn't show.
You only get normal search results.
https://beta.duckduckgo.com/?q=bit+torrent+cheat+sheet

**Comment by vikashvverma** [comment]
@gvanwaelvelde It does display the cheat sheet.

Try this : https://beta.duckduckgo.com/?q=bittorrent+cheat+sheet&ia=cheatsheet

I think, it is because `bit torrent` is not an alias.

**Comment by gvanwaelvelde** [comment]
You're right. I thought that 'bit torrent' was an alias. My mistake.
