### ISSUE TITLE
Problem deploying to beta 

### ISSUE THREAD

**Issue by mohan08p** [duckduckgo/zeroclickinfo-goodies#2226]
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2193
Kindly, check this PR. It's showing had a problem deploying to beta even when it runs properly in staging server and all checks have passed. But, still its properly showing on the beta server.
Why is it showing problem than ? This issue is related to travis CI. 
Signed-off by,
Mohan Pawar
mohanpawary1990@gmail.com

**Comment by GuiltyDolphin** [comment]
@mohan08p Thanks for letting us know - but please use Slack to discuss this sort of issue, rather than GitHub.

@moollaza This one should be closed.
