### ISSUE TITLE
UI issues with about tab

### ISSUE THREAD

**Issue by Sayanc93** [duckduckgo/zeroclickinfo-goodies#2227]
<img width="1272" alt="screen shot 2016-02-04 at 1 09 29 pm" src="https://cloud.githubusercontent.com/assets/6565629/12808925/ab38b41a-cb40-11e5-82f6-da8c141db4f7.png">

**Comment by altern8tif** [comment]
@Sayanc93 could you be a bit more specific?  Not sure what UI issues you may be referring to.

Also, [Wikipedia information](https://duck.co/ia/view/wikipedia_fathead) are served by the [Fathead IA](https://github.com/duckduckgo/zeroclickinfo-fathead).

**Comment by Sayanc93** [comment]
The drop down you see with the celebrity information is way too expanded than the box its contained in.
I believe the wikipedia info box should encapsulate the drop down

**Comment by altern8tif** [comment]
I think that is the intention.  There will be too much unnecessary whitespace if the grey IA box expands to accommodate the sidebar.

If I'm not mistaken, the max height of the IA box with the `zci` class (for the Wikipedia Fathead) is determined by the length of the first paragraph/summary of the content on the respective Wikipedia page (as can be seen by clicking the "Show More" link).

Maybe @abeyang can weigh in on that?

**Comment by vikashvverma** [comment]
I think this can be closed.

**Comment by MrChrisW** [comment]
@Sayanc93 As @altern8tif said I believe this is expected behavior. I'll close this now. Thanks
