### ISSUE TITLE
ParseCron enhancement?

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/zeroclickinfo-goodies#2239]
How feasible is this?

http://crontab.guru/#*_3/4_*_*_0

**Comment by GuiltyDolphin** [comment]
@jbarrett Interactive crontab schedules? Should be feasible given we can use JavaScript - there are *much* more complicated IAs out there already.

@duckduckgo/instant-answer-maintainers Anyone know enough JS to want to tackle this?

**Comment by jbarrett** [comment]
Sorry, wasn't of completely sound mind when I submitted this :smile: 

I'm referring to adding support for start + interval arguments (see 3/4 there)

https://duckduckgo.com/?q=cron+*+3%2F4+*+*+0

Though interactivity would also be cool.

**Comment by GuiltyDolphin** [comment]
@jbarrett Ah, okay.

I'm all for interactivity though :smile:

Yeah, implementing the would be a fair bit simpler @duckduckgo/instant-answer-maintainers Anyone interested?

**Comment by Mailkov** [comment]
@jbarrett  @GuiltyDolphin  I'll do it
