### ISSUE TITLE
IA for Rorainópolis

### ISSUE THREAD

**Issue by khflab** [duckduckgo/zeroclickinfo-goodies#2245]
Guys the description for Rorainópolis it's missing the number of population and is outdated.

I tried to find this IA on duckduckhack without success.

I want to fix it, where can I find this IA?

![ia_rorainopolis](https://cloud.githubusercontent.com/assets/2036324/12873758/4bbf46b2-cd9c-11e5-82b9-561fdf74b41f.png)

![from_wikipedia](https://cloud.githubusercontent.com/assets/2036324/12873765/86f497d2-cd9c-11e5-8da7-0ce9e76f7a5b.png)

**Comment by GuiltyDolphin** [comment]
For https://duckduckgo.com/?q=rorainopolis&t=ffab&ia=about I get:

![screenshot from 2016-02-07 17 21 42](https://cloud.githubusercontent.com/assets/8598426/12873824/5778aac0-cdbf-11e5-8850-905c1d6884fb.png)

The result is from a FatHead that scrapes the articles into a database I believe (See [this search](https://duck.co/ia?q=wikipedia&repo=fathead#)).

We have separate FatHeads for different languages, so any differences could be down to the Wikipedia article or potentially the FatHead.

@moollaza Might be able to enlighten you further.

**Comment by khflab** [comment]
Thanks @GuiltyDolphin, now i understand what to do. I'll go into duckduckhack documentation to see how to work with FatHeads.

Btw this flag is wrong, it's not from Rorainópolis, it's from our state Roraima.

![rorainopolis_flag](https://cloud.githubusercontent.com/assets/2036324/12874011/d9a2aeec-cda1-11e5-851e-f3c611505209.png)

**Comment by GuiltyDolphin** [comment]
@khflab I wouldn't know ;)

Glad you're sorted - I'm having a look at some of the responses for other languages and it looks like they could do with some boosts.

**Comment by moollaza** [comment]
@khflab thanks for reporting!

Wikipedia results are a special kind of Internal FatHead so devs can't do too much to fix them. In this case though, it looks like the issue is the Wiki content itself (which we don't modify) so the solution here is to update the wiki page. DuckDuckgo will get updated shortly after the Wiki page is changed.
