### ISSUE TITLE
FontAwesome Cheatsheet

### ISSUE THREAD

**Issue by mr-karan** [duckduckgo/zeroclickinfo-goodies#2256]
I am planning to make a FontAwesome Cheatsheet but there are 2 options for me currently : 
- Since I would need an external CSS for FontAwesome icons to display correctly, I can't place them in cheatsheets/json and I have to make a new goodie for that. I tried this, have been succesfull but I need to format the data as shown in the image below

![fa](https://cloud.githubusercontent.com/assets/5689132/12942344/31ce7492-d000-11e5-91e5-f6c54c315b5c.png)
- As recommended by @moollaza on Slack group, to just use names and use link template for linking to icons. I took a look at cheatsheet JSON syntax. My JSON is formatted a bit differently where I have just the key:value pair, so I'd need to write an additional script which would do format my JSON like this.

```
"First Section": [
            {
                "key": "Key 2.1",
                "val": "Value 2.2"
            },
            {
                "key": "Key 2.2",
                "val": "Value 2.2"
            }
        ]
```

If anyone is wondering, where am I getting the icon data from, I had created a [CLI for FontAwesome](https://github.com/mr-karan/fate) last week and I am using scripts from that module to get data for IA. I am planning to make an API soon to ease out the process.

So I want to ask the community, what should be my approach for this ? Do you beleive a simple cheatsheet without the icons is useful enough ? Or should I go ahead with stylizing the HTML for the goodie (Any tips on styling it, appreciated)

Thanks

**Comment by pecey** [comment]
Just a personal opinion. I am not sure if a FA cheatsheet without icons would make any sense, since if you would need to be sure you are picking the right icon. So icons would definitely be needed.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
