### ISSUE TITLE
Go Language Cheat Sheet: incorrect formatting

### ISSUE THREAD

**Issue by W25** [duckduckgo/zeroclickinfo-goodies#2257]
```<BR>``` tags are displayed literally (see the screenshot).

![golang](https://cloud.githubusercontent.com/assets/9570467/12948855/032797d6-d005-11e5-9699-f633280c9d16.png)

------
IA Page:  http://duck.co/ia/view/golang_cheat_sheet

**Comment by mr-karan** [comment]
The same happens in [Java Cheat Sheet](https://duckduckgo.com/?q=java+cheat+sheet&ia=cheatsheets)

**Comment by vikashvverma** [comment]
This has already been fixed in PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2209.

Once @moollaza merges his PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1536/files

PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2209 will fix this.
