### ISSUE TITLE
Java Cheat Sheet: HTML tags being displayed

### ISSUE THREAD

**Issue by AdeshAtole** [duckduckgo/zeroclickinfo-goodies#2269]
------
IA Page:  http://duck.co/ia/view/java_cheat_sheet

HTML tags showing up in IA
![screenshot from 2016-02-12 12 58 44](https://cloud.githubusercontent.com/assets/4648201/13001124/bb5c64ba-d188-11e5-9703-3c9490859910.png)

**Comment by vikashvverma** [comment]
@moollaza Can you merge your PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1536/?

I can fix this issue once you merge your PR.

**Comment by yash14123** [comment]
Is this one fixed?

**Comment by mayank7** [comment]
@moollaza I have fixed this in #2337

**Comment by edgesince84** [comment]
@moollaza is this still open, or was it addressed by @mayank7's PR?

**Comment by moollaza** [comment]
@edgesince84 this was fixed by another PR actually 👍
