### ISSUE TITLE
Frequency Spectrum: Cleanup code, make content larger, reduce whitespace

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2295]
The Frequency Spectrum Goodie has now been converted to use templates, but the size of the content has been scaled down and now has extra whitespace.

It would be great if we could reduce the whitespace to make the content large so it's easier to read. If necessary we can add some CSS to expand the size of the graph, but it would be ideal to keep the visuals inside the existing box.

There are also many lines of commented code we should remove.

------ 

IA Page:  https://duck.co/ia/view/frequency_spectrum

**Comment by yash14123** [comment]
I am on it . :) Thanks.
