### ISSUE TITLE
Certain queries causing blank screen

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2304]
For example, on Beta I'm getting:

https://beta.duckduckgo.com/?q=macos+cheat+sheet

![screenshot from 2016-02-16 08 48 56](https://cloud.githubusercontent.com/assets/8598426/13071386/f5d3f536-d48a-11e5-9043-2f7fb73e3c34.png)

(does not do the same on production).

/cc @jdorweiler (Beta bug?)

I spotted one a while back on production (`localhosh:5000\`), but reported it to @moollaza and it's fixed now.

Anyone else seeing this (and/or similar) issue?

**Comment by altern8tif** [comment]
Looks fine for me @GuiltyDolphin 

![screen shot 2016-02-16 at 5 42 10 pm](https://cloud.githubusercontent.com/assets/5793364/13074044/acb8bb08-d4d4-11e5-8bbd-b47f02c1ffdb.png)

**Comment by GuiltyDolphin** [comment]
@altern8tif Still doing it for me.

I'm on Linux Mint (17), with Firefox.

**Comment by jdorweiler** [comment]
@GuiltyDolphin can you try `ctrl+shift+r` to force your browser to reload the JS files?

**Comment by GuiltyDolphin** [comment]
@jdorweiler :+1: That did it. Hae odd ;)
