### ISSUE TITLE
Random Choice: german umlaut

### ISSUE THREAD

**Issue by flipflopsimsommer** [duckduckgo/zeroclickinfo-goodies#2310]
@kablamo @mintsoft 
umlaut are displayed wrong in the description area

![sample](https://gateway.ipfs.io/ipfs/QmadgN3rjfzfohoWREdktM6gyYXHNyR8NZWzy7mtF3pZ1t)

------
IA Page:  http://duck.co/ia/view/abc

**Comment by GuiltyDolphin** [comment]
@flipflopsimsommer You mean the `m&uumll;sli`? That's probably to do with the escaping (which we have to do at the moment - internal stuff).

**Comment by flipflopsimsommer** [comment]
@GuiltyDolphin yes that what i ment

**Comment by flipflopsimsommer** [comment]
seems like somebody fixed it
