### ISSUE TITLE
PigLatin: Need to verify we have a remainder to translate

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2320]
Looks like we're not ensuring there are remainder words to translate!

https://duckduckgo.com/?q=pig+latin&ia=answer
https://duckduckgo.com/?q=Lingua%3A%3APigLatin%3A%3ABidirectional&ia=answer

------
IA Page:  http://duck.co/ia/view/pig_latin
/cc @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@moollaza That should be fixed in #1970
