### ISSUE TITLE
Linux Cheat Sheet: 

### ISSUE THREAD

**Issue by shadiakiki1986** [duckduckgo/zeroclickinfo-goodies#2332]
@crashrane 
I think the ctrl c and ctrl z are swapped

------
IA Page:  http://duck.co/ia/view/linux_cheat_sheet

**Comment by venky18** [comment]
No It's fine. reference : https://files.fosswire.com/2007/08/fwunixref.pdf

**Comment by shadiakiki1986** [comment]
What is written is `ctrl c: backgrounds current command` 
When you use ctrl c, you can't get the job back up again.
If you run `jobs` after a `ctrl z`, you'll see the job, whereas with `ctrl c` you won't.
`ctrl z` is what lets you resume the job in the foreground or the background

**Comment by yash14123** [comment]
Agreed with @shadiakiki1986
