### ISSUE TITLE
Conversions: Display whole number output for temperatures

### ISSUE THREAD

**Issue by NikxDa** [duckduckgo/zeroclickinfo-goodies#2347]
Hi,
I think the formatting for temperature conversions should be changed to output a whole number, for example 29 degrees fahrenheit should be -2 degrees celsius. The correct version might be added in brackets, but this is way more user-friendly than the decimal conversion.

Thanks

**Comment by mintsoft** [comment]
Hi @NikxDa 
I'm not too sure I agree with this, personally I'd want to see as much accuracy as possible. What do @duckduckgo/community-leaders think?

**Comment by GuiltyDolphin** [comment]
@mintsoft I'm all for a good amount of *precision*, as long as it is guaranteed to be *accurate*.

**Comment by mintsoft** [comment]
@NikxDa I'm going to close this for now, if I see a similar suggestion from elsewhere then I'll reopen this
