### ISSUE TITLE
Calculator: Distinguish between log (base 10) and ln (base e)

### ISSUE THREAD

**Issue by jacobq** [duckduckgo/zeroclickinfo-goodies#2351]
@Mailkov Please have the log function either always use base 10 or allow use of a second argument to specify the desired base. Currently, it appears to use base e even though the ln function is already available for that purpose. 

Otherwise, it can be quite confusing when using other tools, such as Symbolab's solver in combination with the basic calculator.

For example, "solve: log(x) = 2" will result with "x = 100" but "log(100)" results in "4.60517018598809" instead of 2.

---

IA Page:  https://duck.co/ia/view/calculator
See also: https://duck.co/ia/view/symbolab

**Comment by Mailkov** [comment]
@jacobq 
Thanks for this issue ! I fixed it now !

FYI: If you want a log base X you can simply use `logX` or `log_X` 
`e.g. log_5(100)  or log5(100)`

**Comment by jacobq** [comment]
Thanks for the quick response. I'm glad there's a way to do it now. The
log_B notation appears to work for for symbolab as well though it treats
logB as an unknown function/symbol, e.g. solve: log10(x) = 2 does not
produce x = 100 but "solve: log_10(x) = 2" does as does "solve: log(x) =
2". So I'll try to keep that in mind next time I use this.

I think it's unfortunate that it still treats log(X) as log_e(X) instead of
log_10(X) since that is different from the convention I am used to (and
ln(X) is already available for exactly that purpose), but I appreciate that
you at least made it possible to do these calculations (not that I do too
much math via DDG, but sometimes it's handier than pulling out a calculator
or opening another program). I also realize that choice of convention (i.e.
https://en.wikipedia.org/wiki/Logarithm#Particular_bases ) is a rather
personal decision and often depends on how / where you were educated, so
it's fair that you as the author should get to pick it :)

-Jacob

**Comment by GuiltyDolphin** [comment]
@Mailkov @jacobq Just let you know, the calculator has been undergoing some work recently in #1927, we need to wait for that to be merged before additional changes as it is a large overhaul.

You can use `log10(X)` or `log_10(X)` to use base 10. There has been some discussion on this before but I believe the general consensus was to stick with the natural log by default.

**Comment by moollaza** [comment]
The new interactive calculator has been implemented which supports log and ln 👍 

When the Perl logic is deprecated (next week) queries with `log()` and `ln()` should be supported.
