### ISSUE TITLE
MySQL Cheat Sheet: cheat sheet not being displayed

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-goodies#2389]
Cheat sheet not visible for query [ `my sql cheat sheet`](https://beta.duckduckgo.com/?q=my+sql+cheat+sheet).

Missing `aliases` section

**Comment by GuiltyDolphin** [comment]
@vikashvverma For future reference, the `aliases` section is entirely optional, I wouldn't add it to a cheat sheet just for the sake of it.
