### ISSUE TITLE
The Travis CI build failure

### ISSUE THREAD

**Issue by mayank7** [duckduckgo/zeroclickinfo-goodies#2412]
The Travis CI build (continuous-integration/travis-ci/pr) is failing for every pull request even if there is very small change and that too is valid and correct.

**Comment by GuiltyDolphin** [comment]
@mayank7 Yup - well aware of this! Thanks - it's a dependency issue and we're working on it.

**Comment by mayank7** [comment]
@GuiltyDolphin So, should we raise pull requests or wait for it to be fixed ??

**Comment by GuiltyDolphin** [comment]
@mayank7 You can still make PR's, but the tests will fail until the dep issue is fixed - so prepare for failing tests.

**Comment by mayank7** [comment]
@GuiltyDolphin Okay, then I am making PR's.

**Comment by mayank7** [comment]
@GuiltyDolphin Sorry I din't get you.
Are you asking us to continue raising PR's or fix the existing PR's failure from our side?
Please clarify.

**Comment by mayank7** [comment]
@GuiltyDolphin One more thing, after this problem is fixed by you people, what about our PR's which have already failed due to this, will that be taken care by you ?

**Comment by GuiltyDolphin** [comment]
@mayank7 Mhmm, I'll just restart the failed builds when I am reviewing.

**Comment by GuiltyDolphin** [comment]
@mayank7 I've put out a temporary fix, so as long as you keep up-to-date with master (`git rebase master && git push -f origin BRANCH` or `git merge master && git push origin BRANCH`) you should be fine.
