### ISSUE TITLE
CheatSheets: Lengthy "terminal" blocks can overlap columns

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2507]
It looks like we may need to tweak the CSS a bit here. Any frontend devs interested in tackling this?

Example:
![md_cheat_sheet_at_duckduckgo_and_1____projects_zeroclickinfo-goodies__bash_](https://cloud.githubusercontent.com/assets/873785/13240667/4dcb5bae-d9b2-11e5-8062-4f0154ed7d57.png)

/cc @duckduckgo/community-leaders @duckduckgo/instant-answer-maintainers

**Comment by jinankjain** [comment]
I would like to work on this bug.

Could someone give me a head start where to start of with @moollaza

**Comment by vikashvverma** [comment]
@moollaza I have fixed that. Just need to create a PR.

**Comment by vikashvverma** [comment]
@moollaza Fixed that!

**Comment by moollaza** [comment]
@jinankjain @vikashvverma @mayank7 thanks for responding!

Let's try not to duplicate effort though guys! It looks like @vikashvverma made a PR first, but @jinankjain had asked for help even before that.

@vikashvverma @mayank7 it's best to help newcomers (instead of beat them to the PR) so we can grow the community :+1:

**Comment by moollaza** [comment]
@vikashvverma thanks for the PR -- I believe the issue is more about the margins/padding because the content is overflowing its container which is a bigger problem. I'd like to avoid word-break because that's going to make the content pretty ugly in cases where it breaks at an awkward point

**Comment by moollaza** [comment]
@jinankjain you'll want to look at https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/cheat_sheets.css -- you'll need to make sure your development environment is setup correctly and you'll need to test your changes on several cheat sheets. If you're new here it may be best to familiarize yourself with DuckDuckHack and CheatSheets first

**Comment by vikashvverma** [comment]
@moollaza I don't think this is a padding issue. The word (link) is too long to be accommodated in the `td` element.

**Comment by vikashvverma** [comment]
@jinankjain Let me know if you are working on this, I will close my PR.

**Comment by vikashvverma** [comment]
@moollaza I think @jinankjain is not reachable right now. I have other idea for fixing this issue.

Should we wait for @jinankjain to fix this?

**Comment by vikashvverma** [comment]
@moollaza It seems @jinankjain is not reachable right now. Can you review my PR.
