### ISSUE TITLE
Blender Cheat Sheet: Broken link

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-goodies#2549]
The cheat sheet [http://overapi.com/blender/](http://overapi.com/blender/) seems to be broken.

**Comment by GuiltyDolphin** [comment]
@vikashvverma Please refrain from opening issues if you intend to open the PR without discussion - the PR can just as easily explain what the problem is (and thus discussion can happen there instead).

**Comment by vikashvverma** [comment]
@GuiltyDolphin sure
