### ISSUE TITLE
TimezoneConverter: add Brazil DST

### ISSUE THREAD

**Issue by Fawers** [duckduckgo/zeroclickinfo-goodies#2625]
@GlitchMr 

Hello,
I'd love to have the option to convert to and from BRDT - Brazil daylight saving time. While BRT is `-0300`, BRDT is `-0200`.

I'd love to add the solution myself, but I have zero-knowledge on Perl.

Thanks in advance!

------
IA Page:  http://duck.co/ia/view/timezone_converter

**Comment by palorieu** [comment]
Hello,
I did not understand your question ?

**Comment by Fawers** [comment]
>I did not understand your question ?

I just wanted an option to convert to and from BRDT as well. You know, Brazil daylight saving time...

**Comment by GuiltyDolphin** [comment]
@Fawers looking at the source for TimezoneConverter, it relies on the Dates GoodieRole for the time zones. I think that if #2626 gets implemented this will probably get solved.

**Comment by Fawers** [comment]
@GuiltyDolphin Nice! I'll subscribe to #2626 as well, then. Thanks!

**Comment by mintsoft** [comment]
@Fawers if you wanted to; it's actually *really* easy and doesn't require any perl knowledge to add to these.

There's a big list of supported timezones in the role here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/GoodieRole/Dates.pm#L82

Just add in BST and BRDT with the appropriate offsets; sorted!

**Comment by Fawers** [comment]
>Just add in BST and BRDT with the appropriate offsets; sorted!

You mean, like, `BRDT => '-0200'`? Well, that sounds easy, lol. Thanks!

**Comment by GuiltyDolphin** [comment]
@Fawers I've just checked the tables and it looks like Brazil Summer Time (UTC-0200) is BRST rather than BRDT, may I ask your source?

**Comment by Fawers** [comment]
@GuiltyDolphin Usually, `BRT` or `BRST` (Brazil Standard Time) are used to define `UTC-3`, while `BRDT` (Brazil Daylight Time, or something like that) is used to define `UTC-2`.

[This source](http://www.tldp.org/HOWTO/TimePrecision-HOWTO/tz.html) uses `BRST` and `BRDT` , and [this one](http://www.timeanddate.com/worldclock/brazil/sao-paulo) uses `BRT`.

Also, [Dates.pm already lists BRT](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/503dc9d9110f35f05b32500f611c954684a21873/lib/DDG/GoodieRole/Dates.pm#L86) and I was on my way to commit `BRDT`. 😁

**Comment by GuiltyDolphin** [comment]
@Fawers Huh... That's the only source I've seen that uses BRDT - all the others I've come across use BRT for UTC-0300 and BRST for UTC-0200.

**Comment by Fawers** [comment]
@GuiltyDolphin No kidding? I always see `BRST` = standard. But it makes sense if you think of `AEST` and `AEDT` - Australia Eastern Standard and Daylight Time.

**Comment by GuiltyDolphin** [comment]
@Fawers Hummm... Yeah, makes sense - I think it should be fine to have BRDT as -0200 (with the source); the potential confusion only arises with BRST.

**Comment by moollaza** [comment]
@GuiltyDolphin will this be fixed in your DatesRole PR?

**Comment by GuiltyDolphin** [comment]
@moollaza Can do!

@Fawers I've been working on the Dates Role a fair bit lately, so I can include the changes with that.

I'll go through and add any missing TZs as well.

**Comment by Fawers** [comment]
Sounds good! I appreciate it.
