### ISSUE TITLE
Dates GoodieRole: Improve handling of time zones

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2626]
#2625 reminded me of a few updates to the Dates GoodieRole I would like to see.

Using data from https://www.timeanddate.com/time/zones/
- Provide support for more time zones
- Have Dates provide support for parsing descriptions of time zones into time zone abbreviations (and vice versa).
- Improve handling of time zones based on whether daylight saving time is in effect in a certain region.

I don't think this would be a fully trivial amount of work - but if anyone is interested in tackling this please let me know, I'll be happy to advise.

/cc @mintsoft

**Comment by mintsoft** [comment]
@GuiltyDolphin sounds good, I'm bombing out the low-hanging-fruit tag though, as the roles can be pretty complex with their X-IA interaction to the uninitiated

**Comment by GuiltyDolphin** [comment]
@mintsoft Whoops! Yeah, not exactly appropriate :wink:

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
