### ISSUE TITLE
Regexp: Improve display for mobile devices

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2643]
Unfortunately in getting `Regexp` to display nicely on full-width screens, it seems the mobile display has been reduced:

![screenshot from 2016-02-27 12 16 30](https://cloud.githubusercontent.com/assets/8598426/13372810/f73af9aa-dd4b-11e5-915e-ead68ec32414.png)

VS

![screenshot from 2016-02-27 12 16 37](https://cloud.githubusercontent.com/assets/8598426/13372812/fd4138b4-dd4b-11e5-9bf8-e0a3be9c327e.png)

What needs to be done:
- Fix the mobile display so that both the pattern names **_and**_ matches consistently display well.
- Ensure the full-screen display is robust and won't be messed up by long queries. 

---

IA Page: https://duck.co/ia/view/regexp

**Comment by jagtalon** [comment]
Oh hey I'm the maintainer!

**Comment by GuiltyDolphin** [comment]
@jagtalon Apparently yes! Any thoughts?

**Comment by jagtalon** [comment]
Uhm, that it should be fixed? Hahaha

I kid. I'll look into it

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin @jagtalon If there has been no update on this issue so far, I'd be interested to try some CSS magic here.

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Go for it - I'm in need of a CSS magician.

**Comment by holtjohnson** [comment]
Bumping this issue.

Is there anything else that needs to be done for this to be finished? I'm very adept at CSS, should it need any finishing touches.
@GuiltyDolphin, @jagtalon, & @NaveenKarippai

**Comment by GuiltyDolphin** [comment]
@holtjohnson The PR is over on https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3154 if you wanted to take a look.

@moollaza What's the status with the PR? Are there any outstanding issues?

**Comment by moollaza** [comment]
> @moollaza What's the status with the PR? Are there any outstanding issues?

Yes, the PR should not add any media queries. If we simply remove the set width, this should mostly be fixed. There's a separate issue that needs to be fixed internally with our `chomp()` function

**Comment by holtjohnson** [comment]
@moollaza I'll make the changes and create a new PR.

**Comment by moollaza** [comment]
@holtjohnson thans a lot!

**Comment by holtjohnson** [comment]
Made the changes and created a PR.

**Comment by holtjohnson** [comment]
Made the changes and created a PR.
@moollaza & @GuiltyDolphin

**Comment by mintsoft** [comment]
Fixed in #2643
