### ISSUE TITLE
Coin: Doesn't trigger on coin flip

### ISSUE THREAD

**Issue by stevenmg** [duckduckgo/zeroclickinfo-goodies#2646]
@mattlehning 

------
IA Page:  http://duck.co/ia/view/coin

**Comment by mintsoft** [comment]
@stevenmg do you mean the actual query `coin flip` as in: https://duckduckgo.com/?q=coin+flip

**Comment by stevenmg** [comment]
@mintsoft Yes, that's what I meant.

**Comment by pnpninja** [comment]
@mintsoft do we make it trigger?

**Comment by mintsoft** [comment]
@pnpninja Yeah, I see no reason not to :+1:

**Comment by pavithirakc** [comment]
I am on it !!

**Comment by pavithirakc** [comment]
I am on it!!

**Comment by pecey** [comment]
Can I work on this one?

**Comment by mintsoft** [comment]
@pecey unfortunatley there's already a PR in progress: #2663

**Comment by tagawa** [comment]
Hi @pecey. It looks like the PR for this is no longer being worked on so would you like to take it on after all?
