### ISSUE TITLE
Ed Cheat Sheet: Switch to `terminal` template

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2664]
Many of these commands are lengthy and it's causing the display to look broken. We should switch this to the `terminal` template to better handle the long lines and paragraphs.

------
IA Page:  http://duck.co/ia/view/ed_cheat_sheet

/cc @Gumnos

**Comment by Gumnos** [comment]
@moollaza When I initially created it, I used the only template I knew/found at the time. I don't object to switching to a `terminal` template and would be glad to make any requisite transformation, but I'd need guidance on where to find this template to make modifications.

**Comment by vikashvverma** [comment]
@Gumnos You can update cheat sheet json from `"template_type": "keyboard"` to `"template_type": "terminal"`.

**Comment by Gumnos** [comment]
@moollaza I made the change as @vikashvverma suggested and it should be good to go.

**Comment by GuiltyDolphin** [comment]
@Gumnos Have you made a PR with the changes?

**Comment by Gumnos** [comment]
@GuiltyDolphin Sorry, I thought the above linking sufficed.  I [created a PR](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2677) but am unsure how to link it to this issue.

**Comment by GuiltyDolphin** [comment]
@Gumnos usually in the description (`Fixes #X`).

**Comment by Gumnos** [comment]
@GuiltyDolphin Odd, that was my recollection, so I'd put it in the description, yet it doesn't appear to have linked properly between the PRs.

**Comment by GuiltyDolphin** [comment]
@Gumnos I updated it for you - I think you put it in the title?
