### ISSUE TITLE
Add tests for custom cheat sheet triggers

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/zeroclickinfo-goodies#2685]
@GuiltyDolphin The cheat sheet tests should check for the following (at least) in custom_triggers:

1. Two cheat sheets using the same trigger.  Currently just silently ignores all but the first.
2. That categories already included by template_type aren't re-added via additional_categories

These should be fatal.  Any others you can think of.  We don't have any going out the door so I didn't think it should hold up the initial PR.

**Comment by GuiltyDolphin** [comment]
@zachthompson Sure! I'll sort these over on #2681.

**Comment by GuiltyDolphin** [comment]
@zachthompson Righty - those are added, and I did another one to check the template type is valid (using the `template_map` defined in `triggers.yaml`).
