### ISSUE TITLE
Move work out of handlers

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2696]
I've been looking through some of the Goodies (Perl) and noticed that in some there is a _lot_ of work being done in the handlers.

Having a lot of work in the handlers means that it is more difficult to understand _what_ the Goodie is doing - the handler should clearly show what information is being retrieved from the query and where it is used.

I have compiled a list (incomplete) of Goodies that I think should be updated. For each of these Goodies we should move work _out_ of the handler and into well-named subroutines that clearly indicate what their role is. The handlers should be concise and convey the overall approach the Goodie has to working with the query - we should minimize the amount of code _defined_ in the handler.
- [ ] [CalcRoots](https://duck.co/ia/view/calc_roots)
- [ ] [ColorCodes](https://duck.co/ia/view/color_codes)
- [ ] [ConvertLatLon](https://duck.co/ia/view/convert_lat_lon)
- [ ] [Dice](https://duck.co/ia/view/dice)
- [ ] [FrequencySpectrum](https://duck.co/ia/view/frequency_spectrum)
- [ ] [ResistorColors](https://duck.co/ia/view/resistor_colors)
- [x] [SubnetCalc](https://duck.co/ia/view/subnet_calc)
- [ ] [TimezoneConverter](https://duck.co/ia/view/timezone_converter)
- [x] [Unicode](https://duck.co/ia/view/unicode)
- [ ] [UnixPermissions](https://duck.co/ia/view/unix_permissions)

If you think there are any Goodies that should be added to this list (or removed), please let me know!

Also, please let me know if you are actively working on any of these - it'd be good to know what is in progress and what has yet to be started.

**Comment by mintsoft** [comment]
@GuiltyDolphin  Hmm I'm not too convinced that this is a preferential path here.

I think building all the answers up front for all inputs isn't necessarily a great move as it will increase memory consumption. The caching within the IA calls should deal with it generally in a transparent way. 
Although static work (i.e. stuff that's recycled for each request irrespective of the input, building regexes for example etc) it makes sense to keep outside of the handlers

**Comment by GuiltyDolphin** [comment]
@mintsoft Can you clarify? If you look at the examples given, there are huge bodies of work being done directly within the handlers (including defining regexes etc..) - it is this which I wish to be eliminated; it makes reading and/or maintaining the Goodie harder, and makes it harder to find out what the Goodie is actually *doing*.

**Comment by MrChrisW** [comment]
@GuiltyDolphin So you're talking about two things here: **Code Readability** & **Code Efficiency**

>Additionally, having a lot of work in the handlers means that it is more difficult to understand what the Goodie is doing - the handler should clearly show what information is being retrieved from the query and where it is used.

Code Readability

You'd like to move the majority of the logic out of the main `handle` subroutine and move it into new subroutines that are named better -  this will allow for better readability and maintainability. This will help new maintainers understand the program flow better. :+1: 

_________
>The handlers have to be called for every query (unless cached). This means that any code within them has to be re-built for every query, which as you can imagine, is quite slow.

Code Efficiency

I'm not sure the efficiency would be improved much at all by moving the code out of the handle. There may be a slight improvement but not much to even notice. :frowning:  see http://www.perlmonks.org/?node_id=1115561

**Comment by GuiltyDolphin** [comment]
@MrChrisW Thanks for the link!

I'd happily sacrifice *some* efficiency for maintainability and readability any day! I think it is important to keep the Goodies in a manner that the open-source community can relatively easily go in and understand the code - without too much head scratching.

Having the code easy to read and work with makes it a lot easier for beginners to get stuck in making changes, fixing bugs etc..., without having to first decipher *what* the source is actually doing!

@mintsoft @MrChrisW Maybe I'm wrong about the efficiency - but even if there isn't an improvement, I don't think it'll make it *worse?*

Anyway, yes, my main concern is the readability and maintainability - that is what prompted this issue; I just felt maybe people might want *more* incentives :wink:

**Comment by mintsoft** [comment]
Yeah, personally I'd much rather focus on readability than anything else. For example I think https://github.com/duckduckgo/zeroclickinfo-goodies/blob/mintsoft/subnet-cleanup/lib/DDG/Goodie/SubnetCalc.pm is more readable than the old version with the subs being defined within the handle

**Comment by MrChrisW** [comment]
@mintsoft Good example. Looking at the IAs listed in the first comment, do you think readability could be improved by creating additional subroutines with well defined names?

@GuiltyDolphin Sounds like a good reason to me :+1: :dolphin:

**Comment by mintsoft** [comment]
@MrChrisW Yeah In some but but not others, I think it really depends. Creating subs everywhere for clarity can help, or alternatively it can make it less clear as the reader has to seek throughout the file to find the definitions. There's a great example of subs-gone-mad around, where they've just made it difficult to follow, but I can't find it right now. IIRC it was doing something to do with workdays between 2 dates or similiar.

Personally I think if the IA is like "do one thing" and it only has a `handle` <200 lines then I don't really think there's a problem, given sufficient test coverage

**Comment by GuiltyDolphin** [comment]
@MrChrisW As I've talked with @mintsoft about before - I'm really into functional programming so I have to restrain myself not to do subs everywhere in Perl :wink:

I think well-named subs are a *huge* benefit for the reader - instead of seeing 10 lines of random regexes and maps they might see a call to a sub `normalize_query_form` or whatever, and that should just tell them what that code is doing - if they want to investigate further they can!

I agree with @mintsoft though - in a language like Perl having *too* many subs could get a bit too much. It shouldn't get to a point where you *have* to read 10 subs just to decipher one bit of code if it could be achieved by 1 or 2 thoughtfully-named (short) subs.

Though I have to disagree with that 200 lines @mintsoft - that is *way* too much!

**Comment by mintsoft** [comment]
Well, maybe not 200; but you know what i mean

**Comment by GuiltyDolphin** [comment]
@mintsoft Hehe... Well, anyway, I'd like to see some people take this up over the next few days/weeks!

**Comment by GuiltyDolphin** [comment]
@moollaza Yeah! Especially for new IAs - getting something working with external packages is great - then if we find we need *more* features we can extend it later on.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
