### ISSUE TITLE
TimezoneConverter: Parses noon as midnight

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#2697]
![noon](https://cloud.githubusercontent.com/assets/978048/13527043/2660f90c-e204-11e5-9a3a-d215b9f82dbd.png)

**Comment by riqpe** [comment]
Reading the commit b9083d30fe05730610bbf2d75abf21c0324cb671 , this seems to be by design, which assumes AM when PM not present. Still, here's a quick PR to fix it #2699.
