### ISSUE TITLE
`\n` and `\t` not working?

### ISSUE THREAD

**Issue by talsraviv** [duckduckgo/zeroclickinfo-goodies#2700]
> Note - finally posting this in the right place - sorry @moollaza 

Was playing in codio with the new escape sequences - is this the right usage of `\n`? I didn't get a line break, and just ran `duckpan upgrade` before it

![screen shot 2016-03-04 at 9 45 28 am](https://cloud.githubusercontent.com/assets/1065307/13530149/f182b218-e1ed-11e5-8cef-14f7c069c9cb.png)

![screen shot 2016-03-04 at 9 45 40 am](https://cloud.githubusercontent.com/assets/1065307/13530153/f5a57664-e1ed-11e5-9c84-295c11911866.png)

(didn't work for code template or keyboard template either)

**Comment by vikashvverma** [comment]
@talsraviv Did you try fetching latest commits from this repo. This has been fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2627

**Comment by talsraviv** [comment]
Yep - thank you. Ok so it only works in the `key` property - will make sure docs make that clear - correct if i'm wrong

cc @moollaza

**Comment by vikashvverma** [comment]
@talsraviv I don't think there is any need for `\n` and `\t` support for value.

**Comment by talsraviv** [comment]
@vikashvverma that's cool with me - just want to make it clear to developers

**Comment by GuiltyDolphin** [comment]
Seems like this is resolved?
