### ISSUE TITLE
GibberishGenerator: Tests randomly fail

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#2707]
I've just had a PR go boom with this randomly failing, if the test are executed like 20 times, then it'll fail 1-2/20:

![randomtests](https://cloud.githubusercontent.com/assets/978048/13553641/c9eaa6ca-e387-11e5-95cf-8c9d073835ee.png)

**Comment by GuiltyDolphin** [comment]
@mintsoft Looks like Unicode issue!

It should support a few languages, it looks like some of the characters are being unhappy! Gimme a mo' and I'll check it out.
