### ISSUE TITLE
Frequency: Should be converted to use List Template

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2715]
This IA only returns a plain text response. Now that we have templates it should be updated to return a `structured_answer`. The `List` group with the record template would work well here. Each letter and its frequency could be a row in the table.

------
IA Page:  http://duck.co/ia/view/frequency
/cc @unlisted

**Comment by vikashvverma** [comment]
@moollaza I can work on this.

**Comment by tagawa** [comment]
Hi @vikashvverma. Are you still happy to work on this or would you like somebody else to help out?

**Comment by sahildua2305** [comment]
@vikashvverma Are you still on this?
@tagawa @moollaza Can I take this up?

**Comment by vikashvverma** [comment]
@sahildua2305 Go ahead, make a PR. I'm busy with other IAs

**Comment by tagawa** [comment]
Thanks @vikashvverma 

@sahildua2305 That would be great! Let us know if you need any help, or ask questions in the #ask-anything channel in Slack.
