### ISSUE TITLE
Dice: Layout regression

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-goodies#2719]
1. Dice are too small and almost illegible
2. Excess padding below the answer (poor vertical centering)
![screen shot 2016-03-08 at 12 10 35 pm](https://cloud.githubusercontent.com/assets/7061920/13615131/abd869cc-e528-11e5-8ae9-4534e403a336.png)

@jagtalon @moollaza @loganom @Mailkov 

------
IA Page:  http://duck.co/ia/view/dice

**Comment by loganom** [comment]
It was updated in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1982

I do agree that there may be some excess padding that is apparent at least when there is a single row of dice.

**Comment by chrismorast** [comment]
Ahh, thanks for pointing that out @loganom !

Updated comment accordingly

**Comment by edgesince84** [comment]
It looks like this was addressed by #1982
