### ISSUE TITLE
Conversions: Speed/Velocity conversions not implemented

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2729]
@phylum 

For example, these queries are not triggering the IA:
https://duckduckgo.com/?q=10+meters+per+second+to+feet+per+second
https://duckduckgo.com/?q=10+km%2Fh+to+mph

[Reported on Twitter](https://twitter.com/lamnatos/status/707581307874844672)

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
Original issue: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/689

**Comment by moollaza** [comment]
> however I can easily add some specific ones for speed in if it's important?

@tagawa @mintsoft I think support for kph and mph alone would cover the majority of distance/time queries?
