### ISSUE TITLE
Json Syntax Cheat Sheet: Complete re-phrasing

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2732]
Many people searching for `json syntax`, `json syntax cheat sheet` etc... Will be looking for a quick example of syntax - and oftentimes be beginners; they are not likely to be looking for this:

![screenshot from 2016-03-11 14 33 11](https://cloud.githubusercontent.com/assets/8598426/13704936/58ce3f2a-e796-11e5-80da-7b5d48a1fd99.png)

I request that someone *please* re-write this cheat sheet so it reads in a manner suitable for general consumption!

/cc @vCillusion

**Comment by jagtalon** [comment]
@GuiltyDolphin maybe something similar to https://duckduckgo.com/?q=go+cheat+sheet&ia=cheatsheet&iax=1?

**Comment by GuiltyDolphin** [comment]
@jagtalon Yeah - I'm thinking examples of what the field can take, rather than a *specification*. For example: `String -> "text"`, `Object -> { key1: val1, key2: val2 }` etc.

**Comment by zachthompson** [comment]
@vCillusion doesn't seem to be around....timed out.

**Comment by johnjkim** [comment]
I would like to work on this, if that's fine.

**Comment by zachthompson** [comment]
@johnjkim Please do, we look forward to your PR.

**Comment by akanshgulati** [comment]
I would like to work on this. Give me more suggestions and I will create a new IA layout adding my ideas too.

**Comment by GuiltyDolphin** [comment]
@akanshgulati All that needs to be done is to re-write the current cheat sheet to give a syntax overview rather than a BNF-style reference; i.e., an overview of the structures allowed in the language.
