### ISSUE TITLE
People in Space IA

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-goodies#2736]
I think we can add designation such as `Commander` as well to IA. This is readily available at data source http://www.howmanypeopleareinspacerightnow.com/

------
IA Page:  http://duck.co/ia/view/people_in_space 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @elebow

**Comment by mintsoft** [comment]
@vikashvverma Do you mean their rank?

**Comment by mintsoft** [comment]
@vikashvverma I've moved this to the spice repo
