### ISSUE TITLE
Zodiac: Images aren't showing?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2751]
It looks like the images for this IA have broken in production. Possibly an internal issue, but I'm not sure yet. Let's investigate and determine the cause!

------
IA Page:  http://duck.co/ia/view/zodiac 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @n0mady

**Comment by GuiltyDolphin** [comment]
@moollaza It's definitely trying to display an image; sometimes the broken image icon appears briefly.

**Comment by moollaza** [comment]
@GuiltyDolphin looks like your PR accidentally broke the images: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2013

Please add back the Goodie Bundle version number to the image path and then it will work as expected :+1:
