### ISSUE TITLE
Sublime Text Cheat Sheet: Add "sublimetext" and "sublimetext2" aliases

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-goodies#2754]
Not listen query `sublimetext Cheat Sheet` (in one word, yes).

It needed (as minimum) for consistency with other IAs and autocompletes. E.g. see [`sublimetext package html`](https://duckduckgo.com/?q=sublimetext+package+html&ia=software), or type "sublimetext" and see list of completions.

------
IA Page:  http://duck.co/ia/view/sublime_text_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @codenirvana

**Comment by codenirvana** [comment]
@fzzr- Only two aliases are given to it i.e, ```sublime``` and ```sublime text 2```
If you like you can make PR to add ```sublimetext``` into aliases.

**Comment by fzzr-** [comment]
>`sublime text 2`

[Hmmmm...](https://duckduckgo.com/?q=sublime+text+Cheat+Sheet&ia=cheatsheet) (without "2").

>PR

Mb. yes. Thx.

**Comment by codenirvana** [comment]
> Hmmmm... (without "2").

That's because of the file name ```sublime-text.json```
