### ISSUE TITLE
NumberStyler: Support words

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2766]
@mintsoft @mwmiller We should standardize parsing of number descriptions.

Currently there are two packages in wide use for Goodies to deal with this: [Lingua::EN::Numericalize](https://metacpan.org/pod/Lingua::EN::Numericalize) and [Lingua::EN::Words2Nums](https://metacpan.org/pod/Lingua::EN::Words2Nums). Unfortunately, both have their own issues.

Instead of relying on these modules _individually_ for each Goodie that requires number parsing, we should move the functionality into the NumberStyler GoodieRole; this would also help open up generic 'number-like' queries to any Goodies that take numbers as input.

I see two main approaches:
1. Create a wrapper around an existing package to attempt to alleviate any bugs; this would likely be less work than the second option, but would put us at the mercy of the foreign package and likely be less extensible.
2. Roll our own - I've looked at the code for both of these packages, and both clock in at about ~ 300 lines for their full functionality (a large portion of which is just definitions - which we could handle through YAML). I think this is easily achievable given we have already done harder parsing in the Dates GoodieRole!

You may have guessed, but my preferred option would be the second :wink:; as with [WhatIs](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/gd/whatis-role/lib/DDG/GoodieRole) I would suggest breaking the Role up into a package structure, appropriately moving NumberStyle in the process.

Any thoughts?

**Comment by mintsoft** [comment]
@GuiltyDolphin Matt (mwmiller) has left DDG now, so I'm basically 'the guy' for the numbers role now. 

What we did with the DatesRole was we started out by wrapping a CPAN module, as the use cases grew we moved the logic into the Role as it became more widely used. This worked pretty well and I don't remember there being any cases where the DatesRole broke anything due to the iterative approach used; so I'd lean towards a similiar evolutionary model personally. 

When you say "both have their own issues"; what are they exactly?

**Comment by GuiltyDolphin** [comment]
@mintsoft From CPAN (and I've encountered many of these in practice):

**Lingua::EN::Numericalize**:
* currently chops off plurals and other suffixes from words that are not numbers. This needs to be fixed since no words here produces no word here and hell hath no fury to hell ha no fury.
* would be nice to handle fractions
* spelled out number e.g. nine one one = 911 (not 11: 9+1+1)
* runnin' => r9 - yikes!

**Lingua::EN::Words2Nums**:
* It does not understand decimals or fractions, yet.
* While it handles googol correctly, googolplex is too large to fit in perl's standard scalar type, and "inf" will be returned.

These are the 'stated' bugs - there may be others.

**Comment by mintsoft** [comment]
Seems like `Words2Num` might actually work unlike `Numericalize` I think the first step would probably be to either: 
* Remove `Numericalize` and replace it with `Words2Num` so we only have one implementation pattern to address
* Wrap `Words2Num` in the role and convert both to use that, providing the interfaces for the two implementations and harmonise them after.

I think we should probably bomb out `Numericalize`?

**Comment by GuiltyDolphin** [comment]
@mintsoft `Numericalize` is just a wrapper around `Words2Nums` anyway, I don't think replacing it will be too much of an issue.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
