### ISSUE TITLE
Calculator: obscure behaviour - result exists but not.

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-goodies#2778]
QUERY: [?q=(2 - (8 \* 42) / 2) --166](https://duckduckgo.com/?q=%282+-+%288+*+42%29+%2F+2%29+--166&t=osx)

I see completion (screenshot) but Calculator not return result. I really don't know what it was.

![screen shot 2016-03-19 at 15 53 12](https://cloud.githubusercontent.com/assets/888526/13898706/6c592a60-edf3-11e5-9cb3-8d658d1def18.png)

![screen shot 2016-03-19 at 15 48 01](https://cloud.githubusercontent.com/assets/888526/13898696/e413cb38-edf2-11e5-856c-04ce7a7f31fc.png)

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@fzzr- We're still on the old calculator unfortunately :sad:

It works fine on the new one:

![screenshot from 2016-03-19 13 00 38](https://cloud.githubusercontent.com/assets/8598426/13898724/d4eae1c0-edd2-11e5-94f6-78ac9321fe20.png)

The answer is 0 in case you were wondering :wink:

**Comment by fzzr-** [comment]
Also for __none-zero__ result:

No completion
![screen shot 2016-03-19 at 16 06 17](https://cloud.githubusercontent.com/assets/888526/13898740/10958cee-edf5-11e5-91bc-07a55e98260e.png)

But after `=` completion is OK
![screen shot 2016-03-19 at 16 06 26](https://cloud.githubusercontent.com/assets/888526/13898742/259d158a-edf5-11e5-98e8-23d8a7b8caaa.png)

Anyway now result of IA :(

**Comment by GuiltyDolphin** [comment]
@fzzr- I don't think that completion is anything to do with the calculator :wink: I believe that means people just *searched* for that `...=0`.

**Comment by fzzr-** [comment]
O_o Okay.

>We're still on the old calculator unfortunately

I tried on beta.ddg.

**Comment by GuiltyDolphin** [comment]
@fzzr- Wait... What? I didn't think we had calculator completion... Weird... I tried it with some very obscure queries and it still works.

**Comment by fzzr-** [comment]
> I don't think that completion is anything to do with the calculator

It's weird. I don't think many people have entered the same expressions I do.

**Comment by GuiltyDolphin** [comment]
@fzzr- Basically there's two things going on here.

1. The query is giving an auto-answer before you hit return.
2. The current calculator does not give a result for the same query. This is fixed in #1927.

The first has nothing to do with the calculator itself AFAIK; I think there must be some internal stuff going on.

**Comment by fzzr-** [comment]
Okay :)

**Comment by pjhampton** [comment]
![screen shot 2017-06-30 at 5 28 43 pm](https://user-images.githubusercontent.com/8960296/27744993-a1cdcd5e-5db9-11e7-9ab9-5a33d364764a.png)

This will be fixed in an upcoming PR. Along with all the other functions 👍
