### ISSUE TITLE
Cheat Sheets (Controller): use production_state

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/zeroclickinfo-goodies#2780]
We be good to use our new `production_state` field to determine whether to load an individual cheat sheet.  This would allow us to turn them on/off without needing to remove the json.

---

IA Page:  http://duck.co/ia/view/cheat_sheets 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

**Comment by GuiltyDolphin** [comment]
@zachthompson Hmm... As with #2776, I could use the same package to grab the production state and switch them on/off?

What were you thinking in terms of loading? When should/shouldn't we load a cheat sheet?

**Comment by zachthompson** [comment]
The idea would be to load them if they are "online" only.  Have to consider how it would work with duckpan or development in general.

**Comment by GuiltyDolphin** [comment]
@zachthompson Seems to work fine. I would just drop them in `generate_triggers` or `get_aliases`. There is a *slight* slow-down waiting for it to fetch the IDs in testing, but only with the `CheatSheets.t` tests, not the JSON tests.

**Comment by shubhamkr1** [comment]
I can take this up. I still new to Perl and DuckDuckGo so I would need some mentor for help.
