### ISSUE TITLE
Cheat Sheets (Controller): Use topics to dynamically assign categories

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2781]
As discussed over on #2776, we could use the topics defined in the metadata on duck.co to dynamically assign categories to cheat sheets (and thus assign triggers).

I've got a 'prototype' over on https://github.com/duckduckgo/zeroclickinfo-goodies/tree/gd/cheatsheets-topic-categories

---

IA Page:  http://duck.co/ia/view/cheat_sheets 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

**Comment by zachthompson** [comment]
Cool.  @moollaza @russellholt @MariagraziaAlastra any thoughts?

**Comment by GuiltyDolphin** [comment]
@zachthompson Also, for testing maybe we could 'cache' the cheat sheets? This would avoid having the slightly longer wait time when loading the CheatSheets for `duckpan query` or `duckpan test`.

**Comment by GuiltyDolphin** [comment]
@zachthompson I think this might play quite well with #2777, where we could better customize what phrasing is ignored when triggering (e.g., we might ignore 'software' for the software group, thus allowing triggers like 'X software cheat sheet', 'cheat sheet X software' etc...).

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
