### ISSUE TITLE
Binary to Unicode Conversion: Triggers and shows empty result for 48 0's

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2783]
https://duckduckgo.com/?q=000000000000000000000000000000000000000000000000&ia=answer

We probably shouldn't trigger on this query, and we definitely shouldn't be showing an empty result!

------
IA Page:  http://duck.co/ia/view/bin2unicode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

**Comment by zachthompson** [comment]
lol :elephant: It's not empty you just need to look at the source.
