### ISSUE TITLE
TimezoneConverter: Shows MSK as UTC+4, should be UTC+3

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2787]
Reported through DDG Feedback. I used a VPN to confirm the bug though:
![10_am_pdt_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/13923268/42faa55e-ef56-11e5-8da9-649d95d6c259.png)

---

IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by tagawa** [comment]
Looks like this can be fixed in the Dates file:
 zeroclickinfo-goodies/lib/DDG/GoodieRole/Dates.pm

**Comment by GuiltyDolphin** [comment]
@tagawa If you check out #2810 I've got an open PR for any modifications to the Dates Role. It looks like the offset is already at +0300 over there, I don't think this is an issue with the Role.

@moollaza @GlitchMr looking at the TimezoneConverter Goodie, I think it is producing *way* too much date parsing logic (I imagine the defined logic is where the bug originates), it should definitely be relying on the Role more - I'll raise this as a separate issue.
