### ISSUE TITLE
IndependenceDay: Missing a few countries

### ISSUE THREAD

**Issue by RCMainak** [duckduckgo/zeroclickinfo-goodies#2790]
Hello, I noticed a few countries are missing in the independence_day.json file as well as no IA's are provided for those countries while searching.

I would like to contribute by adding those infos but I need guidance as it'll be my first contribution in IA. Will updating the independence_day.json file with the info be enough?? or do I need to add something else as well??

------
IA Page:  http://duck.co/ia/view/independence_day 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): ~~@jarmokivekas~~ @RCMainak

**Comment by t2013anurag** [comment]
Hey @RCMainak , I have updated the list. You can take a look at it here #2791 .
Also you just need to update the independence_day.json and country_aliases.json.

**Comment by t2013anurag** [comment]
@moollaza  : Fixed and merged #2791 and #2791.
Maintainer input required to merged the final changes to master.

@RCMainak = thanks a lot for your contribution.
