### ISSUE TITLE
Conversions: change comma/dot meaning (thousands separator / decimal mark) according to chosen language!

### ISSUE THREAD

**Issue by conrad-heimbold** [duckduckgo/zeroclickinfo-goodies#2797]
In countries where people talk English, 
- the **comma** is usually used to indicate parts of **thousands** (e.g. "1,500" means "one thousand five hundred"); 
- whereas the **dot** is used as **decimal mark** (e.g. "1.500" means "one and a half"). 

This is **exactly the other way round** in non-English-countries, e.g. all countries in Europe (except of course the UK), including Germany. Here, 
- the **comma** is used as decimal mark (e.g. "1,500" means "one and a half"); 
- whereas the **dot** is used to indicate parts of **thousands** (e.g. "1.500" means "one thousand five hundred"). 

As you will probably notice, displaying results in the wrong format CAN result in SERIOUS trouble! 

If I set my preferred language at DuckDuckGo to any non-English Language, and type in any Conversion, e.g. "332000000 bit in kilobyte", I still get the English format for numbers as mentioned above ("41,500 kilobyte"), which however means something COMPLETELY different in German (in German, it would just mean forty-one and a half kilobyte). 

Please change the display format for numbers according to the chosen language (make it dependant on the chosen language!). 
I think, this should be pretty easy to do (pseudocode): 
- IF chosen language == English ; THEN decimal mark = dot, thousands separator = comma
- IF chosen language <> English AND IF chosen language == European ; THEN decimal mark = comma, thousands separator = dot . 

I don't know about non-English and non-European countries; how they handle dot/comma and decimal mark/thousands separator. Do you know?

Thank you very much for changing that in advance!

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@corny2 thanks for the feedback, this should be relatively trivial to implement as we have a numbers system that currently 'guesses' the relationship between `,` and `.` depending on the shape of the numbers. 

@moollaza do goodies have access to the user's language preference? I guess `$loc` could also be used.

**Comment by GuiltyDolphin** [comment]
@mintsoft If #2810 goes well, we should be able to implement this relatively trivially. Fingers crossed!

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
