### ISSUE TITLE
PrimeFactors: Improve triggering

### ISSUE THREAD

**Issue by stevenmg** [duckduckgo/zeroclickinfo-goodies#2799]
Should trigger on "is 83 prime"

---

IA Page:  http://duck.co/ia/view/prime_factors 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark

**Comment by NaveenKarippai** [comment]
@stevenmg [noob question]: Is using regex triggers the workaround?

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Nawp. We rarely need regex triggers; this case would best be handled by the word `prime` then filter with a guard regex in the handler.

**Comment by darsnack** [comment]
Is this issue now unclaimed again? If so, I'd like to take a whack at it.
