### ISSUE TITLE
Ascii to Binary: Add option to separate output into sets of 4 bits

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2801]
Suggested through DDG Feedback 

This would probably require JS unless we permanently change the output format from the Perl

---

IA Page:  http://duck.co/ia/view/binary 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by GuiltyDolphin** [comment]
:+1: I agree - just had this same thought. It might improve wrapping too.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
