### ISSUE TITLE
Swift Cheat Sheet: Shows deprecated functionality

### ISSUE THREAD

**Issue by stevenmg** [duckduckgo/zeroclickinfo-goodies#2803]
Some functions shown are deprecated in the latest release of Xcode, and will be removed completely in Swift 3. For example ++ and -- should be replaced with += and -=.

------
IA Page:  http://duck.co/ia/view/swift_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gautamkrishnar

**Comment by gautamkrishnar** [comment]
Okay i will update the cheatsheet now

**Comment by gautamkrishnar** [comment]
Is it the only Change?  @stevenmg

**Comment by stevenmg** [comment]
This is mostly fixed by #2822, but for loop syntax is still using the C style loops which are now deprecated as of Swift 2.2.

I'll take a look at that myself.

**Comment by gautamkrishnar** [comment]
Sure @stevenmg thanks :+1: :smile:

**Comment by stevenmg** [comment]
This was taking care of by PR #2976. Closing it now :)
