### ISSUE TITLE
Swift Cheat Sheet: Very Minor Typo

### ISSUE THREAD

**Issue by AlexanderShapiro** [duckduckgo/zeroclickinfo-goodies#2809]
Under declaring new dictionaries the code reads: `var days = ["mon": "monday", "tue": "tuseday"]` It should be `"tuesday"`

------
IA Page:  http://duck.co/ia/view/swift_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gautamkrishnar

**Comment by gautamkrishnar** [comment]
oops really sorry for the late reply @AlexanderShapiro this is already fixed in #2822
