### ISSUE TITLE
Counter goodie

### ISSUE THREAD

**Issue by mezzodrinker** [duckduckgo/zeroclickinfo-goodies#2818]
Sometimes there are situations in which you need to keep track of something, be it how often you sneezed or how many coffees you had since you started working on that one project today. If, however, you try to find a counter online, http://ddg.gg/?q=counter will show you that you first need to skim through lots and lots of search engine results to find a website which provides you a simple counter.

This IA should provide a simple interface for users who would like to count something, possibly with features like these:
- increase counter
- decrease counter
- (re)set counter

A sample query could look like this:
- `counter` - shows the IA with the counter initialized to 0
- `counter 42` - shows the IA with the counter initialized to 42

---

IA Page: https://duck.co/ia/view/counter

**Comment by tagawa** [comment]
Thanks for the suggestion @mezzodrinker. Are you thinking it should be persistent, i.e. can be used long-term to record totals, or just simply to count clicks and then reset on page load?

**Comment by mezzodrinker** [comment]
@tagawa I think the counter should reset on page load. So "coffees since you started working on that one project" was a bit misleading, sorry.

**Comment by tagawa** [comment]
I see. So another use case could be people arriving at an event or similar. Sounds relatively straightforward to make.

**Comment by mezzodrinker** [comment]
Something like that, yes. It's a niche which should be easy to fill.

**Comment by GuiltyDolphin** [comment]
@mezzodrinker Do you think it would be worth supporting multiple named counters? E.g., `Guests: X`, `VIPs: Y` kind of thing. I think we could probably get some of the CSS out of Timer if so.

**Comment by mezzodrinker** [comment]
@GuiltyDolphin Hmm. Naming timers actually sounds like a nice idea, I didn't think about that. If it's not overly complicated to do, sure. That'd be nice.

**Comment by pjhampton** [comment]
Hey @mezzodrinker 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
