### ISSUE TITLE
Constants: query for "Stefan-Boltzmann" returns the wrong value

### ISSUE THREAD

**Issue by momom4urice** [duckduckgo/zeroclickinfo-goodies#2820]
Query for "Stefan-Boltzmann" returns the Boltzmann constant value (1.38e-23 SI). The Stefan-Boltzmann constant has a value of 5.67e-8 SI (https://en.wikipedia.org/wiki/Stefan%E2%80%93Boltzmann_constant).

Edit: The query I used is: "stefan boltzmann constant" and I got the Boltzmann constant: https://en.wikipedia.org/wiki/Boltzmann_constant

------
IA Page:  http://duck.co/ia/view/constants 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hemanth

**Comment by Roysten** [comment]
Could you post the query you used? When I enter `Stefan-Boltzmann` or `Stefan-Boltzmann constant` it does not trigger the constants IA (as expected, because it does not exist in constants.yml).

**Comment by edgesince84** [comment]
A DuckDuckGo user reported the wrong value for this same query.  They reported the constant should be 

> 5.6704*10^(-8) W m^(-2) K^(-4)

**Comment by mintsoft** [comment]
@Roysten @edgesince84 It's definitely wrong here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/constants/constants.yml#L82
