### ISSUE TITLE
Interactive Java Cheat Sheet: Improve source link

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2827]
We should probably stick to English where possible - visiting the reference page gave me quite a headache!

Admittedly I could not find any other sources for this language - perhaps a local dialect? 

---

IA Page:  http://duck.co/ia/view/interactive_java_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @OscarMZ

**Comment by tagawa** [comment]
@GuiltyDolphin I did the same thing a while ago - looked for an English source but couldn't find anything.

**Comment by GuiltyDolphin** [comment]
@tagawa Odd - @duckduckgo/duckduckhack-contributors anyone know any English references for Interactive Java?

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin http://introcs.cs.princeton.edu/java/11cheatsheet/
this looks like java cheatsheet. Is there a language named "interactive java"?
cc:@oscarMZ

**Comment by ethanchewy** [comment]
@gautamkrishnar That's a good find. That's what I used when I was learning Java! 

@GuiltyDolphin I've never heard of "interactive java" as a programming langauge. I thought that it was just a more interactive style of learning java.

If you are looking for java cheat sheets, here are a few others:
- http://www.dummies.com/how-to/content/java-for-dummies-cheat-sheet.html
- http://mindprod.com/jgloss/jcheat.html
- http://www.digilife.be/quickreferences/QRC/JAVA%20Programming%20Guide%20-%20Quick%20Reference.pdf

**Comment by GuiltyDolphin** [comment]
@ethanchewy @gautamkrishnar My first thoughts were the same, "Isn't this just a *program* for Java?", but alas, the description is "A small cheatsheet about the main functions of Interactive Java, a java-based language" and I cannot read French (nor find any other resources for it) so... *shrug*

**Comment by Nghia11** [comment]
https://www.w88.com
buitrungnghia09@gmail.com

**Comment by EpicWolverine** [comment]
I've never heard of Interactive Java either, and, while I can't read much Spanish (that's Spanish by the way, not French), I can read the code. All of the functions mentioned look suspiciously like [Processing functions](https://processing.org/reference/), though Processing doesn't use main() (it uses setup() and draw()). The source also refers to the language as iJava, which may help us find more on this.

**Comment by GuiltyDolphin** [comment]
@EpicWolverine Haha, so it is! My bad :wink: Hmm... Yeah, there do seem to be some similarities, but that happens across most languages :/ There are plenty of results for `ijava` and `interactive java`... but none of them are anything like this!

@OscarMZ Can you give us any info on this?

**Comment by harisphnx** [comment]
On Mon, May 9, 2016 at 1:54 AM, Ben Moon <notifications@github.com> wrote:
> @EpicWolverine Haha, so it is! My bad Hmm... Yeah, there do seem to be some
> similarities, but that happens across most languages :/ There are plenty of
> results for ijava and interactive java... but none of them are anything like
> this!

True, most of the results are pointing at something else. There
doesn't seem to be a universal language called IJava (or Interactive
Java). I feel this cheatsheet is for something quite specific.

>
> @OscarMZ Can you give us any info on this?
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub



-- 

With regards,

Md Haris Iqbal,
Placement Coordinator, MTech IT
NITK Surathkal,
Contact: +91 8861996962

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
