### ISSUE TITLE
Conversions: mixed units like 5 foot 6

### ISSUE THREAD

**Issue by russellholt** [duckduckgo/zeroclickinfo-goodies#2828]
should be able to used mixed units

https://www.google.com/#q=5+foot+6+to+m

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@russellholt thanks for this; it's already on my todo list: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1118

**Comment by GuiltyDolphin** [comment]
@mintsoft I'll close this for now then, and refer to the other issue.
