### ISSUE TITLE
Multisim Cheat Sheet: Remove 'help' trigger

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2831]
Per #2830, we will be able to trigger on 'multisim help' without needing the alias - we should be able to remove this alias to enable the tests to pass.

---
IA Page: https://duck.co/ia/view/multisim_cheat_sheet
Maintainer: @mRse7enNIT

**Comment by mRse7enNIT** [comment]
what I need to do? @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@mRse7enNIT Just remove the `multisim help` alias from the cheat sheet.
