### ISSUE TITLE
New Instant Answer Suggestion: Hourly Wage to Salary Instant Answer

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#2834]
I was curious to know what an hourly wage of X/hr equates to as a salary, it turns out there's lots of online calculators that do this, but it could be very easily implemented as an Instant Answer.

Some websites are very detailed providing tables of hourly/weekly/bi-weekly/monthly income for a given salary. Some go further and try and evaluate taxes etc.

To start a very basic calculation of a salary for a given wage, or the reverse would be great to have.

@duckduckgo/duckduckhack-contributors is anyone interested in working on this?

Any opinions on what information is most important?

I imagine it should state the assumed hours/week and working weeks/year. If we use a JS-focused Goodie we could use inputs to make all of that configurable.

Alternatively we have Chart.js available and could use that produce a graph that shows a salary for an hourly wage with the axes representing hours/week and weeks/year.

What do you guys think?

**Comment by philipmiesbauer** [comment]
Well, taxes and stuff is very much location based, but simple conversion
from hourly to yearly and reversed should be simple enough.
I am wondering how I would recognize the instant answer or how I would ask
it.

Any ideas, suggestions?

**Comment by philipmiesbauer** [comment]
I really like the idea though

**Comment by gvanwaelvelde** [comment]
Maybe if you search for '10 dollars per hour' you could show all conversions to weekly, monthly and yearly salary.
Other sample queries: annual salary 20000, 200 dollars a week, ...
Problem is that some these queries may have others meanings. For example '10 dollars per hour' might also be a rental price for some equipment or something.

**Comment by mattr555** [comment]
If you need inspiration in the form of an already-live IA, one analog could be the [uptime calculator](https://duckduckgo.com/?q=99%25+uptime&ia=answer).

**Comment by kfrz** [comment]
Searching for this exact issue -- I don't think it would be necessary to do any API calls, if it was kept simple and "assumed" hours/week. @gvanwaelvelde : you're not wrong the meanings could be amiguous but when used with the converter operator, e.g. "$20/hr in salary" or "$30k in hourly," it should be easily parsed.

Maybe there exists an API with detailed data out there, for more i18n-ness. . I'll do some searching but bumping this because I'd like to start contributing to this awesome engine!

**Comment by moollaza** [comment]
> I think I could take a swing at this, if it was kept simple and "assumed" hours/week

@philipmiesbauer that's a good place to start. Let's see how that looks and then we can adjust it.

If you're comfortable with JS, we can go the more interactive route and provide inputs for the user to adjust. This could help make it more clear what assumptions we've made and let them play around with the numbers.

There are a few "Interactive" IAs in progress and live right now:
- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2118
- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2897

**Comment by philipmiesbauer** [comment]
Hi sorry, what is a good idea? I am caught off guard a bit right now.

**Comment by moollaza** [comment]
@philipmiesbauer apologies, I mentioned the wrong person! Meant to mention @kfrz ^^^

**Comment by philipmiesbauer** [comment]
Ok, that makes more sense. :D Cheers and best regards

Zaahir Moolla <notifications@github.com> schrieb am Fr., 24. Juni 2016 um
21:53 Uhr:

**Comment by n-sayenko** [comment]
Is anyone working on this? I'd like to give it a shot if not!

**Comment by kfrz** [comment]
@n-sayenko go for it! I never got around to finishing my attempt, but let me know if you'd like some help or a code review :)
