### ISSUE TITLE
Cheatsheets: Experimental Perl!

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#2835]
```
each on reference is experimental at lib/DDG/Goodie/CheatSheets.pm line 28.
each on reference is experimental at lib/DDG/Goodie/CheatSheets.pm line 35.
each on reference is experimental at lib/DDG/Goodie/CheatSheets.pm line 50.
```
For 
```
rob@set $ perl -v

This is perl 5, version 20, subversion 2 (v5.20.2) built for i586-linux-gnu-thread-multi-64int
```
Which is the perl from Debian Jessie; not sure if this is still the case on the 12.04/14.04 perls

**Comment by GuiltyDolphin** [comment]
@mintsoft Each on reference is experimental? We've used it in a few places, @zachthompson any thoughts?

**Comment by zachthompson** [comment]
Yeah, that's annoying and we should just change it to use the standard de-reffed hash.

**Comment by mintsoft** [comment]
Closed in: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2839
