### ISSUE TITLE
HelpLine: Formatting

### ISSUE THREAD

**Issue by Spagy** [duckduckgo/zeroclickinfo-goodies#2840]
Could the formatting be improved so that different numbers are on different lines?
At the moment they all seem to run into one another.

It would also be nice to have a description of what each number is for if that's possible.

![screenshot_2016-04-07_00-38-39](https://cloud.githubusercontent.com/assets/5479401/14336141/1b4006ac-fc59-11e5-92c4-626f7580815c.png)

------
IA Page:  http://duck.co/ia/view/help_line 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @conorfl

**Comment by moollaza** [comment]
@Spagy thanks for reporting. This IA should likely be ported to use the full templates to take advantage of the List Template.

Then it could produce a table where each row would contain a phone number.

**Comment by moollaza** [comment]
Details about how to convert a Goodie to full templates can be found in #1171

**Comment by NaveenKarippai** [comment]
@moollaza could you please assign this issue to me. I'm interested to work on it.

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai It looks like you aren't in the contributors group? @moollaza I think an invite is in order.

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin Thanks. I'd be glad to get an invite in contributors group.

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Seems fine for me https://duckduckgo.com/?q=suicide+hotline&t=ffab&ia=answer

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin 

**SECOND_UPDATE:** I used **vpn** and it's triggered fine.

**Comment by tagawa** [comment]
Sorry for the delay @NaveenKarippai. I sent you an invitation to join the contributor group. If you accept that then we can assign issues to you.

**Comment by NaveenKarippai** [comment]
@tagawa no worries! And, thanks for the invite :+1:

**Comment by NaveenKarippai** [comment]
**ToDo:**

* [ ] refactor /adapt test suite

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Rather than going for a bulleted list, it may be worth doing a KV list seeing as there is more info in the YAML than just the phone number (you may wish to add a name for each as well).

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin could you please post an example of KV list (appearance) as I'm not sure about it.
Regarding _more info_ on list view, are you refering to `web` data field on yml file? 
And, how would you ask to add names - use _website name_?

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Yeah, I was thinking the website names (/ company names if available) would be best - then you could KV the name with phone number.

Here's a link to a query that shows key values: https://duckduckgo.com/?q=abc+%3D~+%2F%28%3F%3Cfirst%3Ea%29%28%3F%3Csecond%3Eb%29%28%3F%3Cthird%3Ec%29%2F&ia=answer

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin Thanks. It seems that I should ditch custom handlebars template and go for `record` sub-template for KV list. 

**double-checking**; Should I be adding website names explicitly on yml dat- For e.g., `web: http://www.lifeline.org.au/Get-Help/I-Need-Help-Now` should have `name: lifeline` data added and show `name`field as `key` on list?

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Yeah, basically - but find out the actual organization name (which may or may not be the same as the website name).

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin switched to KV list by using `content` sub-template! Could you please review the changeset.

FYI: The longer names (key-data field) are being wrapped off on list view.

**Comment by moollaza** [comment]
@NaveenKarippai please make a PR so we can review

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin I have referenced open PR on issue tracker (if you please scroll up, it should be visible). I still need to refactor/adapt test suite. working on it soon :small_blue_diamond:

**Comment by NaveenKarippai** [comment]
@moollaza  I have referenced open PR on issue tracker (if you please scroll up, it should be visible). I still need to refactor/adapt test suite. working on it soon :small_blue_diamond:

**Comment by mintsoft** [comment]
FIxed in : https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3096
