### ISSUE TITLE
Package Tracking IAs: Solve false-positive triggering between all the carriers 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-goodies#2845]
There are several package tracking instant answers which trigger incorrectly. I recommend that 1 goodie or spice be made that shows all potential delivery services matching the regular expression. e.g. giving the user the option to go to USPS or UPS when the tracking number entered could be both. 

*_Examples of bad triggering can be found in these issues: *_
#2008
#1621
#370

*_The current package tracking IAs include: *_
https://duck.co/ia/view/dhl 
https://duck.co/ia/view/fed_ex
https://duck.co/ia/view/hkdk
https://duck.co/ia/view/ips
https://duck.co/ia/view/laser_ship
https://duck.co/ia/view/ups
https://duck.co/ia/view/usps

Anyone is welcome to reopen and attack these issues individually but I'm going to close them in favor of this.

**Comment by zekiel** [comment]
and there's been a PR in progress for this very idea! https://github.com/duckduckgo/zeroclickinfo-spice/pull/2430

**Comment by moollaza** [comment]
Being handled in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3973
