### ISSUE TITLE
DateMath: Show business days as well

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2847]
For example, `07 Feb 2016 + 45 days` shows `23 Mar 2016` but could also show something like `08 Apr 2016 (business days only)`. It's complicated by needing to reflect the business days for the user's locale however.

As [suggested on Twitter](https://twitter.com/nonesuchzach/status/718222923518119936).

---

IA Page:  http://duck.co/ia/view/date_math 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@tagawa Hmm... An interesting suggestion, I'll have a think.

It wouldn't be terribly easy to do (robustly) with the current setup - and as you say, the meaning of a 'workday' can vary from person-to-person, place-to-place.

Suggestion noted, though.

**Comment by zachthompson** [comment]
Could be done well enough either allowing a user to specify their own workweek, e.g. sat-thu, or storing the 30 or so non-Mon-Fri workweeks listed [here](https://en.wikipedia.org/wiki/Workweek_and_weekend).

**Comment by tagawa** [comment]
That's true. Or even as a stop-gap solution, start by showing Mon-Fri with the label "weekdays".

**Comment by GuiltyDolphin** [comment]
@zachthompson @tagawa There are several Goodies that deal with weekdays/workdays/days between two dates - I'm thinking we could kill several birds with one stone here and add some functionality for date-distances into the Role (I've got an active PR #2810). We could then *consistently* let a user specify workday types.

Would be nice to have this sort of thing in the user preferences - as with letting IAs see things like region & language.

@zachthompson Are you imagining a query of the form `1st Jan + 20 workdays (sat-thu)`?

@tagawa Yeah, so `1st Jan + 20 workdays` -> `(whichever date) (assuming a work week of Monday-Friday)`?

**Comment by zachthompson** [comment]
@GuiltyDolphin Pretty much.  We could default to mon-fri and somehow suggest that you can modify this as well.

**Comment by GuiltyDolphin** [comment]
@zachthompson Yeah, those sorts of suggestions are difficult :wink:

It would be awesome if you could specify it here (in the 'advanced' options):

![screenshot from 2016-04-08 17 47 02](https://cloud.githubusercontent.com/assets/8598426/14391093/f2832294-fdb1-11e5-996e-256b6b7d7f67.png)

And allow IAs to access the preferences.

**Comment by zachthompson** [comment]
Yeah, that's one idea.  Or maybe calculate the major ones (there aren't that many) and allow them to select one if not specified.

**Comment by GuiltyDolphin** [comment]
@zachthompson How would you suggest allowing them to select one? Currently all the date(between) Goodies are pure-Perl AFAIK, and we have no control over what user preferences exist.

Would it be possible for the Role to embed additional JS in a standard manner that would allow for selection menus?

**Comment by zachthompson** [comment]
Well, just thinking out loud, there are only like four major workweeks specified in that link.  Maybe the layout looks roughly like:

 |  | | |
---- | ---- | ---- | ----
2016 Aug 01 | | |
__Mon-Fri__ |  Mon-Sat |  Sat-Thu | Sun-Thu

@moollaza actually has some ideas of how to implement something like this with our templates
