### ISSUE TITLE
Alternate Calendars: Maintainer Request

### ISSUE THREAD

**Issue by gaulrobe** [duckduckgo/zeroclickinfo-goodies#2856]
I would like to become the maintainer for this! Thanks!

------
IA Page:  http://duck.co/ia/view/alt_calendars

**Comment by zekiel** [comment]
@mintsoft  ok?

**Comment by mintsoft** [comment]
@zekiel That's fine

**Comment by zekiel** [comment]
thanks @mintsoft 

@gaulrobe you are now the maintainer!
