### ISSUE TITLE
Array Sorting Cheat Sheet: Maintainer Request

### ISSUE THREAD

**Issue by gaulrobe** [duckduckgo/zeroclickinfo-goodies#2857]
I would like to become the maintainer for this! Thanks!   

------
IA Page:  http://duck.co/ia/view/array_sorting_cheat_sheet

**Comment by abhisheksp** [comment]
I would like to become maintainer/contributer for this.

Thanks

**Comment by GuiltyDolphin** [comment]
cc @navneetzz
