### ISSUE TITLE
BRT: The server doesn't work anymore

### ISSUE THREAD

**Issue by mylainos** [duckduckgo/zeroclickinfo-goodies#2863]
The server http://as777.brt.it is unreachable. Is there an other way to get the tracking information?

---

IA Page:  http://duck.co/ia/view/brt 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @afelicioni

**Comment by afelicioni** [comment]
Thanks for opening this issue.

Sorry to see BRT systems are offline: unfortunately the carrier isn't releasing any alternative tracking control endpoints offered to the public. It's the same used on institutional website, so I may rank it as a temporary issue.

Please anyone can leave a comment if found better alternative instructions, so I will able to look into and make necessary IA code improvements.

**Comment by moollaza** [comment]
Hey guys,

DuckDuckHack is now in Maintenance Mode and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Seeing as this IA is not currently working I've disabled it. It doesn't look like there's an alternative source either so I'm closing this issue.
