### ISSUE TITLE
Unix Time Format Cheat Sheet: Maintainermanship

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2868]
@zekiel I made this one a while back - seems to have been missed out of the 'great assignment'; maintainer status would be dandy, thanks.

------
IA Page:  http://duck.co/ia/view/unix_time_format_cheat_sheet

**Comment by GuiltyDolphin** [comment]
@zekiel That's fast!

**Comment by zekiel** [comment]
you got it! https://duck.co/ia/view/unix_time_format_cheat_sheet 

Thanks!
