### ISSUE TITLE
Data Structure Operations Cheat Sheet: 

### ISSUE THREAD

**Issue by abhisheksp** [duckduckgo/zeroclickinfo-goodies#2872]
I would like to maintain this instant answer.   

------
IA Page:  http://duck.co/ia/view/data_structure_operations_cheat_sheet

**Comment by tagawa** [comment]
Hi @abhisheksp 
Sorry for the delay in getting back to you. That's very kind of you. We'd love to accept your offer!
I've just added your name to the IA page as maintainer. Note that there are no outstanding issues for this cheat sheet at the moment.
