### ISSUE TITLE
Base Conversion: Allow conversions from arbitrary bases

### ISSUE THREAD

**Issue by Spagy** [duckduckgo/zeroclickinfo-goodies#2877]
It would be useful to be able to convert from any base rather than only from base 10.

Example queries:
2A hex to decimal
1111 in binary to decimal
0x14 to decimal
81 in base 9 to base 3

I'm not sure how easy it would be to parse all of those but I think it would be useful if there were at least one syntax that could be used.

Note this would slightly overlap with the HexToDec IA.

------
IA Page:  http://duck.co/ia/view/base 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moritz

**Comment by jonk1993** [comment]
I'm looking into this

**Comment by edgesince84** [comment]
Cool, thanks Jon!
