### ISSUE TITLE
Color: Help Schema.org standardize!

### ISSUE THREAD

**Issue by kevinSuttle** [duckduckgo/zeroclickinfo-goodies#2882]
Wrote this up awhile back, but after seeing search results come back from https://duck.co/ia/view/color_codes, I'm super excited at the possibilities. It would be fantastic to contribute the work you've done already to standardize colors. 

https://github.com/schemaorg/schemaorg/issues/938

**Comment by moollaza** [comment]
@kevinSuttle hey there, thanks for posting this and welcome to DuckDuckHack!

I had a look at your linked message but I'm a little unclear how you think we can help?

What exactly are you looking for?


/cc @mintsoft

**Comment by mintsoft** [comment]
@moollaza Agreed; I don't really understand what's going on here!

**Comment by kevinSuttle** [comment]
Ok, so, first-off, apologies for the vague description. Let me attempt to explain. 

The issue I linked to is a proposal to Schema.org, which I'm sure you're familiar with. 
Right now, there is a schema for `Color`, but it's literally just an arbitrary string value. 

The proposal I put forth is much more robust, and actually codifies the various values and formats of a given Color object inside the detailed schema definition. 

Where DDG comes in: the other day, I searched for an HEX value, and was happily surprised by the "instant answer" result provided by the excellent work @Mailkov has done here: https://duck.co/ia/view/color_codes. 

<img width="577" alt="screen shot 2016-04-15 at 11 44 32 am" src="https://cloud.githubusercontent.com/assets/95672/14566932/a049d880-02ff-11e6-9923-2b640cb5b5da.png">

Since this has direct correlation to search engines, that's where I thought you could help. :) 
Does that make more sense now?
