### ISSUE TITLE
Vim Cheat Sheet: put exit commands at the top :)

### ISSUE THREAD

**Issue by markmckenna** [duckduckgo/zeroclickinfo-goodies#2885]
...for classic reasons.

------
IA Page:  http://duck.co/ia/view/vim_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kablamo

**Comment by GuiltyDolphin** [comment]
@markmckenna Why would you want to leave Vim?

**Comment by swapagarwal** [comment]
![](http://i.imgur.com/VOe71EA.png)

**Comment by J-tt** [comment]
Submitted a pull request now, pending approval.
