### ISSUE TITLE
TimezoneConverter: Make better use of the Dates GoodieRole

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2886]
There is a lot of superfluous date parsing and manipulation logic within the TimezoneConverter Goodie, we should be making better use of the features that the Dates Role provides.

We should already be able to replace a bunch of the logic with helpers provided by the Dates Role, but additional features may be accessible after #2810 is integrated.   

---

IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
