### ISSUE TITLE
IEx Cheat Sheet: Duplicate entry for import_file/1

### ISSUE THREAD

**Issue by milmazz** [duckduckgo/zeroclickinfo-goodies#2899]
The current [iex.json](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/92f315692e4a5739cd2d4b5ba41a140ae43c5708/share/goodie/cheat_sheets/json/iex.json) have a duplicate entry for `import_file/1` IEx helper.

![iex-cheatsheet](https://cloud.githubusercontent.com/assets/34700/14590058/02b1f80a-04b7-11e6-92f0-337e48de0891.png)

Also, It would we awesome if you can sort alphabetically all the IEx commands as appears in the official documentation.

------
IA Page:  http://duck.co/ia/view/iex_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hey @milmazz,

Thanks so much! Well spotted. 
Would you like me to take care of this, or would you like to take it?

p

**Comment by milmazz** [comment]
@pjhampton I'm taking care of this :)
