### ISSUE TITLE
New IA: FIRST Robotics Competition rules

### ISSUE THREAD

**Issue by AlterationBrick** [duckduckgo/zeroclickinfo-goodies#2915]
(Not for the 2016 game because it's almost over)
Idea: When the rules for the FIRST Robotics Competition are released/decrypted next January, make a cheat sheet with things we constantly look up, like:
- Robot dimensions and weight limits
- Distance to elements of the field
- Dimensions of field elements like goals, obstacles, etc.
- Scoring for everything: balls, hoisting, autonomous, etc.
- Match timing
- Any other numbers in the rules that might be useful

I realized my robotics team spends hours looking through 100-page PDFs of dense legalese for these simple numbers, when we could have them all in a nice cheat sheet.

Again, please don't go through all that effort for this year's competition, because the robots are already built and the competitions are almost over.

**Comment by GuiltyDolphin** [comment]
@AlterationBrick We don't usually have cheat sheets that are based on a time-based event (that can cause the contents to be invalidated).

Do you know if there are any APIs that could be used to provide accurate information across time? Or any pages we could scrape?

**Comment by AlterationBrick** [comment]
I haven't seen any APIs for that info. It's all in a very large PDF on FIRST's website.

http://www.firstinspires.org/resource-library/frc/competition-manual-qa-system

But I agree that maintaining it would be a struggle without some automation.

**Comment by alohaas** [comment]
@GuiltyDolphin brings up a good point, we typically want to use data or information that isn't updated frequently for cheat sheets. Since this information is updated annually, I could see making an exception. It would be up to the maintainer of this IA to keep it up to date.

@AlterationBrick correct me if I'm wrong, but the keys for this cheat sheet could be reused every year, making maintenance simpler. For instance, you mentioned robot dimensions and weight limits above. Dimensions and weight limits would always exist as keys, but their values would change year to year. After the competition and until the cheat sheet was updated with the new rules the instant answer could be deactivated.

This might be something that @moollaza might like to chime in on.

**Comment by AlterationBrick** [comment]
@alohaas @GuiltyDolphin Unfortuantely, all the keys except robot weight are subject to change. The way robots score points is always different year-to-year, but this year also differed in that the dimensions of the robots were determined by a maximum perimeter, instead of maximum width and length. This year they required bumpers on robots because there was more contact, and they specified dimensions for them, whereas last year bumpers were totally optional.

Is there a way to encode a date when an IA will automatically deactivate? That would make a good fail-safe in case the maintainer doesn't update it.

**Comment by GuiltyDolphin** [comment]
@AlterationBrick Not AFAIK (without making exceptions), we've not had need of it before.

It sounds like it would be pretty bad if it went out of date and people used it (a warning probably wouldn't help); we'd be giving them incorrect information that they might act upon!

**Comment by moollaza** [comment]
If we know that it's likely to change and will potentially become outdated I would suggest we don't make a cheat sheet for it.

However, maybe a link-based cheat sheet would help? We could provide links to various info, assuming the links are consistent

**Comment by AlterationBrick** [comment]
@moollaza A link-based cheat sheet would work better if the info wasn't so centralized. Right now, all the info we need is in a game manual PDF, which I just checked and is 111 pages long... 

They don't ever post the simple dimensions of things directly on their website, probably in case there is a rules change and that info becomes obsolete.

It's okay, we have 8 months to figure this out.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
