### ISSUE TITLE
Improvement/suggestion for Curl cheat sheet

### ISSUE THREAD

**Issue by lemueldsouza** [duckduckgo/zeroclickinfo-goodies#2917]
This is for https://duck.co/ia/view/curl_cheat_sheet

The page looks fine to me, I just have few small improvements/suggestions
I guess it would be better to 
1. Have a -v (verbose) and --connect-timeout (or -m/--max-time) since they're used frequently
2. Instead of having https://www.cheatography.com/ankushagarwal11/cheat-sheets/curl-cheat-sheet/ as the reference, would it be a good idea to have a link that has all options? Something like http://linux.about.com/od/commands/l/blcmdl1_curl.htm ?

**Comment by vikashvverma** [comment]
@lemueldsouza LGTM
Thanks!

**Comment by mintsoft** [comment]
Closed in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2894#issuecomment-215748443
