### ISSUE TITLE
Emberjs Cheat Sheet: Maintainer request

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-goodies#2918]
I would like to become the maintainer for this! 

Thanks!   

IA Page:  http://duck.co/ia/view/emberjs_cheat_sheet

**Comment by tagawa** [comment]
Hi @vikashvverma. Sorry for the delay in getting back to you and thank you very much for offering to be the maintainer. I've just added your name to the IA page.
