### ISSUE TITLE
Hex To Ascii: Improve triggering

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2921]
We should support forms like `0x1F hex to ascii`, `0x1F to ascii` etc.

------
IA Page:  http://duck.co/ia/view/hex_to_ascii 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by koosha--** [comment]
Good idea. Anybody is welcome to make these changes.
