### ISSUE TITLE
Calculator: Support context-sensitive constants

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2922]
It might be useful to have constants that can vary based on a specified context.

For example, the query `(2G * 1.7e3) / c^2` doesn't yield a result as there are 'undefined' constants; but if you did `(2G * 1.7e3) / c^2 (astrophysics)` we could yield a result informing the user that the calculator interpreted: `G` as the gravitational constant, and `c` as the speed of light in a vacuum.

So, as a quick mock-up:

![screenshot from 2016-04-24 12 28 01](https://cloud.githubusercontent.com/assets/8598426/14767202/12c2d9ba-0a18-11e6-8112-32c0516b0844.png)

/cc @duckduckgo/duckduckhack-contributors Would any of you find this useful?

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by EpicWolverine** [comment]
I think this would be very useful. Perhaps we could even go so far as to try to guess at the constant but have an option to switch to an alternate meaning in a similar manner to the way WolframAlpha handles it. 
![image](https://cloud.githubusercontent.com/assets/2897970/14767524/5ee6ed72-09f5-11e6-8fad-5981512d4963.png)

**Comment by GuiltyDolphin** [comment]
@EpicWolverine I'm currently working on the interactive version (#2848); so I was thinking we could perhaps have it automatically switch to the appropriate constants page (I wish to have a modular constant/function layout); that or have a context automatically set to that inferred, allowing the user to easily switch to another context if desired.

**Comment by mintsoft** [comment]
@GuiltyDolphin sounds cool

**Comment by pjhampton** [comment]
Yeah, I agree. This sounds really cool... but based on the query data there is no business case for it.  Also, I'm not the right dev to implement this into this v2 js calc. I think the way forward here to abandon this, or 2, check out an old version of the exclusive perl backed interfaceless calculator and create a new IA. Regardless, I will close this down for now as there isn't any activity here.
