### ISSUE TITLE
AngularJS Cheat Sheet: Add extra services/directives

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#2934]
A Reddit user provided us with feedback for your IA, via https://www.reddit.com/r/angularjs/comments/4gedzp/help_improve_duckduckgos_angularjsrelated_searches/

Here is the comment:

>    You have some important services missing that you could fit into your page would be $compile and $q ($injector, $parse, $interpolate, $templateCache also worth contenders).
> You might also have some important directives missing such as ngApp, ngRepeat, ngController, ngShow, ngIf, ngHide, ngTransclude. Plus, all of those key-event and mouse-event directives you've got listed could be condensed into something like ng[keyevent] and ng[mouseevent] respectively.
> You might also wish to mention important module instance (angular.module("")) methods such as controller, directive, filter, provider, factory, service, value. constant. As well as config and run.
> To help you, here is a list of providers and directives. https://github.com/angular/angular.js/blob/master/src/AngularPublic.js
> - providers (line 219 to 257). Include the providers with the "$" prefix but ignore those with "$$" as they are internal to Angular and in theory should not be used by developers because they can be changed or deleted in the future.
> - directives (line 176 to 211). There is missing "ngApp" and "ngStrictDi" which are special directives only used during automatic bootstrap).

---

IA Page: http://duck.co/ia/view/angularjs_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @SibuStephen

**Comment by SibuStephen** [comment]
@edgesince84  i will surely take a look into it and embedd the directive, filter, provider etc, into the angular cheatsheet as such.

**Comment by tagawa** [comment]
Thank you @SibuStephen. Feel free to let us know if need any help with this.

**Comment by mr-karan** [comment]
Can I take this up ?
