### ISSUE TITLE
AngularJS Cheat Sheet: Developer attribution not present

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-goodies#2935]
This IA is not displaying developer attribution.

<img width="1439" alt="screen shot 2016-04-27 at 8 26 34 am" src="https://cloud.githubusercontent.com/assets/915277/14840427/e5e43628-0c51-11e6-8ac6-7a46426ff60d.png">
   

IA Page:  http://duck.co/ia/view/angular_js_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @SibuStephen

**Comment by SibuStephen** [comment]
@vikashvverma  will add Developer Attribution for the same as such.

**Comment by jdorweiler** [comment]
That tab name makes me thing something is not right with the IA page data.  I'll take a look at it.

**Comment by jdorweiler** [comment]
IA page ID didn't match the ID in the cheatsheet json file https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/angularjs.json#L2.  `angularjs_cheat_sheet` vs `angular_js_cheat_sheet`.  I updated the ID in the IA page and put it on beta
https://beta.duckduckgo.com/?q=angularjs+cheatsheet&ia=answer&iax=1
