### ISSUE TITLE
Visual Studio C#: Add valid location of snippets

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#2936]
Would it be possible to include the "Valid locations to insert snippet" section of the table from the source to the cheat sheet?

---
https://duck.co/ia/view/c_sharp_snippets_cheat_sheet

**Comment by tagawa** [comment]
Note: The info is already available in the [source table](https://msdn.microsoft.com/en-us/library/z41h7fat.aspx) and could perhaps be added in parentheses to the existing keys/values.

**Comment by marti1125** [comment]
Hi @tagawa please review my PR thanks!!

**Comment by tagawa** [comment]
Thanks for making this change @marti1125 - I'm taking a look now.

**Comment by tagawa** [comment]
I just merged your improvements @marti1125 - thanks very much!

**Comment by marti1125** [comment]
Great :D
