### ISSUE TITLE
CSS Language Cheat Sheet: Fix typo on description

### ISSUE THREAD

**Issue by VitorVRS** [duckduckgo/zeroclickinfo-goodies#2937]
This description: "Specifies the stack order of an elemen"
Should be: "Specifies the stack order of an element"

:ok_hand: 

------
IA Page:  http://duck.co/ia/view/css_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ethanchewy

**Comment by ethanchewy** [comment]
Good catch @VitorVRS !

**Comment by mintsoft** [comment]
closed by https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3046
