### ISSUE TITLE
C Cheat Sheet: Operators should be ordered by precedence

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#2938]
This reference page may help: http://en.cppreference.com/w/c/language/operator_precedence

(Originally reported in the [C subreddit](https://www.reddit.com/r/C_Programming/comments/4gp2xt/help_improve_duckduckgos_crelated_searches/))

------
IA Page:  http://duck.co/ia/view/c_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @harisphnx

**Comment by harisphnx** [comment]
There is the order of precedence given separately. Is it about the precedence in each sub section?

**Comment by tagawa** [comment]
@harisphnx Yes, I think so, if it's possible. I may only be relevant for one or two sub-sections.

**Comment by harisphnx** [comment]
@tagawa, Ok. That can be done. The problem with that is, the ones with the same precedence will also come is separate lines. Like the product * and the division / operation.

**Comment by tagawa** [comment]
@harisphnx I think that's fine. In those cases the order can stay the same (or whatever you like).

**Comment by harisphnx** [comment]
@tagawa, Ok then. I would keep the original order for those cases.
