### ISSUE TITLE
Django Instant answer suggestions

### ISSUE THREAD

**Issue by nickrsan** [duckduckgo/zeroclickinfo-goodies#2940]
Hi there,

I was just testing the Django Instant Answers, and saw that it only seems to come up when you search for "Django Model Cheat Sheet" - which won't get new users to find it. I think it'd be great if it also comes up when the user searches:

- Django model reference
- Django model
- Django model field
- Django model fields
- Django model Relationships (maybe not this one, not sure)
- and probably almost anything that has https://docs.djangoproject.com/en/stable/topics/db/models/ as a top result.

In my testing, the cheat sheet didn't show up on the DDG beta site for any of those searches, but did show up if I specifically put in "cheat sheet" after "django model", but let me know if I'm testing incorrectly! Thanks!

https://duck.co/ia/view/django_model_cheat_sheet

**Comment by pjhampton** [comment]
Hey @nickrsan 

Thanks for your feedback. There is actually another one in the pipes somewhere. 
I think this is a good idea. Would you like to take this enhancement forward? Otherwise I can do it at some stage.

**Comment by nickrsan** [comment]
Probably not right for me in this instance - I *want* to, but I'm sure I'd find myself not making it a priority right now. I'll keep following this, and might try it, but don't count on it! Thank you

**Comment by pjhampton** [comment]
@duckduckgo/duckduckhack-contributors 

Some seriously low hanging fruit if anyone wants it. Would be ideal for a first time contributor. All that is needed is to add the values

- Django model reference
- Django model
- Django model field
- Django model fields

to the alias key on the [Django Models File](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/django-model.json)

https://duck.co/ia/view/django_model_cheat_sheet

**Comment by prasadram** [comment]
I am interested. Can I handle it?

**Comment by hchienjo** [comment]
I am interested.

**Comment by pjhampton** [comment]
@prasadram it's yours :)

Sorry @hchienjo, just a little too late. If I have another I will ping you first - promise :smile:

**Comment by hchienjo** [comment]
@pjhampton, sure, no problem at all.

**Comment by GuiltyDolphin** [comment]
@hchienjo If you're interested in *other* LHF issues there's [plenty](https://github.com/duckduckgo/zeroclickinfo-goodies/labels/Low-Hanging%20Fruit).

**Comment by hchienjo** [comment]
@GuiltyDolphin definitely interested. Thanks.

**Comment by rasikapohankar** [comment]
> the cheat sheet didn't show up on the DDG beta site for any of those searches, but did show up if I specifically put in "cheat sheet" after "django model"
@pjhampton I was wondering, to trigger a cheat sheet we have to search with the cheat sheet name or an alias and a trigger word. So after adding aliases we would still have to search with alias + trigger word. Is that right? Please correct me if I am wrong.

**Comment by GuiltyDolphin** [comment]
@rasikapohankar I've been working on additional trigger mechanisms - allowing additional 'fluff' words, additional trigger words etc. But yes - in essence both a trigger phrase + alias/name will be used to trigger a cheat sheet.

**Comment by rasikapohankar** [comment]
@GuiltyDolphin I was not able to quote the sentence, sorry! I was referring to this,
> the cheat sheet didn't show up on the DDG beta site for any of those searches, but did show up if I specifically put in "cheat sheet" after "django model"

**Comment by GuiltyDolphin** [comment]
@rasikapohankar Yes - at the moment most of those won't trigger on their own due to the way triggering is handled (and will be handled for the foreseeable future - the system works); one way to allow the triggering would be to add

```yaml
django_model_cheat_sheet:
  additional_categories:
    - "reference"
  triggers:
    end:
      - "field"
      - "fields"
      - "relationships"
```
to the `triggers.yaml` file - but I'm not sure the use case warrants a full trigger spec; @zachthompson what do you think?

**Comment by rasikapohankar** [comment]
@GuiltyDolphin Thanks!

**Comment by pjhampton** [comment]
Super thanks for all your help @rasikapohankar 😃  

How are you finding this? Need any help?

**Comment by sahildua2305** [comment]
@rasikapohankar Are you still on this one?

@pjhampton I want to get started. Looking for another 'really' low hanging fruit like this one. Please help.

**Comment by rasikapohankar** [comment]
Hey @sahildua2305, I thought @prasadram was taking it up, https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2940#issuecomment-215504344.
I'm sorry for the confusion. But I haven't yet done this yet, so maybe you can take it. :) :+1: @pjhampton is that okay?

**Comment by prasadram** [comment]
Hi ,
Sorry I couldn't complete it because of some challenges, if any one can
complete that's OK . Otherwise I'll try to complete by this weekend

Thanks and Regards,
Ram Prasad

**Comment by pjhampton** [comment]
That's fine @prasadram & @sahildua2305 😄  Thanks for the update!

Yeah definitely @sahildua2305, this seems like a good opportunity to get more involved! It's yours! 💛

**Comment by sahildua2305** [comment]
Thanks @rasikapohankar @prasadram and @pjhampton I am on this one right now.

Have some suggestions. I strongly think the template type for this IA should be code so that users are able to trigger this IA using keywords like "code snippets" or "syntax" along with the above mentioned keywords (aliases). What do you think?

**Comment by pjhampton** [comment]
If you think that is the way to go @sahildua2305, go for it! I'll be happy to give you some feedback once you submit a PR :smiley_cat:

**Comment by moollaza** [comment]
@sahildua2305 I'm worried that changing the type to `code` is going to make it harder to read. Adding an additional category to the Cheat Sheet in the YAML file is probably a better way to go. It'll add the triggers, but maintain the design.

**Comment by sahildua2305** [comment]
@moollaza Yes, even I realized that `code` won't be a good type for this IA. I have changed it to `reference` because I think it makes more sense.
According to me, users will be searching more for `Django model reference` than `Django model commands` or `Django model code snippets`. Let me know what you think.

**Comment by prasadram** [comment]
Hi @bill,
Thanks for inviting me , and I am interested in python or Perl any one will
be ok for me.

**Comment by edgesince84** [comment]
sounds great @prasadram! 👍

**Comment by edgesince84** [comment]
hey @prasadram did you join our forum yet?  Would love to see you help out with Python or Perl!

**Comment by prasadram** [comment]
hi bill,

just now i have joined  in the new forum <https://forum.duckduckhack.com/>
and sorry for late, please let me know how can i contribute ?

Thanks and Regards,
Ram Prasad.

Thanks and Regards,
Ram Prasad.

**Comment by tagawa** [comment]
Hi @prasadram. Thanks for joining the forum. We're concentrating on improving Instant Answers for five langauges: CSS, JavaScript, Perl, Python, Swift.

You can see the discussions for all five languages here: https://forum.duckduckhack.com/c/programming

I recommend choosing the one you're most familiar with. Then go to the "Brainstorming" topic for discussion of ideas, or the "Overview" topic for actual things to work on. If you're still not sure after that, then just leaving a "How can I help?" comment in the "Overview" topic would be great. Thanks again!
