### ISSUE TITLE
Erlang Cheat Sheet: Add f/1 to shell commands

### ISSUE THREAD

**Issue by sebastiw** [duckduckgo/zeroclickinfo-goodies#2942]
I think a good addition is the following shell command (which IMO is more usable than f/0):

- f(V) forget variable binding <V> 

------
IA Page:  http://duck.co/ia/view/erlang_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Hey @sebastiw,

Thanks for the feedback - really appreciated! 😃 
Sure, feel free to submit a PR and I'll take a look.
