### ISSUE TITLE
Perl Cheat Sheet: Fix shift() syntax

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#2945]
A Reddit user gave us feeback on the perl cheat sheet here: https://www.reddit.com/r/perl/comments/4gr3si/help_improve_duckduckgos_perlrelated_searches/d2kw2vl

>    One minor fix to the cheat sheet: ($a, $b) = shift(@ARGV); is misleading, since shift() only returns one value.

------
IA Page:  http://duck.co/ia/view/perl_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pratik-nagelia

**Comment by hchienjo** [comment]
I am interested in fixing this.

**Comment by tagawa** [comment]
Thank you @hchienjo. Feel free to ask for help if you need any support.

**Comment by hchienjo** [comment]
I had already submitted a [pull request](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2972) a couple of days ago.

**Comment by mintsoft** [comment]
Fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2972

**Comment by tagawa** [comment]
Sorry @hchienjo, I missed that. Thanks very much for fixing this.

**Comment by hchienjo** [comment]
You're welcome.
