### ISSUE TITLE
R Cheat Sheet: 

### ISSUE THREAD

**Issue by cosi1** [duckduckgo/zeroclickinfo-goodies#2947]
Small remark: `<<-` isn't actually a global assignment operator. What it does is assign a value to a variable *in the parent environment* (one level up). Usually it's the global environment, but not always.   

------
IA Page:  http://duck.co/ia/view/r_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @laurenancona

**Comment by laurenancona** [comment]
[Hadley agrees](http://adv-r.had.co.nz/Environments.html).
Thanks @cosi1

**Comment by laurenancona** [comment]
PR forthcoming
