### ISSUE TITLE
Conversions: including degree symbol in query returns no results

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#2950]
A DDG user reported that including the "°" symbol in the query will not trigger the conversions IA.

example: "90°C in f" does not work, but "90c in f" does.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by GuiltyDolphin** [comment]
@duckduckgo/duckduckhack-contributors This should be as simple as adding `°c` to the aliases for `celsius`, anyone interested?

**Comment by xaviervalarino** [comment]
I am not really familiar with with Perl. Is it this line?

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm#L75
```perl
    # hack support for "degrees" prefix on temperatures
    $_ =~ s/ degree[s]? (celsius|fahrenheit|rankine)/ $1/;
```

**Comment by GuiltyDolphin** [comment]
@xaviervalarino There's a separate file, [`ratios.yaml`](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/ratios.yml#L988) which contains the aliases - you'll want to add it there.

**Comment by xaviervalarino** [comment]
Thanks @GuiltyDolphin. I'll make a PR for this
