### ISSUE TITLE
Conversions: show full answer when converting megabytes

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#2951]
A DuckDuckGo user sent in feedback regarding the conversions IA.  Searching for an example -- "100 megabytes in bytes" only returns "1 \* 108 bytes" and not the desired answer:  "104857600."  

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
I think certain `physical quantities` need to be highlighted with a preference for integers; especially the `information` type

**Comment by mintsoft** [comment]
Solved in #3910
