### ISSUE TITLE
German Phrases Cheat Sheet: One small mistranslation/One small addition

### ISSUE THREAD

**Issue by lisabscheibner** [duckduckgo/zeroclickinfo-goodies#2960]
Change to "Going out for dinner" section:
- Appetizer
- Vorspeise

Suggested addition to "Basics" section:
- Goodbye!
- Tschüss!

   

------
IA Page:  http://duck.co/ia/view/german_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @AdamSC1-ddg

**Comment by tagawa** [comment]
Hi @platschi. Thank you for those commits. Would you be able to send them as a pull request so it can be merged into our code? If you go this repository's front page you should see a green "Send pull request" button at the top: https://github.com/duckduckgo/zeroclickinfo-goodies

**Comment by nalinbhardwaj** [comment]
@platschi hasn't responded in a month. Should I make a PR?

**Comment by zekiel** [comment]
@nalinbhardwaj do you think we should get another pass on the language? we could do a "final review" callout in the community channels. Otherwise, ya, that'd be great!

**Comment by platschi** [comment]
@tagawa @zekiel @nalinbhardwaj  sorry for late reply. pull request had been done already long ago: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3059

**Comment by tagawa** [comment]
Thanks @platschi - I've just added a comment to that pull request.
