### ISSUE TITLE
Graph Operations Cheat Sheet: Maintainer request

### ISSUE THREAD

**Issue by vikashvverma** [duckduckgo/zeroclickinfo-goodies#2964]
I would like to become the maintainer for this!

Thanks!

IA Page:  http://duck.co/ia/view/graph_operations_cheat_sheet

**Comment by tagawa** [comment]
Hi @vikashvverma. Thank you for offering! I've just added you as maintainer on the IA page. Just to let you know that there are no other issues open for this IA at the moment.
