### ISSUE TITLE
Various Cheat Sheets: Update aliases

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#2967]
@duckduckgo/duckduckhack-contributors Some very low-hanging-fruit here; we need some aliases updated for a pending PR (#2777):

- [x] https://duck.co/ia/view/dothraki_cheat_sheet (@varundey) - remove `dothraki language`
- [ ] https://duck.co/ia/view/finnish_cheat_sheet (@riqpe) - remove `english to finnish` and `basic finnish`
- [x] https://duck.co/ia/view/greek_cheat_sheet (@synbit) - remove `english to greek` and `basic greek`
- [ ] https://duck.co/ia/view/high_valyrian_cheat_sheet (@siddhanjay) - remove `game of thrones language` and `valyrian language`
- [ ] https://duck.co/ia/view/kannada_cheat_sheet (@pnpninja) - remove `basic kannada`
- [x] https://duck.co/ia/view/minionese_cheat_sheet (@swapagarwal) - remove `minion language`
- [ ] https://duck.co/ia/view/spanish_cheat_sheet (@rasikapohankar)  - remove `basic spanish`
- [x] https://duck.co/ia/view/telugu_cheat_sheet (@roxxup) - remove `english to telugu` and `basic telugu`

**Comment by synbit** [comment]
@GuiltyDolphin this will leave ```aliases``` empty (if I amend according to this: https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/126863668#L551).

Is that going to be a problem? Should I delete ```aliases``` altogether? Sorry if I misunderstood...

**Comment by GuiltyDolphin** [comment]
@synbit It is fine to have no aliases! Just make sure to remove the field if the array is empty.

**Comment by swapagarwal** [comment]
@GuiltyDolphin `minion language` is an alias for `minionese` and both should trigger the cheatsheet.

**Comment by GuiltyDolphin** [comment]
@swapagarwal If you update the alias to `minion` then it will still trigger after changes are implemented.

**Comment by swapagarwal** [comment]
Cool, will `minions` be handled automatically too?

**Comment by GuiltyDolphin** [comment]
@swapagarwal No - I'm not sure why you'd want it to though?

**Comment by swapagarwal** [comment]
like `minion phrases` and `minions phrases` both should trigger the cheatsheet

**Comment by GuiltyDolphin** [comment]
@swapagarwal Then you'd want to add `minions` to the aliases.

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin If still open, can I pick finnish_cheat_sheet , spanish_cheat_sheet
