### ISSUE TITLE
Git Cheat Sheet: 

### ISSUE THREAD

**Issue by chrissherlock** [duckduckgo/zeroclickinfo-goodies#2970]
Under "Redo Commits" it shows as:

> Undoes all commits after \[commit\], preserving changes locally

Note the backslashes before the square brackets. Can't understand why they are there though...

------
IA Page:  http://duck.co/ia/view/git_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zekiel

**Comment by zekiel** [comment]
fixed via #2971
