### ISSUE TITLE
Calculator: Square Root symbol

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-goodies#2988]
Maybe support `√` symbol[?](http://unicode-table.com/en/221A/)
(`U+221A` / `E2 88 9A`)

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@fzzr- :+1: Sure; Dev version: 

![screenshot-2016-05-01-12 59 24_303_50](https://cloud.githubusercontent.com/assets/8598426/14941688/974d9e5c-0f9c-11e6-913d-d184cb8aa758.png)

![screenshot-2016-05-01-13 02 00_949_233](https://cloud.githubusercontent.com/assets/8598426/14941695/f3ffd28c-0f9c-11e6-93af-57d9a6c7cb49.png)

**Comment by fzzr-** [comment]
Thx! Okay :)

**Comment by zekiel** [comment]
@fzzr-  @GuiltyDolphin  what action is required to move forward with this?

**Comment by mintsoft** [comment]
@zekiel The calculator rewrite needs merging :)

**Comment by GuiltyDolphin** [comment]
@zekiel It's been since December ^.^ - I've also got the interactive version in-progress, but that *also* relies on the Calculator.

**Comment by mintsoft** [comment]
@GuiltyDolphin Once it's been live for a bit I'll be comfortable merging small changes in

**Comment by zekiel** [comment]
Thx all. Gonna try to get some help w/ these internally so there are extra eyes on it and it doesn't get lost in the github fray.
