### ISSUE TITLE
Conversions: Plural for feet shows as "foots" 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-goodies#3004]
reported on twitter for "acre square feet" e.g. https://twitter.com/ralphscenic/status/728388908824690688 
also impacting others like: https://duckduckgo.com/?q=hectare+square+feet&ia=answer 

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
ffs dunno how I missed that!
