### ISSUE TITLE
Conversions: No teaspoon/tablespoon support

### ISSUE THREAD

**Issue by Zacqary** [duckduckgo/zeroclickinfo-goodies#3008]
Queries like `teaspoons in a tablespoon` or `6 tsp in tbsp` return no Instant Answer.
 
I'm not sure where in `Conversions.pm` the possible units of measurement are defined, except for temperatures in `sub convert_temperatures`. Would be glad to help implement this if someone could help me follow the breadcrumbs.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@Zacqary Sounds good; they're defined here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/ratios.yml
