### ISSUE TITLE
Markdown Cheat Sheet: Update Perl Module

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3010]
Currently the metadata states that `DDG::Goodie::MarkdownCheatSheet` is the `perl_module`, we should change this to `DDG::Goodie::CheatSheets`.

/cc @moollaza @zekiel 

------
IA Page:  http://duck.co/ia/view/markdown_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @marianosimone

**Comment by tagawa** [comment]
Fixed: https://duck.co/ia/view/markdown_cheat_sheet
