### ISSUE TITLE
Cheat Sheets (Controller): Verify Metadata

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#3016]
Could the cheatsheet test check that there is an IA page using the ID from the cheatsheet json file?

------
IA Page:  http://duck.co/ia/view/cheat_sheets 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

**Comment by zachthompson** [comment]
Yeah, I actually thought it *might* be there already.  We probably want a way to verify arbitrary metadata fields from anywhere.  For example:
```Perl
verify_metadata({
    id => $id,
    name => $name,
    perl_module => $pm
});
or
verify_metadata({ perl_module => $pm, repo => $repo});
```
We can always do this by just getting all of the metadata and DIY.  However, there's no reason to write the logic repeatedly, also some subtleties, e.g. id or module is required and module returns an array.

@GuiltyDolphin you interested?

**Comment by GuiltyDolphin** [comment]
@zachthompson @jdorweiler Sure, should be pretty easy - just make sure an IA page exists via DDG::Meta::Data.

**Comment by GuiltyDolphin** [comment]
@zachthompson @jdorweiler Oh boy... The failures!

Looks like people don't like to keep descriptions consistent between metadata and JSON!

**Comment by jdorweiler** [comment]
I'm mostly worried about things like this
https://beta.duckduckgo.com/?q=cash+cheat+sheet&ia=cheatsheetscontroller

**Comment by jdorweiler** [comment]
Is there a test we could do to catch these? I've found and fixed a live one last week with the same "cheatsheet controller" tab name.

**Comment by GuiltyDolphin** [comment]
@jdorweiler What's the cause? It looks like it is using 'name' as 'CheatSheets (Controller)'...

We can easily check for the presence of an IA page, but I'm not sure what's causing that?

**Comment by GuiltyDolphin** [comment]
@zachthompson @jdorweiler What do you think? https://github.com/duckduckgo/zeroclickinfo-goodies/tree/gd/cheat-sheets-use-meta

There's no clashes with the existing infrastructure as we override any JSON definitions with metadata... So we could just 'phase' the JSON out without issue (more focus on correct metadata).

**Comment by jdorweiler** [comment]
I think it's the case where the id in the cheatsheet json doesn't match an existing IA page.

**Comment by GuiltyDolphin** [comment]
@jdorweiler Yeah, you're right: the tests picked up a few, and I tried a couple - the name was wrong (for example, `backbonejs cheat sheet`).
