### ISSUE TITLE
CheatSheets: Use metadata in place of some fields

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3023]
@zachthompson I mentioned this briefly on #3016, but in summary:
- We have several fields on cheat sheets (such as description, name, source etc.) that are already in the metadata.
- Preferring metadata over the JSON fields is trivial, and does not cause conflicts; it deprecates the use of the fields in the JSON.
- We could potentially greatly simplify the tests (depending on whether or not we want to check the contents of the fields - I think there might be too many update issues to keep any metadata specific tests).

See https://github.com/duckduckgo/zeroclickinfo-goodies/tree/gd/cheat-sheets-use-meta for a working version.

@zachthompson @jdorweiler @moollaza @mintsoft Any thoughts? This would mean we don't have to have any PRs for 'updated description' or 'updated source' etc. and means we should have more consistent information with what is displayed on the metadata page.

IA Page: https://duck.co/ia/view/cheat_sheets
Maintainer: @zachthompson

**Comment by GuiltyDolphin** [comment]
Ping @zachthompson @jdorweiler @moollaza @mintsoft What do you guys think? It'd definitely help with reducing the number of minor edit PRs we get, and we can create an issue for people to ensure their IA pages are up-to-date and remove the redundant metadata from the JSON.

As a reminder, this would *not* conflict with the existing JSON, it would instead *supersede* it and only the fields directly from the metadata would be used where appropriate.

@zachthompson If you agree, I'll make a PR with that branch.

**Comment by GuiltyDolphin** [comment]
@zachthompson Ping - I think catching this earlier than later is probably best if we wish to get people to keep the metadata up-to-date.

Any thoughts on this?

**Comment by moollaza** [comment]
@zachthompson I like the idea of using the Metadata for the Description and Source, I would opt to grab the IA Page Metadata on the Frontend though seeing as we already make it available. That way we can simplify the Perl a little.

**Comment by GuiltyDolphin** [comment]
@zachthompson Any thoughts?

@moollaza have you come up with a solution to the front-end issue (cannot access metadata), or do you think the back-end will be fine?

**Comment by GuiltyDolphin** [comment]
Ping @zachthompson @moollaza any thoughts? This would be fairly trivial to implement and also easy to remove if things go wrong.

cc @duckduckgo/community-leaders any other thoughts on use of metadata in general?
