### ISSUE TITLE
Backbone.js Cheat Sheet: Update ID

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3024]
1. Update the ID in the JSON to `backbone_js_cheat_sheet`.
2. Remove the `backbone js` alias.
3. Add `backbonejs` as an alias.

------
IA Page:  http://duck.co/ia/view/backbone_js_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by vikashvverma** [comment]
@GuiltyDolphin The file name is `backbonejs.json` so the id should be `backbonejs_cheat_sheet` not `backbone_js_cheat_sheet`.

**Comment by GuiltyDolphin** [comment]
@vikashvverma Then update the file name too.
