### ISSUE TITLE
Kotlin Cheat Sheet: Update ID on IA Page

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3025]
@zekiel @moollaza @zachthompson We should update the IA Page to `kotlin_cheat_sheet`.

------
IA Page:  https://duck.co/ia/view/kotlin_cheat_sheet
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @max-vogler

**Comment by max-vogler** [comment]
👍 If I see this correctly, there's no way for me as maintainer to update it?

**Comment by GuiltyDolphin** [comment]
@max-vogler Unfortunately not, but thanks for responding so quickly!

**Comment by moollaza** [comment]
done 👍 

https://duck.co/ia/view/kotlin_cheat_sheet
