### ISSUE TITLE
Facebook React Cheat Sheet: Update IA Page ID to reactjs_cheat_sheet

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3026]
@zekiel @moollaza @zachthompson We should update the IA Page to `reactjs_cheat_sheet`.

------
IA Page:  https://duck.co/ia/view/reactjs_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by moollaza** [comment]
Done 👍 

https://duck.co/ia/view/reactjs_cheat_sheet
