### ISSUE TITLE
UnderscoreJS Cheat Sheet: Dev stage needs bumping up

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3027]
@zekiel @moollaza @zachthompson This is currently only in planning? I think it needs bumping up (and we should provide planning IAs in the metadata); the tests are unable to fetch the metadata for this cheat sheet even though the ID is correct.

IA Page: https://duck.co/ia/view/underscore_js_cheat_sheet
Maintainer: @pecey

**Comment by zachthompson** [comment]
Yeah, I agree.  We've discussed this a bit.  You could bump it up to dev to get it in the feed for now.

**Comment by GuiltyDolphin** [comment]
@zachthompson I'm unable to do that (unless you mean by a PR); any news on Community Platform perms for CLs?

**Comment by zachthompson** [comment]
Argh, that's a good question.  I have to imagine we have that listed somewhere.  Updated.

**Comment by zachthompson** [comment]
FYI, you can update IAs to which you've contributed but not all atm.  We have a task to look into it.

**Comment by GuiltyDolphin** [comment]
@zachthompson Yeah - though I believe it has to go through a review process, and you can't update *everything*?
