### ISSUE TITLE
ES6/Babel in Frontend Code?

### ISSUE THREAD

**Issue by Zacqary** [duckduckgo/zeroclickinfo-goodies#3028]
I'm wondering if there are any plans to enable ES6 syntax (at the very least) or modules (at best) in frontend JS for instant answers? I'm looking to contribute more, but I've grown pretty used to stuff like destructuring and `import`-able code.

Not sure what specific challenges the wider DDG codebase has to overcome in order to build with Babel (which is basically required if you want ES6 to work in older browsers), but I'm interested to know. Sorry if this has been brought up before.

**Comment by kirkins** [comment]
You could compile ES6 to standard javascript.

We can probably close this one.

**Comment by pjhampton** [comment]
No, there is no discussions like this at the moment. However, it's inevitable that we're going to have to use something like http://browserify.org/ for the v2 calculator when we move away from regular expressions. I'll close this for now
