### ISSUE TITLE
SQL Cheat Sheet: the 'FOREIGN KEY' statement appear 2 times

### ISSUE THREAD

**Issue by LudoBike** [duckduckgo/zeroclickinfo-goodies#3036]
Hi, 

I was read sql cheat sheet when I note that the 'FOREIGN KEY' appear 2 times. For information I use firefox 49.0.1 on updated Archlinux.

------
IA Page:  http://duck.co/ia/view/sql_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jophab

**Comment by jophab** [comment]
@LudoBike Corrected :+1:
