### ISSUE TITLE
Tips: Ensure a currency is always specified

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3065]
Currently the Tips IA can handle queries such as `25% of 500`, which it shouldn't.

We should make sure that a currency is always present so we are only doing tip calculations, not arbitrary percentages. If the word 'tip' is present we can probably assume this is what they want.

---

IA Page:  http://duck.co/ia/view/tips 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattlehning

**Comment by mintsoft** [comment]
@GuiltyDolphin Would these queries be handled by another IA?

**Comment by GuiltyDolphin** [comment]
@mintsoft Possibly - it would open it up for another IA at least; the queries aren't relevant to this IA and I would consider it *major* over triggering.

**Comment by mintsoft** [comment]
Hmm; I see where you're coming from, however if a user searches for "25% of 500" they get the answer; with this removed they wouldn't?

**Comment by GuiltyDolphin** [comment]
@mintsoft No - but I think we should open this up to someone else for a new IA; this Goodie is trying to do too much.

**Comment by mintsoft** [comment]
Yeah OK; if the functionality is replaced by another IA then :+1:

**Comment by sach2211** [comment]
Probably, user already knows which currency he is paying in, so not letting him know what he wants to  know might be a bad ux.

**Comment by GuiltyDolphin** [comment]
@sach2211 Ux? I'm referring to cases where there is no currency involved (or tips); such as `25% of 100`. If they say `25% tip of 100` or `25% of $100` it should still trigger.

**Comment by GuiltyDolphin** [comment]
@mintsoft I think this could be handled by https://duck.co/ia/view/percent_of

/cc @puskin94

**Comment by sahildua2305** [comment]
@GuiltyDolphin Is there anyone working on this? If no, I would like to get started with this issue.

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Not yet, we'd be grateful for the contribution!

Would you like to add the functionality to https://duck.co/ia/view/percent_of at the same time?

**Comment by sahildua2305** [comment]
@GuiltyDolphin I would love to. Though I will need some help in getting started with how Perl package are organized for IAs. Any pointers?

**Comment by GuiltyDolphin** [comment]
@sahildua2305 I'll have to put this on hold for the mo' while we sort #3208 - I'll ping you when that's done.

**Comment by GuiltyDolphin** [comment]
@sahildua2305 We should be good to go now :)

**Comment by shubhamkr1** [comment]
does this require changing the regular expression used in Tips.pm file?

**Comment by mintsoft** [comment]
@shubh1m Yeah but probably in a minor way, taking off the optional flag (`?`) from the capture

**Comment by pjhampton** [comment]
This IA has changed significantly since this issue was created.
