### ISSUE TITLE
Fibonacci: Support assertion queries

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3070]
It'd be great if we could do `is X a fibonacci number?`, `is X in the fibonacci sequence?`.

See #3068 - but in summary there is the `Math::NumSeq::Fibonacci` package that can do this already.

/cc @mintsoft 

------
IA Page:  http://duck.co/ia/view/fibonacci 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by koosha--** [comment]
It's OK to implement this, but, I think we should be wary of performance issues with large numbers.

**Comment by GuiltyDolphin** [comment]
@koosha-- It's seems fine up to approx. `10^22` before I can notice anything - you might want to have a cap though.

**Comment by shellhead** [comment]
Is this (and the associated) issue open to work on? Newbie here looking to help out, looks like this would be a good one to get my feet wet.

**Comment by mintsoft** [comment]
@shellhead Indeed it is! We'd be delighted if you take this up. We'd ask you to open a PR as soon you start work on it so we "know" that you're doing it and we can avoid repeated work.

**Comment by edgesince84** [comment]
@shellhead sounds great, Michael!  Let me know if you need any help

**Comment by GuiltyDolphin** [comment]
Implemented in #3215.
