### ISSUE TITLE
Lubuntu website has changed

### ISSUE THREAD

**Issue by tsimonq2** [duckduckgo/zeroclickinfo-goodies#3085]
The Lubuntu website has changed from Lubuntu.net to Lubuntu.me and the search result needs to be adjusted for that.

**Comment by GuiltyDolphin** [comment]
Hey @tsimonq2 - could you include a link to the Instant Answer pages for the Goodies that are affected by this update? There is a `Create Issue` button on the duck.co Instant Answer pages you can use to ensure all the necessary info is filled out!

**Comment by tsimonq2** [comment]
Whoops, it seems it was changed after I updated the Wikipedia page to what it needs to be. All fixed!
