### ISSUE TITLE
Facebook Cheat Sheet: https://www.facebook.com/hieu.nguyentrong.10441?pnref=story#

### ISSUE THREAD

**Issue by appleiphonegodfather** [duckduckgo/zeroclickinfo-goodies#3112]
[@]([url](

- 

- [ ] [url](url)

))   

------
IA Page:  http://duck.co/ia/view/facebook_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @saifakhan

**Comment by GuiltyDolphin** [comment]
@appleiphonegodfather Accident?

**Comment by edgesince84** [comment]
@appleiphonegodfather is there something I can help you with?  I see you've opened two issues, but both seems to be unclear.
