### ISSUE TITLE
Intel 8085 Cheat Sheet: No Link

### ISSUE THREAD

**Issue by mRse7enNIT** [duckduckgo/zeroclickinfo-goodies#3115]
Hello, When I am clicking the IITK website it is redirecting to a page which is giving 404. Please fix it

------
IA Page:  http://duck.co/ia/view/intel_8085_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jophab

**Comment by tagawa** [comment]
@mRse7enNIT Thanks for reporting this.

@jophab It looks like the source PDF has been taken down. Maybe we could link to this source instead: http://scanftree.com/microprocessor/Instruction-Set-In-8085
