### ISSUE TITLE
Refactor tests for Goodies using Roles

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3121]
### Abstract

Goodies should only be testing their own specific functionality and triggering, they should not be testing the Roles' parsing capabilities.

The Roles should fully cover (with tests) what they can, and cannot, parse; failure to parse (for example) a date on production should be considered an 'issue' with the Role and brought up as one, specifics can be uncovered there.

The Roles need to be flexible, able to change _how_ they handle queries and cause backwards incompatible changes _without_ breaking Goodies in the process, something that is infeasible with the current state of tests.
### What needs to be done

Tests should be updated in the following ways:

Any dates should be updated to use ISO8601 format (`YYYY-MM-DD` and `YYYY-MM-DDTHH:MM:SSZ`). Tests that are clearly only testing the date formats should be removed.

Numbers should only use Perl format, i.e, no commas, use a period for the decimal place.

Once you're done, the following should be true about the tests:
1. The tests _only_ test the functionality of the Goodie, they don't test locale-specific or ambiguous dates or numbers.
2. Dates within the test queries use ISO8601 format, numbers within the test queries use simple Perl format.
3. There are no redundant tests (redundant if it doesn't test any functionality/cases that aren't covered by another test).
4. Custom parsing done by the Instant Answer that is _separate_ from parsing done by the Role should still be tested! E.g., the position of a date within the string should be tested, but not the format of the date.
### How To Get Started

_Stolen from Zaahir_
1. Find an Instant Answer in the list below that doesn't have a name beside it.
2. Leave a comment below that indicates which IA(s) you'd like to tackle. One of the community leaders or staff will put your name beside the IA in the list below indicating that it's been claimed.
3. Get coding and make a Pull Request.
   Be sure to include the link to the related Instant Answer Page in your PR Comment. This is **required** for us to be able to deploy your PR to Beta and ultimately merge it.
   
   Also, make sure you mention this issue in your PR. That way we can keep track of all the PR's in here as well. Something like "Updates X Goodie Re: #3121" is good.

---

Here's the list of IA's that need to be converted. If you'd like to work on one, please leave a comment letting everyone know, so we can avoid and duplicated efforts.
- [ ] Calculator - @GuiltyDolphin
- [ ] CalendarConversion - @GuiltyDolphin (#3187)
- [ ] CalendarToday
- [ ] ChineseZodiac
- [ ] CoffeeToWaterRatio
- [ ] Combination
- [ ] Conversions - @mintsoft 
- [ ] DateMath - @GuiltyDolphin
- [ ] DayOfWeek
- [ ] DaysBetween
- [ ] FenViewer
- [ ] NameDays
- [ ] SigFigs
- [ ] Stardate
- [ ] SunInfo
- [ ] Tips
- [ ] Uptime
- [ ] WeekdaysBetween
- [ ] Week
- [ ] WorkdaysBetween
- [ ] Zodiac

**Comment by mintsoft** [comment]
@GuiltyDolphin It's probably worth mentioning that if the IAs aren't purely using the Dates Role (i.e. they've got their own handling as well) then tests exercising it's custom handling shouldn't be deleted!

**Comment by GuiltyDolphin** [comment]
@mintsoft Yeah - sorry; I'll update the description to clarify. I was including that in the 'Goodie functionality' section.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
