### ISSUE TITLE
New Role for list parsing

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3135]
@mintsoft @moollaza We have quite a few Goodies that parse lists of items, I think having a Role that can deal with parsing various formats of lists (`[1, 2, 3]`, `1 and 2, and 3`, `1 2 3` etc.) as well as giving a way to format the lists in a standard way would be quite useful.

This Role would also be quite useful to be *used* in some of the other roles; allowing easy parsing of lists of dates or numbers.

@duckduckgo/community-leaders What do you think? If you guys agree I'll open a PR for this - I've been playing around with list parsing a bit with [shuffle](https://duck.co/ia/view/shuffle) so I've got some ideas for which libraries would be useful.

**Comment by mintsoft** [comment]
Sounds like a plan! Nice and simple too :)

**Comment by GuiltyDolphin** [comment]
@mintsoft I was thinking of namespacing it as `DDG::GoodieRole::Parse::List` so we could group miscellaneous (mainly) parsing roles together, do you agree?
