### ISSUE TITLE
Split Role tests up

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3136]
@moollaza @mintsoft @zachthompson Currently we've got all the role tests in `t/00-roles.t`, but in general the tests for each Role are pretty huge; I think it might be beneficial to split the tests into `t/00-roles/00-dates.t`, `t/00-roles/01-numberstyle.t` etc., (or similar; split `00-roles.t` into a directory).

Thoughts? I think this might make it a _bit_ easier to work on the roles.

**Comment by mintsoft** [comment]
@GuiltyDolphin Completely agree; although I think we're best to do with when there are no Role PR's in progress

**Comment by GuiltyDolphin** [comment]
@mintsoft Meh, shouldn't be too much of an issue - each one can just pull out its own tests (overwriting master - i.e., automatic conflict resolution ^.^).

**Comment by mintsoft** [comment]
Yeah true!

**Comment by moollaza** [comment]
I'm always a fan of sub-directories for organizing things 👍

**Comment by GuiltyDolphin** [comment]
@mintsoft @moollaza What do you think of [this structure](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/2477d0090a9b4de9e60e94e7b8cf05b36d2b015a/t/00-roles/Parse/List.t)?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
