### ISSUE TITLE
Sort: Update to use NumberStyle Role

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3137]
Currently Sort is doing its own number parsing - we should use the NumberStyle Role instead (and update the tests re #3121).

---

IA Page:  http://duck.co/ia/view/sort 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
