### ISSUE TITLE
DuckDuckGo Shortcuts: Key commands difficult to read when expressing ORs

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/zeroclickinfo-goodies#3141]
Broken syntax making keyboard shortcuts not show properly. Please see http://docs.duckduckhack.com/frontend-reference/cheat-sheet-reference.html#cheat-sheet-json-reference for guidance or feel free to ask! 

![screen shot 2016-05-23 at 2 03 34 pm](https://cloud.githubusercontent.com/assets/1846953/15479663/3cdea9b6-20ef-11e6-86b2-d006bf442f98.png)

------
IA Page:  http://duck.co/ia/view/duckduckgo_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Qeole

**Comment by Qeole** [comment]
I have not worked on this in a while (it was not even in JSON at that time), but I will fix it.

I agree that it does not show properly, but I fail to see where the syntax is broken? I feel like [the JSON file for this cheat sheet](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/duckduckgo.json) does stick to [the reference](http://docs.duckduckhack.com/frontend-reference/cheat-sheet-reference.html#alternative-keys-eg-pressing-either-a-or-b), in particular to the model provided for alternative keys, e.g. `[Ctrl] ( [L] / [P] )`. Or did I miss something? @zekiel, could you please provide some hint?

**Comment by zekiel** [comment]
@Qeole Sorry for the lack of clarity on this -- I think my first reaction was that it was broken syntax but it's really just that the parentheses are making it difficult to read. We should think about how to improve that and update the [reference](http://docs.duckduckhack.com/frontend-reference/cheat-sheet-reference.html#alternative-keys-eg-pressing-either-a-or-b) 

nothing needed here unless you'd like to experiment! I'll update the title.

**Comment by Qeole** [comment]
@zekiel I may experiment when I got some spare time, which I reckon is not for anytime soon :-) so do not wait for me. I remain available if some nice idea emerges and we need to fix the cheat sheet or the reference.
