### ISSUE TITLE
Constants: possible issue with "electron charge" answer

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3142]
A user on DuckDuckGo reported a potential issue with the constant for "electron charge."  They stated that the IA should have a minus.  Is this an incorrect answer?

---

IA Page:  http://duck.co/ia/view/constants 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hemanth

**Comment by mintsoft** [comment]
@edgesince84 Yes; the charge on an electron is -1.6 E-19C; the charge on a proton is +1.6E-19C

**Comment by GuiltyDolphin** [comment]
@mintsoft How about `magnitude of charge on an electron`?

**Comment by mintsoft** [comment]
@GuiltyDolphin Sounds good

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
