### ISSUE TITLE
Sort: Shouldn't trigger on single numbers

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3144]
We shouldn't trigger if there is only one input number, eg., https://duckduckgo.com/?q=sort+1&ia=answer

------
IA Page:  http://duck.co/ia/view/sort 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by tagawa** [comment]
Looks like this was fixed - thank you 🍰
