### ISSUE TITLE
Sort: Displaying 'inf' in place of large numbers

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3145]
For example https://duckduckgo.com/?q=sort+1e1000%2C1e200&ia=answer

---

IA Page:  http://duck.co/ia/view/sort 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin PR #3157 should fix this issue. The new changeset shows the output result number format same as input format. For example, (.5) is shown as (.5) in output instead of (0.5)

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
