### ISSUE TITLE
SHA 3: end of string gets cut off

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-goodies#3147]
![screenshot-staging duckduckgo com 2016-05-25 19-50-13](https://cloud.githubusercontent.com/assets/3652195/15553576/f28dcc84-22bf-11e6-87fd-6a82ff1be5d3.png)
   

------
IA Page:  http://duck.co/ia/view/sha3 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rafacas

**Comment by mintsoft** [comment]
@MariagraziaAlastra I've just switched this to the text template (not sure if it's live yet, but on beta: https://beta.duckduckgo.com/?q=sha3+my+awesome+string&ia=answer ) and it still seems to be doing it. I think this is probably a broader problem with the template itself if the `title` is long.

**Comment by MariagraziaAlastra** [comment]
@mintsoft Yup, it's live and yeah, if you remove overflow:hidden; from .c-base__title in the dev tools, it shows the full string (quite long indeed):
![screenshot-duckduckgo com 2016-05-26 16-19-22](https://cloud.githubusercontent.com/assets/3652195/15577691/d6018c1a-235d-11e6-8d29-a596a473ea91.png)

Adding word-break: break-all; instead keeps the string within the boundaries by breaking it into multiple lines:
![screenshot-duckduckgo com 2016-05-26 16-23-34](https://cloud.githubusercontent.com/assets/3652195/15577782/3bb1e186-235e-11e6-9d8e-1420cfeab49d.png)

**Comment by mintsoft** [comment]
@MariagraziaAlastra Hmm I think `word-break: break-all` should probably put onto the text template then? I can't think of a situation in which we'd want to hide that output?

**Comment by moollaza** [comment]
`break-all` would break long words in the middle, instead of forcing them to wrap. Seeing as the string has no non-alpha chars there's no good place to break it and we also don't mind wrapping it anywhere in the string. For any other kind of string we would though...

**Comment by MariagraziaAlastra** [comment]
@mintsoft It would be better to add a custom CSS file for this IA specifically.

**Comment by mintsoft** [comment]
@moollaza @MariagraziaAlastra Makes sense; I'll sort that in a min
