### ISSUE TITLE
R Cheat Sheet: unrelated front-end files listed on IA page

### ISSUE THREAD

**Issue by laurenancona** [duckduckgo/zeroclickinfo-goodies#3148]
I think the only file that should appear under **Front End Files** should be `r.json`:
<img width="1010" alt="screen shot 2016-05-25 at 6 53 01 pm" src="https://cloud.githubusercontent.com/assets/2152151/15558717/3908c882-22aa-11e6-9330-3beec13b28cb.png">
   
Haven't seen this happening in any other cheat sheet goodies.

------
IA Page:  http://duck.co/ia/view/r_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @laurenancona

**Comment by mintsoft** [comment]
@alohaas Not sure if this your field of expertise?

**Comment by alohaas** [comment]
@mintsoft @laurenancona very strange! Thank you for alerting us to this issue.
It seems like a front-end issue with our IA Pages on the [Community Platform](https://github.com/duckduckgo/community-platform). I'm going to close this issue and open a new issue in that repo.

**Comment by alohaas** [comment]
Found a similar issue here - https://github.com/duckduckgo/community-platform/issues/1248
