### ISSUE TITLE
Calculator: Unable to evaluate some expressions

### ISSUE THREAD

**Issue by germangb** [duckduckgo/zeroclickinfo-goodies#3150]
Some expressions are not being triggered

`cos(pi) + sin(pi)` works
`cos(pi/2) + sin(pi)` doesn't work
`cos(pi)/2 + sin(pi)` doesn't work

The same thing happens with other functions

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by mintsoft** [comment]
Already fixed in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927

**Comment by mintsoft** [comment]
@zekiel Another case of an already solved problem!

**Comment by germangb** [comment]
Okey sorry for the duplicate. I'll make sure to do the research next time

**Comment by GuiltyDolphin** [comment]
@germangb Nono, it's a valid issue - we've got a PR that reworks a bunch of the calculator and happens to fix this; when that's merged this will be resolved :+1:

**Comment by moollaza** [comment]
This is solved in the new Interactive calculator 👍
