### ISSUE TITLE
Unicode: Unicode codepoints in 7.0 are not available

### ISSUE THREAD

**Issue by ssaavedra** [duckduckgo/zeroclickinfo-goodies#3162]
Unicode codepoints introduced in version 7.0 of Unicode are not detected by the unicode IA currently. Such points can be e.g., U+1F642 (🙂), but the search on http://ddg.gg/U+1F642 does not trigger the unicode instant answer.

---

IA Page:  http://duck.co/ia/view/unicode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cosimo

**Comment by edgesince84** [comment]
@cosimo will you be able to take a look at this?  thanks for reporting it @ssaavedra

**Comment by cosimo** [comment]
Yes, will fix it.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
