### ISSUE TITLE
Random Number: Prevent triggering on just 'random'

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3168]
See ['random'](https://duckduckgo.com/?q=random&ia=answer) - we shouldn't trigger on such a generic query.

---

IA Page:  http://duck.co/ia/view/random_number 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jonk1993

**Comment by jmwoliver** [comment]
@GuiltyDolphin I can take this one and https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3169 if you would like. They are pretty much identical to the one you just helped me finish.

**Comment by GuiltyDolphin** [comment]
@jmwoliver Go for it - ping me when you're ready.

**Comment by jmwoliver** [comment]
@GuiltyDolphin It should be good to go.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
