### ISSUE TITLE
Random Number: Don't trigger if lower and upper bounds are the same

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3169]
For example ['random 7 7'](https://duckduckgo.com/?q=random+7+7&ia=answer) and ['random 1'](https://duckduckgo.com/?q=random+1&ia=answer). We cannot provide a 'random' number when the bounds are the same.

---

IA Page:  http://duck.co/ia/view/random_number 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jonk1993

**Comment by jmwoliver** [comment]
@GuiltyDolphin I can take this one and https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3168 if you would like. They are pretty much identical to the one you just helped me finish.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
