### ISSUE TITLE
i3 Window Manager Cheat Sheet: trigger for more queries and refactor json data

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-goodies#3175]
The i3 window manager cheatsheet should be triggered for more queries like: 

> i3 wm cheatsheet, i3 window manager cheatsheet, i3wm cheatsheet

Description of the cheatsheet and other basic json data needs to be refactored. For example, `Mod1 <number>` should follow docs guidelines.

---

IA Page:  http://duck.co/ia/view/i3_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @goromlagche

Dev to notify: @moollaza , @GuiltyDolphin , @zekiel , @edgesince84

**Comment by edgesince84** [comment]
Thanks, Naveen - I agree.  Those should trigger this cheat sheet, for sure.

**Comment by pjhampton** [comment]
Hey  all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
