### ISSUE TITLE
PHP Cheat Sheet: Need improvement

### ISSUE THREAD

**Issue by shahbaz17** [duckduckgo/zeroclickinfo-goodies#3183]
There is lot of functions in this cheat sheet which nobody uses in day to day life. I guess cheat sheet are meant to be useful for quick summarizing the concept. There is no MySQL functions which is used in daily basis. And why we need Regular expression in this cheat sheet.

Need improvement

------
IA Page:  http://duck.co/ia/view/php_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rathoreanirudh

**Comment by alohaas** [comment]
@shahbaz17 are there other kinds of PHP functions besides MYSQL that you use regularly?

**Comment by sahildua2305** [comment]
Also, I feel that many functions under sections PHP array functions and string functions aren't in proper order. That means some of the similar functions should be put together to make it a good reference for users. I'll be submitting a PR soon.

**Comment by shubhamrajput** [comment]
Also,regex cheat sheet is already there so we can remove the regex part from the php cheat sheet.

**Comment by sahildua2305** [comment]
Point! @shubhamrajput

**Comment by shahbaz17** [comment]
Hello @alohaas , @sahildua2305 has taken this opportunity to make this cheat-sheet more useful. His latest commit has all what is needed in regular day to day php functions. Also there is always a room for improvement. And Thanks @himanshu53 , @sahildua2305 and @shubhamrajput for your quick reaction.

**Comment by sahildua2305** [comment]
@shahbaz17 My pull request isn't yet merged though.

**Comment by shahbaz17** [comment]
Hello @sahildua2305 , I have seen the PR and gone through the conversation. Maintainer input is required and we follow a set of rules . Just be patient , you have done a great job. Your PR will get merged once maintainer reply or after 14 days. Keep contributing :+1:

**Comment by sahildua2305** [comment]
Thank you :smile:

**Comment by himanshu53** [comment]
Thank you
