### ISSUE TITLE
URL Decode: Fails for character '

### ISSUE THREAD

**Issue by p512** [duckduckgo/zeroclickinfo-goodies#3186]
Decoding `%27` should result in `'` but returns `&#39;` instead.
Example: https://duckduckgo.com/?q=urldecode+%2527test%2527&ia=answer

------
IA Page:  http://duck.co/ia/view/urldecode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@p512 Thanks for raising the issue; sadly we've had to html encode the output in order to protect us from XSS. I agree that is looks crap though; I'm going to have a look around and see if we can use the template system to protect us without requiring this bodgery

**Comment by GuiltyDolphin** [comment]
@moollaza What's the priority for output encoding? It's *really* obvious when you see it, and yes, as @mintsoft says, it just looks horrible.

I've not heard many complaints - but I do wonder what newcomers must think when the output shows these apparently random strings of characters!

/cc @duckduckgo/community-leaders

**Comment by p512** [comment]
@mintsoft Sure thing!
I guess it's obvious but the error also exists with url encode which for `'` returns `&#39;` instead of `%27`.
