### ISSUE TITLE
Dates Goodie Role: Include handling for time queries

### ISSUE THREAD

**Issue by rasikapohankar** [duckduckgo/zeroclickinfo-goodies#3188]
Update Dates Goodie Role to add handling for time queries.

Following queries currently don't give an answer and should be handled:
1. Date along with time
For example 6th June 3 pm or 3 pm 6th June. Currently only the date is parsed, the time should also be parsed and hours, minutes, seconds for that date be changed accordingly.
2. Time of the form hours[:minutes][:seconds] am/pm, that is time only as 8 pm or 8:00 pm should also match.
3. Parse queries with days of the week and time. For example, Monday, next Monday; or any  days of the week, Monday 10 pm, next Monday 10 pm.
4. Queries with relative dates and time, i.e. tomorrow 10 am, today 10 am, next week 10 am, etc

---

People to notify: @GuiltyDolphin @mintsoft

**Comment by GuiltyDolphin** [comment]
@rasikapohankar Thanks!

I'll incorporate date+time, time and days of the week into #2810.

**Comment by rasikapohankar** [comment]
@GuiltyDolphin :+1: How can I help?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar If you can give me some more examples of dates you think should match that'd be great - I've pretty much got standard format (time) working now :)

**Comment by rasikapohankar** [comment]
@GuiltyDolphin I could only think of the ones I had included in #2808 for now, I'll add if I remember more.

**Comment by rasikapohankar** [comment]
@GuiltyDolphin One more: Queries with relative dates, i.e. tomorrow 10 am, today 10 am, next week 10 am, etc

**Comment by GuiltyDolphin** [comment]
@rasikapohankar Ah, yeah - sure (that should be fairly automatic).

**Comment by rasikapohankar** [comment]
Yes :+1: I assumed if we say `next week 10 am` it will move to the same day of week as the current one only in the next week and the time will be 10 am. I hadn't thought about `next month` but I guess it will move to the same date in the next month and change to the time specified? But a month is long so maybe we won't ask `next month 10 am`?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar Lets say you are on `January 31`, then Feburary will never have a `31st`, it doesn't really make sense to say `10 am next month` as a month is not a fixed unit.

Maybe, regarding the week form, we can always remove it if it has issues.

**Comment by rasikapohankar** [comment]
Hey @GuiltyDolphin! :) This is the design for the Countdown Goodie: 
![coutndown](https://cloud.githubusercontent.com/assets/8025692/16127878/fb58be4c-341b-11e6-8665-f3ccd1b45444.jpg)
The subtitle has the date as: July 26th, 2018, 10:00 am. Could we please add this to `date_output_string` in the Role as `%B %d, %Y, %r %Z`, as a second option along with `%d %b %Y %T %Z`?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar I'm not sure what advantage that would add - the current format has all the information required. We prefer to go for 24-hour time rather than 12-hour (more 'standard').

All output dates should be in either `%d %b %Y` or `%d %b %Y %T %Z` format (unless there's a good reason); why have you gone for that format? I'd suggest updating the Goodie to the standard format.

**Comment by rasikapohankar** [comment]
@GuiltyDolphin Actually the design was prepared by the design team, I'm trying to stick to it. I thought we could add it in the Role in case it's needed later on as well. Do you feel this format won't be required else where, in that case I can add the format directly only in this Goodie?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar I've brought this up in discussion - hopefully we can resolve how to handle _all_ date formats for the foreseeable future.

**Comment by rasikapohankar** [comment]
Hey @GuiltyDolphin! Is [this](https://github.com/duckduckgo/duckduckgo-utils/issues/9) the discussion?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar Part of it (sorry for not getting back).

I think a direction we want to move in is handling dates with locale-awareness (in output) to give a more *natural* feel to results for users.

Consequently, the format you are using at the moment should be fine for the time being - at least until we've sorted how we want to fully handle date results.

**Comment by rasikapohankar** [comment]
Thanks @GuiltyDolphin. I tried to search a little, found this: https://github.com/moment/moment/issues/1044, so I guess moment.js does not detect the user's browser settings for formatting the date? 
We want to add a function in the Dates Role such that the output format will depend on the location of the user and similarly for javascript, is that right? I don't know the details but have seen discussions about `$loc`, can we use that with some Perl module that can help in formatting the dates?

**Comment by GuiltyDolphin** [comment]
@rasikapohankar It's a one-liner (ish) I'll stick in #2810 - the PR already adds locale-support for other functionality, so formatting isn't an issue.

I'm not 100% sure the situation with `moment.js` - it definitely *supports* locale-based formatting, though I'm not sure if it *will* detect browser settings.

Another alternative might be to return a format string (either transparently or hidden) from the Perl side and use that to format dates in the front-end.

**Comment by elmerehbi** [comment]
Hello, thanks for the great hack. I am not sure it was suggested. I tried the following:

`30 days before april 12 0940`

I wanted it to calculate the date/time 30 days preceding 0940 hrs of April 12 of this year.

**Comment by mintsoft** [comment]
@elmerehbi is this the answer you're looking for: https://duckduckgo.com/?q=30+hours+before+12+april+2017+09%3A40%3A00&t=ffab&ia=answer ? However you want to be able to specify it in a more ambiguous format?

**Comment by elmerehbi** [comment]
@mintsoft Yes it is. I would have preferred that It understood my input.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
