### ISSUE TITLE
Subnet Calculator should more information about IANA special ranges

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#319]
As suggested by @macfreek: 

The subnet calc should really provide some more useful information for special IP address ranges: http://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

------
IA Page: https://duck.co/ia/view/subnet_calc

**Comment by javathunderman** [comment]
@jagtalon Was this fixed with that last PR?

**Comment by mintsoft** [comment]
@javathunderman I don't believe so

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.
