### ISSUE TITLE
Morse: Bad example queries

### ISSUE THREAD

**Issue by Asternitix** [duckduckgo/zeroclickinfo-goodies#3193]
The translation from morse does not trigger when I type in "morse ... --- ..."

IA Page:  http://duck.co/ia/view/morse 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @und3f

**Comment by alohaas** [comment]
Hi @Asternitix thanks for discovering this triggering bug. From what I can see, even though the IA page for this lists "Morse SOS" or "Morse ...---..." as queries that would trigger this IA, the actual triggering does or reflect this. 

If you look in the `morse.pm` file you'll notice that it should trigger on 
`triggers start => "morse code for", "morse for";`
`triggers end => "to morse code", "to morse";`

@und3f, do you have a minute to change the example queries? Let me know if not. 

Thanks!

**Comment by edgesince84** [comment]
hey @und3f, I wanted to ping you again and see if you are able to address this.

@Asternitix thank you again for finding this, we really appreciate it! I also wanted to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by kirkins** [comment]
This seems to be fixed as it's not an example query anymore.

**Comment by pjhampton** [comment]
Maybe, but I think we can add the trigginer in for `morse ... --- ...`. Makes sense. Want to add it @kirkins?

**Comment by kirkins** [comment]
@pjhampton happy to make the change 👍

**Comment by kirkins** [comment]
I guess this issue can be closed, made the change as suggested and it was closed.
