### ISSUE TITLE
DaysBetween: add option to exclude weekends from calculated days

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-goodies#3194]
could add an option to exclude weekends from calculated days between IA (apparently by the use of additional query trigger words). 

------
IA Page:  http://duck.co/ia/view/days_between 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @JetFault

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai We already have a Goodie for this, [WeekdaysBetween](https://duck.co/ia/view/weekdays_between).

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin ah,cool!
