### ISSUE TITLE
Sha: SHA-256 hash too large to display

### ISSUE THREAD

**Issue by p512** [duckduckgo/zeroclickinfo-goodies#3195]
Example query: https://duckduckgo.com/?q=sha-256+this&ia=answer
See these screenshots: [Imgur (Desktop)](http://i.imgur.com/G7zn1TE.png), [Imgur (Android)](http://i.imgur.com/XughgKu.png)
   

------
IA Page:  http://duck.co/ia/view/sha 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by mintsoft** [comment]
@p512 I'll fix that!

**Comment by p512** [comment]
@mintsoft Ah, cool!
