### ISSUE TITLE
Calculato:2654

### ISSUE THREAD

**Issue by nunukhalay** [duckduckgo/zeroclickinfo-goodies#3199]
---Issue---
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by nunukhalay** [comment]
Thank you

**Comment by GuiltyDolphin** [comment]
@nunukhalay Is this regarding #2654? Are you in favor of adding octal notation?

**Comment by nunukhalay** [comment]
May.20.2017

**Comment by nunukhalay** [comment]
On

**Comment by nunukhalay** [comment]
Thank you

**Comment by zekiel** [comment]
closing/reporting.
