### ISSUE TITLE
URLEncode: Trigger on "uri" as well

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/zeroclickinfo-goodies#3201]
Should probably trigger on `uri` in addition to `url`.

------
IA Page:  http://duck.co/ia/view/urlencode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

**Comment by neosilky** [comment]
Seems like a fair change - I can quickly do this if no one else wants to.

**Comment by tagawa** [comment]
Thank you @neosilky - it's all yours! I agree, it should be a quick update.

**Comment by zachthompson** [comment]
If we don't hear from @nishanths at [14 days](http://docs.duckduckhack.com/maintaining/guidelines.html) we'll move forward with the PR.
