### ISSUE TITLE
Ascii to Binary: handle phrase/sentences

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/zeroclickinfo-goodies#3203]
What about handling longer input so we can essentially reverse answers like [01001101 01110101 01100011 01101000 01100001 01110011 00100000 01000111 01110010 01100001 01100011 01101001 01100001 01110011 00100000 01000011 01101111 01101101 01110000 01100001 01110011 0100110111110000](https://duckduckgo.com/?q=01001101+01110101+01100011+01101000+01100001+01110011+00100000+01000111+01110010+01100001+01100011+01101001+01100001+01110011+00100000+01000011+01101111+01101101+01110000+01100001+01110011+0100110111110000&ia=answer)?

---

IA Page:  http://duck.co/ia/view/binary 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by tagawa** [comment]
This seems to be working for me - can anyone confirm?

**Comment by tagawa** [comment]
Thanks @ManrajGrover. I'll close this and we can re-open if it's still a problem.

**Comment by zachthompson** [comment]
I don't think the *ascii* to *binary* has been done yet.  If you're just clicking on the link I posted above that's Bin2Unicode.  I was suggesting being able to *reverse* that query, i.e. [M u c h a s G r a c i a s C o m p a s ䷰](https://duckduckgo.com/?q=M+u+c+h+a+s+G+r+a+c+i+a+s+C+o+m+p+a+s+%E4%B7%B0&ia=web)

**Comment by tagawa** [comment]
Ah, I misunderstood. Thanks for the clarification.
