### ISSUE TITLE
C String Formatting Cheat Sheet: Maintainer request 

### ISSUE THREAD

**Issue by neosilky** [duckduckgo/zeroclickinfo-goodies#3212]
I'm happy to take over this cheat sheet. Shouldn't need updating too often but I can look after it in the mean time.

~ Neo   

------
IA Page:  http://duck.co/ia/view/c_string_formatting_cheat_sheet

**Comment by tagawa** [comment]
Hi @neosilky and welcome! That's very kind of you to offer. I've added your name as maintainer - thanks!
