### ISSUE TITLE
Conversions: gallon to cubic iches

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3221]
Should 1 US gallon, converted to cubic inches be exactly 231?  The IA shows "231.001 cubic inches"   

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@edgesince84 According to Wikipedia (https://en.wikipedia.org/wiki/Gallon); the US gallon is defined as 231 cubic inches so yes. I'll have a look at that when I get home

**Comment by edgesince84** [comment]
Great, thanks Rob!  It was feedback from someone in the community, so that little .001 is nagging some people out there 😆
