### ISSUE TITLE
Visual Studio Cheat Sheet: Add more shortcuts

### ISSUE THREAD

**Issue by biscuitNinja** [duckduckgo/zeroclickinfo-goodies#3230]
I think this cheat needs more. 

There are literally hundreds of shortcut key combinations for VS 2015 and it would be nice to see some of the more interesting/useful ones featured so this CheatSheet is of interest to more seasoned VS developers as well as beginners.

I'm happy to help.
## Thanks

IA Page:  http://duck.co/ia/view/visual_studio_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gautamkrishnar

**Comment by gautamkrishnar** [comment]
Yes!  Waiting for your pull request....  :smile: :+1:

**Comment by biscuitNinja** [comment]
I'll crack on with it then! ;)

**Comment by edgesince84** [comment]
@biscuitNinja sounds like a plan! 😸

**Comment by gautamkrishnar** [comment]
@biscuitNinja  any update on this one??

**Comment by JasonCFisher** [comment]
Do you still need work done on this?

**Comment by biscuitNinja** [comment]
Apologies for absence, some work done. I'll make a fresh effort to get my changes finished in the next week or so.

**Comment by gautamkrishnar** [comment]
@moollaza Pls remove the "Maintainer input requested" tag

**Comment by gautamkrishnar** [comment]
@biscuitNinja  any update on this one?

**Comment by biscuitNinja** [comment]
@gautamkrishnar I will absolutely be cracking on with this it this week. It will be my lunchtime project. (There's a good number of shortcut keys to verify!)

Can we please remove the Needs a Developer label.

**Comment by gautamkrishnar** [comment]
@GuiltyDolphin We need to remove the 'Needs a dev' label

**Comment by biscuitNinja** [comment]
No idea where I stashed the original work undertaken, re-started from scratch.
Most recent commit: https://github.com/biscuitNinja/zeroclickinfo-goodies/commit/dd4fe3f7b4d3a699d5a4e688d0d2ffd57a5284a5

Apologies for foot dragging. Will aim to complete by the end of the week.
