### ISSUE TITLE
Add support for setting a timer to a specific time

### ISSUE THREAD

**Issue by tsimonq2** [duckduckgo/zeroclickinfo-goodies#3237]
In Google, I can type: [set timer for 12:00 PM](https://www.google.com/#q=set+timer+for+12:00+PM) and it will set a countdown timer to that time.

In DuckDuckGo, when I type: [set timer for 12:00 PM](https://duckduckgo.com/?q=set+timer+for+12%3A00+PM&t=canonical&ia=timer), it sets a timer for 12 minutes. Support should be added for this.

**Comment by GuiltyDolphin** [comment]
@tsimonq2 This should be handled in #2810 hopefully.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
