### ISSUE TITLE
Add support for the hourly forecast

### ISSUE THREAD

**Issue by tsimonq2** [duckduckgo/zeroclickinfo-goodies#3238]
It would be very beneficial to support viewing of an hourly forecast instead of the generic weather IA. I typed [hourly forecast green bay wi](https://duckduckgo.com/?q=hourly+forecast+green+bay+wi&t=canonical&ia=weather&iai=0) (the city that I live in) and I got a generic weather IA.

**Comment by GuiltyDolphin** [comment]
@tsimonq2 Is this an issue for https://duck.co/ia/view/forecast? Using the `Create Issue` button on the IA page will PR the correct repository with everything linked :)

**Comment by tsimonq2** [comment]
@GuiltyDolphin yes, thank you
