### ISSUE TITLE
CalcRoots: Reign in Triggering; Merge into calculator later

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3245]
For example:

https://beta.duckduckgo.com/?q=3+%2B+square+root+of+5&ia=answer

![screenshot-2016-06-13-21 30 11_381_160](https://cloud.githubusercontent.com/assets/8598426/16022085/0f272f82-31ae-11e6-8129-494eba005064.png)

And https://duckduckgo.com/?q=square+root+of+5+squared+%2B+3&t=ffab&ia=answer

![screenshot-2016-06-13-21 31 14_344_146](https://cloud.githubusercontent.com/assets/8598426/16022116/304820b8-31ae-11e6-9591-b47e9f788389.png)

It seems to me that this Goodie should just be merged into the calculator, adding support for Xth roots would be trivial and this is currently blocking a rather large set of queries involving roots.

@duckduckgo/community-leaders Any thoughts?   

---

IA Page:  http://duck.co/ia/view/calc_roots

**Comment by edgesince84** [comment]
thanks Ben, I think that's a good plan

**Comment by moollaza** [comment]
@GuiltyDolphin That sounds fine.

For now can we should improve the triggering.

@duckduckgo/duckduckhack-contributors anyone interested in investigating and simplifying the triggering of this IA and fixing it to avoid the types if queries it can't handle?

**Comment by GuiltyDolphin** [comment]
@moollaza I notice this doesn't have a maintainer - would you mind setting me as maintainer so we don't upset anyone later on when we merge it?

**Comment by edgesince84** [comment]
@GuiltyDolphin I took care of that for you.  You're now the maintainer 👍

**Comment by moollaza** [comment]
A user pointed out today that this IA triggers for the query `square root of minus garfield` which is a comic. There is definitely a big bug in the logic here.

@GuiltyDolphin would you be interested in fixing this?
