### ISSUE TITLE
Conversions: Display conversion calculation

### ISSUE THREAD

**Issue by malbin** [duckduckgo/zeroclickinfo-goodies#3247]
This is more of a suggestion--would be cool if the conversions goodie displayed the actual conversion calculation.

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by GuiltyDolphin** [comment]
@mintsoft @malbin Hmm, yeah - this might be nice for queries like `how to convert degrees to fahrenheit` or similar.

**Comment by mintsoft** [comment]
@malbin so the query `15 metres in feet` should show something like:
```
15m * 3.281m/feet = 49.213 feet
```
?

**Comment by GuiltyDolphin** [comment]
@mintsoft Aren't we going interactive? Perhaps you could hover over the answer to see the calculation? Or some other interactive method?

**Comment by mintsoft** [comment]
@GuiltyDolphin That is indeed the plan; not sure how this'd fit into the GUI

**Comment by GuiltyDolphin** [comment]
@mintsoft Lets worry about interactivity before we add new visual features then - the sooner we have interactive Conversions the better :)
