### ISSUE TITLE
Evernote Cheat Sheet: Should include Mac shortcuts

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3252]
Perhaps they can be added as new sections to this cheat sheet. Either that or create a new cheat sheet, but that would require more specific triggering.

------
IA Page:  http://duck.co/ia/view/evernote_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @smitche60

**Comment by smitche60** [comment]
Sounds good, I'll add these as new sections asap

**Comment by zekiel** [comment]
@smitche60 circling back on this in case it slipped :) No rush but good to know if it's a work-in-progress.

**Comment by smitche60** [comment]
Sorry about that- this is still on my radar. I should be able to complete this over the weekend.

**Comment by smitche60** [comment]
This is a work in progress, but I'll need to push back another week

**Comment by tagawa** [comment]
No worries @smitche60 - thanks for the update. If you feel you have too much on your plate, we may be able to get the community to help out. Just let us know!

**Comment by smitche60** [comment]
#3401
