### ISSUE TITLE
C++ Algorithms Cheat Sheet should be verbose like C++ Strings

### ISSUE THREAD

**Issue by ManrajGrover** [duckduckgo/zeroclickinfo-goodies#3263]
[C++ Strings](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-strings.json) Cheat Sheet provides syntax on how to use the function. This is not the case with [C++ Algorithms](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-algorithms.json). Is it necessary or should it be fixed? Asking because of inconsistency being introduced here.

**Comment by ManrajGrover** [comment]
@moollaza Please help me with this. #3271 is related to this and can be fixed if necessary. :blush:

**Comment by zekiel** [comment]
@ManrajGrover good spot -- yes, they should have consistency and it's useful to have the syntax. This should not prevent current or future pull requests from merging but is a best-practice to follow. 

Would you like to modify #3257 before merge? Or any others?

**Comment by ManrajGrover** [comment]
I'll make those changes in [C++ Algorithms](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-algorithms.json) as well as [C++ Complex](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/cpp-complex.json) Cheat Sheet then. Thank you. :blush:
