### ISSUE TITLE
Calculator: Support tau

### ISSUE THREAD

**Issue by 12people** [duckduckgo/zeroclickinfo-goodies#3267]
It'd be useful if the calculator supported the constant tau (tau = 2 \* pi). Tau is a nicer constant than pi for a number of reasons -- see http://tauday.com/ .
While I realize that tau isn't used very widely yet, it is gaining momentum. Even Google's calculator now supports tau.

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by mintsoft** [comment]
:+1: @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@12people You don't need to convince me ;) - I'm an advocate of Tau already.

Enjoy!

![screenshot-2016-06-17-16 37 26_463_162](https://cloud.githubusercontent.com/assets/8598426/16155983/dd3e7d3c-34a9-11e6-96e8-c1efda99fc39.png)

**Comment by 12people** [comment]
Awesome, thanks! 👍

**Comment by alohaas** [comment]
Thanks for the suggestion @12people :)

**Comment by 12people** [comment]
@GuiltyDolphin Any idea when this will be in the production version of DuckDuckGo? It's not working for me.

**Comment by GuiltyDolphin** [comment]
@12people No, sorry - the calculator rewrite is low priority at the moment as we are focussed on the programming mission. I'll let you know if there are any updates.
