### ISSUE TITLE
Unicode:  Add a link to http://unicode-table.com/en/

### ISSUE THREAD

**Issue by sneetsher** [duckduckgo/zeroclickinfo-goodies#3269]
It will be more helpful if it provides  a link to the corresponding page at  
http://unicode-table.com/en/

---

IA Page:  http://duck.co/ia/view/unicode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cosimo

**Comment by edgesince84** [comment]
hey @sneetsher thanks for suggesting this.  I'm sure @cosimo will address it shortly 🎯

**Comment by cosimo** [comment]
I understand that to add a HTML link, I need to change the plugin type? or at least the type or reply.
Anyway, I'm struggling to setup a functional development environment, so this might take a while more than expected (left some questions in duckduckhack slack in case somebody can help).

**Comment by moollaza** [comment]
@cosimo I replied to you on Slack -- please see https://github.com/duckduckgo/p5-app-duckpan/blob/master/README.md#additional-dependencies for help

That should sort out installing DuckPAN.

> I need to change the plugin type? or at least the type or reply.

@cosimo we only need to update what the IA returns. Right now it's a plaintext response. We need to update it to use our template system which means it needs to return a hash that specifies the template and the template data.

We should be able to use the simple `text` template with a `title` and `subtitle`. If we need to return a list of result there's the `list` template.

Here's examples of IA's using the text template: https://github.com/duckduckgo/zeroclickinfo-goodies/search?utf8=%E2%9C%93&q=group+text

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
