### ISSUE TITLE
Differentiation cheat sheet

### ISSUE THREAD

**Issue by sam09** [duckduckgo/zeroclickinfo-goodies#3270]
There is already a cheat sheet in development for Integration. We could have one for differentiation also.

**Comment by zekiel** [comment]
Current integral cheat sheet 
IA Page = https://duck.co/ia/view/integral_cheat_sheet
Beta Link = https://beta.duckduckgo.com/?q=integral+cheat+sheet&ia=cheatsheet&iax=1

**Comment by ManrajGrover** [comment]
@zekiel I can pick this one up if no one is already working on it.

Something I would like to know is how to show differential. `df/dx`. Is there a better way? :blush:

**Comment by gautamkrishnar** [comment]
Yes implementing this one would be awesome. @ManrajGrover make sure to include all standard derivatives. Really waiting to see this going live :+1:

**Comment by ManrajGrover** [comment]
@gautamkrishnar Yes, I found Wikipedia's [Differentiation rules](https://en.wikipedia.org/wiki/Differentiation_rules) page to be a good source.

> Something I would like to know is how to show differential. `df/dx` . Is there a better way? 

Please help me with this.

**Comment by gautamkrishnar** [comment]
@ManrajGrover i think the cheatsheet goodie is not  yet programmed to support maths, so it doesn't allow you to display dy/dx like this:
![d36698dfedf3d0c19fa023a43f369be5_400x400](https://cloud.githubusercontent.com/assets/8397274/16177126/1cb705d0-3642-11e6-8a51-0161171938cb.png)

So you can specify equations like: dy/dx(x^2)=2x
 
take a look at the [Boolean algebra cheatsheet](https://duckduckgo.com/?q=boolean+algebra+cheatsheet&ia=cheatsheet)

**Comment by ManrajGrover** [comment]
Sounds great @gautamkrishnar. I'll get on with this.

**Comment by ManrajGrover** [comment]
This can be closed now that #3301 is merged. :smile:
