### ISSUE TITLE
Special days

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#3286]
While doing a search for "fathers day" duckduckgo must display the day and month of the father's day celebration as 19th June. 

I don't know whether this is implemented already. But doing a quick search didn't triggered anything. **"It is actually triggering the news IA"** 
https://duckduckgo.com/?q=fathers+day

I think it should be better if we have one...

cc: @duckduckgo/community-leaders @moollaza @zekiel @GuiltyDolphin  What is your opinion on this? Anyone like to implement this?

**Comment by zekiel** [comment]
Maybe the Today-In-History IA can be leveraged for this? It's a WIP somewhere

**Comment by tagawa** [comment]
This is actually implemented in the Public Holidays IA, but is currently offline because it was over-triggering. There is a PR being worked on by @sekhavati to fix it: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2678

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
