### ISSUE TITLE
Add Math Template for Cheat Sheets

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#3288]
From PR #3270 i found that the cheatsheet goodie require new feature to specify mathematical equations as **val** key so that the goodie will display the specified equations like this (well formatted):
![Maths equation](https://cloud.githubusercontent.com/assets/8397274/16177252/f85bb26a-3643-11e6-9634-62523a26f1b8.jpg)

A new template named maths can be created. 
What is your opinion? Anyone like to implement this?

cc: @duckduckgo/community-leaders @duckduckgo/duckduckhack-contributors @moollaza @zekiel

**Comment by ManrajGrover** [comment]
I was just commenting on issue #3270. :smile: We can use [MathJax](https://github.com/mathjax/MathJax) or other similar library for this. :blush:

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Indeed - we've been getting quite a lot of mathematically-oriented cheat sheets lately, we should support LaTeX (perhaps through MathJax, as @ManrajGrover suggested) with pretty rendering.

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Indeed - we've been getting quite a lot of mathematically-oriented cheat sheets lately, we should support LaTeX (perhaps through MathJax, as @ManrajGrover suggested) with pretty rendering.

/cc @zachthompson

**Comment by gaulrobe** [comment]
:+1: for Mathjax! I have helped integrate it before on sites. It'd be cool if we could integrate that into DDG when applicable. It has some really neat features for math aficionados :smile:

**Comment by moollaza** [comment]
We have support for LaTeX available via [Mathquill](http://mathquill.com/). It's being used in the Symbolab Spice currently.

IIRC when I investigated libs for making Math look nice, the MathJAX lib was very large so I avoided it.

Happy to be proven wrong though.

This looks to be the size of the Mathquill assets:

![calculate_integral_x 5-5_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/16238184/8b22ffbc-37ad-11e6-82ea-a8b930e4f256.png)

**Comment by gaulrobe** [comment]
@moollaza I hadn't heard of Mathquill, but it looks much more lightweight and easier to configure. Mathjax has a LOT of configuration options so maybe there is a way to make it lighter, but I'd say Mathquill works here going forward!

**Comment by GuiltyDolphin** [comment]
@moollaza Oooh, that might be nice for the Interactive Calculator... Sweet.

**Comment by ManrajGrover** [comment]
Mathquill does look like better option. I have seen equations requiring MathJax taking time to render after page load. :smile:

**Comment by kammitama5** [comment]
Mathquill looks amazing. Thank you for mentioning this.

**Comment by tagawa** [comment]
I checked with @moollaza and to make this happen, the cheatsheet main JS file "would need to be updated with some logic to determine if MathQuill is required and load it if so". Should be this file:  `zeroclickinfo-goodies/share/goodie/cheat_sheets/cheat_sheets.js`

**Comment by gautamkrishnar** [comment]
Yes i think we could use some regexp to detect mats queries and make the MathQuill trigger...

**Comment by moollaza** [comment]
> Yes i think we could use some regexp to detect mats queries and make the MathQuill trigger...

I think that's too unreliable. We'll need a more declarative approach. For example a new "Math" template type, or variable that indicates the section/key/value contain math. We now have a few cheat sheets that contains math so that would be a good starting point.

- https://duck.co/ia/view/laplace_transform_cheat_sheet
- https://duck.co/ia/view/integral_cheat_sheet

**Comment by sahildua2305** [comment]
:+1: for the new `Math` template. Much needed.

**Comment by GuiltyDolphin** [comment]
@moollaza I think we should have a new template type. It would work well with the new trigger system too (custom triggers for all math cheat sheets).

**Comment by Owlree** [comment]
Is anyone working on this one? I would like to take care of it.

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now.
