### ISSUE TITLE
Tips IA maintainer request

### ISSUE THREAD

**Issue by gaulrobe** [duckduckgo/zeroclickinfo-goodies#3290]
There has been several maintainer timeouts for the Tips IA. If @mattlehning does not have any objections I would like to takeover as maintainer. Thanks!

https://duck.co/ia/view/tips

cc @moollaza @edgesince84 @zekiel

**Comment by edgesince84** [comment]
Thanks @gaulrobe - I'll keep an eye out for a response or objection from @mattlehning

**Comment by edgesince84** [comment]
@gaulrobe I made you the maintainer here!  thanks for volunteering to pick this up.

**Comment by gaulrobe** [comment]
Thanks @edgesince84!
