### ISSUE TITLE
Conversions: Result spelling should match query spelling

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3291]
For example, searching for "6 feet in metres" (British spelling) should show the result also with British spelling ("metres"): https://duckduckgo.com/?q=6+feet+in+metres&ia=answer   

[Reported on Twitter](https://twitter.com/MartijnSaly/status/744824285722718208)

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by GuiltyDolphin** [comment]
@mintsoft How do you like locales? ;)

**Comment by mintsoft** [comment]
Hmmm; it's doable. I'll probably do the same as the dates formatting stuff we talked about before. Default to correct (metre) and then override for US :laughing:

**Comment by moollaza** [comment]
Due to maintenance mode I'm marking this as tolerated. It's nice to have but non-essential.

FWIW Google doesn't appear to do this.
