### ISSUE TITLE
ColorCodes: Triggers on any query ending in "color <name>"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3294]
### Description
This IA is triggering for any query that ends in `color <name>` causing some irrelevant results.

e.g. https://duckduckgo.com/?q=symbolism+of+the+color+red&ia=answer

We need to verify that the query doesn't contain other words when the trigger is `color`

## People to notify
/cc @mintsoft 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

IA Page:  http://duck.co/ia/view/color_codes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by Mailkov** [comment]
@moollaza  Ok, I'm working to solve it

**Comment by moollaza** [comment]
Here's a visualization of the regex:

![debuggex__online_visual_regex_tester__javascript__python__and_pcre_](https://cloud.githubusercontent.com/assets/873785/16274316/1281bde8-3873-11e6-9010-c5c06f14354b.png)

You can see that it's possible to have any string before "color red" because of the `(.*?)` in the regex...

**Comment by Mailkov** [comment]
@moollaza In this moment IA ColorCode is supporting the query "rgb color code for red" or "red color code for html" so I'm not sure I will change the regex ...

**Comment by gaulrobe** [comment]
Maybe we need to be tighter with the regex and enforce "color code" being in the query, code not being optional?

**Comment by moollaza** [comment]
I think we should break apart that big regex so it's easier to understand and then replace the `(.*?)` with words we actually expect to see.

Or maybe as a heuristic if the string doesn't contain "color code", but contains a named colour **and** other words, we should bail out?

@gaulrobe I'm not sure we want to be so strict as to require "color code" just yet. The IA is just a little too flexible with it's triggering right now.

**Comment by gaulrobe** [comment]
@moollaza it might help to require it in cases where "color" is in the query, since that is gonna be very ambiguous. "color code" at least is explicit in what is being asked. But either way, maybe too early to go that far. :smile:

**Comment by moollaza** [comment]
@gaulrobe ah sorry I misunderstood you!

It looks like there are a few common search forms that just contain `color` though...
![drake_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/16322928/c9119bb2-3974-11e6-8d22-8691a39c2900.png)

![hex_color_dark_brown_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/16322909/9e74654c-3974-11e6-866a-a5da14a17643.png)

An alternative approach is to remove words and phrases we expect to be in the query and if the result is a valid colour name or code then we could trigger.

Ultimately I think we need to break up the logic we use to evaluate the query so it's easier to reason about, and then add more tests!

**Comment by moollaza** [comment]
BTW I just noticed that "#E0E0E0 color" and  "#E0E0E0 css color" don't trigger this Instant Answer -- they definitely should!

**Comment by mintsoft** [comment]
@moollaza good catch

@Mailkov Have you got a fork in progress somewhere? I don't mind picking this up if you don't have time

**Comment by GuiltyDolphin** [comment]
@mintsoft If you do, some of the test queries from #3346 might be useful to ensure it isn't over-triggering.

**Comment by moollaza** [comment]
Ping! I'm just checking in to see if anyone is still interested in finishing this one up?

**Comment by abijith-ka00** [comment]
color: "your color";
or
 backgroundbg color: " your color";
