### ISSUE TITLE
Duration Calculator: Add support for more than 2 inputs and 1 operation

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3304]
- We should be able to add or subtract more than 2 inputs: `12 days + 2300 hours + 5 weeks`
- We should also be should be able to combine: `340 days - 70 days + 3 weeks`

---

IA Page:  http://duck.co/ia/view/duration_calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sam09

**Comment by sam09** [comment]
Even I think that it should support multiple inputs. I think this should make pretty simple newcomer issue
