### ISSUE TITLE
USPS: Triggering on iOS error code: 18446744073709550611

### ISSUE THREAD

**Issue by stevenmg** [duckduckgo/zeroclickinfo-goodies#3314]
https://duckduckgo.com/?q=18446744073709550611&t=ffab&ia=answer
## Shows USPS tracking IA which takes you to an invalid tracking number page. The number is an NSURLErrorDomain code for iOS.

IA Page:  http://duck.co/ia/view/usps 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by pjhampton** [comment]
Thanks @stevenmg! There has been a couple of issues with this IA. We're going to try and address it here: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3973
