### ISSUE TITLE
Conversions: converting cm to feet and inches

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3317]
When trying to convert centimeters to Imperial units, it does not show inches - only feet.  

Example: "200 cm = 6.562 feet" instead of the desired feet _and_ inches

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by GuiltyDolphin** [comment]
Yeah, it'd be nice to support this - @mintsoft I *think* we have an issue for multiple-unit answers already?

**Comment by mintsoft** [comment]
Yeah there's a variety of unit combo suggestions on the todo list :+1:

**Comment by edgesince84** [comment]
thank you, fellas!

**Comment by pjhampton** [comment]
This is a bit out of scope for the current triggering + the interactive one unit boxes. Closing for now 👍
