### ISSUE TITLE
Tests currently noisy

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3320]
We're getting a lot of `add_country_alias(): alias already in use: Laos` and `add_country_alias(): alias already in use: Russia` in the tests at the moment, making it pretty hard to read the test output. We should probably deal with this sooner rather than later.

cc @moollaza @zachthompson @duckduckgo/community-leaders

**Comment by zachthompson** [comment]
It's due to the release of Locale::Codes [v3.39](https://metacpan.org/pod/distribution/Locale-Codes/lib/Locale/Codes/Changes.pod#VERSION-3.39-2016-05-31-sbeck).

**Comment by GuiltyDolphin** [comment]
Fixed in duckduckgo/duckduckgo#209.
