### ISSUE TITLE
Cheat Sheets (Controller): Incorrectly determining '`end`' triggers

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3324]
An issue brought up in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3319 revealed a bug in the triggering process.

Due to the way triggers are handled, the first trigger found (earliest in the query) will be used as the trigger for the IA, regardless of whether or not it is valid.

For example, without `words` as a trigger, `words used in kabaddi cheat sheet` will be treated like so:

Trigger: `cheat sheet`
Remainder: `words used in kabaddi`,

But with `words` as a `language` trigger (which should not affect the Kabaddi cheat sheet - ideally):

Trigger: `words`
Remainder: `used in kabaddi cheat sheet`

As `words` appears earliest in the string.

---

In terms of working around this, my immediate thoughts are that we should check the remainder of the query for any further trigger words, then if any are found re-run the process with a different remainder; though I'm not sure how resource-costly this would be.

cc @zachthompson 

---

IA Page:  http://duck.co/ia/view/cheat_sheets 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zachthompson

**Comment by zachthompson** [comment]
This seems like an edge case where we're trying to have category triggers and aliases with the same terms.  I would opt for 

1. removing `words used in kabaddi` from the aliases
2. Or, removing it from the category with the `words` trigger

I don't think we want to get into multiple triggers at this point.

**Comment by GuiltyDolphin** [comment]
@zachthompson Edge case indeed!

We may wish to remove the alias then - more cheat sheets are likely to benefit from the added trigger than that single cheat sheet would from keeping the alias.

We'll want to keep this in mind for the future though.

**Comment by sahildua2305** [comment]
@GuiltyDolphin So should I go ahead and remove that alias from `kabaddi` cheat sheet?

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Yes - go ahead and remove the alias.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
