### ISSUE TITLE
Unicode: Control characters affect display of character information

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3326]
Here's an example:
https://duckduckgo.com/?q=U%2B202E&ia=answer

The U+202E character is a right-to-left conversion character. When our code renders it, it writes the description right-to-left. We should make exceptions for such characters and not render them.

Affected characters, according to a [helpful tweet](https://twitter.com/FakeUnicode/status/748540297861341184), are:
U+202A
U+202B
U+202C
U+202D
U+202E
U+2066
U+2067
U+2068
U+2069

[Reported on Twitter](https://twitter.com/LucasWerkmeistr/status/748500151107469312)

---

IA Page:  http://duck.co/ia/view/unicode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cosimo

**Comment by lucaswerkmeister** [comment]
U+202D LEFT-TO-RIGHT OVERRIDE might be similarly problematic for people in RTL locales.

**Comment by lucaswerkmeister** [comment]
Instead of not rendering the character, you could also wrap it in a `<div>`, which encapsulates the effect of the direction override. (A `<span>` doesn’t.) I think this would also make sense, semantically – separating the character from its description.

**Comment by tagawa** [comment]
That's a good idea @lucaswerkmeister - I might try that out.

**Comment by tagawa** [comment]
That PR should take care of it. Will try to install it to the beta server for testing.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
