### ISSUE TITLE
Duration Calculator: Improve handling of ambiguous units

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3330]
Some units, such as 'months', don't have a static duration. 

We should have a transparent way of handling these types of units, perhaps with a statement such as `assuming 1 month is 30 days`, not accepting them (this would be undesirable), or something very clever!

There are a few cases of the first suggestion (a statement); due to the way a year has a consistent number of months, we wouldn't need to provide an additional statement in certain cases:
- `"1 month + 2 months" = "3 months"` - no statement needed.
- `"1 year + 1 month (in months)" = "13 months"` - no statement needed.
- `"1 month + 31 days" = "~ 2 months (maybe)"` - statement **needed**.

@sam09 Any other ideas on how to handle this?

---

IA Page:  http://duck.co/ia/view/duration_calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sam09

**Comment by gaulrobe** [comment]
@GuiltyDolphin @sam09 just a thought... maybe use the smallest duration as the resolution. So for `1 month + 31 days` queries the answer would be (365/12 + 31) = `61.42 days`. The idea here is to convert down to the smallest duration unit in a statement in order to get better resolution. Could even do something like `61.42 days or ~2 months` as an answer.

**Comment by GuiltyDolphin** [comment]
@gaulrobe Would you expect a fractional result when you add days to months? I wouldn't.

For your second point, there may be some value in using approximations - though I think we should avoid it when possible.

It's a bit of a pain because usually when using months you are working relative to some date, in which case months are well defined (we know the length of each month).

@sam09 It might be worth playing around with some other tools that perform a similar role - there's likely something on https://timeanddate.com

**Comment by gaulrobe** [comment]
@GuiltyDolphin the problem being day + month queries need to be generalized since you have no point of reference. And given the 1 month = 30.417 days conversion (https://duckduckgo.com/?q=1+month+to+days&bext=mcp&ia=answer) maybe fractional answers are expected here since generalizations need to be made without a point of reference.

**Comment by sam09** [comment]
I think a fractional result would be unexpected in cases we are adding two
whole values. Eg: 1 month + 31 days is either 2 months or 2 months + 1 day.
Either one of them is an expected answer.

**Comment by gaulrobe** [comment]
A fairly authoritative source: https://www.wolframalpha.com/input/?i=1+month+%2B+15+days

I'm not saying we can't do things differently, but to support these queries and to ensure users get accurate information, I think we need to standardize what a month means. It might also be more valuable to create an interactive duration calculator where users can input a reference point and add time units to it.

**Comment by GuiltyDolphin** [comment]
@gaulrobe One way to do that would be to say *which* month we are using - see for example [this section](https://en.wikipedia.org/wiki/Month#Types_of_months_in_astronomy) on Wikipedia.

Your case for fractional results does make sense - it's just whether users would prefer it to integral results.

Gah! Why can't we standardize these things!

**Comment by mintsoft** [comment]
@GuiltyDolphin Because there's a non-integer ratio and when rounded a poorly factorable relationship between the rate of rotation of the earth and the orbital period of the earth! 

For the record, conversions defines a year as exactly 365 days and a month as 365/12 ~ 30.417 days.

**Comment by GuiltyDolphin** [comment]
@mintsoft Years are a bit easier - we can just use the [common year](https://en.wikipedia.org/wiki/Common_year). I don't think there's a 'common month' though.

**Comment by mintsoft** [comment]
Yeah; I think the only sensible thing is to ask the question "what would the user expect if they asked 1day + 12 months"; I think they expect 366 days

**Comment by GuiltyDolphin** [comment]
@mintsoft Indeed. In that case we can just treat `12 months` as exactly `1 year` though; making working with days a bit easier.

What about `1 month + 1 day`? `32 days`? `31 days`? `30 days` (please no)?

Hmm, @gaulrobe how about something similar to your idea of fractional results, but for the final result we *round* it to the nearest integer? 

`10 months -> 304.166... -> 304 days` (and 1 month would become `30 days`). Then we could say `to the nearest day` or similar in the output.

Regardless, I think we need to make it clear what we are using for months.

**Comment by mintsoft** [comment]
Yeah personally I lean towards the average month; so 1 month + 1 day is 31.417 days. We could just implement that and wait for feedback?

**Comment by GuiltyDolphin** [comment]
@mintsoft Hmm, true.

@sam09 Would you be happy with that approach? To use a month as `365/12` days and see if we get any feedback on fractional results?

**Comment by zekiel** [comment]
I believe this is how it was handled when Wolfram|Alpha was used as an IA so definitely OK as is but also good to see what people think once live. I do remember some feedback on it being a little odd but that can probably be mitigated by showing multiple interpretations based on the first unit expressed. 

https://duckduckgo.com/?q=7+months+%2B+12+weeks&t=ffab&ia=answer
would show as is, **9 months, 3 weeks, and 1 day** 

https://duckduckgo.com/?q=12+weeks+%2B+7+months&t=ffab&ia=answer
would show **42.42 weeks**

**Comment by zekiel** [comment]
Nm my comment -- leaving it here because it's wrong and just shows how it gets weird when there's a remainder and its expressed as a fraction or written form. At some point, do you show hr/min/sec? 

don't mind me.

**Comment by pjhampton** [comment]
Hey all,

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
