### ISSUE TITLE
SHA: When I SHA256 or SHA512 something, it gets cut off

### ISSUE THREAD

**Issue by ArtskydJ** [duckduckgo/zeroclickinfo-goodies#3332]
E.g. `sha256 lol` should have `c9c1abc` after what I see below:
![sha256-ddg](https://cloud.githubusercontent.com/assets/1833684/16535089/420d82d4-3faa-11e6-8c7b-8492c78257e8.PNG)

------
IA Page:  http://duck.co/ia/view/sha 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by ManrajGrover** [comment]
This is because of `overflow: hidden` being applied by class `c-base__title`. Removing it fixes the issue.

![screenshot from 2016-07-02 03 31 07](https://cloud.githubusercontent.com/assets/5673050/16535516/9cdafa2e-4005-11e6-8beb-63b77d23b4bb.png)

**Comment by tagawa** [comment]
@ArtskydJ @ManrajGrover Thanks for reporting and looking into this. It looks like removing `overflow: hidden` will still truncate the string on smaller screens so may be `overflow: scroll` (or `overflow: auto`) is better. I'll see if the design team can take a look.

**Comment by mintsoft** [comment]
@tagawa I fixed this already in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3196 and https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3151 is this not live?
