### ISSUE TITLE
UnderScore.js Cheat Sheet Maintainer Request

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3335]
I noticed that underscore.js cheat sheet has no maintainer. I'd like to take over this one, if no one has any issues.

https://duck.co/ia/view/underscore_js_cheat_sheet

/cc @moollaza @edgesince84

**Comment by tagawa** [comment]
Hi @sahildua2305 - you're very fast! I've just made you the maintainer. Thanks for being so keen and helping out 😃

**Comment by sahildua2305** [comment]
:tada: Thanks @tagawa
