### ISSUE TITLE
Use of single and double quotes in templates

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3347]
As of now the templates use a mix of double quotes and single quotes. In my opinion, we should make changes to use either of these to bring uniformity.

Example - [Goodie Template](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/template/lib/DDG/Goodie/Example.pm)

/cc @moollaza @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Sure, we should prefer single quotes if there's no interpolation.

TBH we expect the user to completely wipe most of the template strings, oft removing quotes entirely.

But for cases such as `"text"` in `templates` we should definitely be using single quotes.

**Comment by sahildua2305** [comment]
So should I submit a PR to make the changes?

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Go for it!
