### ISSUE TITLE
New Goodie(s): Pinout of various microcontrollers

### ISSUE THREAD

**Issue by 122131** [duckduckgo/zeroclickinfo-goodies#3354]
I was thinking of making a new Goodie for Arduino pinout, but I don't know if it's better to have a single Goodie for all microcontrollers (Raspberry Pi, Teensy...)

What is your opinion? 😄 

@moollaza @zekiel

**Comment by GuiltyDolphin** [comment]
@122131 Are there any APIs that can serve this information? If so, this would make a great Spice. If not, are there any pages that can be scraped for the information? This could be an awesome FatHead.

If the dataset is relatively small, and we can easily retrieve it then sure, we could store it all in some files for use in a (single) Goodie.

**Comment by 122131** [comment]
@GuiltyDolphin I had a quick look, but I haven't found any API focused on pinouts. 
Instead I found [this](https://github.com/Bouni/Arduino-Pinout), but it's only for Arduino.
I don't think the dataset will be too large (an image for each microcontroller, a little description and/or some special notes), even if it will be expandable with other microcontrollers.

**Comment by GuiltyDolphin** [comment]
@122131 Hmm, interesting repo. I've done a bit o' searching and haven't found any APIs that provide diagrams.

Perhaps we could use those images along with additional data from an API in an item view? Any thoughts @moollaza ?

**Comment by 122131** [comment]
@GuiltyDolphin I also found [this](http://pinout.xyz/) ([repository](https://github.com/Gadgetoid/Pinout2)) for Raspberry PI...

**Comment by moollaza** [comment]
Sounds like this could work similarly to our Minecraft Goodie -- a collection of images and descriptions used by a Goodie 👍

**Comment by moollaza** [comment]
Hey @122131,

DuckDuckHack is now in Maintenance Mode and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can act on and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
