### ISSUE TITLE
Local Sunrise/Sunset: Should be given display priority

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3359]
Currently the query "sunset" or "sunrise" shows the Meaning tab by default, but I think the Answer tab should have priority.   

---

IA Page:  http://duck.co/ia/view/sun_info 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by mintsoft** [comment]
This has just been raised again by a user in the wild (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3762); I think this is probably worth doing.
