### ISSUE TITLE
Calculator: create simple UI

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-goodies#3362]
Can we add a simple JavaScript User Interface (buttons and result field) on calculator IA. This could be highly helpful!   

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai Sure, https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2848

Yeah, that quick.

**Comment by edgesince84** [comment]
sorry for the delay here - I'll get that prodding done!

**Comment by pjhampton** [comment]
Looks like this has now been resolved!
