### ISSUE TITLE
New Color Role

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3371]
We've got a few Goodies ([ColorCodes](https://duck.co/ia/view/color_codes), [RGBColor](https://duck.co/ia/view/rgb_color)) including a port ([ColorPicker](https://duck.co/ia/view/color_picker)) that use similar methods for parsing and working with Colors; I think this presents an ideal opportunity to refactor the common logic out into a Role.

@duckduckgo/community-leaders Any thoughts? Good idea? Bad idea? Is there anything you'd like to see included?

**Comment by GuiltyDolphin** [comment]
@moollaza Any thoughts? We've got 2 new Goodies in the works, plus one port - all of which could benefit from this Role.

**Comment by sahildua2305** [comment]
@GuiltyDolphin how does a `Role` work?

**Comment by GuiltyDolphin** [comment]
@sahildua2305 For a description (and some references) check out `perldoc Moo::Role`. For the Roles we use check out http://docs.duckduckhack.com/backend-reference/goodie-helpers.html

I'm not *100%* sure why we use Roles rather than just packages in some of the circumstances (Role functionality not used), but we generally use Roles for any features we want any Goodies to be able to access (which not *all* Goodies would need to).

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
