### ISSUE TITLE
Counter-Strike Go Cheat Sheet: Add aliases

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3385]
This could probably benefit from a few aliases, for example:
"counter-strike go", "counter strike go", "cs:go", "counter-strike global offensive", "counter strike global offensive"

------
IA Page:  http://duck.co/ia/view/csgo_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @aiyankovil

**Comment by tagawa** [comment]
Actually, the description should be updated as well to something like:
"Describes various abbreviations and chat meanings for Counter-Strike: Global Offensive"

**Comment by sahildua2305** [comment]
I will fix this one @tagawa
