### ISSUE TITLE
JIRA: source no longer active

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3387]
The query for the airplane "DC10" triggers this IA, and the source is closed now.

------
IA Page:  http://duck.co/ia/view/jira 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @arroway

**Comment by moollaza** [comment]
@edgesince84 I'm not able to trigger the JIRA Goodie for that query, but for others, everything seems to be fine?

https://duckduckgo.com/?q=SOLR-4530&ia=answer

https://issues.apache.org/jira/browse/SOLR-4530
