### ISSUE TITLE
Create CSS Colours List Goodie

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3388]
### Background

We do not have and Instant Answer to display all the named CSS colours. We should!

### Objective

Build a Goodie that displays a list of all names CSS colours, along with their colour codes and a sample of the colour.

Essentially we should re-create [this CSS-Tricks table](https://css-tricks.com/snippets/css/named-colors-and-hex-equivalents/). w3Schools has a [similar table](http://www.w3schools.com/cssref/css_colors.asp)

This can be achieved with a Goodie using the List template. We can get a list of all the colours from the [Color::Library](https://metacpan.org/pod/Color::Library) module

#### Example Queries

- css colors
- css3 colors
- css named colors
- list of css colors
- list of named css colors
- all the above spelled with "colours" (the _correct_ spelling :wink:)

### What to do: 
1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Fathead documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) and [other Fatheads](https://duck.co/ia?repo=fathead) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes

### Who to contact for help: 
Please contact @moollaza  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

----

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/create-ia-css-colors-list/230

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in making this CSS Colors List Goodies? 

It will require Perl coding and should be fairly easy to build using the List template.

**Comment by sahildua2305** [comment]
@moollaza I'd like to take this up.
