### ISSUE TITLE
Create CSS Animations Goodie

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3389]
### Background

CSS Animations are very popular and we can very easily display a tile view of CSS Animation demos, that show what the effect of the animation is. 

Ideally we can link to a live demo of the CSS where the user can copy and modify the CSS we've demonstrated.

For example, CSS-Tricks has a great post with embedded samples: https://css-tricks.com/css-animation-tricks/
### Objective

Build a Goodie that displays a tile view where each tile demonstrates a different CSS animation technique. Each tile should be a link to a CodePen where the user can see and play with the code.
#### Example Queries
- "css animations"
- "css animations demos"
- "css animations examples"
#### Example Animation Demos
- https://robots.thoughtbot.com/css-animation-for-beginners
- http://www.webdesignerdepot.com/2014/05/8-simple-css3-transitions-that-will-wow-your-users/
- http://www.the-art-of-web.com/css/css-animation/
  Reply
### What to do:
1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Fathead documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) and [other Fatheads](https://duck.co/ia?repo=fathead) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes
### Who to contact for help:

Please contact @moollaza  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

---

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/create-ia-css-animations-goodie/262/2

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in making this CSS Animations Goodie?

It will require Perl and/or JS (depending on implementation) and definitely some advanced CSS skills. The will likely warrant the use of a custom tile template and plenty of CSS to create the various animations.

This has the potential to be one of the coolest looking Instant Answers if built well.

If anyone has suggestions on which animation techniques we should demo, please let us know!

**Comment by ManrajGrover** [comment]
@moollaza I can take this one up if it isn't on High Priority. :smile:
