### ISSUE TITLE
Parcelforce: Should not trigger for "luhn 1234554651"

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3391]
Direct link: https://duckduckgo.com/?q=luhn+1234554651

------
IA Page:  http://duck.co/ia/view/parcelforce 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Fix: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3398
