### ISSUE TITLE
UnixTime: Convert human-readable datetime to unix timestamp

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3392]
For example, the query "Fri Feb 13 23:31:30 2009 UTC timestamp" (or similar) would convert to "1234567890".
Not sure if this should be an update to this IA or a new IA.   

[Suggested on Twitter](https://twitter.com/ashishwt/status/753549227595182080)

---

IA Page:  http://duck.co/ia/view/unix_time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @codejoust

**Comment by GuiltyDolphin** [comment]
@tagawa I've got a Goodie in planning that would provide something of an interface to the Dates Role - mostly for parsing dates of various formats to a canonical (possibly user decided) form. I'm waiting on #2810 before I do anything with that though.

Potentially the 'reverse' of this, I guess :wink:

**Comment by iammrigank** [comment]
Is anyone working on this @tagawa? Is this dependent yet on #2810 or can we proceed with this?
This would complete the Unixtime IA I think and will be of great help to the users.
:)

**Comment by tagawa** [comment]
Hi @iammrigank. I don't think anyone's working on this at the moment because we're currently focusing on the programming mission and only reviewing pull requests for our targeted languages - see this post for more details: https://forum.duckduckhack.com/t/duckduckhack-getting-started/53

I still think this would be a good IA to improve but it probably wouldn't be merged until after the programming mission, and we don't have a timeline for that just yet.

**Comment by iammrigank** [comment]
Thank you for the update.
And i hope to contribute to the programming mission myself.

Have a good day!

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
