### ISSUE TITLE
URL Decode: Trigger is capitalization dependent

### ISSUE THREAD

**Issue by suryansh-tibarewal** [duckduckgo/zeroclickinfo-goodies#3395]
Does not trigger when trigger word URL is written in caps   
eg. "url decode <link>" triggers the IA but "URL decode <link>" does not.
------
IA Page:  http://duck.co/ia/view/urldecode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Thanks for the report @suryansh-tibarewal I have a fix incoming: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3397
