### ISSUE TITLE
Random Date: Allow some customization

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3407]
For example, it'd be good to be able to restrict the date to certain years or time periods, e.g.:
`random date (in) 2016`
`random date (in the) past`
`random date (in the) future`   

------
IA Page:  http://duck.co/ia/view/random_date 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@tagawa Hmm, interesting idea.

I'll have a quick poke and see what this'd require.

**Comment by GuiltyDolphin** [comment]
Partially solved in #3409 - though once #2810 is merged we should be able to handle the rest of the cases.
