### ISSUE TITLE
JS Minifier - minify CSS as well

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-goodies#3413]
The library used for JS Minifier IA, [prettydiff](https://github.com/prettydiff/prettydiff) can handle CSS too, shouldn't be too hard to add that functionality.

//cc @moollaza 

---

IA Page: https://duck.co/ia/view/js_minify
Maintainer: @sahildua2305

**Comment by ManrajGrover** [comment]
@MariagraziaAlastra I can take this one up. :smile:

**Comment by sahildua2305** [comment]
@ManrajGrover Actually, I discussed with Maria that it will require just checking whether the query contains `CSS` or `JS` and set the language accordingly for the library. I have the fix for this ready. I'll push in a while. Thanks for offering help however :smile:

**Comment by amarlearning** [comment]
@sahildua2305 Have you pushed the code for CSS?

**Comment by sahildua2305** [comment]
@amarlearning No. Got busy with other stuff. I'll do so next week. Otherwise, if you are interested in tackling this before that, let me know 👍

**Comment by amarlearning** [comment]
I am not sure about this week!
But if you are busy in next week also, then let me know I will try to do this!
