### ISSUE TITLE
JavaScript Minifier: Code refactor + Design Adjustments

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3415]
Lot's of improvements to be made:

### Perl
- Better query validation
  - Use `startend` trigger + add more triggers, or keep with `any` but use regex to evaluate the query is valid. We should ignore certain queries like "gulp minify js"
- Add triggers for 'JSON'
- Use `title` property to render Title instead of using `<h5>` in template
- Add a `subtitle` explaining how to use this?

### JS
- Refactor code to use `DDG.build_async` and only display IA after PrettyDiff has loaded
 - Look at WhereAmI Goodie for `build_async` example
- Setup default display properties of elements using CSS, instead of modifying via jQuery after render

### CSS & Handlebars
- use `is-hidden` to hide elements by default
- add `tx--##`, `tx-clr--`, and `bg-clr--` classes instead of hardcoded CSS colors to prevent breaking DDG Themes
- use our `btn` class to style the `<button>`
- More details on DDG CSS classes here: **https://duckduckgo.com/styleguide**
- Add CSS for Mobile screens
 - We should probably stack the windows always?
- set `font-family: 'monospace'` for `<textareas>`

/cc @MariagraziaAlastra 

------
IA Page:  http://duck.co/ia/view/js_minify 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
@moollaza I just got to know from @MariagraziaAlastra that you two discussed the loading of the library. So, should I leave it as it is? Loading library only when we are sure that we need it?

**Comment by MariagraziaAlastra** [comment]
@moollaza As discussed, the library is quite heavy and we agreed internally that it should load on textarea change, so that we're fairly sure the user intends to use it. 
Otherwise we'd load it even if the user intends to click on organics instead of using the IA.
