### ISSUE TITLE
Timezone Converter: IST to CST conversion bug

### ISSUE THREAD

**Issue by SudShekhar** [duckduckgo/zeroclickinfo-goodies#3420]
I tried : 16:18 ist to cst   

Got 4:48:55 CST whereas it should be 5:58.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by alohaas** [comment]
@SudShekharth I'm not sure this is wrong. I just checked another time zone converter and it looks like the conversion is correct. Take a look at the link below. I think you may have misread something?

http://www.timeanddate.com/worldclock/converted.html?iso=20160720T1615&p1=54&p2=94

**Comment by SudShekhar** [comment]
I might be wrong here (timezone's confuse the hell out of me anyhow). 

But right now, it's `23:54` in IST.
DuckDuckGo shows `12:24 CST` (when I put in as ist to cst converter)
Google shows the conversion as `01:25PM`.

`
I actually caught this issue when comparing the output in java 

    Calendar cal = Calendar.getInstance(TimeZone.getTimeZone("UTC+05:30"));
    Date now = cal.getTime()
    DateFormat timeOutputFormat = new SimpleDateFormat("HH:mm", Locale.ENGLISH);
    timeOutputFormat.setTimeZone(TimeZone.getTimeZone("CST"));
    timeOutputFormat.format(now);
`
The output given here matches that of Google and not DuckDuckGo.

Maybe its a daylight savings issue?

**Comment by alohaas** [comment]
Time zones are super confusing! I agree. 

Thanks for going more in depth with your explanation and background. It looks like you are definitely on to something here...maybe daylight savings? maybe a bug? 

In any case, I've flagged this as needing a DuckDuckHack developer.

**Comment by mintsoft** [comment]
@SudShekhar @alohaas I've had a quick look this morning; our answer isn't wrong per-se and google isn't wrong per-se either. 

The conversion that Google is doing is for the query `23:54 IST in CST` is actually applying daylight savings time (hence why it says Central Time not CST or CDT); personally I think that's the wrong answer as it's answered a different question!

Our query: https://duckduckgo.com/?q=23%3A54+IST+in+CDT&ia=answer returns the same answer as Google.

**Comment by GuiltyDolphin** [comment]
@SudShekhar I've just checked another TZ converter and it agrees with our answer, you're working with IST = Indian Standard Time, correct?

**Comment by SudShekhar** [comment]
Yes. The output given by DDG is correct in terms of `CST`.

 Whether the answer should account for daylight savings or not is debatable :) not because Google does it but because Java standard libraries (and I am assuming maybe others languages too) might've implemented it under the hood. It's pretty confusing to get a different answer from the web and the standard library unless you know why. 

Anyways, please feel free to close the issue since this isn't really a bug anyhow.

**Comment by tagawa** [comment]
Thanks for the investigation everyone. As @SudShekhar suggests, I'll close this for now but we can re-open if we feel it needs to be tackled after all.
