### ISSUE TITLE
Suggestion: Add JSON Validator

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3431]
_(Bringing this from forum as an issue)_

I will work on this. I have found this [pretty neat snippet](http://stackoverflow.com/a/12217209) to check if the json is valid or not. Please correct me, if I am wrong with this one.

EDIT: [Alternative solution](http://stackoverflow.com/a/20392392) (Without using jQuery)

/cc @MariagraziaAlastra @moollaza

**Comment by MariagraziaAlastra** [comment]
Thanks @sahildua2305!
What about using a library like [jsonlint](https://cdnjs.com/libraries/jsonlint)? This also provides a specific error for invalid JSON. Try it [here](http://zaa.ch/jsonlint/)

**Comment by sahildua2305** [comment]
Yeah! This library seems pretty good. I was just testing it locally. Looks good to me. :smile:

**Comment by MariagraziaAlastra** [comment]
Or we could go pro and have the whole JSON visualizer + validator using [jsoneditor](https://cdnjs.com/libraries/jsoneditor) - GitHub repo [here](https://github.com/josdejong/jsoneditor/)

**Comment by sahildua2305** [comment]
Looks good. I think we can have two separated IAs for visualizer and validator.  What say?
