### ISSUE TITLE
Conversions: feet + inches to metric

### ISSUE THREAD

**Issue by Klesus** [duckduckgo/zeroclickinfo-goodies#3433]
I'm European and basically the only times I see imperial height measurements they most often come in the format of x' y'' which (to my knowledge) DDG cannot convert. To do this I have to do 2 queries and then sum. One for feet and one for inches.
My request is that this get patched to be able to handle feet and inches in a single query, meaning being able to handle ft + in postfixes as well as ' as feet and both double quotes " and 2 single quotes '' as inches.
I also imagine that people in countries that use imperial would like to have metric converted to 2 answers (at least when querying about "x unit to ft"); one that simply converts x to y, and one that converts x to y' z''.

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@Klesus Thanks for the report; as a fellow european I share your frustration. This feature is next on my todo list!
