### ISSUE TITLE
Dice: "Roll a dice" search doesn't trigger Instant Answer

### ISSUE THREAD

**Issue by shadabk** [duckduckgo/zeroclickinfo-goodies#3437]
Even though 'Dice' is the plural of 'Die' and "roll 'a' dice" is not entirely valid, 'roll a dice' should return the result of "roll a die".
------
IA Page:  http://duck.co/ia/view/dice 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @loganom

**Comment by loganom** [comment]
I completely agree.

**Comment by zekiel** [comment]
@loganom  I've added the Needs a Developer label but please remove if you're going to tackle.

**Comment by shadabk** [comment]
@loganom @zekiel https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3467

**Comment by tagawa** [comment]
Thanks to @shadabk for implementing this. It's working here on beta: https://beta.duckduckgo.com/?q=roll+a+dice&ia=answer
and should go live in the next few days.
