### ISSUE TITLE
Day of the Week Calculator: wrong date in result

### ISSUE THREAD

**Issue by jumpball** [duckduckgo/zeroclickinfo-goodies#3438]
When I search for "what day of week was 8.7.2016", it doesn't show the day of week for 8th Juli 2016, but the day of week for 7th August 2016. However, it works correctly for day numbers bigger than 12.

---

IA Page:  http://duck.co/ia/view/day_of_week

**Comment by mintsoft** [comment]
@jumpball Thanks for the report; we have a system that guesses what format is meant by the user that currently isn't location aware and it defaults to US handling. We know this isn't ideal for the rest of the work (personally I'm British so mm/dd/yyyy is utter nonsense to me). Until we implement locale awareness into the role you can ensure consistent handling using other formats:

https://duckduckgo.com/?q=what+day+of+week+was+8-jul-2016&t=ffab&ia=answer
https://duckduckgo.com/?q=what+day+of+week+was+2016-07-8&t=ffab&ia=answer

**Comment by GuiltyDolphin** [comment]
@mintsoft @jumpball This should be handled in #2810 - assuming you have your language set up correctly then it should detect your locale preferences for parsing the date.

Using `DDG_TEST_LANGUAGE=de duckpan query DayOfWeek` with #2810 then doing `what day of the week was 8.7.2016` I get `Day of the week for: 08 Juli 2016` and `Freitag`.

**Comment by mintsoft** [comment]
Good point @GuiltyDolphin I forgot about that!
