### ISSUE TITLE
Chess Cheat Sheet: 

### ISSUE THREAD

**Issue by DPAUTHe** [duckduckgo/zeroclickinfo-goodies#3442]
The chess cheat sheet is really useful for someone who does not how to play chess, but I believe that it would become even more useful if you put a chess emoji next to the pieces. ex. Knight -♘. With the chess emojis the user will be able to understand to what piece you are reffering to. Here is a useful source to add emojis https://www.emojibase.com/emojilist/chess
------
IA Page:  http://duck.co/ia/view/chess_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @samskeller

**Comment by samskeller** [comment]
@DPAUTHe cool idea! I'll get started on it
