### ISSUE TITLE
UnixTime: Time does not update

### ISSUE THREAD

**Issue by rushsteve1** [duckduckgo/zeroclickinfo-goodies#3446]
The time does not update on the page, and requires a refresh to do so.
This can lead to the page displaying a completely inaccurate time.

---

IA Page:  http://duck.co/ia/view/unix_time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @codejoust

**Comment by zekiel** [comment]
@rushsteve1 it sounds like the unixtime answer should be rendered as a live counter, if I'm reading your issue/suggestion correctly. 

If someone were to tackle this, you might be able to leverage some of the timer IAs front-end: https://duck.co/ia/view/timer 

Looking forward to codejoust's thoughts as well.

**Comment by rushsteve1** [comment]
Yes that is what I meant. It seems a bit pointless that a clock does not update without reloading.

**Comment by mintsoft** [comment]
@rushsteve1 Something you may have missed here, is that the IA can take in a unix time: https://duckduckgo.com/?q=1469160580+unixtime&t=ffab&ia=answer it's not just for seeing the current time in seconds since the epoch

**Comment by rushsteve1** [comment]
Regardless of its extra features such as this, all I'm saying is that a clock that you have to reload the page to have update is problematic, as it only shows the correct time at the instant the page loads. By the time someone gets the chance to actually look at it, the actual time is different from the one displayed.

**Comment by GuiltyDolphin** [comment]
@rushsteve1 I don't think this leads to it displaying an incorrect time - it shows the exact times it is considering in the list fields.

Could you give an example of when it actually displays an *incorrect* result?

**Comment by rushsteve1** [comment]
@GuiltyDolphin Many of us, myself included, leave a browser window open while we are programming for various reasons.
If you knew that you were going to need to know the UNIX time, to say compare with a running timestamp to determine if it was synced correctly, then if you open IA first then it would always be behind the running timestamp, even if you reloaded the page.
This could lead some to believe that their time was incorrect, though most would just go look for another UNIX time utility.

The real issue isn't that the IA shows only the moment the page loaded by default, its that it os incapable of showing a running time at all.

**Comment by zekiel** [comment]
There's a bunch of good feedback in here that would probably be useful in a variety of current/future Instant Answer scenarios. 

This particular issue seems correctly stated and labeled as an "Improvement" but I've also added "Suggestion" because there's no real issue or bug with the IA. It's assumed that most people read the output as the time of their query execution, not the moment in time they look at it. Similar to weather, it doesn't update in real-time but _could_.

**Comment by rushsteve1** [comment]
A proposed solution:
Add a toggle button that gets the new current time and causes the clocks (UNIX, UTC, and Local) to start updating in real time while the button is pressed and stopping again when depressed.
At the moment I don't know enough about IA to do this myself, but maybe I'll do some reading and submit a PR.
If anyone else more more familiar would like to take this on, feel free.

**Comment by ishan1604** [comment]
@rushsteve1 If you have not started working on this, I'd like to take this up.
@zekiel Thoughts ? 
Thanks

**Comment by rushsteve1** [comment]
@ishan1604 Nope I haven't started (got dragged away for various reasons)
It's all yours, have fun.

**Comment by zekiel** [comment]
@ishan1604  I've invited you to the Contributors' Team: https://github.com/orgs/duckduckgo/teams/duckduckhack-contributors  If you accept the invite, I can assign you to this issue.

**Comment by ishan1604** [comment]
@zekiel Thanks for the invite, you can now assign me the issue ☺️

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
