### ISSUE TITLE
Calculator:  -A + B not works

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/zeroclickinfo-goodies#3450]
Expr. [`-2 + 2 =`](https://duckduckgo.com/?q=-2+%2B+2+=) isn't works because starts with `-`.

---

IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by edgesince84** [comment]
good find, @fzzr!

**Comment by Fzzr** [comment]
@edgesince84 you probably meant "good find, @fzzr-!" Don't worry about it, we have this happen a lot ^_^'

**Comment by edgesince84** [comment]
😆 - sorry for the noise @fzzr!

**Comment by GuiltyDolphin** [comment]
@fzzr- @edgesince84 This is working in the new version: https://beta.duckduckgo.com/?q=-2+%2B+2&ia=answer

**Comment by moollaza** [comment]
This has been addressed.

https://duckduckgo.com/?q=-2+%2B+2+%3D&ia=answer
