### ISSUE TITLE
President of the United States (POTUS): Add support for specific dates

### ISSUE THREAD

**Issue by mrshu** [duckduckgo/zeroclickinfo-goodies#3452]
It seems that this IA returns a wrong answer for [this query](https://duckduckgo.com/?q=president+of+the+united+states+of+america+in+1863).

```
president of the united states of america in 1863
```

I am not exactly sure what the answer ought to be, but `Barack Obama` seems to be incorrect.

---

IA Page:  http://duck.co/ia/view/potus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @numbertheory

**Comment by kriman** [comment]
the problem is that this IA does not support this format. if you look at the IA's page you can see it says the correct query is  _"who was the 16th president of the united states"_ or _"potus 16"_.
but if no one's working on it i can take a look at it

**Comment by kriman** [comment]
i made a list of presidents [potus_list.txt](https://gist.github.com/kriman/441fd72514c1b2877c521ed6a808e0e6)
and a python file which do the trick [potus.py](https://gist.github.com/kriman/349eacde86009e60bd8afb9af57f1814)
(i know the ddg written in perl but i don't speak perl, someone should write it as perl)
((and i should learn perl))

**Comment by GuiltyDolphin** [comment]
@kriman It should be easy enough to add dates to [the YAML file](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/potus/presidents.yml) - then if a specific year is requested just do a quick search for the president with a start/end date in which the desired date lies.

**Comment by kirkins** [comment]
I just wanted to ping that this can probably be closed. 

I was going to add an issue about POTUS not triggering but it seems this IA was taken offline.

https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4117#issuecomment-296430197
