### ISSUE TITLE
JSON Validator: prettyprint JSON when it's valid

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-goodies#3459]
## Background
The library used for the JSON Validator, [jsonlint](https://github.com/zaach/jsonlint), seems to also allow JSON prettyprinting when it's valid, in addition to outputting useful errors in case it isn't.

## To Do
- Broaden the trigger space (use triggers  like "json prettyprint", "json beautify", etc
- Edit the description to make it clear this IA doesn't just validate JSON, but beautifies it as well
- Either replace the input with its beautified version if it's valid, or show the beautified version next to it

## Forum
See the topic [Improve JSON Lint Goodie](https://forum.duckduckhack.com/t/improve-json-lint-goodie/327/4)

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

---------------------------------------------------
IA Page: https://duck.co/ia/view/json_validator
maintainer: @sahildua2305

**Comment by sahildua2305** [comment]
On it, @MariagraziaAlastra :+1:

**Comment by MariagraziaAlastra** [comment]
Thanks @sahildua2305!
