### ISSUE TITLE
Microsoft Powershell Cheat Sheet: typo 

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3472]
Relaying some feedback from a DuckDuckGo user:

> Typo under switch statements: \n\n"switch -CaseSentitive ('test'){ 'Te*'{1} }"\n\nflag is -CaseSensitive, not -CaseSenstitive.\n   

---

IA Page:  http://duck.co/ia/view/powershell_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @AnthonyNeace

**Comment by thereg0** [comment]
I would like to correct this error

**Comment by AnthonyNeace** [comment]
@thereg0 No concerns here, feel free to go ahead.

Here is the offending line: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/ba2760f03485f32f10de1e85c19b11415cb8528b/share/goodie/cheat_sheets/json/powershell.json#L205

**Comment by pjhampton** [comment]
Hey @thereg0 / @AnthonyNeace - any update here?

**Comment by AnthonyNeace** [comment]
@pjhampton Haven't heard of anything since the last message. If @thereg0 doesn't reply feel free to pass this on to someone looking for some low-hanging fruit, seems well-scoped for a new programmer. If after a while nobody wants it, can take care of it myself.

**Comment by adv16** [comment]
Hi guys,

I am a newbie and wanted to start somewhere, hence I have jumped in and fixed the issue . I have tried my best to go through the guide and follow the standards while committing. Please let me know if I need to update anything else . The PR is #4001 . Thank you. @AnthonyNeace , @pjhampton .
