### ISSUE TITLE
Ruby on Rails 4 Cheat Sheet: 

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3479]
Maybe we should update this to Rails 5 now? Alternatively we can change the trigger to `Rails 4 cheatsheet` instead of `Rails cheatsheet`

---

IA Page:  http://duck.co/ia/view/rails_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Sayanc93

**Comment by tagawa** [comment]
@pjhampton Is Rails 5 sufficiently different to warrant a new cheatsheet, or can the two versions be combined in a single one?

**Comment by pjhampton** [comment]
Sorry @tagawa. I forgot to reply. 

Based on this _basic_ cheatsheet, there is no difference (I think). I think we should take two actions here:

1) Removed the '4' from the title
2) Expand it. What do you think?

cc. @duckduckgo/duckduckhack-contributors

**Comment by kotoshenya** [comment]
[`bin/rails <command>` can run all commands in Rails 5](http://weblog.rubyonrails.org/2015/12/18/Rails-5-0-beta1/#one-rails-command-to-rule-them-all), though all of the old `rake` commands still exist so everything on this cheat sheet should work in a Rails 5 project.

The test runner has also had some `rspec`-like features added, which may be useful to document:

```
$ rails test --help
minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
        --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: rails, pride

Usage: bin/rails test [options] [files or directories]
You can run a single test by appending a line number to a filename:

    bin/rails test test/models/user_test.rb:27

You can run multiple files and directories at the same time:

    bin/rails test test/controllers test/integration/login_test.rb

By default test failures and errors are reported inline during a run.

Rails options:
    -e, --environment ENV            Run tests in the ENV environment
    -b, --backtrace                  Show the complete backtrace
    -d, --defer-output               Output test failures and errors after the test run
    -f, --fail-fast                  Abort test run on first failure or error
    -c, --[no-]color                 Enable color in the output
```

Could we do something like

>     rails test tests/models/user_test.rb:27
> Run a single test by line number *(Rails 5.0 and later)*

for example?

**Comment by tagawa** [comment]
@pjhampton @kotoshenya Having it relevant for both and including a note for Rails 5-only entries sounds good to me!
And I've updated the IA page to be more generic: https://duck.co/ia/view/rails_cheat_sheet
