### ISSUE TITLE
Countdown: "countdown to tomorrow"

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3487]
Should "countdown to tomorrow" be a 24-hour countdown?  It's near noon here, so I was expecting  ~twelve-hour countdown.  I don't know if that's possible, but it's one of the example queries, and it's confusing.

---

IA Page:  http://duck.co/ia/view/countdown 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by sriranganathan** [comment]
If no one is working on this, I'd like to!

**Comment by GuiltyDolphin** [comment]
@edgesince84 I think the new behaviour for the Role deals with this (I believe @mintsoft's preference was for 'tomorrow' to refer to midnight).

**Comment by mintsoft** [comment]
@GuiltyDolphin @edgesince84 That is indeed my preference, following the premise that tomorrow starts at midnight

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
