### ISSUE TITLE
Indian Languages Cheat Sheet: Create Spacing Between States With Multi Part Names?

### ISSUE THREAD

**Issue by kingballer29** [duckduckgo/zeroclickinfo-goodies#3489]
It seems that states with multi part names are treated as one. For example, **Andhra Pradesh** on the cheat sheet is listed as **AndhraPradesh** with no space in between.

------
IA Page:  http://duck.co/ia/view/indian_languages_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sinwar

**Comment by sinwar** [comment]
okk I'll solve the issue @kingballer29

**Comment by sinwar** [comment]
I've made PR for this issue 
Please check out [here](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3490)

**Comment by kingballer29** [comment]
Thanks @sinwar !
