### ISSUE TITLE
Docs: Mention JSON Validator in Cheat Sheets guide

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3491]
We can mention [this](https://duckduckgo.com/?q=json+validator&ia=answer) interactive JSON Validator in cheat sheets guide (docs) to facilitate the new developers working on cheat sheets.

I'll take this up.

/cc @edgesince84 @tagawa 

IA Page
---
https://duck.co/ia/view/json_validator

**Comment by tagawa** [comment]
Good idea - thanks @sahildua2305

**Comment by edgesince84** [comment]
Please do!
