### ISSUE TITLE
Icon Sizes: 

### ISSUE THREAD

**Issue by Nikitaw99** [duckduckgo/zeroclickinfo-goodies#3494]
Icon sizes for various Operating Systems.
Windows: 16x16, 24x24, 32x32, 48x48, 256x256
Mac OS X: 16x16, 32x32, 64x64, 128x128, 256x256, 512x512, 1024x1024
Linux: 16x16, 24x24, 48x48, and 96x96
iOS 6: 29x29, 50x50, 57x57, 58x58, 72x72, 100x100, 114x114, 144x144, 1024x1024
iOS 8: 29x29, 40x40, 58x58, 60x60, 76x76, 80x80, 120x120, 152x152, 180x180, 1024x1024
Android L: 24x24, 48x48, 192x192, 512x512
Windows Phone: 62x62, 99x99, 173x173, 200x200

---

IA Page:  http://duck.co/ia/view/icon_sizes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Nikitaw99

**Comment by pjhampton** [comment]
Looks like this can be closed :+1:
