### ISSUE TITLE
Countdown: Needs to load alarm sound using versioned asset path

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3500]
In production, all paths for `/share` are versioned based on the current repo release number.

For Goodies, we need to manually build the `/share` path by passing the current Goodie Repo version to the JS and construction the path.

An example of grabbing the Perl version number can be seen in the [SolarSystem](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/SolarSystem.pm#L14) Goodie.

We need to use that same approach to ensure the audio asset is successfully loaded.

---

IA Page:  http://duck.co/ia/view/countdown 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by rasikapohankar** [comment]
Thanks @moollaza, this clears my doubt about what the path generated by
`get_asset_path()` means :+1:
I'll make the changes

**Comment by moollaza** [comment]
Unfortunately we don't have support for Goodies yet in out `get_asset_path()` function, but it's on our to-do list!

**Comment by rasikapohankar** [comment]
Should we add to the docs that the number in the generated path is the current repository release number? I'm not sure if anyone else has wondered what the number was, but it wasn't evident to me and I was curious :smile:
