### ISSUE TITLE
url encode/decode "URL percent-encode:"/answer (respectively) getting double html entities encoded

### ISSUE THREAD

**Issue by slinnufra** [duckduckgo/zeroclickinfo-goodies#3502]
https://duckduckgo.com/?q=url+encode+%22instant+answers%22&t=h_&ia=answer

The output looks like:
`URL percent-encode: &quot;instant answers&quot;`
The HTML is:
`URL percent-encode: &amp;quot;instant answers&amp;quot;`
The HTML should be:
`URL percent-encode: &quot;instant answers&quot;`

https://duckduckgo.com/?q=url+decode+%2522instant%2520answers%2522&t=h_&ia=answer

The output looks like:
`&quot;instant answers&quot;`
The HTML is:
`&amp;quot;instant answers&amp;quot;`
The HTML should be:
`&quot;instant answers&quot;`

It's right in the JSON; it seems the script just needs to take the existing encoding into account.

**Comment by GuiltyDolphin** [comment]
@slinnufra This could be something to do with one of our internal result issues - @moollaza what do you think (the encoding issue we had with output from Goodies)?

**Comment by moollaza** [comment]
@GuiltyDolphin yes this is a result of the encoding we're doing -- I'll bring it up again internally.

For now I'm to mark as tolerated because there's no immediate solution that I'm aware of.

**Comment by moollaza** [comment]
We should be able to fix this once https://github.com/duckduckgo/p5-app-duckpan/pull/372 is merged 👍
