### ISSUE TITLE
Youtube Cheat Sheet: 

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3512]
"K" is a better shortcut to pause the video, since a lot of browsers use the space bar to page down.

------
IA Page:  http://duck.co/ia/view/youtube_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @benabrahamson

**Comment by benabrahamson** [comment]
@edgesince84 Thanks for letting me know - I forgot about that! I've now changed it. 👍

**Comment by edgesince84** [comment]
I was going to just respond with "K" but I wanted to say thanks! 😄

**Comment by benabrahamson** [comment]
@edgesince84 Haha! Lol
