### ISSUE TITLE
PHP Cheat Sheet: missing functions

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3515]
Some feedback from a DDG user:

> no often used builtin php functions mentioned here

What else can be added to make this more useful?

------
IA Page:  http://duck.co/ia/view/php_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
Thanks @edgesince84 

I will look into it.
