### ISSUE TITLE
Arch Linux Cheat Sheet: just for pacman package manager?

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3516]
Some feedback from a DDG user:

> these are not arch linux cheat sheet. instead this could be called as the cheat sheet for pacman package manager

Should this cheat sheet + triggers be narrowed specifically for the pacman package manager?

---

IA Page:  http://duck.co/ia/view/arch_linux_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @direwolf424

**Comment by iah** [comment]
@edgesince84 is correct. The cheat applies to all distributions that uses pacman. For example, Manjaro, Antergos.

**Comment by tagawa** [comment]
Thanks for the clarification @iah. Sounds like this cheat sheet's name, filename and ID should be changed to pacman package manager, and then we can add Arch Linux, Manjaro and Antergos as aliases.

**Comment by iah** [comment]
Absolutely @tagawa. Do you want me to fix this or does the maintainer need to?

**Comment by sriranganathan** [comment]
@akanshgulati Can I take this up?
