### ISSUE TITLE
Binary Logic: Increase scope

### ISSUE THREAD

**Issue by kinitrupti** [duckduckgo/zeroclickinfo-goodies#3529]
Support for `true` and `false` and output trigger on symbolic queries as well.

---

IA Page:  http://duck.co/ia/view/binary_logic 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Sloff

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
