### ISSUE TITLE
Microsoft Visual Basic Cheat Sheet Adoption

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3532]
As of **Weekly Update 114: The importance of IA pages** - I'm happy to adopt this cheat sheet.

p

**Comment by tagawa** [comment]
@pjhampton Thanks very much for offering. I've actually just tried to make the change but it turns out the IA page is a duplicate of an existing IA which already has a maintainer. My mistake - I'll get that IA page removed and sorry for the hassle.
