### ISSUE TITLE
Conversions: Can't convert various metric measurements

### ISSUE THREAD

**Issue by Zekario** [duckduckgo/zeroclickinfo-goodies#3534]
I can't convert to or from Hecto-, Deka-, Deci-, and get an instant answer. Also, Mega- gets counted as Milli- (Mega uses M and Milli uses m). There may be more.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@Zekario Thanks for the report; I am aware of these issues I've got an issue raised to tackle them but I'll add this as an explicit thing to my backlog

**Comment by holtjohnson** [comment]
If you don't mind I took the liberty of adding the additional conversions. I didn't add all [16 prefixes](https://en.wikipedia.org/wiki/Metric_prefix), just the ones that seemed reasonable for people to search for. I don't have that much extra time.
I would also note the alias's for decameter (dam & dams) might cause issues being accidentally called when people just search for dam. I don't know how this IA is activated, so I'm probably wrong.

**Comment by mintsoft** [comment]
@holtjohnson Not at all; that's awesome!

**Comment by mintsoft** [comment]
@Zekario More units have been added by @holtjohnson which should help close the gap somewhat!
