### ISSUE TITLE
CSS Colors: Lacking "rebeccapurple" in the list

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#3541]
https://css-tricks.com/rebbeccapurple-663399/

---

IA Pages: https://duck.co/ia/view/css_colors

**Comment by moollaza** [comment]
I believe this would need to be added to the CPAN module that Instant Answer uses to get the colours from?

**Comment by sahildua2305** [comment]
Yes! I agree with @moollaza. We are using `Color::Library` to fetch list of colors.

**Comment by tagawa** [comment]
There's information on how to submit bugs and feature requests for this module here: http://search.cpan.org/~rkrimen/Color-Library/lib/Color/Library.pm

**Comment by sahildua2305** [comment]
On it, @tagawa! Thanks 😄

**Comment by ManrajGrover** [comment]
Leaving `Color::Library` issue which would eventually fix this here for further updates.

https://rt.cpan.org/Public/Bug/Display.html?id=118051
