### ISSUE TITLE
CSS Colors: Remove vertical divider after 'Show more'

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/zeroclickinfo-goodies#3542]
<img width="494" alt="screen shot 2016-08-19 at 9 13 03 am" src="https://cloud.githubusercontent.com/assets/7061920/17816311/72fdefaa-65ed-11e6-8f18-e5e7e142f67e.png">
   

------
IA Page:  http://duck.co/ia/view/css_colors 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
@moollaza Do you have any idea why do we get this vertical bar?

**Comment by joudoman** [comment]
Hi I checked it out and it's due to this. Try removing it.
![image](https://cloud.githubusercontent.com/assets/11301935/18587445/1acae2a2-7bf0-11e6-8980-245ab703384f.png)

**Comment by khanujasunny** [comment]
Fix:
.sep--before:before, .sep--after:after{
    content: none;
}

**Comment by joudoman** [comment]
Noice!

**Comment by sahildua2305** [comment]
Good job @khanujasunny!

However, I am thinking that this is just a temporary solution (hack). There has to be something internal that needs fix, @moollaza your views on this?

**Comment by joudoman** [comment]
Yeah good job not that someone else pointed out before...Just sayin....

**Comment by sahildua2305** [comment]
@joudoman that was to just acknowledge his proposed solution. Sorry for not acknowledging your comment before which was actually original. I'll go ahead and edit my comment. Thanks for the clever find 😄

**Comment by joudoman** [comment]
@sahildua2305  you don't have to I was just being a smart bmbm haha
I don't know how to go back to the list of CSS's .
I can find them really easy if someone can give me the navigation to the list of CSS problems.

**Comment by moollaza** [comment]
We can simply provide a relevant More At link so that developers can visit a website with more related information. Then the divider will serve its purpose 👍

**Comment by amarlearning** [comment]
@moollaza @sahildua2305 i think we should now remove this label **"status: Needs a Developer"**
