### ISSUE TITLE
Conversions: Add digital speeds (Mbit/s to MB/s)

### ISSUE THREAD

**Issue by holtjohnson** [duckduckgo/zeroclickinfo-goodies#3544]
In the USA many internet providers advertise their speeds in megabit per second. This is a deceitful way of advertising, because megabits are eight times smaller than megabytes (which most everything else is measured by). Those in IT often end up having to convert the two for comparison. I'll do the work if you can point the way.

https://en.wikipedia.org/wiki/Data_rate_units#Conversion_table

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@holtjohnson it might be worth doing a separate IA for that all together (a cheatsheet would be an easy to implement option): http://docs.duckduckhack.com/walkthroughs/programming-syntax.html

**Comment by pjhampton** [comment]
Thanks @holtjohnson!
We will continue this here: #3990
