### ISSUE TITLE
Netbeans IDE Cheat Sheet: 

### ISSUE THREAD

**Issue by atilacamurca** [duckduckgo/zeroclickinfo-goodies#3547]
I’d like to maintain this.

I use netbeans almost everyday and use a lot of its shortcuts.

------
IA Page:  http://duck.co/ia/view/netbeans_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gautamkrishnar

**Comment by gautamkrishnar** [comment]
Really sorry for that. i am a maintainer for this ia.... please check out any other orphaned ia...

**Comment by atilacamurca** [comment]
great man, still I will submit a pull request about some great shortcuts, see you soon.
