### ISSUE TITLE
Youtube Cheat Sheet: 

### ISSUE THREAD

**Issue by theniels17** [duckduckgo/zeroclickinfo-goodies#3548]
other usefull hotkeys in youtube are
J  for going back 10s
L  for going forward 10s
M to mute 

------
IA Page:  http://duck.co/ia/view/youtube_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @benabrahamson

**Comment by benabrahamson** [comment]
@theniels17 Thanks for the suggestions. I've created a PR (#3549) with them. :+1:

**Comment by edgesince84** [comment]
fixed with #3549!  thanks
