### ISSUE TITLE
Uppercase: breaks on accented letters

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3551]
This doesn't work for queries such as "uppercase é"

this is what it shows:
<img width="934" alt="screen shot 2016-08-22 at 2 36 13 pm" src="https://cloud.githubusercontent.com/assets/9668802/17866793/e654004a-6875-11e6-9074-fa8160b384f6.png">
   

------
IA Page:  http://duck.co/ia/view/uppercase 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gdrooid

**Comment by GuiltyDolphin** [comment]
@edgesince84 This doesn't appear to happen any more (likely due to the removal of `html_enc`).
