### ISSUE TITLE
Least Common Multiple: 

### ISSUE THREAD

**Issue by sadhanakesavan** [duckduckgo/zeroclickinfo-goodies#3554]
For some reason. The web search doesnt display the least common multiple IA page.
https://duckduckgo.com/?q=lcm+8+4&t=hi&ia=web
------
IA Page:  http://duck.co/ia/view/least_common_multiple 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rpatel3001

**Comment by GuiltyDolphin** [comment]
@sadhanakesavan The IA is currently only in testing (it is on beta though: https://beta.duckduckgo.com/?q=lcm+5+7&ia=answer).

**Comment by sadhanakesavan** [comment]
oh cool !
