### ISSUE TITLE
Help Line: Add links to HelpLine entries

### ISSUE THREAD

**Issue by leesdolphin** [duckduckgo/zeroclickinfo-goodies#3557]
For New Zealand there is just one helpline listed (Lifeline NZ); however there is no way to access their website given it doesn't appear in the search results.

I would like to make one or more of the following changes:
- Make the name link to the organisation's website.
- Add a (i) icon to the name or phone number.
- Display the url underneath each entry.

---

IA Page:  http://duck.co/ia/view/help_line 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @conorfl

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
