### ISSUE TITLE
Help Line: Adding support for multiple means of contact

### ISSUE THREAD

**Issue by leesdolphin** [duckduckgo/zeroclickinfo-goodies#3558]
Can this instant answer add support for text, email and webchat. For example, New Zealand has [YouthLine](https://www.youthline.co.nz/) which has a phone number and a text number. IT also has email and live chat. All of which would be great to provide as an instant answer to someone in need.

I'm guessing that this could be extended to other countries. 

---

IA Page:  http://duck.co/ia/view/help_line 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @conorfl

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
