### ISSUE TITLE
Poker Hands Cheat Sheet: 

### ISSUE THREAD

**Issue by JasonCFisher** [duckduckgo/zeroclickinfo-goodies#3559]
I'd like to make a minor change to the Three of a Kind description to specify that the two remaining cards do not match.

Also, I noticed that there are nearly identical cheat sheets for both "Poker" and "Poker Hands", the only difference being that the Poker Cheat Sheet does not list probabilities.  Would it make sense to combine the two cheat sheets somehow?

Thanks

---

IA Page:  http://duck.co/ia/view/poker_hands_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jee1mr

**Comment by thereg0** [comment]
Id like to work on your suggestion

**Comment by pjhampton** [comment]
It looks like this has gone stale. Closing as a result 👍 

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄
