### ISSUE TITLE
Http Status Codes

### ISSUE THREAD

**Issue by gameFace22** [duckduckgo/zeroclickinfo-goodies#3561]
Hi, 

Is the IA live? 
I have a small suggestion to improve it :)    

For example, searching for an error code could possibly definition of the same in the IA.

------
IA Page:  http://duck.co/ia/view/http_status_codes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @tobyaherbert

**Comment by tobyaherbert** [comment]
Hi gameFace22,

Nope, the IA isn't live.

I'm just testing duckduckhack at the moment and won't be releasing this IA as duckduckgo maintain this one: https://duck.co/ia/view/httpstatus

**Comment by edgesince84** [comment]
I couldn't have said it better, @tobyaherbert!  Thanks.
