### ISSUE TITLE
Remove `html_enc` from Goodies. No longer needed :)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3563]
for fixing bug #3563

**Comment by sahildua2305** [comment]
@moollaza I'll take up last 8 Goodies from the list. Should I push changes to all 8 goodies in one PR?

**Comment by moollaza** [comment]
> Should I push changes to all 8 Goodies in one PR?

That should be OK

**Comment by JSSaini07** [comment]
@moollaza removed html_enc from ABC,ANAGRAM,AVERAGE,BASE64,BITSUM,CHARS

**Comment by ManrajGrover** [comment]
@moollaza Fixed CurrencyIn, EmailValidator, HexToASCII, Lowercase, MacAddress, MagicEightBall, Morse, NoteFrequency, PaleoIngredientCheck, Reverse, Rc4, PigLatin and PhoneAlphabet

**Comment by sahildua2305** [comment]
Fixed MD4, MD5, NameDays, RandomDate and Regexp as well (except last 8 in the list). @moollaza

**Comment by GuiltyDolphin** [comment]
@sahildua2305 What do you need help with?

**Comment by sahildua2305** [comment]
@GuiltyDolphin The use of `html_enc` in these IAs is very complicated and I couldn't understand how it was working. It will be good to have insight of someone who has worked on these or the maintainers themselves.

**Comment by gautamkrishnar** [comment]
Fixed for Sha3.pm
