### ISSUE TITLE
Timezone Converter: CEST to MSK correct, but CEST to default msk is wrong

### ISSUE THREAD

**Issue by aardvark** [duckduckgo/zeroclickinfo-goodies#3573]
I have getting stange interaction with default time zone when i am entering '3pm cest' i am getting:
5:00 PM MSK
Convert Timezone: 3:00 PM CEST (UTC+2) to MSK (UTC+4)

But if i inputing '3pm cest to msk' i am getting correct one: 
4:00 PM MSK
Convert Timezone: 3:00 PM CEST (UTC+2) to MSK (UTC+3)
## This is highly misleading and i think maybe due to some defaults of summer non summer chages in default RU zone. 

IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
