### ISSUE TITLE
Number Sequences: Create Instant Answer

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-goodies#3580]
As disussed with @Hasil-Sharma, this would be an Instant Answer to handle many number-sequence queries.

`Math::NumSeq` provides a common interface through which many number sequences can be accessed (even numbers, prime numbers, happy numbers, to name a few!).

We can use this interface to build a wrapper that can make use of the standard functions (nth, next, predicates etc.) to handle queries for _many_ different number sequences.

In the end, we should end up being able to add new sequences by specifying new elements of a hash, with the name of the sequence, the module, and potentially some other attributes.

---

IA Page:  http://duck.co/ia/view/number_sequences 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by Hasil-Sharma** [comment]
I'm starting with tackling prime numbers, problems like "Is 5 a prime number?" "5th prime number" etc.

**Comment by Hasil-Sharma** [comment]
So you are asking me to think something along the lines of "nth number of type m" ?

**Comment by GuiltyDolphin** [comment]
@Hasil-Sharma Yeah, think more `Nth X number` - as there will be parts of the queries that will need to be auto-generated, not hard-coded.

**Comment by pjhampton** [comment]
Hey @GuiltyDolphin 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
