### ISSUE TITLE
Password: Minimum password generated should be at least 9 characters

### ISSUE THREAD

**Issue by atoponce** [duckduckgo/zeroclickinfo-goodies#3589]
A modest password cracking machine with 6x Nvidia GeForce GTX 970 GPUs can crack an unsalted SHA-1 digest built from every possible 8-character password in the 95 printable characters on the keyboard (includes the space) in 1 week. However, this also means that a 9-character password in that same space would take 95 weeks, or just shy of 2 years on the same hardware.

As such, the minimum length generated should be 9 characters, assuming the threat model is leaked hashed password databases protected with fast generic hashing functions such as MD5 or SHA-1.

---

IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by akanshgulati** [comment]
@cngarrison, I think we should improve this password generator something like this : http://passwordsgenerator.net/

**Comment by cngarrison** [comment]
On 2 Nov 2016, at 5:40, Akansh Gulati wrote:

> @cngarrison , I think we should improve this password generator 
> something like this :   http://passwordsgenerator.net/

Do you have ideas for how the search query would be formed to indicate 
which options should be included when generating a password?

Since IA’s don’t use an html form (with checkboxes), the options 
would need to be part of the query. I’ll consider some different ways 
to structure queries to support different options.

Thanks for your suggestion.

Charlie

-- 

     Charlie Garrison                   <charlie@garrison.com.au>
     Garrison Computer Services      <http://www.garrison.com.au>
     PO Box 380
     Tumbarumba NSW 2653  Australia

[Conundrum](http://www.ietf.org/rfc/rfc1855.txt)

**Comment by atoponce** [comment]
I've also created my own password generator. In production, it can be found at https://ae7.st/g/. Source code at https://github.com/atoponce/webpassgen (there is also a nodejs version at https://github.com/atoponce/nodepassgen). If it's helpful.

**Comment by riqpe** [comment]
@cngarrison, as I see it, the options could be preceded with plus or minus symbols (e.g. pw 50 +symbols -similar -ambiguous) unless there is a technical reason preventing this. I'm not sure if DDG is pre parsing those symbols or passing them directly to appropriate IAs.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
