### ISSUE TITLE
Roman Numerals: Add Trigers

### ISSUE THREAD

**Issue by DPAUTH** [duckduckgo/zeroclickinfo-goodies#3592]
When I search "15 to roman numerals" or "xv to arabic numerals" the IA does not work and it's pretty frustrating.

------
IA Page:  http://duck.co/ia/view/roman 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hchienjo

**Comment by hchienjo** [comment]
@DPAUTH Working on a fix asap.
