### ISSUE TITLE
JSON Syntax Cheat Sheet: "typo" feedback from user

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-goodies#3595]
> There's a typo on the first object "Doe," should be "Doe", .\nAlso, obj[0] will return undefined (at least on Firefox)

---

IA Page:  http://duck.co/ia/view/json_syntax_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vCillusion

**Comment by ManrajGrover** [comment]
I can take this one up. Also, can confirm obj[0] will return undefined.
