### ISSUE TITLE
Bond enthalpy cheat sheet or fathead

### ISSUE THREAD

**Issue by AlterationBrick** [duckduckgo/zeroclickinfo-goodies#3598]
A quick way to access bond enthalpy/bond disassociation energy from DuckDuckGo would be helpful for chemistry students like me. There are a limited number of common ones, as can be seen in this pdf: http://www4.ncsu.edu/~shultz/Common_Bond_enthalpies.pdf

A fathead that returned results for "bond enthalpy o=o c-o h-h" would be ideal, so one doesn't have to go hunting through the whole list.

I miss the days of wolfram|alpha integration...

**Comment by gautamkrishnar** [comment]
:+1: yes this one looks cool

**Comment by ahetawal-p** [comment]
So what exactly is the ask here, the Fathead should just return the parsed value from the pdf (or any other source) mentioned for each bond Or  it should calculate the final bond enthalpy for a given equation ?

**Comment by AlterationBrick** [comment]
@ahetawal-p It would be much easier and less error-prone to return the value for each bond, rather than trying to calculate the number and type of bonds in a chemical equation, if that's what you're asking. That would be adequate functionality.

I've also realized that some bonds are triple bonds, which would have to be represented some other way in queries, maybe "---" as in 3 dashes... if someone has a better solution I'm all ears.

**Comment by ahetawal-p** [comment]
Thanks @AlterationBrick yes makes much more sense now. For 3 dashes I think that's a good compromise for the lookups.
Also in terms of the source of these enthalpies do have any other source links or the above PDF is the only one ? This will be a pretty small fathead !

**Comment by gautamkrishnar** [comment]
@ahetawal-p Please mention me if you are ready to take this one so that i can assign this to you....

**Comment by ahetawal-p** [comment]
@gautamkrishnar I would love to, However just need to get all the correct requirements before I commit to. I guess I have these 2 open questions :

1.  In terms of the source of these enthalpies do we have any other source links or the above PDF is the only one ?
2. For the query part, will the query correspond to a single bond enthalpy like ex: "bond enthalpy C=0" or multiple bonds in the same query like "bond enthaply C=O O=H"?

**Comment by gautamkrishnar** [comment]
@tagawa please add @ahetawal-p to the organization and assign him to the PR

**Comment by tagawa** [comment]
Thanks @gautamkrishnar and @ahetawal-p - done.

**Comment by ahetawal-p** [comment]
@AlterationBrick any ideas for my questions above ?

**Comment by AlterationBrick** [comment]
@ahetawal-p It would be good to have multiple bonds in the same query, and more sources can be found at http://www.kentchemistry.com/links/Kinetics/BondEnergy.htm and http://cxp.cengage.com/contentservice/assets/owms01h/references/chemtables/gen_chem/bond.html

**Comment by ahetawal-p** [comment]
So i am assuming if we have multiple bonds the IA will contain the total enthalpy (sum of all) of the all bonds mentioned? If yes, this seems to be more leaning towards a goodie than a Fathead.

**Comment by AlterationBrick** [comment]
Yes, well the two ways I could see it working would be

1. it just returns each queried bond and its enthalpy in a table or similar construct, or
2. it sums up the enthalpies, taking the number to the left of each bond type to mean the number of that bond to compute (for example, `50 c=o + 24 o---o` for 50 c=o bonds and 24 o---o bonds)

**Comment by pjhampton** [comment]
Hey @AlterationBrick 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
