### ISSUE TITLE
SecurityAddons: Remove vertical divider after 'Show more'

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3604]
![selection_165](https://cloud.githubusercontent.com/assets/5206277/18257439/e0047586-73c3-11e6-8e99-7d64ad56ce92.png)

Looks like this is a common problem with `list` type Goodies.

------ 

IA Page:  https://duck.co/ia/view/security_addons

**Comment by moollaza** [comment]
This is a known (low priority) internal bug. It will be fixed internally.
