### ISSUE TITLE
HTMLEntitiesEncode: 

### ISSUE THREAD

**Issue by Targren** [duckduckgo/zeroclickinfo-goodies#3607]
As of 2 minutes before posting this, the HTMLEntitiesEncode function is apparently replacing the entity output rather than displaying it raw. 

Example query: "Trademark entity" 

Expected Result:  &amp;#8482; (™)

Received result: ™ (™)

Tested on the latest versions of Chrome and Palemoon 

------
IA Page:  http://duck.co/ia/view/htmlentities_encode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nishanths

**Comment by nishanths** [comment]
might be related to https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3601?

**Comment by GuiltyDolphin** [comment]
@nishanths Yes - thank you for noticing that.

We should employ the use of `HTML::Entities` (or similar) for the encoding.

**Comment by gautamkrishnar** [comment]
:smile:  Stated working on it
