### ISSUE TITLE
Unicode should be replaced by images instead.

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#361]
Some of the unicode characters (such as emoji) don't display well on browsers such as Google Chrome.

![screen shot 2014-03-14 at 6 28 34 pm](https://f.cloud.github.com/assets/81969/2426583/411474e6-abc8-11e3-8564-f1297d04bb33.png)

It's worth noting that websites like http://www.emoji-cheat-sheet.com/ and Github use images for their emoji.

-----
IA Page: https://duck.co/ia/view/unicode_fuzzy_search

**Comment by zekiel** [comment]
seems irrelephant right now. IA isn't triggering and the site has been majorly updated since this issue was filed. Closing but reopen if it persists after the IA comes back
