### ISSUE TITLE
Conversions: Consider intelligent defaults when only a source unit is provided

### ISSUE THREAD

**Issue by mcomella** [duckduckgo/zeroclickinfo-goodies#3610]
On OS X, spotlight will give you intelligent defaults for unit conversion when only a source unit is provided. For example, typing "68km" will print "42.25 miles" and provide a drop-down with the equivalent meters, yards, feet & inches, and inches (see the attached screenshot).

![screen shot 2016-09-10 at 12 32 54](https://cloud.githubusercontent.com/assets/759372/18413060/c4e4fca2-7752-11e6-8e1d-5fe0b31d7da6.png)

It'd be great to provide a similar system. It's particularly useful on mobile since you can type less.

---

IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@mcomella sounds like a good idea; we're planning a new UI with interactive features which would probably include something similiar by default

**Comment by pjhampton** [comment]
Looks like this has been solved.
