### ISSUE TITLE
Physics/Chemistry formula goodie

### ISSUE THREAD

**Issue by AlterationBrick** [duckduckgo/zeroclickinfo-goodies#3632]
Suggestion: Inspired by the "area of a circle" and "volume of a sphere" instant answers, it would be nice to expand these to popular formulae in physics and chemistry. Some I was looking for recently have been:
- "boyle's law"
- "combined gas law"
- the rest of the gas laws (ideal gas law, etc)

Perhaps this already exists, but then the triggering isn't picking up my queries.
As a student taking both an advanced physics and an advanced chem course, this would save me many seconds.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
