### ISSUE TITLE
Nepali Cheat Sheet: 

### ISSUE THREAD

**Issue by surit** [duckduckgo/zeroclickinfo-goodies#3637]
------
IA Page:  http://duck.co/ia/view/nepali_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @surit

**Comment by surit** [comment]
Hi I want to create a Nepali cheat sheet. I dont know if it is the right way to do so. Please help me and forgive me for any wrong doings.

**Comment by gautamkrishnar** [comment]
@surit  it is not possible to accept cheatsheet on places. Please pick up some  another topic

**Comment by akanshgulati** [comment]
@surit We are right now focussing on Programming related CheatSheets. You can look at this for more information on contribution. 
https://forum.duckduckhack.com/t/how-to-contribute-to-the-programming-mission/881
