### ISSUE TITLE
JSON Validator: Improve title/subtitle to clarify usage

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3643]
Moving here from https://github.com/duckduckgo/zeroclickinfo-fathead/issues/390

It's indeed confusing for users when they see the name JSON Validator while they were trying to search for `prettyprint json`.

I'd propose setting `title` according to the query. Is it's all about `json validation`, we can show `JSON Validator` otherwise `JSON Beautifier`.

\cc @moollaza @MariagraziaAlastra 

---
IA Page: https://duck.co/ia/view/json_validator

**Comment by moollaza** [comment]
@sahildua2305 I suggest we just change the title of the output to something like:

**JSON Beautifier & Validator**

The subtitle should explain that you an use the IA to format JSON and also check for syntax errors

**Comment by sahildua2305** [comment]
I will make the suggested changes @moollaza 👍
