### ISSUE TITLE
should also trigger when someone search ".htaccess Cheat Sheet" .htaccess Cheat Sheet: 

### ISSUE THREAD

**Issue by amarlearning** [duckduckgo/zeroclickinfo-goodies#3646]
.htaccess cheat sheet is awesome!
But the only thing that should be changed or modified is "when should this cheat sheet trigger"

According to me, the cheat sheet should also trigger when some searches ".httaccess cheat sheet"
because many users might search with that DOT "."

Let me know what you think!

------
IA Page:  http://duck.co/ia/view/htaccess_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
Makes sense! Should be an easy fix. Would you like to add another entry `.htaccess` in `aliases` for that? @amarlearning

**Comment by amarlearning** [comment]
@sahildua2305  ok.
