### ISSUE TITLE
Calculator: Improvement

### ISSUE THREAD

**Issue by amarlearning** [duckduckgo/zeroclickinfo-goodies#3657]
calculator is awesome!
But one thing that we can do is, instead of displaying a result. there should be an actual calculator where we can run another mathematical expression as well.

let me know what you think!

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
See https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2848
