### ISSUE TITLE
JIRA Bug Tracker: Detect and exclude queries relating to Kenwood radios (model number TS-_____)

### ISSUE THREAD

**Issue by zekesonxx** [duckduckgo/zeroclickinfo-goodies#3673]
[Kenwood](https://en.wikipedia.org/wiki/Kenwood_Corporation) is a Japanese company that makes, among other things, [amateur radio transceivers](https://en.wikipedia.org/wiki/Kenwood_Corporation#Amateur_radio_transceivers). Kenwood's HF transceivers have model numbers that start with `TS-`, which also matches the issue format for Apache Traffic Server JIRA issues.

And this is kinda getting annoying. Even just excluding queries with the word "kenwood" or "radio" would work.

Examples:
- [`kenwood ts-440s`](https://duckduckgo.com/?q=kenwood+ts-440s&ia=answer) (a radio I own and search for things relating to a lot)
- [`ts-590 troubleshooting`](https://duckduckgo.com/?q=ts-590+troubleshooting&ia=answer)
- [`cheap kenwood ts-520`](https://duckduckgo.com/?q=cheap+kenwood+ts-520s&ia=answer)
- [`kenwood ts-2000 release date`](https://duckduckgo.com/?q=kenwood+ts-2000+release+date&ia=answer)

---

IA Page:  http://duck.co/ia/view/jira 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @arroway

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
