### ISSUE TITLE
Convert Latitude/Longitude: support for more output formats

### ISSUE THREAD

**Issue by ns130291** [duckduckgo/zeroclickinfo-goodies#3678]
I think there should be more output formats when using the lat-long converter. For example the satnav in my car expects the location in degrees, minutes and seconds, and the seconds additionally have a decimal place:
![satnav](https://cloud.githubusercontent.com/assets/1678202/19243165/bef15d28-8f16-11e6-9a20-dee65dd71ef6.jpg)
So if I enter [52.167556° -12.132545° as dms](https://duckduckgo.com/?q=52.167556%C2%B0+12.132545%C2%B0+W+as+dms&t=ffsb&ia=answer) I get `52° 10′ 3″, -12° 7′ 57″` as an answer, so it's missing the decimal place and I don't know whether the `-` sign stands for east or west. So an optimal answer for me would be an additional line with something like `52° 10′ 3.2" N, 12° 7′ 57.16" W` as the coordinates.

---

IA Page:  http://duck.co/ia/view/convert_lat_lon 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @wilkox

**Comment by pjhampton** [comment]
Hey all 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
