### ISSUE TITLE
Calendar: Should take short hand queries and target year

### ISSUE THREAD

**Issue by pavkum** [duckduckgo/zeroclickinfo-goodies#3682]
I have noticed instant answer pops up only for specific queries.

I tried 
- feb calendar - No IA
- February calendar 2017 - No IA
- february calendar - IA

IA should accommodate all these use cases since it is generally expected for people to use short hands for month names and also expect target year.  

---

IA Page:  http://duck.co/ia/view/calendar_today 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by GuiltyDolphin** [comment]
I believe this is just an issue with where the trigger words are, for example [calendar for februray 2017](https://duckduckgo.com/?q=calendar+for+february+2017&ia=answer) *does* trigger this IA, so in the case of `februray calendar 2017` we should probably be looking at the remainder `february 2017`.

**Comment by AlterationBrick** [comment]
I can give this a shot, if it's not being worked on yet.  `feb calendar` _does_ work on my end; I don't know if that was just recently fixed.

**Comment by pavkum** [comment]
Well `feb calendar` worked for me too. May be search got cached or updated its relevancy. But try 
`feb calendar <random_year>` I tried for 2013. It didn't work.

But the exact search string `calendar for <month> <year>` always works

**Comment by mintsoft** [comment]
@AlterationBrick @pavkum This should be handled by the dates role so I believe it will essentially take a reasonably flexible input; although you can't separate the triggering "calendar" from the date; they need to be either $date calendar or calendar $date where $date is "feb" or "feb 2013" or whatever

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
