### ISSUE TITLE
Password: Denial of Service Vector?

### ISSUE THREAD

**Issue by allonhadaya** [duckduckgo/zeroclickinfo-goodies#3686]
Does calling pwgen consume bytes from the entropy pool? If it does, an attacker could very easily hit `https://duckduckgo.com/?q=pwgen` really fast to drain the pool. Could this pose a denial of service risk if the server must wait for the entropy pool to replenish for certain actions?

------
IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by tagawa** [comment]
Hi @allonhadaya. Thanks for raising this. I'm not sure but have forwarded it to the ops team to take a look at and assess the risk.

**Comment by mintsoft** [comment]
@allonhadaya @tagawa I don't believe that srand uses the system entropy as it's not a cryptographically secure random generator; this isn't true for `Crypt::Random` which does use `/dev/random`

**Comment by tagawa** [comment]
Thanks @mintsoft. I've checked with our ops folks and it does seem this is not a concern.
@allonhadaya Thank you again for raising the issue to make sure.

**Comment by allonhadaya** [comment]
@mintsoft @tagawa Excellent, my pleasure. Thanks for sharing your findings with us!
