### ISSUE TITLE
Feature request: Latex cheat sheet

### ISSUE THREAD

**Issue by QVaucher** [duckduckgo/zeroclickinfo-goodies#3691]
I've just noticed that they're no cheat sheet for Latex! Could be useful...

**Comment by gautamkrishnar** [comment]
Looking good... @duckduckgo/duckduckhack-contributors please check this out

**Comment by gautamkrishnar** [comment]
There's already a goodie on this one https://duck.co/ia/view/latex

**Comment by QVaucher** [comment]
Yep I saw the goodie too, but I think the cheat sheet could be helpful when we just forget the name of a common markup!

**Comment by nalinbhardwaj** [comment]
Is anyone working on this?

If not, should I take it up?

**Comment by vikashvverma** [comment]
@nalinbhardwaj Go ahead man, claim it

**Comment by nalinbhardwaj** [comment]
Small question, there is no way to use Latex in the cheat sheets themselves right? I thought it would be a good idea to show the symbols as well.

**Comment by vikashvverma** [comment]
I think something like this would be good: https://wch.github.io/latexsheet/
