### ISSUE TITLE
Improvement in Docker Cheat Sheet

### ISSUE THREAD

**Issue by shubh1m** [duckduckgo/zeroclickinfo-goodies#3694]
Currently Docker cheat sheet uses information from unofficial resources, also it lacks some information. Idea is to use information from the official site itself.  

Official command line reference: [Docker docs](https://docs.docker.com/engine/reference/commandline/)
IA Page: https://duck.co/ia/view/docker_cheat_sheet 

cc @moollaza, @GuiltyDolphin

**Comment by sahildua2305** [comment]
@shubh1m can you please use the default issue template and mention the IA page link for Docker Cheat Sheet so that this issue can be linked to the actual existing IA?

**Comment by prabhakar267** [comment]
If no one is working on this, I'd like to!

**Comment by sahildua2305** [comment]
Thanks for your interest, @prabhakar267. It's all yours. Looking forward to your PR. :+1:
