### ISSUE TITLE
FedEx Smartpost Tracking numbers should link to FedEx not USPS

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#370]
For example 9261292701027635365840 (https://duckduckgo.com/?q=9261292701027635365840). I think there is some confusion since SmartPost is a collaboration between FedEx and USPS.

-----
IA Page: https://duck.co/ia/view/usps, https://duck.co/ia/view/fed_ex

**Comment by crazedpsyc** [comment]
Here's an example of the opposite issue: https://duckduckgo.com/?q=9361289877724123423129
This is a USPS tracking number, but it's recognized as FedEx.

Should the goodies just be combined, so that both options are available? e.g. "Track this shipment at FedEx or USPS."

**Comment by mintsoft** [comment]
thanks @crazedpsyc .Maybe it's worth combining them, I think when I looked through the docs, it should be possible to always tell one from other as long as the checksum is checked.

**Comment by moollaza** [comment]
There was an in progress PR which was attempting to combine all the package tracking IAs now that we have a new design. I believe that PR has been abandoned now though, I will try check in on it...

**Comment by javathunderman** [comment]
Related: #1621

**Comment by sumsted** [comment]
In my experience smarpost can be tracked by both USPS and FDX. The availability of scans varies between their services. For smartpost use the USPS mod test and check for 92 on the frontend.
I can help with the logic to distinguish between USPS, UPS, FedEx and their various services but would need some help in navigating this project.

**Comment by zekiel** [comment]
closing per https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2845
