### ISSUE TITLE
duckpan server command is not working on codio.

### ISSUE THREAD

**Issue by raj-maurya** [duckduckgo/zeroclickinfo-goodies#3702]
Hi,

I am trying to test my cheatsheet on codio by running "duckpan server" command on terminal but it is not running.

Please help!

**Comment by sahildua2305** [comment]
Hi @raj-maurya can you please post the error message you get?

**Comment by raj-maurya** [comment]
@sahildua2305 

It says:

-bash: duckpan: command not found

**Comment by gautamkrishnar** [comment]
I think you hadn't cloned the box correctly.  Please delete your current project and close the box in codio as per as the instructions given in the www.docs.duckduckhack.com...

**Comment by raj-maurya** [comment]
@gautamkrishnar 

I had selected the "Box & Project" clone option during the FORK. I had followed the documentation. 

I have tried to restart and reset the box but, duckpan commands are still not working .
ScreenShot:
![screenshot from 2016-10-17 00 00 41](https://cloud.githubusercontent.com/assets/9070249/19427549/4b0dd91c-9462-11e6-80f7-36782f6963f9.png)

**Comment by gautamkrishnar** [comment]
@moollaza @guythedolphin any idea why this is happening?

**Comment by GuiltyDolphin** [comment]
@gautamkrishnar Sorry, I don't really use the Codio env. There was some discussion about DuckPAN not working on Codio in Slack a bit back though.

**Comment by moollaza** [comment]
I spoke with @raj-maurya -- his Codio project is from the old (now deprecated Codio box). Last week I upgraded the box, but unfortunately those changes cannot be applied to all the users who've previously cloned the Codio box.

Everyone will need to re-fork the Codio box by January when the old box architecture goes offline.

@raj-maurya please confirm a new clone of the duckduckhack project solves your problems 👍

**Comment by mintsoft** [comment]
@moollaza @tagawa can we announce that (on slack or something) ?

**Comment by akanshgulati** [comment]
@raj-maurya Please find the steps here : https://forum.duckduckhack.com/t/how-to-migrate-to-new-ddg-box-on-codio/1023
If the commands are working now, please close the issue.

**Comment by raj-maurya** [comment]
@moollaza @sahildua2305 @akanshgulati @gautamkrishnar 

Thanks for the help! Every thing working fine. 
Hence closing this issue.
