### ISSUE TITLE
NumpyCheatSheet Bug: Source URL needs to point to the official documentation

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3703]
## Type of Issue

- [X] Bug (incorrect behavior)
    - [ ] Triggering
    - [ ] Relevancy
    - [ ] Internal (issue with code)
- [ ] Feature Request
    - [ ] Triggers (new triggers)
    - [ ] Design Change

## Description

The `More at` link should go to some official documentation. Currently, it points to a `non-official` website where exactly same amount of information is available, hence serves absolutely no purpose.

## Steps to recreate

https://beta.duckduckgo.com/?q=numpy+cheat+sheet&ia=cheatsheet

## People to notify

@amarlearning 

---

Instant Answer Page: https://duck.co/ia/view/numpy_cheat_sheet

**Comment by amarlearning** [comment]
Yeah! that's right @sahildua2305. that would be an easy fix. would you like to do it or should I do ?

**Comment by sahildua2305** [comment]
I'll push in a couple of hours. 👍

**Comment by sahildua2305** [comment]
@amarlearning as a moderator of this cheat sheet, which documentation link would you like to have in this cheat sheet for reference?

**Comment by amarlearning** [comment]
@sahildua2305 https://docs.scipy.org/doc/numpy/reference/
