### ISSUE TITLE
Suggestion: MLA format goodie

### ISSUE THREAD

**Issue by AlterationBrick** [duckduckgo/zeroclickinfo-goodies#3706]
## Type of Issue

- [ ] Bug (incorrect behavior)
  - [ ] Triggering
  - [ ] Relevancy
  - [ ] Internal (issue with code)
- [x] Feature Request
  - [ ] Triggers (new triggers)
  - [x] Design Change
## Description

Return the correct MLA (or APA, or Chicago) Works Cited format for a certain medium, with placeholder text.

Example query: "mla cite website"

Example answer: 

Lastname, Firstname. "Title." _Website title._ Publisher, date published. Web. Date accessed.

10/10 would use if it existed!
## People to notify

---

Instant Answer Page: https://duck.co/ia/view/citation_formatting_goodie

**Comment by amarlearning** [comment]
@AlterationBrick Please update your issue with correct **Instant Answer Page** url!

**Comment by AlterationBrick** [comment]
@amarlearning Thanks, I made one just now and updated the issue accordingly.

**Comment by pjhampton** [comment]
Thanks guys. We don't need issues for cheat sheets. Feel free to send unsolicited Pull Requests though 👍  😄
