### ISSUE TITLE
Suggestion: Add JSON Lint to Travis for new cheat sheets

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3708]
## Type of Issue

- [ ] Bug (incorrect behavior)
  - [ ] Triggering
  - [ ] Relevancy
  - [ ] Internal (issue with code)
- [X] Feature Request
  - [ ] Triggers (new triggers)
  - [ ] Design Change
## Description

Since we have a lot of new cheat sheets coming up daily, it's going to be hard to maintain proper json formatting (indentations, spaces etc). I suggest that we should add some sort of json linter to travis integration tests to make sure every new cheat sheet uses proper json formatting. If lint tests fail, we can easily point contributors to [this link](https://duckduckgo.com/?q=json+formatter&t=h_&ia=answer).

## People to notify

@duckduckgo/community-leaders

**Comment by gautamkrishnar** [comment]
Looking great :+1.

**Comment by sriranganathan** [comment]
If no one is working on this, I would like to.

**Comment by ManrajGrover** [comment]
@sriranganathan Go ahead! 😄

**Comment by sahildua2305** [comment]
@sriranganathan Good to see that you're interested in working on this. However, before you get into this, can you please share how you're going to approach this, so that we can have a discussion about the solution you propose?

**Comment by sriranganathan** [comment]
@sahildua2305 I was thinking of writing another test file which will check all the json files for proper formatting. For each file the we can load the json and prettify it and check it against the contents of that file. For prettifying the json we can use the pretty function of the JSON module(http://search.cpan.org/~makamaka/JSON-2.90/lib/JSON.pm#pretty).

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
