### ISSUE TITLE
Suggestion: Add a "Hello World!" example for programming cheat sheets

### ISSUE THREAD

**Issue by napnac** [duckduckgo/zeroclickinfo-goodies#3710]
## Type of Issue
- [ ] Bug (incorrect behavior)
  - [ ] Triggering
  - [ ] Relevancy
  - [ ] Internal (issue with code)
- [X] Feature Request
  - [ ] Triggers (new triggers)
  - [ ] Design Change
## Description

Why don't we add an example for each programming languages to display the famous "Hello world!" as part of the cheat sheet ? This will be a small and concrete example that could be useful for a beginner to visualize more easily the syntax.

**Comment by stanly-johnson** [comment]
Good idea. Maybe implement a new cheat sheet for programming languages.

**Comment by pjhampton** [comment]
There is actually a really kick-ass Fathead for this. Checkout [Hello World Examples](https://duck.co/ia/view/hello_world). With this, I don't really see the point of a cheat sheet
