### ISSUE TITLE
JavaScript: Create New JS Lint Goodie

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-goodies#3720]
### Description

Use [JSHint](https://cdnjs.com/libraries/jshint) Library to build an interactive JS linter; it also has quite interesting error explanations; try it out online [here](http://jshint.com/).
### Forum

See the topic [Create IA : JS Lint](https://forum.duckduckhack.com/t/create-ia-jslint/177)
## People to notify

@mbad0la 
@moollaza 

---

Instant Answer Page: _to be created by developer_

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

**Comment by akanshgulati** [comment]
@bfmags I would like to take this up.

**Comment by mbad0la** [comment]
Hey @akanshgulati

As you can see I was assigned this, so I was hoping to get to do it. 

Although, if you're intending to finish it up in a week or two, I'd be happy to let you do this as I'm in between my semester exams this month.

**Comment by akanshgulati** [comment]
@mbad0la Hi. It's all yours brother. Take your time and let us know in case you stuck anywhere. :) All the best for exams.

**Comment by pjhampton** [comment]
Hey @bfmags 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
