### ISSUE TITLE
Libre Office Writer Cheat Sheet: 

### ISSUE THREAD

**Issue by ambrish61** [duckduckgo/zeroclickinfo-goodies#3727]
-----
![screenshot 22](https://cloud.githubusercontent.com/assets/13643308/19956678/5132bb90-a1b5-11e6-9e5a-32e43251b2a7.png)
![screenshot 23](https://cloud.githubusercontent.com/assets/13643308/19956679/513a3636-a1b5-11e6-8ce6-d55a21390194.png)
There is error in two lines of Instant Answer as per reference help from LibreOffice
IA Page:  http://duck.co/ia/view/libre_office_writer_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @DPAUTH

**Comment by DPAUTH** [comment]
@ambrish61  Sorry it took me so long to see the message working on some pther projects and other IAs. I  
will fix the issue ASAP.
