### ISSUE TITLE
Sudoku: How to activate?

### ISSUE THREAD

**Issue by DrDub** [duckduckgo/zeroclickinfo-goodies#3730]
## Type of Issue

- [X ] Bug (incorrect behavior)
    - [X ] Triggering
    - [ ] Relevancy
    - [ ] Internal (issue with code)
- [ ] Feature Request
    - [ ] Triggers (new triggers)
    - [ ] Design Change

## Description

From the code, it looks like searching on DDG with "sudoku easy" should produce a sudoku, but it doesn't.

## Steps to recreate

search for: sudoku easy

## People to notify

cc: @mintsoft

**Comment by mintsoft** [comment]
@DrDub Hello; as far as I know this IA never made it live. It is available on beta however: https://beta.duckduckgo.com/?q=sudoku&t=h_&ia=answer

**Comment by DrDub** [comment]
Ah, great. Didn't know about the Beta.

Thanks!
