### ISSUE TITLE
"Roll 2 dice" Query shows 7

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#3732]
![screenshot 217](https://cloud.githubusercontent.com/assets/8397274/20029124/3b1dfa70-a36a-11e6-9eaf-af6028e1a83a.png)

---

Instant Answer Page: https://duck.co/ia/view/dice

**Comment by sahildua2305** [comment]
@gautamkrishnar what's the expected behaviour or bug? Please mention that as well.

**Comment by gautamkrishnar** [comment]
I think it should show two random numbers like in the coin goodie which triggers on typing *toss 2 coins* 

Eg: 6,2

**Comment by gautamkrishnar** [comment]
It shouldn't display 7. The normal dice have only 6 sides...

**Comment by logically-untangled** [comment]
@gautamkrishnar It displays the total outcome of 2 dies being rolled. First dice landed on 5 and the second one on 2, the sum of that is what is being displayed.

**Comment by loganom** [comment]
Yes, "roll 2 dice" will roll 2 dice and display the sum, followed by the two dice rolls. I'm going to close this issue.

Thanks for the posting the clarification @logically-untangled.

**Comment by gautamkrishnar** [comment]
Okay...  Good to go :+1:
