### ISSUE TITLE
Password: Longer passwords get cut off

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/zeroclickinfo-goodies#3739]
E.g. https://duckduckgo.com/?q=password+60 - you may need to refresh a bit to see it.

![screenshot from 2016-11-08 15-01-34](https://cloud.githubusercontent.com/assets/1431577/20104171/d9a8f2ba-a5c4-11e6-8a9e-cdea9b66fb16.png)

------
IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by moollaza** [comment]
@andrey-p this actually affects all Goodies using the `text` templates. Our CSS prevents the overflow from showing, and I think we prevent the text from wrapping.

```
base__title {
    ...
    overflow: hidden;
}
```
