### ISSUE TITLE
IA Idea: Bluej Commands Cheatsheet

### ISSUE THREAD

**Issue by aviatorpranoy** [duckduckgo/zeroclickinfo-goodies#3743]
New IA Idea: A cheatsheet to show the basic keyboard commands of a BlueJ

Example Query: BlueJ Commands, BlueJ Cheat Sheet

**Comment by marti1125** [comment]
Hi @aviatorpranoy you have to send a PR with a new IA =D

**Comment by aviatorpranoy** [comment]
@marti1125 Sorry I didn't get you. What do you meanby  a PR with a new IA?

**Comment by kumarankit0411** [comment]
@aviatorpranoy If you want to submit a new cheat sheet instant answer, you have to open a pull request for that. Issues is not meant to submit new IA. To know more about how to submit a pull request, follow [this documentation](https://docs.duckduckhack.com/submitting/pull-request.html) step by step.

**Comment by aviatorpranoy** [comment]
okay thank you guys :)
