### ISSUE TITLE
Currency: Triggers for non-question formats

### ISSUE THREAD

**Issue by adityasiwan** [duckduckgo/zeroclickinfo-goodies#3747]
### Description

Although this query `currency in/of/for $country` is triggering the [result](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/currency_in/currencies.json). What could be done to trigger the result for some of the queries like `currency $country` or `$country currency`.

### What is triggering

https://duckduckgo.com/?q=currency+of+india&ia=answer
### What is not triggering

https://duckduckgo.com/?q=india+currency
https://duckduckgo.com/?q=currency+india

## People to notify

@moollaza @zekiel @Alchymista @ozdemirburak Please have a look into this.

---

Instant Answer Page: https://duck.co/ia/view/currency_in

**Comment by mintsoft** [comment]
@adityasiwan Currently the regex for the query will only return a result if the query contains `in|of|for` in it, which is why `india currency` does not trigger (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/CurrencyIn.pm#L43).

This can be changed if the maintainer (@Alchymista) agrees

**Comment by Alchymista** [comment]
Yes, I absolutely agree.
Logic can be changed in a way, that "query"/"user question" can be "exploded" into array of  words,
and if any word matches "currency|currencies" and another word matches country name in list of countries,
then it will return currencies for that country..
(currency|currencies is already trigger of goodie, so just name of country should be checked)

**Comment by mintsoft** [comment]
Thanks @Alchymista do you want to do that or would you prefer someone else made those changes? Either way is fine 👍

**Comment by Alchymista** [comment]
I may try to play with that, but its already few years since I used Perl last time ;) ...
I am already refreshing my knowledge, so I will see.... if I will struggle or someone really, really wants to do that, then its fine with me...

**Comment by ThePinger** [comment]
Can you assign me ? @mintsoft

**Comment by mintsoft** [comment]
@ThePinger I can assign you if you join the duckduckhack Team: https://github.com/orgs/duckduckgo/teams/duckduckhack-contributors

**Comment by ThePinger** [comment]
The link gives 404 so how can I join the duckduckhack Team ? @mintsoft

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
