### ISSUE TITLE
Email validation give unformated response with invalid email address

### ISSUE THREAD

**Issue by 0xbsec** [duckduckgo/zeroclickinfo-goodies#3748]
### Description

When I search for an invalid email address I get 
>E-mail address **$address** is invalid.

Screenshot:

<img width="875" alt="screen shot 2016-11-14 at 5 09 04 pm" src="https://cloud.githubusercontent.com/assets/8887221/20269763/42cd4864-aa8d-11e6-8efe-a0cb9142ef7b.png">

## Steps to recreate

`given` goes to  https://duckduckgo.com/
`and` search for: `validate test@tes;t.com`
`then`
**expected**
IA response should be: 
>E-mail address **test@tes;t.com** is invalid.

**Actual**
IA response is:
>E-mail address **$address** is invalid.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/email_validator

**Comment by sahildua2305** [comment]
Thanks for reporting @0xbsec! This is a bug indeed. I will push a fix later today.

**Comment by 0xbsec** [comment]
@sahildua2305 I'm sending a PR to fix it now.

**Comment by sahildua2305** [comment]
Cool @0xbsec, go ahead!

**Comment by 0xbsec** [comment]
@sahildua2305 done in #3749.
