### ISSUE TITLE
Hex To Ascii: template issue

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3751]
<img width="1020" alt="screen shot 2016-11-15 at 6 39 03 am" src="https://cloud.githubusercontent.com/assets/126358/20304450/46b46d6a-aafe-11e6-8008-46c98dccec73.png">
   

------
IA Page:  http://duck.co/ia/view/hex_to_ascii 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @koosha--

**Comment by mintsoft** [comment]
@bsstoner Just to clarify: I'm guessing the string of binary passed in represents nothing but unprintable characters? (`SOH,NUL,SOH,SOH,SOH,DLE,DLE,SOH,DLE,SOH,DC1,SOH,DLE,DLE,NUL,SOH,DC1,SOH,NUL,NUL,SLE,NUL,SOH`)

**Comment by bsstoner** [comment]
yea, but why is it printing out the markup like that?

**Comment by mintsoft** [comment]
Hmm, it's broken :)

In all seriousness; it looks like when it was converted to use the handlebars templates the HTML wasn't removed in `printable_chr` for unprintable chars (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/HexToASCII.pm#L102). The handbars then is treating that as unsafe (correctly) and writing out the literals. It's actually a little tricky to get the old behaviour back; maybe a quick fix would be to just remove the markup and return "[NUL]" for NULL
