### ISSUE TITLE
New Cheatsheet: ggplot2 for R

### ISSUE THREAD

**Issue by mr-karan** [duckduckgo/zeroclickinfo-goodies#3754]
Create a new cheatsheet for [ggplot2](http://ggplot2.org/).  

Source: https://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf

---

Instant Answer Page: https://duck.co/ia/view/ggplot2_cheatsheet

**Comment by mr-karan** [comment]
I'd like to take this up! :)

**Comment by tagawa** [comment]
Hi @mr-karan. This sounds good. Do you know how to get started? Just in case:

1. Create a new IA page here: https://duck.co/ia/new_ia
2. In Codio, create a new Git branch and make the cheatsheet as a JSON file
3. Submit a PR, pasting the link to the IA page in the description (as you did in this issue)

If you need help with any stage, please let me know or ask in the forum or Slack.

**Comment by mr-karan** [comment]
Yep, I'm starting with this but have found an alternate source for cheatsheet : http://docs.ggplot2.org/current/

[This] one lacks explanation for commands because the use of images. Should I go ahead with the new source?

**Comment by tagawa** [comment]
@mr-karan I agree, that new cheatsheet looks like a better source, and it's an official ggplot2 one as well. Feel free to use that, and thanks for checking!
