### ISSUE TITLE
Asciinema cheatsheet Bug

### ISSUE THREAD

**Issue by mr-karan** [duckduckgo/zeroclickinfo-goodies#3757]
### Description

The cheatsheet is triggered for search terms [adoc cheatsheet](https://duckduckgo.com/?q=adoc+cheatsheet&t=hq&ia=software) but nothing is loaded.

See the screenshot for more deatils:

![screen shot 2016-11-17 at 2 13 21 pm](https://cloud.githubusercontent.com/assets/5689132/20382333/6d73d916-acd1-11e6-8f3d-3aa18ceea357.png)

## Steps to recreate

https://duckduckgo.com/?q=adoc+cheatsheet&t=hq&ia=software

## People to notify

Maintainer: @tagawa 

---

Instant Answer Page: https://duck.co/ia/view/asciidoc_cheat_sheet

**Comment by tagawa** [comment]
There are two IAs available for this query so the user has a choice. The GitHub repo is shown by default, but if the user clicks the "Cheat Sheet" tab (next to "Software") then our cheat sheet will be displayed.

**Comment by mr-karan** [comment]
Ah my bad. Closing.

**Comment by mr-karan** [comment]
Ah my bad. Closing.

**Comment by mr-karan** [comment]
Ah my bad. Closing.

**Comment by tagawa** [comment]
No problem - thanks for checking!
