### ISSUE TITLE
President of the United States (POTUS): shouldn't trigger on president-elect

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3760]
<img width="697" alt="screen shot 2016-11-17 at 7 48 28 am" src="https://cloud.githubusercontent.com/assets/126358/20389950/511af736-ac9a-11e6-807a-5871190c6d19.png">
   

------
IA Page:  http://duck.co/ia/view/potus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @numbertheory

**Comment by jasonporta** [comment]
I'm new at contributing on GitHub (I have my own projects, I use GitHub desktop, and I've completed the set up process for Codio and everything). I found potus.pm and this seems like an easy fix (is it even still an issue after 25 days?) Do I discuss it in Slack or add my edits and submit a pull request? Through Codio or GitHub Desktop? 

Sorry. Like I said, I'm new at this and I'm trying to get involved so I can contribute to more projects and in grow my portfolio to get a programming job in the process.

**Comment by mintsoft** [comment]
This is actually really strange; with the query `who is the president-elect of the us` the value of `$rem` on https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/POTUS.pm#L22 is `who is the` whereas I wouldn't expect it to trigger at all because the string `president of the us` isn't present in the query.

Feels like it might be broader than just this IA's interesting triggering mechanism misfiring

**Comment by nalinbhardwaj** [comment]
@bsstoner @mintsoft I can't seem to be able to trigger the IA. Was it shut down due to the aforementioned issues?

**Comment by moollaza** [comment]
> I can't seem to be able to trigger the IA. Was it shut down or something due to the aforementioned issues?

Yes it was taken offline

> whereas I wouldn't expect it to trigger at all because the string president of the us isn't present in the query.

@mintsoft that's really odd...possibly a bug in DuckDuckGo Repo.

Either way, one big issues is that the regex inside the `handle` is not anchored. We need to ensure that the query **only** matches the phrases we expect and nothing else.

For example it currently triggers on "who is the worst president of the us" which it should not!

**Comment by mintsoft** [comment]
@moollaza is it worth fixing this or has it been replaced by the wikipedia fatheat thingymabob?

**Comment by bsstoner** [comment]
It will likely be made irrelevant in the near future.

**Comment by moollaza** [comment]
Looks like our Wikipedia Instant Answer covers just about all the "Nth president of the US" type queries:

https://duckduckgo.com/?q=23rd+president+of+the+united+states&ia=web

Perhaps we should just remove this IA 👍  -- It's already offline anyways.

**Comment by moollaza** [comment]
We don't seem to handle the "who is/was the nth president" style queries though Wiki is usually the first result. I've merged your PR @mintsoft I suppose we can keep this around a little bit longer if we want.

**Comment by mintsoft** [comment]
@moollaza I say delete it if it's not needed 👍

**Comment by moollaza** [comment]
A few users have noticed this IA is offline. There are a few queries that the Wikipedia Fathead doesn't handle, e.g. "potus 15"

I suppose we could keep it around with a reduced trigger space?
