### ISSUE TITLE
SSH Cheat Sheet: Duplicate entry for "Launch a local x11 session for a given application"

### ISSUE THREAD

**Issue by enigene** [duckduckgo/zeroclickinfo-goodies#3761]
Hi! This section is repeating twice. At lines 72-75 and 84-87.
```json
      {
        "val": "Launch a local x11 session for a given application",
        "key": "ssh -X user@remotehost.com \"xterm\""
      },
```
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/ssh.json#L72

------
IA Page:  http://duck.co/ia/view/ssh_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @wilhelm1973

**Comment by rwsender** [comment]
I can fix this.

**Comment by mintsoft** [comment]
Closed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3786
