### ISSUE TITLE
Question: Can we save some Goodie settings in user session?

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3763]
### Description

Is it possible to save some settings that user selects in some Goodie and keep them persistent across the page reloads?

## People to notify

@moollaza @tagawa

**Comment by moollaza** [comment]
@sahildua2305 yes -- we do this in the Forecast Instant Answer:

https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L364

**Comment by moollaza** [comment]
I believe this is the only Instant Answer that currently does this
