### ISSUE TITLE
Calculator: 10+9 returns a false answer

### ISSUE THREAD

**Issue by iExplosive** [duckduckgo/zeroclickinfo-goodies#3768]
It has come to my attention that when the search engine
calculates 10 + 9 or 9 + 10, the answer it gives me is 19. That is not true,
as I went on Vine to see the actual answer, which is 21. Please fix this issue.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by sahildua2305** [comment]
@iExplosive it looks good to me. Working as expected.

Closing the issue. Let me know if something's still wrong. 🙂
