### ISSUE TITLE
SQL Cheat Sheet: AS (alias) is described two times

### ISSUE THREAD

**Issue by QVaucher** [duckduckgo/zeroclickinfo-goodies#3772]
Description
------
I've just noticed that the AS (alias) appears two times in the cheat sheet

Link
-----
IA Page:  http://duck.co/ia/view/sql_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jophab

**Comment by QVaucher** [comment]
As well as the UNION description actually...

**Comment by gautamkrishnar** [comment]
@jophab please issue a quick fix

**Comment by rwsender** [comment]
I can work on this, I am working at the Ulster meetup.

**Comment by gautamkrishnar** [comment]
@rwsender You can take this up this since @jophab  is busy with his exams.
Please notify me once you had finished it, so that we can get it merged soon.

**Comment by rwsender** [comment]
@gautamkrishnar issue should now be fixed!
