### ISSUE TITLE
Emmet CheatSheet : Add Examples and Improve cheatsheet

### ISSUE THREAD

**Issue by akanshgulati** [duckduckgo/zeroclickinfo-goodies#3781]
SUGGESTION

{Emmet CheatSheet} Suggestion: The cheatsheet is not that effective for a new user. It covers less cases and should have different layout to incorporate examples for users. It will give better idea about shortcuts. 

  
### Description

The present cheatsheet is less effective for users and it should be improved so that even a newbie can pick things from the cheatsheet. Adding examples will make visualisation better. 

## People to notify

@philoniare 

---

Instant Answer Page: https://duck.co/ia/view/emmet_cheat_sheet

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
