### ISSUE TITLE
Ascii to Binary: WRONG (and dubious) answers

### ISSUE THREAD

**Issue by rdebath** [duckduckgo/zeroclickinfo-goodies#3784]
https://duckduckgo.com/?q=0.2+in+binary

I would not expect `0.2` to be converted as an ascii string, it's a valid number and so "should be" converted as such ie:
```
0.0011001100110011001100110011001100110011001100110011001100110011001...
```

Also in this answer, the "string to binary" does NOT say what character set it's using, this is obviously not relevant in provinces such as "america" that only use "ASCII" but something like
```
日本語 in binary
```
gives a completely wrong answer... `111001010010110010011110`

------
IA Page:  http://duck.co/ia/view/binary 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hunterlang

**Comment by mintsoft** [comment]
@rdebath To clarify; what exactly would you expect 0.2 to be converted to? I was expecting the IEEE 754 representation personally. I don't understand what `0.0011001100110011001100110011001100110011001100110011001100110011001` is; could you clarify?

Thanks,

**Comment by rdebath** [comment]
If you're working in binary and have the binary number `10` (two in English) and divide it by `1010` (ten in English) you get a repeating binary number `0.001100110011 ... etc` (two tenths in English)

So that's a binary point giving the shorthand for the decimal sum.
```
1.0/8 + 1.0/16 + 1.0/128 + 1.0/256 + 1.0/2048 + 1.0/4096 ...
```
Which gets closer to `0.2` decimal as you add terms.

Obviously, that only works well for numbers that don't need too many zeros; the binary equivalent of scientific notation would be needed for very large or very small numbers.

Showing it as an IEEE754 double (like https://www.h-schmidt.net/FloatConverter/IEEE754.html) would be a nice extra, but, I don't think it'd be as useful. IME most people treat `doubles` as a completely opaque type, I know I usually do, partly because of the complexity of the type (as described on that page)

However, [Wolfram Alpha](https://www.wolframalpha.com/input/?i=0.2+in+binary) shows both.

**Comment by mintsoft** [comment]
@rdebath Ah! I understand now, thanks for clarifying. @Mylainos are you interested in looking at this perhaps?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
