### ISSUE TITLE
PostgreSQL cheat sheet Bug: One column not showing up properly

### ISSUE THREAD

**Issue by aleksandar-todorovic** [duckduckgo/zeroclickinfo-goodies#3791]
### Description

There are seven different categories listed in the cheat sheet, and the most important one (actual PostgreSQL commands) shows the commands, but not their explanation.

## Steps to recreate

1. Open the PostgreSQL cheat sheet.
2. Click on "more".
3. Notice the lack of explanation in the `PosgreSQL` category.

## People to notify

Seems like @gautamkrishnar is the only one who contributed to this cheat sheet so far.

---

Instant Answer Page: https://duck.co/ia/view/postgresql_cheat_sheet

**Comment by tagawa** [comment]
Thanks for spotting this @aleksandar-todorovic. Looks like it's because the attributes are named `value` instead of `val` in the code for that section: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/postgresql.json
