### ISSUE TITLE
Constants: More Constants

### ISSUE THREAD

**Issue by GeraldNDA** [duckduckgo/zeroclickinfo-goodies#3792]
I think it'd be beneficial if the following constants were added:

- Faraday's Constant
- More values of the Universal Gas Constants
- Potentially Gravity of the Earth (not sure if this falls under constants but it'd be useful if I wanted more digits)

------
IA Page:  http://duck.co/ia/view/constants 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hemanth

**Comment by GeraldNDA** [comment]
Also Permittivity of Free Space constant

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
