### ISSUE TITLE
New Cheatsheet: ohmyzsh for zsh shell

### ISSUE THREAD

**Issue by mr-karan** [duckduckgo/zeroclickinfo-goodies#3794]
Create a new cheatsheet for [ohmyzsh](http://ohmyz.sh/).

Source: https://github.com/robbyrussell/oh-my-zsh/wiki/Cheatsheet

## Get Started
- [-] 1) Claim this issue by commenting below
- [-] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [-] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/ohmyzsh_cheatsheet

**Comment by mr-karan** [comment]
I'd like to work on this :smile:

**Comment by pjhampton** [comment]
This looks like it has seized. Closing for now. 

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄
