### ISSUE TITLE
Calculator: Handle units in calculations

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3803]
For example the query [100 meters * 100 meters](https://duckduckgo.com/?q=10+meters+*+10+meters) should return 100 m2

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by mintsoft** [comment]
@tagawa We really need to get https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927 merged in and live before we start adding new features into Calculator IMO

**Comment by GuiltyDolphin** [comment]
@mintsoft Hehe, yeah.

@tagawa @mintsoft and I have discussed some integration between the calculator and conversions, my plan for the calculator was to provide a back-end that provided basic operations, which could then be used by conversions and the interactive front-end so we could have consistent calculations across IAs.

Not sure what the status on that is though.

**Comment by pjhampton** [comment]
I have looked at the query data and there isn't much of a business case of this atm. Also, I'd like to think this is an expansion of conversions, or a separate IA rather than the Calculator IA.
