### ISSUE TITLE
Linux Cheat Sheet: Suggestion

### ISSUE THREAD

**Issue by Hasil-Sharma** [duckduckgo/zeroclickinfo-goodies#3812]
I think query "unix cheat sheet" should also trigger this same cheat sheet. 

Thoughts ?

------
IA Page:  http://duck.co/ia/view/linux_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @crashrane

**Comment by Hasil-Sharma** [comment]
@crashrane : What do you think ?

**Comment by crashrane** [comment]
Most of the commands are similar to that of Linux
So it would be great if it triggered the same cheat sheet.
