### ISSUE TITLE
CSS: Create New CSS Gradients Generator Instant Answer

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#3816]
## Description
We have a nice CSS animations Instant Answer here: https://beta.duckduckgo.com/?q=CSS+Animations&ia=answer
It would be great to have a similar one showing demos of CSS gradients. 

The CSS animations backend and frontend files are listed here, for reference: https://duck.co/ia/view/css_animations

The demos themselves can be created on Codepen with a preview for each one shown in the Instant Answer. Does anyone fancy taking this up?

Related: #3815 

## People to notify
@hchienjo 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by ManrajGrover** [comment]
@tagawa I can take this one up too since I'm currently aware of the code. Let's discuss as to what can be shown in the IA. 😄

**Comment by moollaza** [comment]
@tagawa @ManrajGrover the same goes for this issue, we should have a Gradient _generator_, not examples of gradients.

E.g.
- http://www.colorzilla.com/gradient-editor/
- http://www.cssmatic.com/gradient-generator
- http://gradientgenerator.com/

A tool like this would be far more useful than a list of examples -- it would also be much more fun/challenging to implement 👍

**Comment by agunay** [comment]
@moollaza it seems like no one is working on this anymore. I would love to give it a try if it's okay.

**Comment by pjhampton** [comment]
Hey @agunay,

Yeah, that would be awesome!

**Comment by agunay** [comment]
@pjhampton thanks!

I have a question to get started though. I created a base for this new IA and when I tried to test the triggers, either interactively or with "duckpan query", it gives me the warning: DDG::Goodie::CssGradientGenerator   "Could not retrieve metadata - please ensure the Instant Answer page is in development status or later."

As I understand it I first need to create an instant answer page for this IA now, correct? Should I include only the base with the related PR, and then build on top of that? Sorry if answers to those are obvious, I am pretty new around here and I could not find anything in documents about this warning.

**Comment by pjhampton** [comment]
Hey @agunay,

Yeah, that makes sense. Can you please create a new IA page with the name CssGradientGenerator here? - https://duck.co/ia/new_ia, then let me know either on Github or on Slack. I can move the development status. That's cool, welcome! 👋  😄

**Comment by agunay** [comment]
@pjhampton, this is to let you know that I am still working on this, just had a really busy week. I will create a pull request in couple of days with the first version.

**Comment by pjhampton** [comment]
Awesome! Thanks for the update @agunay! 👍

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
