### ISSUE TITLE
Base64: Encode image

### ISSUE THREAD

**Issue by math2001** [duckduckgo/zeroclickinfo-goodies#3819]
Hello!

When I tried the base64 URL encoder, I tried `base64 <URL_of_image>`. But, instead of getting the code of the image, I got the URL encoded.

So, here's what I think'd be a good idea:

```
Use a regex to see if the text to convert is a valid URL
backup = True
if it_is_an_URL:
    backup = False
    ajax to get the image
    if we get a 404:
        backup = True
    convert it to base64
if backup:
    convert text to base64
```

And a button `convert my image` to upload an image and convert it'd be cool, too.

What do you guys think about it? If you think it's a good idea, I'd love to develop it, I already done this JS converter a while ago (from URL & uploaded file) in local, and really want to contribute to Duck Duck Go.

------
IA Page:  http://duck.co/ia/view/base64
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @dogweather

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
