### ISSUE TITLE
PrimeFactors: Use a faster backend for Math::Prime::Util

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#382]
Math::Prime::Util::GMP is said to be a lot faster in computing factors than the pure Perl implementation in Math::Prime::Util. See how feasible this is, and if installing GMP on people's systems is difficult (since people with DuckPAN will be using it on Linux and OS X), move it to another repository like https://github.com/duckduckgo/zeroclickinfo-goodie-qrcode.

Make sure to add install instructions there, too.

**Update:**
We're now accepting external libraries (such as https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/ChineseZodiac.pm#L5 which depends on https://duckduckgo.com/?q=mpfr). So using a XS version of Math::Prime::Util is totally fine.

------
IA Page: https://duck.co/ia/view/prime_factors

**Comment by zekiel** [comment]
I'm not sure if this is still a suggestion or (in the many PRs since) irrelephant now? :)

**Comment by GuiltyDolphin** [comment]
@zekiel Irrelephant? Oh boy :grinning: It looks like we're still using the same package, so I think it is still relephant.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
