### ISSUE TITLE
Travis CI failing error

### ISSUE THREAD

**Issue by amarlearning** [duckduckgo/zeroclickinfo-goodies#3821]
The command "dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --quiet --notest --mirror http://www.cpan.org/ --mirror http://duckpan.org" failed and exited with 123 during .

PR #3820

#### People to Notify
@tagawa

<!-- LANGUAGE LEADERS ONLY: REMOVE THIS LINE
## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by Hasil-Sharma** [comment]
I'm facing similar issue today again
PR #3835

Can it be something I'm doing?

**Comment by pjhampton** [comment]
This has been resolved 👍
