### ISSUE TITLE
Suggestion: New Cheat Sheet Wireshark/Tshark

### ISSUE THREAD

**Issue by vduddu** [duckduckgo/zeroclickinfo-goodies#3827]
### Description

It would be very helpful if someone compiles the cheatsheet for various filters in wireshark and commands for using tshark

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by adityatandon007** [comment]
Hi vuddu, I would like to work on this cheatsheet.

**Comment by vduddu** [comment]
Sure

**Comment by adityatandon007** [comment]
Thanks, but I have one suggestion can we make both Wireshark and Tshark separately. Since one is the GUI and other is CLI it will be better to present them with different templates instead of using one. I would love to know your response

**Comment by vduddu** [comment]
I think it's a good idea. For wireshark, include all the filters (as there are no commands as such) and for tshark include the commands.

**Comment by adityatandon007** [comment]
Hey, @vduddu I have submitted a Tshark cheat sheet and I have used the terminal template because it is Command line tool. Could you review

**Comment by pjhampton** [comment]
Hey @vduddu and @adityatandon007 

Thanks for your suggestion! 😄  As cheat sheets trigger for such a small share of the overall query space, your suggestion may or may not be a good direction at the moment. We will close this for the time being and revisit in the future. 

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄
