### ISSUE TITLE
Vim CheatSheet: Should trigger for 'vim beginner cheat sheet' too

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#3828]
### Description

It should trigger on `vim beginner cheat sheet` too. I found myself (unintentionally) searching for it and couldn't see any cheatsheet. 

## People to notify

@NaveenKarippai 

---

Instant Answer Page: https://duck.co/ia/view/vim_cheat_sheet

**Comment by gautamkrishnar** [comment]
@duckduckgo/community-leaders I think we must update triggers.yml to make this trigger available to all cheat sheets.
What's your opinion ?
