### ISSUE TITLE
New Apache Hive Cheat Sheet

### ISSUE THREAD

**Issue by Hasil-Sharma** [duckduckgo/zeroclickinfo-goodies#3832]
Cheat Sheet for Apache Hive   

------
IA Page:  http://duck.co/ia/view/apache_hive_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Hasil-Sharma

**Comment by marti1125** [comment]
Hi @Hasil-Sharma you could create a PR for this new AI following this doc https://docs.duckduckhack.com/walkthroughs/programming-syntax.html
like this example https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3715
