### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by laorynas** [duckduckgo/zeroclickinfo-goodies#3839]
**Digital storage inacurate conversions**

[![Screenshot (7).png](https://s28.postimg.org/kzhaly68t/Screenshot_7.png)](https://postimg.org/image/ngt1t7q55/)
1 GB = 1000 MB = (1000 x 1000) KB = (1000 x 1000 x 1000) = 1000000000 Bytes

But in reality
1 GB = 1024 MB = (1024 x 1024) KB = (1024 x 1024 x 1024) = 1073741824 Bytes.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@laorynas Thanks for raising this, due to ambiguity we've decided for now to define mega, kilo, giga etc to be SI definitions (10^3); for binary prefixes we've opted for the SI Mebi/Kibi/Gibi/ (visible here: https://duckduckgo.com/?q=1GiB+to+MiB&t=ffab&ia=answer)

**Comment by laorynas** [comment]
Ok thanks
