### ISSUE TITLE
URL Decode: 

### ISSUE THREAD

**Issue by wildnwicked** [duckduckgo/zeroclickinfo-goodies#3847]
https://www.facebook.com/alfonso.bundy.7965?lst=100003940977870%3A100014184700418%3A1483029453   

------
IA Page:  http://duck.co/ia/view/urldecode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@wildnwicked Hi, sorry I'm not sure what the problem is here?

**Comment by pjhampton** [comment]
Hey @wildnwicked,

Feel free to reply and we will reopen this! 😄  👍
