### ISSUE TITLE
Public DNS: Add CCC + Wikileaks IPs

### ISSUE THREAD

**Issue by almereyda** [duckduckgo/zeroclickinfo-goodies#3850]
CCC and Wikileaks also maintain lists of IPs, of which some may be good to add.

* https://www.ccc.de/de/censorship/dns-howto
* https://wikileaks.org/wiki/Alternative_DNS

------
IA Page:  http://duck.co/ia/view/public_dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mailkov

**Comment by nalinbhardwaj** [comment]
Fixed via #3883. Please review.
