### ISSUE TITLE
JavaScript and JSON Minifier: Better function to minify script

### ISSUE THREAD

**Issue by amarlearning** [duckduckgo/zeroclickinfo-goodies#3851]
JavaScirpt File : [this](https://raw.githubusercontent.com/amarlearning/Supreme-Angular/master/Week%20One/Assignment/app.js)
Character Count : 1354

Now I minified the above JavaScript File using these two tools:
1. [JavaScript Minifier DuckDuckGo](https://duckduckgo.com/?q=javascript+minifier&atb=v46-3__&ia=answer) 
Character count of minified script is: 1141

2. [Other JavaScript Minifier](https://javascript-minifier.com/) 
Character count of minified script is: 790

For counting character, I used this [tool](http://www.lettercount.com/)

The other JavaScript Minifier that I used offers API as well. Let me know what you think about this.

------
IA Page:  http://duck.co/ia/view/js_minify 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by sahildua2305** [comment]
@amarlearning thanks a lot for suggesting an apparently better solution. However, one important aspect to consider will be the size of the library. Oh wait, do they even provide a library which you can easily load and do the minify stuff?

If it's just an API, then we can't really have an interactive IA like the one we have right now. Let me know what you find out after digging in deeper. I'd be happy to discuss the possibilities. 😃
