### ISSUE TITLE
JavaScript and JSON Minifier: Add Copy button to copy minified script

### ISSUE THREAD

**Issue by amarlearning** [duckduckgo/zeroclickinfo-goodies#3852]
There Should be copy button on the top of the minified script so that user can easily copy the script.

------
IA Page:  http://duck.co/ia/view/js_minify 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by pjhampton** [comment]
Hey

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
