### ISSUE TITLE
Calculator: trigger performance issues

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/zeroclickinfo-goodies#3853]
The trigger has some serious performance issues that we'd like to resolve asap.  In general it's checking for too many *optional* things, e.g. [here](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm#L18), [here](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm#L20), and again [here](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm#L24), etc., on triggering that don't need to be since they are fully processed in the handler.  

The approach should probably be to:

1. check for the *minimum required* mathematical expression(s)
2. reject in the handler

The `alarm` should be removed as well since it's done internally.

cc @moollaza 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by mintsoft** [comment]
@zachthompson I presume this refers to the currently live calculator as all the triggers have changed etc in the new one (that @GuiltyDolphin wrote) : https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927

**Comment by zachthompson** [comment]
@mintsoft Yeah. We should probably spend some cycles in the near future moving the new calc through.  In the meantime we need to dumb down the triggering in the current version.

**Comment by moollaza** [comment]
Reopening as we still need to remove the `alarm`

**Comment by moollaza** [comment]
Actually I'll move that to a new issue.
