### ISSUE TITLE
Calculator: logarithms not detected independently

### ISSUE THREAD

**Issue by lemontheme** [duckduckgo/zeroclickinfo-goodies#3861]
Needed to find a quick logarithm and noticed that, whereas it's possible to get a result for, e.g, `2 * log10`, searching for the log on its own (e.g., as `log10` or `log of 10` or `log10 of 10`, etc.) yields no results. Incidentally, natural logarithms (e.g., `ln5`) don't appear to work at all.

No biggie. Just a small addition that might bring the calculator slightly closer to being on par with Google's.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@lemontheme I believe this is fixed in #1880.

**Comment by lemontheme** [comment]
Thank you for referring me to that pull request. Using the `F(X)` form described there, e.g., such that `log(20)`, seems to do the trick!

**Comment by GuiltyDolphin** [comment]
@lemontheme When the calculator gets updated I'll update the example queries - I'm not sure how accurate the existing examples are as the precedence can vary somewhat with the old version.
