### ISSUE TITLE
Calculator: Remove `alarm`

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#3867]
### Description
The calculator wraps its evaluation of the input in an `alarm` to keep it from running too long. We've since limited the execution time of Goodies internally the alarm in the IA is no longer needed.

**Note**: The PrimeFactors Goodie also has an alarm that should be removed.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by nalinbhardwaj** [comment]
Hi,
Fixed via #3881. Please review.
