### ISSUE TITLE
Solar System: show in different unit of measure?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3870]
User Feedback:
_Should be in SI units and not in "lbs". Come on get serious it's 2017 now. When I'm looking for the mass of the Earth the last thing I want to know is the number in disgusting imperial units._   

------
IA Page:  http://duck.co/ia/view/solar_system 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by bsstoner** [comment]
Another one:
_lbs is not a unit of mass. Slugs or Kilograms are._

**Comment by MrChrisW** [comment]
@bsstoner I'll take this. The USA is reason we show imperial units, it was discussed in the original MR 😃

**Comment by bsstoner** [comment]
We could tie it to the Unit of Measure setting?
https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L350

**Comment by MrChrisW** [comment]
@bsstoner sure, would we default to SI units (metric) if there's no preference?

**Comment by bsstoner** [comment]
yea, that's the problem with that setting, it defaults to USA which probably won't solve the problem for most people...

We could use their locale and just show lbs for US and metric for everyone else? https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Currency.pm#L119

**Comment by MrChrisW** [comment]
@bsstoner that's what we do currently 😕  https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/SolarSystem.pm#L51-L58

**Comment by bsstoner** [comment]
lol, doh!

**Comment by MrChrisW** [comment]
related issue https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2116

**Comment by bsstoner** [comment]
Oh interesting, I didn't realize you were already discussing this. Linking to the unit of measure setting makes sense.

FWIW Google, Wikipedia, Wolfram Alpha all use kg (even for me in the US). We could maybe just drop lbs and show kgs to everyone?

**Comment by bsstoner** [comment]
We've gotten some more feedback on this:
_"Most people searching for Mars' radius will be doing so for scientific purposes and thus SI units should be used."_

I would say just switch to kgs everywhere? We can see if there's any backlash and re-adjust if so?

**Comment by mintsoft** [comment]
> I would say just switch to kgs everywhere? We can see if there's any backlash and re-adjust if so?

Absolutely! Only damn American's use silly units like lbs!
