### ISSUE TITLE
Calculator: Not triggering for some queries

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3871]
User Feedback:
**3^6067**
[https://duckduckgo.com/?q=3%5E6067&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=3%5E6067&kp=1&kad=wt_WT&kl=wt-wt)
_Mathematical formulae could be solved by an online solver like wolfram alpha, and the results could be displayed._

**-13/9**
[https://duckduckgo.com/?q=-13%2F9&kp=1&kad=wt_WT&kl=uk-en](https://duckduckgo.com/?q=-13%2F9&kp=1&kad=wt_WT&kl=uk-en)
_Should return embedded calculator result_

-85*65432 + (85*74+59)*876
[https://duckduckgo.com/?q=-85%2A65432%20%2B%20%2885%2A74%2B59%29%2A876&kp=1&kad=wt_WT&kl=be-fr](https://duckduckgo.com/?q=-85%2A65432%20%2B%20%2885%2A74%2B59%29%2A876&kp=1&kad=wt_WT&kl=be-fr)
_Where is the result of the calculation?_

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@bsstoner I believe these are all fixed in #1927. There are several other issues relating to triggering which are also fixed.

**Comment by bsstoner** [comment]
Nice, had a feeling that might be the case, but figured more examples might help.

**Comment by bsstoner** [comment]
Feel free to merge or close into #1927

**Comment by pjhampton** [comment]
Fixed now with the new UI. The first one doesn't trigger but we will capture those in the pixel logs
