### ISSUE TITLE
Conversions: Ability to convert µm to mil

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3872]
Example:

**0.1 µm in mil**
[https://duckduckgo.com/?q=0.1%20%C2%B5m%20in%20mil&kp=1&kad=en_US&kl=wt-wt](https://duckduckgo.com/?q=0.1%20%C2%B5m%20in%20mil&kp=1&kad=en_US&kl=wt-wt)

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by nalinbhardwaj** [comment]
Fixed via #3885. Please review.
