### ISSUE TITLE
Conversions: Convert Pascals to Megapascals

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3873]
Example:

**101300 Pa to MPa**
[https://duckduckgo.com/?q=101300%20Pa%20to%20MPa&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=101300%20Pa%20to%20MPa&kp=1&kad=wt_WT&kl=wt-wt)

<img width="802" alt="screen shot 2017-01-21 at 10 01 44 am" src="https://cloud.githubusercontent.com/assets/126358/22175325/b060c37a-dfc0-11e6-8749-5b01f6269afb.png">

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by nalinbhardwaj** [comment]
Fixed via #3885. Please review.
