### ISSUE TITLE
Conversions: Convert centigrade to farenheit

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3874]
Example:
   
**convert 50 centigrade to fahrenheit**
[https://duckduckgo.com/?q=convert+50+centigrade+to+fahrenheit](https://duckduckgo.com/?q=convert+50+centigrade+to+fahrenheit)
_"It would be really helpful if a simple calculation like this could show me the solution right at the top of the search results page, rather than me having to click through to a conversion site to do this conversion."_

<img width="882" alt="screen shot 2017-01-21 at 10 07 12 am" src="https://cloud.githubusercontent.com/assets/126358/22175377/688fd4f4-dfc1-11e6-9da5-71f372a2ebbf.png">

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
That should absolutely already work

**Comment by bsstoner** [comment]
Deployed and working in production 👍 
https://duckduckgo.com/?q=convert+50+centigrade+to+fahrenheit
