### ISSUE TITLE
Conversions: Convert picometers

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3876]
Example:

**161 pm to m**
[https://duckduckgo.com/?q=161%20pm%20to%20m&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=161%20pm%20to%20m&kp=1&kad=wt_WT&kl=wt-wt)

<img width="814" alt="screen shot 2017-01-21 at 10 10 11 am" src="https://cloud.githubusercontent.com/assets/126358/22175402/df467a30-dfc1-11e6-9741-169361ba6e8f.png">

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by nalinbhardwaj** [comment]
Fixed via #3885. Please review.

**Comment by bsstoner** [comment]
This was deployed and is working in production. Thanks!
