### ISSUE TITLE
Minecraft: Wrong Recipe

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3880]
User Feedback:
**minecraft fence recipe**
[https://duckduckgo.com/?q=minecraft%20fence%20recipe&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=minecraft%20fence%20recipe&kp=1&kad=wt_WT&kl=wt-wt)
_"I search for minecraft fence recipe. The Instant Answer shows the minecraft fence GATE recipe, which is a different item. It should show the fence recipe, not the fence gate recipe."_

------
IA Page:  http://duck.co/ia/view/minecraft 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @engvik

**Comment by nalinbhardwaj** [comment]
Fixed via #3882 . Please review.

**Comment by bsstoner** [comment]
The fix is live in production: https://duckduckgo.com/?q=minecraft%20fence%20recipe&kp=1&kad=wt_WT&kl=wt-wt

Thanks!
