### ISSUE TITLE
Calculator: Float precision

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3899]
https://duckduckgo.com/?q=(4.2-4.1)*6000

<img width="395" alt="screen shot 2017-01-30 at 6 46 08 am" src="https://cloud.githubusercontent.com/assets/126358/22421943/cf4c5f9e-e6b7-11e6-8b9e-bbd57875bdcf.png">

/cc @zachthompson @moollaza 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@bsstoner In #1927 the precision is determined a bit more robustly, so that expresion yields the correct result (`600`).

**Comment by pjhampton** [comment]
This has been addressed 👍 
![screen shot 2017-05-09 at 6 34 07 pm](https://cloud.githubusercontent.com/assets/8960296/25864143/452b9398-34e6-11e7-81fc-bb707ad5253f.png)
