### ISSUE TITLE
Parcelforce: Incorrectly triggering on lapost numbers

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3900]
**cc737873589FR**
[https://duckduckgo.com/?q=cc737873589FR&kp=1](https://duckduckgo.com/?q=cc737873589FR&kp=1)
_"number is actually a laposte number, parcel can only be followed by [http://www.laposte.fr/particulier/outils/suivre-vos-envois](http://www.laposte.fr/particulier/outils/suivre-vos-envois)"_

------
IA Page:  http://duck.co/ia/view/parcelforce 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Hmm if the parcel comes into the UK then parcelforce will be able to track it, I think that's why it'll accept any 2 letters on the end. However 99% of parcels will be `GB$` so I'll make the IA only return for those, I think the false positives are worse than the alternative
