### ISSUE TITLE
MD5: Ignore searches with filenames

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3901]
Passing along user feedback:

**tails-i386-2.10.iso md5**
[https://duckduckgo.com/?q=tails-i386-2.10.iso%20md5&kp=1](https://duckduckgo.com/?q=tails-i386-2.10.iso%20md5&kp=1)
_DDG reports the MD5 hex hash of tails-i386-2.10.iso to be:
54774f463860d40362d3ff9c5220ecc5.
It should be:
ba7fa6db178fb8c8feecd2a200cf5641_

------
IA Page:  http://duck.co/ia/view/md5 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jarmokivekas

**Comment by moollaza** [comment]
@bsstoner I think the user thinks we're showing them the MD5 for the actual software package (i.e. `gpg --keyid-format 0xlong --verify tails-i386-2.10.iso.sig tails-i386-2.10.iso`), whereas we're actually showing them the MD5 for the literal string "tails-i386-2.10.iso"

Perhaps we should ignore queries matching file names?

**Comment by jarmokivekas** [comment]
I agree this should not trigger the IA. Probably keeping trigger the same way, but check the end of the the string for certain extensions.

I'd suggest to check against a regex like `\w\.(iso|img|dmg|deb|rpm|snap|sqlite|hex|gzip|gz|zip|bzip|bzip2|tar|hdf|dsk)$` and return early if it matches. These are just file formats from the top of my head that someone may want check fingerprints for.

**Comment by pjhampton** [comment]
Closing due to #3971
