### ISSUE TITLE
FedEx: Incorrectly triggering on ISBN numbers

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3902]
**9781492143239**
[https://duckduckgo.com/?q=9781492143239&kp=1](https://duckduckgo.com/?q=9781492143239&kp=1)
_"Its an ISBN, not a valid tracking number"_

------
IA Page:  http://duck.co/ia/view/fed_ex 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by moollaza** [comment]
The ideal fix here is to migrate the regex triggers from the remaining Package Tracking Goodies into the new Package Spice: https://duck.co/ia/view/package_tracker

https://duck.co/ia/view/package_tracking

This applies to #3900
