### ISSUE TITLE
FIGlet: What are the currently supported fonts?

### ISSUE THREAD

**Issue by camilosampedro** [duckduckgo/zeroclickinfo-goodies#3904]
Is there any way to know what are the available [read fonts](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/FIGlet.pm#L18)?

Thank you!

------
IA Page:  http://duck.co/ia/view/figlet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @engvik

**Comment by engvik** [comment]
Hi!

The fonts available can be found at https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/figlet

**Comment by camilosampedro** [comment]
Thank you very much! 😃

It's an awesome Instant Answer, I think there could be a little reference in the [IA page](https://duck.co/ia/view/figlet)

**Comment by BuonOmo** [comment]
Maybe we should think of a dropdown menu that let user select a font?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
