### ISSUE TITLE
Conversions: Not triggering temperature conversion on "<num> degrees c to f"

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3918]
User Feedback:
**65 degrees c to f**
https://duckduckgo.com/?q=65%20degrees%20c%20to%20f&kp=1
_Comment: It would be nice to have simple conversions and calculations done. Just like google or other search engine_

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Amusingly https://duckduckgo.com?q=65+c+to+f&kp=1&ia=answer works; it's only with the degrees that it doesn't

**Comment by mintsoft** [comment]
I'll fix this after https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3917 is merged; I find it easier to only have 1 PR/IA in flight at a time
