### ISSUE TITLE
President of the United States (POTUS): 

### ISSUE THREAD

**Issue by itsN1X** [duckduckgo/zeroclickinfo-goodies#3924]
Add Donald J trump

----

- [x]  KnowledgeBases Update
------
IA Page:  http://duck.co/ia/view/potus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @numbertheory

**Comment by mintsoft** [comment]
Fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3921
