### ISSUE TITLE
Cheat Sheet : Create a sublime text 3 cheat sheet

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-goodies#3929]
New Instant answer : Create sublime text 3 cheat sheet

SUGGESTION
Sublime text 3 cheat sheet: This IA would provide the required shortcuts for sublime text 3 

### Description
New sublime text 3 cheat sheet

## People to notify
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by adityatandon007** [comment]
@pjhampton I would like to take this issue :smile:

**Comment by pjhampton** [comment]
Thanks @adityatandon007! We believe it's standard practice to submit unsolicited PRs for cheat sheets. No need to open an issue before hand 😄  Just create the IA page and work away.

**Comment by adityatandon007** [comment]
@pjhampton I didn't know about this My apologizes

**Comment by pjhampton** [comment]
No need to apologize!
