### ISSUE TITLE
Calculator: Not triggering when using pi symbol

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3935]
**π * 180**
[https://duckduckgo.com/?q=%CF%80%20%2A%20180](https://duckduckgo.com/?q=%CF%80%20%2A%20180)
_When searching for a calculating term like "π * 180" you won't get a result of calculation. The π symbol is easy to type in macOS, by just pressing and holdin "alt + P", which I often use._   

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by nalinbhardwaj** [comment]
Also needs to be put on hold till #1927 is merged. @GuiltyDolphin
