### ISSUE TITLE
Calculator: Expected calculator to trigger with leading ='s

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3942]
**=2016 - 44**
[https://duckduckgo.com/?q=%3D2016%20-%2044](https://duckduckgo.com/?q=%3D2016%20-%2044)
_Comment: Expected an integer result as the answer_

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by pjhampton** [comment]
Placing this on hold due to the calculator rewrite.
