### ISSUE TITLE
Calculator: should log use base e or 10?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3943]
**log(4000)**
[https://duckduckgo.com/?q=log%284000%29](https://duckduckgo.com/?q=log%284000%29)
_Comment: Hi, Your automatic log(x) answer takes log with base e. Shouldn't that be ln(x) instead of log(x)?_   

![screen shot 2017-02-15 at 3 11 41 pm](https://cloud.githubusercontent.com/assets/126358/22993453/194e8ce4-f391-11e6-9151-c0af1539fbb2.png)
![screen shot 2017-02-15 at 3 11 50 pm](https://cloud.githubusercontent.com/assets/126358/22993452/194e501c-f391-11e6-8142-966ca52979d1.png)

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by mintsoft** [comment]
Hmm that's debatable as to whether it should or not. It's effectively ambiguous; ISO 31-11 doesn't define how this should be handled and it's often inferred from context (think this is still true in 80000 but I don't have it to hand). That said `ln` is always base `e` and `lg` is base `10` in 31-11.

For comparison: WolframAlpha always uses `e` as the base of `log` as does `perl`, `php`, `python`, `ruby`, `.NET`, `JavaScript`, `MatLab`/`octave`. Bing and G use base 10. Symbolab uses base 10 but has a "did you mean" style section stating that `ln` is also available.

Either way, I think the biggest problem is that it isn't explicit as to the base of the log used. If it said `log_e(4000) = yadda` then I think it'd be better in either case.

**Comment by GuiltyDolphin** [comment]
Also in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2351
