### ISSUE TITLE
Grep Cheat Sheet: missing -r option

### ISSUE THREAD

**Issue by laurengarcia** [duckduckgo/zeroclickinfo-goodies#3944]
maybe `-r` is implicit? but its not there, just thought I'd flag it.
------
IA Page:  http://duck.co/ia/view/grep_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adityabhushan

**Comment by nalinbhardwaj** [comment]
Fixed vai #3946. Please review :)
