### ISSUE TITLE
Rails Console Cheat Sheet

### ISSUE THREAD

**Issue by GPhantom** [duckduckgo/zeroclickinfo-goodies#3952]
------
IA Page:  http://duck.co/ia/view/rails_console_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GPhantom

**Comment by pjhampton** [comment]
Hey @GPhantom, 

Thanks for your suggestion! 😄  As cheat sheets trigger for such a small share of the overall query space, your suggestion may or may not be a good direction at the moment. We will close this for the time being and revisit in the future. 

If you are looking for something more substantial to work through that will have a big impact for the users of DuckDuckGo, please check out the [DuckDuckHack Issues Table](https://duckduckhack.com/issues). 🚀  😄
