### ISSUE TITLE
Conversions: Add support for transfer rate conversions

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3955]
**convert 50 Mbps to Kbps**
[https://duckduckgo.com/?q=convert%2050%20Mbps%20to%20Kbps](https://duckduckgo.com/?q=convert%2050%20Mbps%20to%20Kbps)
   
------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@bsstoner I'll do this after https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3917 and https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3918

**Comment by mintsoft** [comment]
Related: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3544

**Comment by anewuser** [comment]
Make sure it's case-sensitive for queries like `10Mbps to MBps` to work.

**Comment by pjhampton** [comment]
Looks like this has been solved 👍 
Adding case sensitivity to upcoming PR.
