### ISSUE TITLE
W3m cheat sheet: 

### ISSUE THREAD

**Issue by d-nnis** [duckduckgo/zeroclickinfo-goodies#3959]
Not an issue really, rather a THANK YOU!
Anyway, might I suggest to offer a _printable_ button for this splendid overview of shortcuts? Might be difficult with layouting and such things... Along the lines of the attached PDF.
[W3M-Shortcuts.pdf](https://github.com/duckduckgo/zeroclickinfo-goodies/files/791488/W3M-Shortcuts.pdf)

------
IA Page:  http://duck.co/ia/view/w3m_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @preemeijer

**Comment by preemeijer** [comment]
Hello @d-nnis, thank you for telling us this. Appreciate it.
There has been some talks around IA's and making them printable. Not only this cheat sheet.

This "issue" can be closed. And thanks again for your feedback.
Cheers, Paul
