### ISSUE TITLE
Timezone Converter: EEST issue?

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#3964]
**7:00 AM CST to EEST**
[https://duckduckgo.com/?q=7%3A00%20AM%20CST%20to%20EEST](https://duckduckgo.com/?q=7%3A00%20AM%20CST%20to%20EEST)
_Comment: It considers EEST as UTC+3 when it's UTC+2_

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by adityatandon007** [comment]
@bsstoner I think its working alright as EEST(Eastern european summer time also known as daylight time) is (UTC+3) though it used by only some countries and they switch back to the standard eastern time in winters.
UTC+2 is for EET(Eastern european time) which is the standard. I think the conversion is working fine.

![screenshot from 2017-02-22 23-30-00](https://cloud.githubusercontent.com/assets/25108385/23225191/0a6980e6-f957-11e6-81b8-2e96ff8bbbf2.png)
![screenshot from 2017-02-22 23-30-24](https://cloud.githubusercontent.com/assets/25108385/23225192/0a6a52f0-f957-11e6-9b0a-1924fa8a4af3.png)

**Comment by bsstoner** [comment]
👍  I think you're right, thank you.
