### ISSUE TITLE
MD5: Ignore filenames

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3974]
### Description

Based on [feedback](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3901), one user was confused about the MD5 Instant Answer. They believed the md5 hash was for that file, and not the string "tails-i386-2.10.iso". 

![screen shot 2017-03-02 at 4 00 58 pm](https://cloud.githubusercontent.com/assets/8960296/23515335/c72594e4-ff61-11e6-9a9b-3bafa4bf4c8a.png)

We need to update this IA so that it ignores file names. A suggested implementation would be to find file names with probable extensions using a RegEx.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: http://duck.co/ia/view/md5

**Comment by GPhantom** [comment]
So if the query was "anything.anything" then ignore it or just ignore a specific files format?

**Comment by pjhampton** [comment]
I think we can focus on common file extensions for now 😄  https://fileinfo.com/filetypes/common

**Comment by GPhantom** [comment]
No I mean what we are trying to achieve with the regular expressions? if the query contains .commonfileextension then return? @pjhampton

**Comment by GPhantom** [comment]
I think I can do this, can you assign me? @pjhampton
