### ISSUE TITLE
Conversions: Round to appropriate decimal place

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3984]
### Description

User feedback suggests that [rounding to 3 decimal places is confusing](https://duckduckgo.com/?q=cup+to+gallon&ia=answer). 

A more appropriate response for this search would be **1 Cup = 0.0625 Gallon**. We could do with a solution to display the appropriate number of decimal places.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
@pjhampton This might be fixed here already: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3917
