### ISSUE TITLE
Dice: Set upper limit on max dice rolls and number of sides per dice

### ISSUE THREAD

**Issue by 8084** [duckduckgo/zeroclickinfo-goodies#3989]
## Problem
When the Dice Goodie is given an extremely large number of sides for a dice roll, the DuckDuckGo UI breaks.

Eg. https://duckduckgo.com/?q=roll+6d12000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

## Solution

We should:
1. Limit the max number of simultaneous dice rolls to **10**
2. Limit the max number of sides for a given dice to **31**

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---
https://duck.co/ia/view/dice

**Comment by nalinbhardwaj** [comment]
I'm not sure what the reason is, but it seems to break when rolls or faces are greater than 10^200, if this is of help to anyone. [example](https://duckduckgo.com/?q=roll+100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d6)

**Comment by nalinbhardwaj** [comment]
Actually just checked properly, the rolls in the internals of the IA are all `inf` in such queries(overflow). Is it best to just ignore such queries and not return instead of breaking the page?

**Comment by nalinbhardwaj** [comment]
I've made a fix for this in [nalinbhardwaj/dice-overflow-fix](https://github.com/nalinbhardwaj/zeroclickinfo-goodies/tree/dice-overflow-fix) and also added a couple tests to check it. If everyone thinks it's best to not return anything in case of overflow, I'll make a PR with those changes. @8084 @pjhampton thoughts?

**Comment by pjhampton** [comment]
I just chatted with @moollaza. Rather than try identity infinite numbers, we should enforce a hard limit to the number of die.

**Comment by nalinbhardwaj** [comment]
@pjhampton that would still cause breaking of [this query](https://duckduckgo.com/?q=roll+100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d6) and I'm not sure why it's a worse idea to check infinity than imposing hard limits?

**Comment by moollaza** [comment]
@nalinbhardwaj let's just set a very sane upper limit on the number of and the max sides for the dice.

I can we can limit to 10 dice, and max of 31 sides according to https://commons.wikimedia.org/wiki/Dice_by_number_of_sides

**Comment by nalinbhardwaj** [comment]
@moollaza Personally I don't see a point in limiting the search engine capabilities when we can clearly support the queries easily. Maybe check the traffic data with more than 10 dice or more than 31 sides?

**Comment by nalinbhardwaj** [comment]
@moollaza I don't see a very good point in limiting the search engine capabilities when we should be able to support those queries. Maybe look into the traffic data for > 10 dice or > 31 sides?

**Comment by moollaza** [comment]
> Maybe look into the traffic data for > 10 dice or > 31 sides?

@nalinbhardwaj I checked, but we don't have much info for this IA because it triggers very little. The few queries I saw were related to rolling a single dice a few times. e.g. "roll a dice 4 times"

We'll be OK with using sane limits. I can't see what practical use someone has for rolling a 100+ sided dice, or rolling more than 10 die simultaneously.

Any dice roll result that involves scientific notation is just silly :)

We can always increase the limits if needed, but I don't expect we'll need to

**Comment by 8084** [comment]
I don't think side count should be limited. Actually I was not aware of the rules saying that each dice must have maximum 31 sides.

Someone would probably call me a strange person, but I like to kill my time rolling a dice until I guess the number. And if there would be no more than 31 sides, ddg roll function will be pretty useless for this purpose.

**Comment by nalinbhardwaj** [comment]
I think the best idea that keeps in account requests such as @8084's might be to limit sides and rolls at much higher constants(something like 10^4). Thoughts @pjhampton @moollaza ?

**Comment by moollaza** [comment]
> Thoughts @pjhampton @moollaza ?

We have a random number Goodie that can be used for what @8084 describes: https://duckduckgo.com/?q=random+number+between+1+and+1000&ia=answer

It only generates a single random number, but I see no reason why it can't be extended to provide multiple random numbers.

I don't see why a dice roll Instant Answer should deal with such large numbers though, especially when it's very unlikely to ever be used.

**Comment by moollaza** [comment]
For now, let's go with my recommendation so we can fix this bug. We can debate if the limits for the dice Goodie should be increased once the bug is fixed 😃

**Comment by lernae** [comment]
Hi @moollaza- I'm interested in working on this.
