### ISSUE TITLE
Conversions: Mistaking MB for Mb

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3990]
### Description

Based on some user feedback, the [Conversions IA](https://duck.co/ia/view/conversions) is not disambiguating between MegaBytes (MB) and MegaBits (Mb). It is, therefore, nessesary to extend this IA to solve this issue

#### Correct 👍 

![screen shot 2017-03-08 at 1 49 40 pm](https://cloud.githubusercontent.com/assets/8960296/23706463/33966394-0406-11e7-84e3-20c7004631fd.png)

#### Not Correct 👎 

![screen shot 2017-03-08 at 1 49 26 pm](https://cloud.githubusercontent.com/assets/8960296/23706457/298b46ee-0406-11e7-99d5-4e6e29b27927.png)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by nalinbhardwaj** [comment]
I think it's a better idea idea to make a separate issue to add case sensitivity to the IA. This and [some other units](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3885#issuecomment-275150788) can be sorted out with that.

**Comment by mintsoft** [comment]
Basically a duplicate: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3544

**Comment by pjhampton** [comment]
Thanks! Yeah, it's quite chaotic at the moment due to the backlog of solicited + unsolicited issues / prs. One thing that we're taking away from the Programming Mission is the success of consistent and descriptive task templates / Meta Issues. The highest priority tasks are coming from the SERP feedback box. The reason for this is that the feedback is internally vetted and search data is analyzed against the feedback. We'll continue #3544 here.

**Comment by nalinbhardwaj** [comment]
@mintsoft if you're not working on this issue I can take it up. Also I think this issue should be expanded to enable case sensitivity for all units.

**Comment by mintsoft** [comment]
@nalinbhardwaj I am already working on it, I'm waiting for https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3988, then case sensitivity is the next step

**Comment by mintsoft** [comment]
Actually; I missed one, this is next after https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3993 / https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3918

**Comment by mintsoft** [comment]
@pjhampton Having just looked at it, this is *definitely* not low hanging fruit; it's going to be ... interesting getting this to behave as users expect

**Comment by pjhampton** [comment]
Sure, @mintsoft. Someone labeled it low hanging fruit in the internal pipeline - I didn't look into it enough to dispute this reasoning. Feel free to adjust the labeling as you feel fit.

**Comment by mintsoft** [comment]
@pjhampton I just noticed that both of the screenshot examples are wrong! The first query is actually `kilobits to megabytes` and the second is `kilobits to megabits` both mistreat `Kb` as kilobytes

**Comment by pjhampton** [comment]
@mintsoft Ah, nice catch! 😄 
That's interesting though because that was the user's exact query from the feedback. I believe they were expecting a conversion from Kilobytes. Thanks for pointing this out! I will update the description later on for the sake of clarity 👍
