### ISSUE TITLE
Reference: Create ASCII Codes Table

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3991]
#### Problem

Currently, we have an internal ASCII Table that is rendered via an iframe on the SERP (Search Engine Results Page). Users have complained that the table doesn't look great with the Dark theme because of the black text (see Screenshot 2). 

#### Screenshot 1 (Default theme)
![white](https://cloud.githubusercontent.com/assets/8960296/23720437/9482a0d4-0436-11e7-9155-6eeef9cf04a6.png)

#### Screenshot 2 (Dark Theme)
![black](https://cloud.githubusercontent.com/assets/8960296/23720438/94869c20-0436-11e7-9c80-d7abce714c68.png)

### Solution

Reimplement this as an open source **Goodie with a custom template**. The internal IA can then be deprecated in favour of this community built Instant Answer.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: N/a

**Comment by mintsoft** [comment]
@pjhampton Not sure there's really perl or skill required for this, it'll just be returning the template. All the work will actually be in the template itself I think?

**Comment by pjhampton** [comment]
Yeah, @mintsoft. You are right. However, the plan is to abstract whatever the contributor creates and turn it into a reusable table template: https://github.com/duckduckgo/duckduckgo-answerbar-templates

Due to this, it would probably be ideal that the data is loaded into the table, rather than hard coded. Opinions?

**Comment by ManrajGrover** [comment]
@moollaza @pjhampton I can take this one up. I would be needing inputs on the design. 😄

**Comment by moollaza** [comment]
> I would be needing inputs on the design.

Sure thing! We'll be able to give some design feedback once we have something working on Beta. I think for now we can replicate the layout/design of the table. We can probably kill the red text in favour of a darker grey though 👍

**Comment by pjhampton** [comment]
Hey @ManrajGrover,

How are you getting on? Do you have any questions, etc? 😄

**Comment by ManrajGrover** [comment]
@pjhampton Pretty well. 😄 Expect a PR soon. :)
