### ISSUE TITLE
Public DNS: Privacy and security improvements

### ISSUE THREAD

**Issue by DeltaHeavy** [duckduckgo/zeroclickinfo-goodies#3992]
Remove "Comodo Secure DNS" as Comodo has a terrible history of security and privacy (promoting use of their Chrome and FF clones with Same Origin-Policy removed), bad Certificate Authority practices, etc.

Remove or put an asterisk or footnote on Google DNS, as one of the major purposes of DuckDuckGo is to avoid the monolithic privacy violation that is Google's data collection machine.

Put a footnote next to any DNS servers which support DNSSEC.

Thank you!

------
IA Page:  http://duck.co/ia/view/public_dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mailkov

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
