### ISSUE TITLE
Reference: New HTML Entities Table

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#3998]
### Problem

Currently, there is an [HTML Entities](https://www.w3schools.com/html/html_entities.asp) table rendered through an iframe by the internal team. It's cool, but:

1. It doesn't look great in one of the darker themes (see Screenshot 2)
2. It's not open source.

**Screenshot 1 (Default theme)**

![screen shot 2017-03-09 at 8 35 02 pm](https://cloud.githubusercontent.com/assets/8960296/23769943/01115cfe-0509-11e7-9fb3-3e92adfa9389.png)

**Screenshot 2 (Darker theme)**

![screen shot 2017-03-09 at 8 34 50 pm](https://cloud.githubusercontent.com/assets/8960296/23769932/fa19b9be-0508-11e7-8adf-1c942d59a37f.png)

## Solution

Reimplement this as an open source Goodie with a custom template. The internal IA can then be deprecated in favour of this community built Instant Answer.

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by Owlree** [comment]
I would like this. 😄

**Comment by mintsoft** [comment]
Thanks @Owlree Can you open a PR so we can reference it from this issue?

**Comment by mintsoft** [comment]
Also, can you apply to join https://github.com/orgs/duckduckgo/teams/duckduckhack-contributors so I can assign this to you? :+1:

**Comment by Owlree** [comment]
@mintsoft I am in the organization now, you can assign it to me. I'll open the PR soon enough as well.

**Comment by pjhampton** [comment]
How are you getting on, @Owlree? 😄  Do you have any questions or need some help?

**Comment by Owlree** [comment]
@pjhampton No questions for now. Paradoxically, it seems that I have less free time since I quit my job. I'll get it done over the weekend though.

**Comment by pjhampton** [comment]
@Owlree No problem! I'm around over the weekend so just ping me if you need some help 😄
