### ISSUE TITLE
Release Atbash

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#400]
Looks like it was merged a year ago. See if we can get it ready for BTTF release.

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Atbash.pm

**Comment by javathunderman** [comment]
@jagtalon Is this up?

**Comment by javathunderman** [comment]
@moollaza Seems like this is ready to go then? Is there anything to do?

**Comment by moollaza** [comment]
Setup for release.
