### ISSUE TITLE
Radare2 Cheat Sheet: 

### ISSUE THREAD

**Issue by rubikkk** [duckduckgo/zeroclickinfo-goodies#4008]
hello! I was looking for r2 debug mode commands, and I realized they're not in the CS so I added them :)

------
IA Page:  http://duck.co/ia/view/radare2_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @therealkbhat

**Comment by pjhampton** [comment]
Thanks @rubikkk,

This reads like a PR, but it's an issue. I think there may have been a mistake. Closing. Reach out if I'm wrong.
