### ISSUE TITLE
Dice: Footer redundancies

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-goodies#4014]
### Description

Queries like `roll 3d12 and 2d4` have a redundant "Show more" button at bottom which does nothing(disappears on-click). It's useless for only upto 3 rows in table.

Also, the `|` is redundant and seems out of place. The template probably needs modifications for the IA.

I'll try to fix these and make a PR. If not, someone else should take this up.

## Steps to recreate

[roll 3d12 and 2d4](https://duckduckgo.com/?q=roll+3d12+and+2d4&ia=answer)

## People to notify

@loganom 

---

Instant Answer Page: https://duck.co/ia/view/dice

**Comment by pjhampton** [comment]
Hmm, I think this may be an issue with [the template](https://github.com/duckduckgo/duckduckgo-answerbar-templates) rather than the IA.

**Comment by kirkins** [comment]
This seems to be fixed, I'm not seeing a "show more" button.

**Comment by nalinbhardwaj** [comment]
@kirkins perhaps this is browser dependent, but I'm still seeing the button(and dissapearing) in Safari version 10.1

**Comment by kirkins** [comment]
My mistake I was just searching "roll 3d12" not "roll 3d12 and 2d4".

**Comment by marianosimone** [comment]
I, too, think, that this is related to the template (see [here](https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/master/detail/list_detail.handlebars#L25)), which includes [chomp_links](https://github.com/duckduckgo/duckduckgo-answerbar-templates/blob/fa9f96d3a599ae486982b196591b457e0852a5c9/shared/chomp_link.handlebars), regardless of if they should be shown or no.

I couldn't find the js logic that ends up removing the whole thing if you click on "Show more" and then "Show less", though. Any pointers from @pjhampton on how to work on the templates repo and try stuff out there?

As a side note, this is somehow related to https://github.com/duckduckgo/duckduckgo-answerbar-templates/issues/16, which also shows that affects all other IA that use the list template (and probably others)

**Comment by moollaza** [comment]
@marianosimone is correct -- this is an internal bug related to our chomp functionality. I'll close this and move the bug report internal.
