### ISSUE TITLE
Public DNS: More public DNS servers (Freenom World)

### ISSUE THREAD

**Issue by xtaran** [duckduckgo/zeroclickinfo-goodies#4016]
Missing public DNS servers:

* 80.80.80.80 (Freenom World, see http://www.freenom.world/en/index.html)
* 80.80.81.81 (Freenom World, see http://www.freenom.world/en/index.html)

------
IA Page:  http://duck.co/ia/view/public_dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mailkov

**Comment by mintsoft** [comment]
@xtaran Many thanks for the suggestion, looks good. 

If you're at all interested you could add these yourself! We keep these in https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/public_dns/providers.yml feel free to do a PR. If not, someone from the community will pick it up :+1:
