### ISSUE TITLE
Public DNS: Mention that the well-known Level 3 DNS servers at 4.2.2.[1-6] should no more be used

### ISSUE THREAD

**Issue by xtaran** [duckduckgo/zeroclickinfo-goodies#4017]
It would be nice if there would be a footnote or similar added to the Level 3 entry that the Level 3 DNS servers under 4.2.2.[1-6] (especially 4.2.2.2 and 4.2.2.4) might be working as public DNS servers, but should not be used as they are not meant as public DNS servers.

They're not listed (probably on purpose), but still well-known and such a comment will likely avoid people filing bug reports to get them (re-)added.

As reference, https://www.tummy.com/articles/famous-dns-server/ is probably a good link.

------
IA Page:  http://duck.co/ia/view/public_dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mailkov

**Comment by mintsoft** [comment]
I think if they're not meant to be public we might as well just remove them. There's plenty of other actually public DNS servers available on the list

**Comment by xtaran** [comment]
@mintsoft: No need to remove anything. As I wrote, they're not listed, but well-known due to their easy to remember IP addresses.

**Comment by mintsoft** [comment]
Ah sorry, I totally misinterpreted what you meant there

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
