### ISSUE TITLE
AltCal: no results for example query

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#402]

**Comment by moollaza** [comment]
This one should be converted to a structured answer, or it could use the text template!

**Comment by marianosimone** [comment]
Seems like the code for this was already converted to a structured answer, but it's somehow disabled.

Anything we can do to help get it released (or discarded)?

**Comment by zekiel** [comment]
@rafacas  do you need any particular help?

**Comment by jdorweiler** [comment]
This is it? https://duckduckgo.com/?q=meiji+1&ia=answer

**Comment by javathunderman** [comment]
@marianosimone any update on this?

**Comment by jdorweiler** [comment]
Looks like it works now.
