### ISSUE TITLE
Calculator: [Stage 1] Add Interactive UI to Calculator

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4020]
## Problem

A lot of user feedback has requested an interactive calculator. A [Pull Request was created 2 years ago](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1727) to create a JS based interactive calculator... but was unfortunately never finished. It was first implemented as a Spice, but it should now be created as a Goodie. There is now 30 open issues against the calculator IA. We should put them all on hold to get this working.

![Screenshot](http://i.imgur.com/aMhOLwf.png)

## Solution [Stage 1]

For now, we should reduce ambitions and be more realistic. 

The developer should: 

1. Implement these UI assets on top of the existing [calculator Instant Answer](https://duck.co/ia/view/calculator)

2.  Get the basic calculations to work. See stage 1 in the figure below (Red box).

![687474703a2f2f692e696d6775722e636f6d2f614d684f4c77662e706e67](https://cloud.githubusercontent.com/assets/8960296/24167471/c61d3e64-0e6e-11e7-98cd-2d0c5895b02f.png)

## Implementation

- Use `DDG.require("math.js", function(){ ... })` to make Math.js available to the Instant Answer

This is a top priority task and requires an experienced DuckDuckHack contributor.

## People to notify

- @pjhampton
- @moollaza 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by pjhampton** [comment]
cc. @zodiac403, @Lord-Lavios

**Comment by kirkins** [comment]
Anyone working on this right now?

**Comment by Lord-Lavios** [comment]
@kirkins I was going to start working on this tomorrow but if you want to work on this, go ahead.

**Comment by kirkins** [comment]
In the implementation there is a `math.js` mentioned. I've looked through the file structure of the repo a few times and don't see it.

Would that be a completely new file or am I missing it?

**Comment by pjhampton** [comment]
This is a difficult / high-priority / urgent issue @kirkins. Please only take it if you feel you have the programming expertise to take it forward 👍 

As for math.js, this was added by the internal guys last week. To bring it into scope, you would wrap the logic with the following statement. 

`DDG.require('math.js', function(){})`

An example would be https://github.com/duckduckgo/zeroclickinfo-goodies/blob/ba2760f03485f32f10de1e85c19b11415cb8528b/share/goodie/countdown/countdown.js#L143

**Comment by kirkins** [comment]
@pjhampton thanks for the example. I'm still wondering where to see the contents of `math.js` ?

Same for the `moment.js` file in the example you posted. Doing a [search for moment.js ](https://github.com/duckduckgo/zeroclickinfo-goodies/search?utf8=%E2%9C%93&q=moment.js&type=)I only find that single reference. 

Are these two files closed source or located in another repo?

**Comment by kirkins** [comment]
@pjhampton I will let @Lord-Lavios work on this one since it is high-priority and this would be my first duckduckgo module.

I have another idea to improve a different IA module anyways. Though I'm still curious about my question above.

**Comment by pjhampton** [comment]
That's fine 😄  These are external dependencies. See [Math.js](https://github.com/josdejong/mathjs).

Using math.js allows strings to be easily evaluated as mathematical expressions, using the `math.eval()` function. [Moment.js](https://momentjs.com/) is also an external dep but has nothing to do with this project. Hope that helps!

**Comment by pjhampton** [comment]
@Lord-Lavios so can I take it you're happy taking this forward? 😄

**Comment by Lord-Lavios** [comment]
@pjhampton I'll take it. I've been looking around and I've got some questions.

Do all the queries(using the calculator) get calculated in the back end or only the initial one(the one that triggers the IA)? If all, then how can I send the query to the server, I wasn't able to find any documentation on this.

How can I detect if the user is using the dark or light mode for the search engine, this is to switch the calculator theme?

**Comment by Lord-Lavios** [comment]
@pjhampton 👍 Sorry, for the delay. I wasn't able to find time earlier and then it took some time to figure out how to do it and stuff.

**Comment by pjhampton** [comment]
That's cool, @Lord-Lavios 💙  Thanks anyway!
