### ISSUE TITLE
Chars: Fix Overtriggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4028]
## Problem

From query data, it seems that this IA is overtriggering like crazy. This is down to two things, **poor triggering** and **the position of the trigger words in the query**. 

![screen shot 2017-03-22 at 8 59 31 pm](https://cloud.githubusercontent.com/assets/8960296/24220569/9fec0430-0f42-11e7-8df0-a84bd6b7139d.png)

## Solution

The handle setting should be set to start only, and some of the less intuitive triggers should be removed such as `chars`, and `length of string`.

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page:https://duck.co/ia/view/chars

**Comment by SophieDurrant** [comment]
I can claim the issue

**Comment by SophieDurrant** [comment]
Should I also remove the leading word 'of' so 'length in characters of foo' shows up 3 instead of 6?

**Comment by pjhampton** [comment]
Yeah, that would be a good idea 👍
