### ISSUE TITLE
Timer: Always shows 1 minute

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4035]
Set the timer for any length of time, it will only countdown from one minute, e.g.:

https://duckduckgo.com/?q=9+minute+timer

https://duckduckgo.com/?q=timer+5+seconds

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by mattr555** [comment]
Can't test for sure at the moment but I'm pretty sure #4034 will fix this.

**Comment by moollaza** [comment]
This was my mistake. Fixed in #4034
