### ISSUE TITLE
Awesome Window Manager Cheat Sheet: New Documentation URL

### ISSUE THREAD

**Issue by azhargiri** [duckduckgo/zeroclickinfo-goodies#4036]
Awesome window manager documention URL now move to https://awesomewm.org/doc/manpages/awesome.1.html   

------
IA Page:  http://duck.co/ia/view/awesome_window_manager_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @kennyballou

**Comment by kennyballou** [comment]
I need to update the commit, but this will be fixed shortly.
