### ISSUE TITLE
Timer: Improve triggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4038]
## Problem

Based on user feedback and unanswered query data, This IA isn't triggering enough. @moollaza just merged a PR that ported this IA from a Spice to a Goodie.

**Triggering** 👍 

![screen shot 2017-03-24 at 6 55 21 pm](https://cloud.githubusercontent.com/assets/8960296/24309573/42fd6178-10c4-11e7-8dd2-a184b6692bfb.png)

**Not triggering** 👎 

![screen shot 2017-03-24 at 6 55 38 pm](https://cloud.githubusercontent.com/assets/8960296/24309589/5314b660-10c4-11e7-9827-9811f40dab30.png)

## Solution

1. Add one, two, or three tests! 😉 
2. Add the trigger words `mins`, `minutes`

## People to notify

@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/timer

**Comment by TheSpeedyBlur** [comment]
Is anyone working on this? I would like to, if it's possible. (I'm new btw, I'm still reading the contrib guide 😝)

**Comment by ManrajGrover** [comment]
@TheSpeedyBlur Great! Sure, go ahead with this. If you face any issue, feel free to ping on Slack.

**Comment by TheSpeedyBlur** [comment]
Okay, I'm sorry, I was too dumb to look at this issue in detail, and I'm sorry, I would like to cancel my application for this issue. I'm new to the programming language (perl) and this task is too complex for me at the first try. I've been sitting on it for two hours, and again, I'm sorry for dropping this, but I'm afraid I would only be able to accomplish progress if I would rewrite the whole Timer script. 😞

**Comment by BillyBarbaro** [comment]
@TheSpeedyBlur I know perl can be a bit intimidating (I'm relatively new to it myself), but I don't think this would be too hard with a bit of help.  I'd be willing to point you in the right direction if you still want to take the issue.  Ping me on Slack (my username there is the same as my Github) and let me know.  We could figure out this one together.

**Comment by TheSpeedyBlur** [comment]
@BillyBarbaro I'd be happy to do this actually and if you're willing to help me I'd be glad. I will ping you on slack when I'm available.

**Comment by pjhampton** [comment]
Thanks very much @TheSpeedyBlur and @BillyBarbaro!! I noticed you're not part of the DDG org on Github @TheSpeedyBlur, so I have only assigned @BillyBarbaro for the time being. 💙  💛  💜  ❤️

**Comment by TheSpeedyBlur** [comment]
@pjhampton Should we trigger on `hours / hrs`, `seconds / secs` as well.
