### ISSUE TITLE
Release BirthStone

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#404]

**Comment by javathunderman** [comment]
@jagtalon I assume this is ready to go up, no?

**Comment by javathunderman** [comment]
@moollaza Saw this in while developing the Sales Tax goodie. The code seems to run fine and responds when I start up DuckPAN. Should this be closed then?

**Comment by moollaza** [comment]
Code LGTM :+1: 

Needs design sign off:

![2015-01-30_17h26_09](https://cloud.githubusercontent.com/assets/873785/5984539/29c2d15e-a8a5-11e4-9fb4-911782a75deb.png)

**Comment by javathunderman** [comment]
@moollaza Great!

**Comment by moollaza** [comment]
Setup for release.
