### ISSUE TITLE
Sudoku on complete check if user was correct

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-goodies#4045]
## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by pjhampton** [comment]
Thanks, @kirkins.

The way this is written, I'm not sure how we/I can act on this. Please follow best practices when opening Issues in the future, and be as descriptive as possible.

**Comment by kirkins** [comment]
I'm not sure how one would expand on this.

1.Play Sudoku
2. Be done game
3. Have no way to know if correct without checking manually

**Solution Idea #1:** Add a check button, when clicked check if all columns filled out, if yes check logic for winning sudoku.

**Solution Idea #2:** Use event listener each time column filled out, if all columns filled out return correct or incorrect to user.
