### ISSUE TITLE
Calculator: support equals sign when triggering percentage queries

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4052]
## Problem

Based on user feedback, the calculator is not triggering on the query `7970 - 20% =`, but triggers on `7970 - 20%`. 

**Triggers** 👍 

![screen shot 2017-03-28 at 10 06 24 am](https://cloud.githubusercontent.com/assets/8960296/24397785/304f4dce-139f-11e7-9f4b-3c9be32d2133.png)

**Doesn't Trigger** 👎 

![screen shot 2017-03-28 at 10 06 54 am](https://cloud.githubusercontent.com/assets/8960296/24397793/36738d00-139f-11e7-9b39-e631fb67d764.png)

## Solution

1. Add a test, or two!
2. The user should update the [query handling regex](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/PercentOf.pm#L16) to also make this trigger appropriately. 

## People to notify
@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by edcallaghan** [comment]
Can claim issue. Already submitted pull request,
