### ISSUE TITLE
Release GreatestCommonFactor

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#407]
example: https://next.duckduckgo.com/?q=99+9+greatest+common+factor

**Comment by javathunderman** [comment]
@moollaza Based on what @jagtalon said, is this ready to go?

**Comment by moollaza** [comment]
Code LGTM :+1: 

The design team still needs to review these older Goodies though, I'll speak with them.

![2015-01-30_13h57_00](https://cloud.githubusercontent.com/assets/873785/5981402/e041ffe0-a887-11e4-8e6f-13a89cbfd309.png)

Some room for improvement though in handling more than two input numbers.

**Comment by javathunderman** [comment]
Good to see this going up then!

**Comment by moollaza** [comment]
Setup for release. Improvement task made: #1031
