### ISSUE TITLE
most results in 404 errors on webmd.com

### ISSUE THREAD

**Issue by krihsna** [duckduckgo/zeroclickinfo-goodies#4074]
when i search for anything, if webmd.com is the first result, if i click the webpage, it shows 404 error, i am providing two links with issue.

https://duckduckgo.com/?q=grapes+uses&t=fpas&ia=web

https://duckduckgo.com/?q=Cardamom+uses&t=fpas&iax=1&ia=images

**Comment by kirkins** [comment]
When I click the webmd link from the first one the website loads fine for me. Try using another browser/computer and see if you get the same results?

**Comment by adityatandon007** [comment]
Its working fine for me. @krihsna I think the problem seems to be at your end regarding connection.

**Comment by pjhampton** [comment]
I can't reproduce either. I think this is probably to do with webmd redirecting you based on your IP data.
