### ISSUE TITLE
Calculator: Decimal numbers too long for box

### ISSUE THREAD

**Issue by roastchicken** [duckduckgo/zeroclickinfo-goodies#4075]
The calculator goodie appears to truncate decimal numbers at 15 places. This sometimes causes the number to be too wide to be displayed, in which case the leading part of the number runs off and can't be seen. I think it would make more sense to left-align the number once it gets too wide for the box, or simply truncate to a shorter length to prevent this from happening.

Note: This does not appear to affect calculations entered into the calculator, only calculations entered into the search box. Calculations entered into the calculator seem to truncate at 11 decimal places.

![Screenshot showing number being too large for box](http://i.imgur.com/OGPXjL7.png)

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by pjhampton** [comment]
Thanks for the feedback, @roastchicken! 

This will close this because of my PR to implement the scientific calculator next week and add it to my backlog here for mobile devices.

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4067
