### ISSUE TITLE
Empty 'Full example' field

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-goodies#4076]
### Description

The full example field is shown on this search but is only populated if you press show more. 

## Steps to recreate

https://duckduckgo.com/?t=palemoon&q=curl+json&ia=qa

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/stack_overflow

**Comment by pjhampton** [comment]
@kirkins this is a longtail, not a goodie. There is nothing we can do in this repo 👍  Please reopen this issue in the longtail repo
