### ISSUE TITLE
HTML Entities: Add additional trigger words

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4086]
## Background

The current existing hard-coded iframe appears for the following queries:

- html characters
- html chars
- html named characters
- html escape sequences
- html entities
- html named entities
- html entities codes

We should ensure we continue to show the new open source IA for the same set of queries.

## What to do

- Add the above trigger words to the `triggers` in `[HtmlEntities.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/HtmlEntities.pm#L13)`
- Adjust the regex in the `handle` function accordingly

/cc @Owlree 

------
IA Page:  http://duck.co/ia/view/html_entities

**Comment by Owlree** [comment]
You can assign me. 😀

**Comment by ManrajGrover** [comment]
@Owlree Go ahead! 😄

**Comment by moollaza** [comment]
@Owlree thanks! I added one more trigger phase btw 👍

**Comment by Owlree** [comment]
Shall I add all of them in a .txt file and use that as a list of triggers?

**Comment by ManrajGrover** [comment]
@Owlree Yes, please do.
