### ISSUE TITLE
Timer: Stop triggering on edge cases

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4089]
### Problem

We need to update the triggers for the Timer IA so it **doesn't trigger** under ambiguous cases. These are:

1. `20 minutes`
2. `60 minutes`
3. `48 hours`

_These are navigational queries where a user is trying to get to specific news websites_

![screen shot 2017-04-13 at 3 28 59 pm](https://cloud.githubusercontent.com/assets/8960296/25009263/036fb778-205e-11e7-93e0-b2ff818b7964.png)

## Solution

1. Add 3 tests, each covering a case in [Timer.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Timer.t)

2. Update [Timer.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Timer.pm) to stop trigger on these specific edge cases.

3. Test it (`duckpan test timer`). Make sure all tests pass!

4. Create a PR

## People to notify

@pjhampton @moollaza 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/timer

**Comment by shivam99aa** [comment]
Hi, I would like to take ownership of this task.

**Comment by pjhampton** [comment]
Awesome! Thanks @shivam99aa! It's all yours 👍

**Comment by moollaza** [comment]
@shivam99aa I've invited you to the DDH Org, please accept the invitation and ping us here so we can assign the issue to you 👍

**Comment by shivam99aa** [comment]
@moollaza Invitation accepted. You can assign the issue to me.

**Comment by shivam99aa** [comment]
Do we need to stop Timer IA on only above 3 cases or all such cases? 
If it is latter then Timer IA will not come on 15 minutes. Please clarify. @moollaza

**Comment by mintsoft** [comment]
@shivam99aa just the cases above, they're basically the name of american news programs

**Comment by bsstoner** [comment]
This was released to production 🚀
