### ISSUE TITLE
Combination: Add support for "nCr" and "nPr" triggers

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4091]
### Description
We should add support for queries of the format `\d+ nCr \d+` and `\d+ nPr \d+`

Examples:
- "20 nCr 5"
- "18 nPr 3"

## People to notify
@tagawa 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/combination

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @richardscollin

**Comment by shivam99aa** [comment]
nCr thing is already working at present while nPr is not working.
@tagawa  You can assign this issue to me and I will finish it for nPr too.

**Comment by tagawa** [comment]
Hi @shivam99aa - thank you for offering!

**Comment by shivam99aa** [comment]
It seems that I was wrong earlier and trigger for `nPr` is also present in the code. 
Although the behavior I am seeing while searching for ex `10 nPr 2` is that instead of showing answer it is showing news at the top by default.It is because nPr is also short for `national public radio`.
 If I manually click on `answer` link then it is shown that the IA is present there. I think there is nothing that needs to be done for this issue as both triggers are present. 

@moollaza @tagawa Can you please confirm this so that this issue can be closed or if there is still something that needs to be done here please update.

**Comment by richardscollin** [comment]
What are the criteria that it uses to match news articles? Is this code in an instant answer or something else? It appears that for some queries it doesn't match news articles e.g. 2 npr 1 while others it does: 10 npr 5.

**Comment by shivam99aa** [comment]
If you check in the search results which are coming. There will be some result present which will match one number present in the search. This might be causing news article to come instead of IA.

**Comment by shivam99aa** [comment]
Can someone update me how news gets triggered and we actually need to edit that code to not get triggered for this scenario. Combination IA is perfect and nothing needs to be done here.

@tagawa

**Comment by mintsoft** [comment]
@moollaza @tagawa  Those queries are already answered : https://duckduckgo.com/?q=10+nPr+4&t=vivaldi&ia=answer
https://duckduckgo.com/?q=10+nCr+4&t=vivaldi&ia=answer 

I don't see there's anything to do here at all

**Comment by richardscollin** [comment]
@minsoft entering `10 npr 5` in my browser results in the following url: https://duckduckgo.com/?q=10+npr+5&t=fpas&iax=1&ia=news

Note that for `10 npr 4` it seems to work as expected. As @shivam99aa mentioned it looks like it depends if the news article contains one of the given numbers.

Seeing as the answer is still calculated and just in a separate clickable tab I don't think it's a big issue. It would be preferable for queries like this to default to showing the result of the calculation though. This would require changes elsewhere in whatever triggers the news instant answers or whatever selects the default shown ia.

**Comment by mintsoft** [comment]
@richardscollin We can return high signal for this IA to take precedence (like: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/ba2760f03485f32f10de1e85c19b11415cb8528b/lib/DDG/Goodie/Constants.pm#L480 @moollaza I presume there's no issue with doing that?

**Comment by adityatandon007** [comment]
@mintsolft @moollaza I don't see any point why news is set to default in this case. I think what @mintsoft said

> We can return high signal for this IA to take precedence 
could be a way to handle this issue.

**Comment by richardscollin** [comment]
Would it be preferable to always enable high priority or restrict it to the cases with `npr` and `ncr` as the trigger words @mintsoft @moollaza ? Either way I can make a PR with the change once I know which way is preferred.

**Comment by shivam99aa** [comment]
@tagawa @moollaza Can someone comment on this issue on what will be the best approach to proceed on this?

**Comment by mintsoft** [comment]
@richardscollin I think so yes; if the IA returns an answer then I'd say the user's intention is probably to calculate the nCr or nPr rather than searching for the terms

**Comment by moollaza** [comment]
This was migrated from an older issue, but I'm not sure how I didn't see those results before!

I've adjusted the priority in the backend. Changes should be live in an hour or so 👍 

Thanks everyone
