### ISSUE TITLE
ASCII Codes Table Suggestion: more compact table

### ISSUE THREAD

**Issue by yugecin** [duckduckgo/zeroclickinfo-goodies#4092]
### Description

The new ascii table IA is far less compact as opposed to the old one. It requires more user input to find the desired value in the table (clicking on show more, scrolling). With the old one, I usually found what I was seaching for in the blink of an eye. See screenshot below for comparison.

![image](https://cloud.githubusercontent.com/assets/12662260/25040789/cdc340e6-210b-11e7-95e2-79a7906e3e7b.png)

## Steps to recreate

https://duckduckgo.com/?q=ascii+table

## People to notify

@ManrajGrover
@pjhampton

---

IA Page:  http://duck.co/ia/view/ascii_table 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover

**Comment by moollaza** [comment]
@yugecin thanks for bringing this up!

We are planning to find a better overall presentation for this. First we wanted to address the biggest complaint we get, which was the colour of the old result in the dark theme.

Next we'll be working with the design team to develop a better template for information dense Instant Answers like this 👍

**Comment by moollaza** [comment]
Marking as "On hold" while we think about this.

**Comment by ManrajGrover** [comment]
@yugecin Hi, thanks for opening this issue. 😄 

Currently, there are plans to generalize it as `table` template which other IAs can also use. If you have a design in mind, please do share here and we can discuss the same.

I'll be more than happy to make the required changes.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
