### ISSUE TITLE
Calendar: Shouldn't trigger on query for "calendar.google.com"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4102]
This IA triggers on the navigational queries for the Google Calendar website. We shouldn't show our calendar here as it's probably not relevant to someone who is trying to get to Google calendar.

https://duckduckgo.com/?q=calendar.google.com&ia=answer

This is partially due the the way the DDG lib handles trigger words. If there is no remainder, we need to verify that the `$query_lc == 'calendar';

------
IA Page:  http://duck.co/ia/view/calendar_today 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by lernae** [comment]
Hi @moollaza  I'd like to take this one.

**Comment by lernae** [comment]
Hi @moollaza, @pjhampton-  in addition to not triggering on "calendar.google.com", should it also not trigger on queries containing it such as "today calendar.google.com", "calendar.google.com tomorrow"?
