### ISSUE TITLE
ASCII Codes Table: Add additional trigger words

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4107]
# Background

The current existing hard-coded iframe appears for the following queries:

- ascii table
- ascii codes
- char codes
- character codes
- ascii character codes
- ascii codes
- ascii characters

## What to do

- Add the above trigger words to the `triggers` in `[HtmlEntities.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/HtmlEntities.pm#L13)`
- Adjust the regex in the `handle` function accordingly

------
IA Page:  http://duck.co/ia/view/ascii_table 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover

**Comment by adityatandon007** [comment]
@moollaza I'll like to take this up
