### ISSUE TITLE
Release Sudoku

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#411]
Make sure to have https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Sudoku.pm reviewed and released.

**Comment by moollaza** [comment]
This should be converted to use a template (potentially a custom template)

**Comment by GuiltyDolphin** [comment]
@jagtalon The tests for this seem to take quite a while (a few seconds on my machine), are there any easy ways to speed this up? Perhaps we could remove a couple of the tests that overlap somewhat?

Anyone else got this issue?

**Comment by mintsoft** [comment]
@GuiltyDolphin IIRC the sudoku generator module is extortionately slow

**Comment by moollaza** [comment]
I believe @Mailkov is working on a JS Sudoku lib and plans to use it for this IA. I was just about to close this task...

**Comment by moollaza** [comment]
> IIRC the sudoku generator module is extortionately slow

I believe in updating the IA @Mailkov realized this as well?
