### ISSUE TITLE
President of the United States (POTUS): 

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-goodies#4117]
Using POTUS keyword does not give results (example: https://duckduckgo.com/?q=potus%2016&ia=answer )   

------
IA Page:  http://duck.co/ia/view/potus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @numbertheory

**Comment by adityatandon007** [comment]
@x-15a2 I think this IA is offline for now. @moollaza can you start this IA

**Comment by moollaza** [comment]
More Details: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3760

**Comment by x-15a2** [comment]
Thanks for the info, I'll update my comments in the subReddit. Can someone update the information on the IA info page: https://duck.co/ia/view/potus ? Thanks!

**Comment by kirkins** [comment]
This should probably be re-enabled. I imagine it got more hits than other goodies like https://duck.co/ia/view/people_in_space

**Comment by kirkins** [comment]
Then again the wikipedia entry seems to have all the information needed and consistent triggering for "Xth president" queues.
