### ISSUE TITLE
Calculator: Trigonometric Result Error

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-goodies#4121]
**Calculator**: Degrees/Radian Issue

**Issue:**
The trigonometric expressions doesn't work in degrees.
Ex: `sin(45)+cos(45)` with `degree` as selected gives message `Error`  as result

![imageedit_2_6205813579](https://cloud.githubusercontent.com/assets/25108385/25332361/d4d45bd6-2903-11e7-9ce4-5ce1bdcb4dcf.gif)

**The result**

![imageedit_4_9626783065](https://cloud.githubusercontent.com/assets/25108385/25332373/df38e786-2903-11e7-945b-2309f15d2dd8.gif)

**Issue 2:** Two tabs for calculator

![imageedit_8_7346419040](https://cloud.githubusercontent.com/assets/25108385/25332420/0cdf3686-2904-11e7-974a-a7a328622c13.gif)

##People to notify

@pjhampton @moollaza 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Awesome! Thanks @adityatandon007 😄  I will look at this tonight.
We can deprioritize the Calculator tab issue as it's only an issue in duckpan and not in production.

**Comment by moollaza** [comment]
@pjhampton it's actually an issue in production as well. We have the Symbolab Spice that also doesn't calculations via an API. We need to prevent it from triggering on things the updated calc triggers on. It's best at solving expressions with unknowns or doing derivatives
