### ISSUE TITLE
Release KernelTaint

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#413]
Make sure to review and release https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/KernelTaint.pm

------
IA Page:  n/a

**Comment by moollaza** [comment]
This needs to be converted to a Structured Answer, or the `text` Template.

**Comment by pjhampton** [comment]
Closing legacy issue. This can be reviewed in batch at another time.
