### ISSUE TITLE
Release JsKeycodes

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#414]
Working on duckpan but not on live site.  https://next.duckduckgo.com/?q=keycode+tab

**Comment by javathunderman** [comment]
@moollaza @jagtalon For this one, I recommend we just slurp this all in one- it's a bit lengthy having all that stuff there.

**Comment by moollaza** [comment]
We can remove this IA or port the new Spice Implementation back to this and update it to be a new JS powered Goodie.

**Comment by moollaza** [comment]
Closing. The new Spice is nearly done. Can be ported to a Goodie now that they support JS.
