### ISSUE TITLE
Base Conversion: Allow fractions

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-goodies#4140]
At the moment only integers can be converted:
22 base 3 to base 12

It would be nice if this IA could also be used to convert fractions in different bases:
3.5 base 7 to decimal

------
IA Page:  http://duck.co/ia/view/base 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moritz

**Comment by nalinbhardwaj** [comment]
Currently, perl `Math::Int2Base` doesn't support fractions by default so we'll have to work this out specially for fractions. Because it has tag `Status: Discussion`, are there any reasons not to support fractions? If not, I can do this.

**Comment by pjhampton** [comment]
Nope @nalinbhardwaj. Do you want to take this forward?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
