### ISSUE TITLE
Conversions: wrong results on dyne prefixes and dyne <-> newton conversion.

### ISSUE THREAD

**Issue by ezhmd** [duckduckgo/zeroclickinfo-goodies#4141]
Following queries display wrong result :

"1 dyne in newton",
DuckDuckGo answered: 100,000 newtons. It should be 1 * 10^(-5) newtons.

"1 newton in dyne",
DuckDuckGo answered: 1 * 10^(-5) dynes. It should be 100,000 dynes.

"1 dyne in kilodyne",
DuckDuckGo answered: 1,000 kildynes. It should be 1 * 10^(-3) kilodynes.

"1 kilodyne in dyne",
DuckDuckGo answered: 0.00100 dynes. It should be 1000 dynes.

"1 dyne in megadyne" also gives wrong answer.

@adityatandon007 

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by adityatandon007** [comment]
@pjhamton I am working on it. I think math.js is working fine.

**Comment by pjhampton** [comment]
Yeah, it is @adityatandon007 after I rejigged some things. 
I'm not sure if this is worth your effort because this is going to be overriden in my UI changes. We won't need the factors any more. Should I move this to on hold?

**Comment by adityatandon007** [comment]
@pjhampton I have the PR ready so if you want I can just push right now

**Comment by ezhmd** [comment]
I noticed this problem has been fixed in duckduckgo site. Thanks for the great work!

**Comment by pjhampton** [comment]
Thanks @ezhmd, and thanks for the bugs. If you find any more feel free to open more GH issues 💙  💜  💛
