### ISSUE TITLE
Suggestion: download time calculator

### ISSUE THREAD

**Issue by anewuser** [duckduckgo/zeroclickinfo-goodies#4145]
Sample query: `3.53GB/100KBps`

Snippet given by Google that you could implement, preferably converting it to hours and minutes: 

```
(3.53 gigabytes) / (100 KBps) =
9.80555556 hours
```

---

**Comment by adityatandon007** [comment]
@anewuser yeah! that w'd be awesome feature to implement

**Comment by gautamkrishnar** [comment]
Yes looking great 👍  @duckduckgo/duckduckhack-contributors anyone like to implement this one?

**Comment by adityatandon007** [comment]
what are the trigger words going to be for this thing to trigger. :thinking:

**Comment by pjhampton** [comment]
You don't need necessarily need words @adityatandon007, you can use patterns.
Think Currency spice, Calculator Goodie that you have worked on before 👍

**Comment by nalinbhardwaj** [comment]
I'll take this up 👍

**Comment by pjhampton** [comment]
Sweet @nalinbhardwaj!
Look forward to seeing what you create
