### ISSUE TITLE
JavaScript (Core) Cheat Sheet: Broken URL

### ISSUE THREAD

**Issue by refola** [duckduckgo/zeroclickinfo-goodies#4146]
Current URL in "More at OverAPI" link: `http://overapi.com/javascript/`
Correct URL to change it to: `http://overapi.com/javascript` (note the lack of trailing slash `/`)

When I searched for "javascript reference" on DuckDuckGo and clicked the link, it gave a "Sorry Something Wrong..." error which links to a bunch of references including the desired on without the trailing slash.

------
IA Page:  http://duck.co/ia/view/javascript_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @TanaLandis

**Comment by adityatandon007** [comment]
@refola thanks for reporting this. 
@pjhampton picking this
