### ISSUE TITLE
Need to Fix CSS problem on my Website

### ISSUE THREAD

**Issue by 7Emiratte** [duckduckgo/zeroclickinfo-goodies#4147]
Hay i am facing some alignment issue on my website [http://7Emirate.com](url)
The below part of home page where latest listings are displaying the images and buttons are not coming in line there is some disorder if anyone help me its really appreciated thanks.

**Comment by adityatandon007** [comment]
@duckduckgo/community-leaders is this a spam?. The link directs to [https://github.com/duckduckgo/zeroclickinfo-goodies/issues/url](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/url)

**Comment by gautamkrishnar** [comment]
Unrelated issue...
