### ISSUE TITLE
New Atom Cheat Sheet

### ISSUE THREAD

**Issue by namandistro** [duckduckgo/zeroclickinfo-goodies#4150]
I guess there are 2 cheat sheet with diffrent maintainers
https://duck.co/ia/view/github_atom_mac_cheat_sheet

------
IA Page:  http://duck.co/ia/view/atom_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @typo

**Comment by pjhampton** [comment]
I have submitted a PR to deprecate one 👍
