### ISSUE TITLE
Calculator Suggestion: Support comma in floating numbers

### ISSUE THREAD

**Issue by samsk** [duckduckgo/zeroclickinfo-goodies#4156]
Calculator should support comma as decimals separator in floating numbers.

Example:
ddg:  2,2 - 3 = 19
google 2,2 - 3 = -0.8

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
This is quite tricky because we need to support this logic in the expression builder and the expression normalizer as mathjs doesn't support `,` as decimal. If someone from @duckduckgo/duckduckhack-contributors what's to try take this on, you are more than welcome.

**Comment by DGMurdockIII** [comment]
https://github.com/sanity/LastCalc

**Comment by BillyBarbaro** [comment]
@pjhapmton I'll give this one a go.  Out of curiosity, how should be handle instances where the user mixes notations?  Like what if the user submits "10,05 + 10.01"?  Should the IA just not trigger?  or should I try and get it to evaluate to 10.06?

**Comment by samsk** [comment]
I would prefer to accept mixed notation - when I'm copying numbers from different sources, I always have to unify them now (on google). I (as a human) see both as a float, so IMHO ddg should also :)

**Comment by mintsoft** [comment]
It's a little more complex than that @samsk as it depends on culture. In mainland Europe they would write the number 1 million and 1 one-hundredth as  `1.000.000,01` whereas in the UK/US etc it would be written as `1,000,000.01` 

You can see how if the number isn't large, mixing them becomes problematic

**Comment by pjhampton** [comment]
I see what you guys are saying.

Regardless, we need to evaluate the expression how we are currently. So if `1.000.000,01` is entered we need to rewrite the token to `1,000,000.01` regardless. 

I guess we could allow comma by changing [Line 40](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/137f98c31bdb190e42c6d3ef05d7f532d1000ce1/share/goodie/calculator/calculator.js#L40) to a comma and in the [evaluate function](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/137f98c31bdb190e42c6d3ef05d7f532d1000ce1/share/goodie/calculator/calculator.js#L437) or in the [normalizeExpression function](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/137f98c31bdb190e42c6d3ef05d7f532d1000ce1/share/goodie/calculator/calculator.js#L86) and rewrite the comma based tokens with heuristics.

**Comment by BillyBarbaro** [comment]
@pjhampton As @mintsoft pointed out, the NumberStyler does not currently allow mixed formats.  Since this is used to parse the input, the Goodie is not triggered if the user submits a mixed pair.  This could be fixed, but it would involved changing the NumberStyle (which may break other things) or implementing some sort of substitution upstream of the call to NumberStyle in Calculator.pm.

**Comment by pjhampton** [comment]
@BillyBarbaro Sure, but we can still support it in the UI. The engagement rate is up, which suggests that users are hitting a query, and then interacting with the calculator.

**Comment by BillyBarbaro** [comment]
@pjhampton When I interact with the calculator, anytime I try and type a comma, it just gives me a decimal.  So it seems this issue can only occur when the user submits a query in the search bar.

**Comment by pjhampton** [comment]
Yeah, but I think what @samsk is saying is that he wants to type `,` and get a `,`. Can you confirm this is correct?

**Comment by BillyBarbaro** [comment]
Sounds good.  I've found a way to get the commas working on queries submitted through the search bar by using NumberStyle.  Should I create a PR for that then work on the JS enhancement (if needed) on another branch?  Or is it easier to keep the 2 together?

**Comment by pjhampton** [comment]
I actually think this should be 2 separate PRs. But I'll let you use your best judgement 👍

**Comment by BillyBarbaro** [comment]
I'll go ahead and do it as 2 separate ones.

I've been refactoring the tests to reflect the changes I made for the search bar PR.  This test `$3,4+$34,4` is identified by the NumberStyler as already in "perl" form (decimal is . and thousands is ,) as opposed to "euro" form (decimal is , and thousands is .).  Any idea why this might be?

**Comment by samsk** [comment]
@pjhampton I want to type 2,3-1 and get correct result, how it will displayed is not important (at least for me not).

**Comment by BillyBarbaro** [comment]
@pjhampton To clarify my last question, it appears that math with dollar amounts triggers the IA, but does not display in it.  Is it safe to assume I don't have to fix/add this functionality in my PR?

**Comment by pjhampton** [comment]
Thanks @BillyBarbaro 
This should now be resolved @samsk

**Comment by samsk** [comment]
It's live and works perfect ;)
Great work, Thanks.

**Comment by pjhampton** [comment]
I try support commas in the UI in the rewrite :-)
