### ISSUE TITLE
Brainy Quote: Show more than one quote

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4157]
## Problem

Currently, we only show one quote on this IA. We should increase this to 3 if the plural `quotes` is contained in the query we should show more than 1.

![screen shot 2017-05-04 at 11 53 37 am](https://cloud.githubusercontent.com/assets/8960296/25700621/6083e7b4-30c0-11e7-88dd-115e3c4af537.png)

## Solution

1. Add a couple of tests to [BrainyQuote.t](https://github.com/duckduckgo/zeroclickinfo-spice/tree/master/t/BrainyQuote.t)

2. Rewrite the retrieval logic. The developer will have to use multiple ajax calls because the API only returns one result at a time... eg: https://www.brainyquote.com/api/ddg?q=love

3. For multiple quotes, implement the list view. 

## People to notify

@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/brainy_quote

**Comment by darsnack** [comment]
Am I imagining things or should this issue be for the Spice repo?

**Comment by pjhampton** [comment]
Well spotted @darsnack
