### ISSUE TITLE
Calculator: Does not handle log bases correctly

### ISSUE THREAD

**Issue by RoryCrispin** [duckduckgo/zeroclickinfo-goodies#4158]
log2(2) returns 0
Should be returning 1

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Just to add more context to this issue. The query `log2(2)` fails in the front-end logic, and as a result we bail and show the calculator anyway. We should remove the triggering in the Perl file to stop custom log bases until we can handle that in the expression normalizer.

**Comment by lernae** [comment]
@pjhampton  I'll take this one.  So Perl triggering should only allow log base 10.  Is this correct?

**Comment by pjhampton** [comment]
Yeah, please @lernae!

**Comment by pranati18** [comment]
Also when just log 10 or log 2 10 is searched (or any log values), the calculator does not open up directly to change or fiddle with the values. Only, Symbolab.com instant answers are pulled. I feel the calculator should also come up. 

P.S- I am not sure if this is the correct place to post this comment.

**Comment by pjhampton** [comment]
Thanks @pranati18 and thanks for taking the time to search the open issues! ❤️  
I am currently working on this 😄  Hopefully done soon

**Comment by pjhampton** [comment]
This got fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4318 - Hopefully released today🤘 😄 🤘
