### ISSUE TITLE
Conversions: Regressions

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#4159]
### Description
Yo's; just noticed a few things I missed when I looked over the PR:

The following used to trigger:
* https://duckduckgo.com/?q=1GiB+in+MiB&t=vivaldi&ia=web
* https://duckduckgo.com/?q=1+ping+in+square+feet&t=vivaldi&ia=web (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2125)
* https://duckduckgo.com/?q=BTU+to+KwH&t=vivaldi&ia=web (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1385)
* https://duckduckgo.com/?q=light+year+in+m&t=vivaldi&ia=web (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1102)

* Now gets the unit wrong, treats b as bytes when it should be bits (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3990) : https://duckduckgo.com/?q=1+Gb+in+MB&t=vivaldi&ia=answer 

* Accuracy regression: https://duckduckgo.com/?q=100+megabytes+in+bytes&t=vivaldi&ia=answer (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2951), probably irrelevent for megabytes, but important for mebibytes

## People to notify
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by pjhampton** [comment]
Hey @duckduckgo/duckduckhack-contributors 

Would anybody like to support these over the weekend? 
I have a dump of conversions that had to be dropped in the v2 initially - but can now be added back in.

**Comment by pjhampton** [comment]
Now that I've thought about it a bit, maybe we should break this down into many smaller tasks. We're not just regressing here but across all the categories. Further, these are just some examples - we want to be as comprehensive as possible like Bing.

Let's start with closing this and creating an issue to improve Digital Conversions by adding anything that's missing. What do you guys think?

**Comment by Lord-Lavios** [comment]
@pjhampton I've already started working on adding more digital conversions.

**Comment by pjhampton** [comment]
Ahh, nice @Lord-Lavios. Thanks! I will create an issue later for you and assign it to you so we can keep track of this stuff. 

Maybe this is an excuse to leverage Github Projects.

**Comment by pjhampton** [comment]
Closing. See

- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4178
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4177
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4176
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4175
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4174
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4173
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4172
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4171
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4170
