### ISSUE TITLE
Conversions: Add further triggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4161]
### Problem

[In the v2](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4135), we a[dded in some generic triggers](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/lib/DDG/Goodie/Conversions.pm#L32) to broaden the triggering of this IA. It [opens up **length** by default](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/share/goodie/conversions/conversions.js#L363) if no base was specified. 

It would be great to add in more triggers such as:
`length converter`, `mass converter`, etc etc and have them open the correct base in the JS UI.

## Solution

1. Add in some triggering tests to [Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/t/Conversions.t)

2. Add a new set of triggers to an array in [Conversions.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/lib/DDG/Goodie/Conversions.pm)

3. Update the initialize information in [Conversions.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/share/goodie/conversions/conversions.js)

## People to notify

@mintsoft 
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by adityatandon007** [comment]
@pjhampton I w'd like to try it! I will ask for help in case needed.

**Comment by pjhampton** [comment]
Awesome @adityatandon007!!
Sure, always reach out if unsure 👍

**Comment by adityatandon007** [comment]
I wasn't clear about the things that I have to add in the conversion.js file. I tried looking for the initialize function but I couldn't find any initialize function.

**Comment by pjhampton** [comment]
Initialize isn't a func. See lines [362-367](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/share/goodie/conversions/conversions.js#L362). This block is getting the information from the perl backend (the `data` hash).

Lines [381-394](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/share/goodie/conversions/conversions.js#L381) set up the UI with that information.

You will want to create new triggers and pass it to the front-end [so line 363](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/54533e63cf1ce810f8c1eefcf31ec7f3c5ab4b38/share/goodie/conversions/conversions.js#L363) can seed the value into the UI
