### ISSUE TITLE
Calculator: x^(xy) != x^(x)y

### ISSUE THREAD

**Issue by Janjoch** [duckduckgo/zeroclickinfo-goodies#4166]
When I enter in the calculator 2^2 * 2 without writing "*", the Result will be 4,194,304. (Combination: [2] + [x^2] + [2] + [=]) But 4,194,304 is the result of 2^22.

The same mistake is also with 4^(4)4 != 4^(44)  or  1^(2)3 != 1^(23)

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by kirkins** [comment]
I'm testing this on the live site and it seems to work as expected _(returning 8)_.

Has this been fixed and ready to close?

**Comment by Janjoch** [comment]
Hi,

I’m sorry, but it still doesn’t work… I use Firefox Nightly 55 in German (Switzerland). Here is a photo to show:



Greetings form Switzerland,
Janosch Jörg

**Comment by kirkins** [comment]
@Janjoch I'm not seeing the photo.

**Comment by Janjoch** [comment]
I just replied to the email and added an image. In this case, GitHub doesn’t support images :/ Here is a link: https://www.dropbox.com/s/bo4s986kq2g1aon/DuckDuckGoBugReport.png?dl=0

**Comment by kirkins** [comment]
@Janjoch can you send a duckduckgo.com with the query so that we can reproduce this error?

**Comment by Janjoch** [comment]
It isn’t possible to show the error in the text field / url. But I can give you a precise guidance to reproduce the error: Type „2^2*2“ in the field. Now the answer is (as to be expected) 8. But when you hit the Buttons: [2] + [x^2] + [2] + [=], (the same as before but without „*“), the result will be the result of 2 ^ 22  = 4,194,304. But with mathematical correct reading there is squaring before the multiplication, this means (2 ^ 2) * 2 and not 2 ^ (2 * 2).

**Comment by kirkins** [comment]
@Janjoch 

Sorry can you clarify button order? From what you say I'm thinking:

- 2
- x
- ^
- 2
- 2
- =

This doesn't seem right as it would produce something completely different.

**Comment by Janjoch** [comment]
2
x^2
2
=
=> This gives a false result (The problem is the missing multiplication-sign which can be let away in a correct mathematical way)

2
x^2
2
x
2
=> This gives the correct result

I’ve drawn it to visualise it: https://www.dropbox.com/s/dz45xahq19d3wrd/DuckDuckGoBugReport2.png?dl=0 <https://www.dropbox.com/s/dz45xahq19d3wrd/DuckDuckGoBugReport2.png?dl=0>

In the right column, it’s shown correct (the grey, small text at the top), but in the big result window it’s highlighted as 2^22.

**Comment by kirkins** [comment]
@Janjoch thanks now I understand!

**Comment by kirkins** [comment]
I think we should keep the current behavior, but make it act along the lines of the X^y button.

That is it should be 2^22 with the correct formatting (not 2, small 2, big 2).

I wanted to compare Googles calculator but they only have the X^y button, no ^2, or ^3 buttons.

**Comment by kirkins** [comment]
Ignore my last comment, it doesn't make sense. What you originally suggested is the best way to do it.
