### ISSUE TITLE
Conversions Suggestion: (ANGLE) - Add Missing Units

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4170]
## Problem

We recently migrated the conversions API into an interactive UI. However, some units were ditched for various reasons and the legacy code didn't necessarily support all of the units that were desired from users. This is a good opportunity to take the lead in the search engine conversion game.

![screen shot 2017-05-08 at 6 37 07 pm](https://cloud.githubusercontent.com/assets/8960296/25816857/61b6abb6-341d-11e7-9d9f-c89e9dc6ea36.png)

## Solution

1. Add some front-end tests to [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/spec/conversions_spec.js). This will test the custom units

2. Add some back-end tests to [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Conversions.t). This will test the triggering.

3. Update the triggering in [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) 

4. Add the custom unit to [Conversions.js (Line 45)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) and add it to the Units Object in [Conversions.js (Line 166)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166)

### UNITS
- [x] microradian
- [x] revolution
- [x] milliarcsecond
- [x] microarcsecond

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by DGMurdockIII** [comment]
https://github.com/ben-ng/convert-units

www.npmjs.com/package/convert-units

**Comment by pjhampton** [comment]
@DGMurdockIII While your involvement is appreciated - Please stop spamming the issues with links that 1, have no context, and 2, don't necessarily solve the problem. These links don't help and it will confuse some of our new contributors. I'm going to delete these comments now.

**Comment by DGMurdockIII** [comment]
Ok where should I share them then

**Comment by pash90** [comment]
@pjhampton I would like to work on this.

**Comment by pjhampton** [comment]
Thanks @pash90! It's all yours. 
If you need any help or have any questions feel free to ask here or on slack. We'll get you added to the DDG github org soon

**Comment by pjhampton** [comment]
Hey @pash90 

Just to let you know, some of these have come in and have been merged. I'm linking to them just incase you need some inspiration or help 👍 

- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4196
- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4195
- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4197

**Comment by pash90** [comment]
@pjhampton thanks for the heads up! I have actually finished up the issue. Just finishing up some final testing will raise a PR soon 👍
