### ISSUE TITLE
Conversions Suggestion: (ENERGY) - Add Missing Units

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4173]
## Problem

We recently migrated the conversions API into an interactive UI. However, some units were ditched for various reasons and the legacy code didn't necessarily support all of the units that were desired from users. This is a good opportunity to take the lead in the search engine conversions game.

![screen shot 2017-05-08 at 6 37 07 pm](https://cloud.githubusercontent.com/assets/8960296/25816857/61b6abb6-341d-11e7-9d9f-c89e9dc6ea36.png)

## Solution

1. Add some front-end tests to [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/spec/conversions_spec.js). This will test the custom units

2. Add some back-end tests to [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Conversions.t). This will test the triggering.

3. Update the triggering in [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) 

4. Add the custom unit to [Conversions.js (Line 45)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) and add it to the Units Object in [Conversions.js (Line 166)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166)

### UNITS

- [ ] Foot pound
- [ ] Decielectron volt
- [ ] Centielectron volt
- [ ] Millielectron volt
- [ ] Microelectron volt
- [ ] Nanoelectron volt
- [ ] Picoelectron volt
- [ ] Femtoelectron volt
- [ ] Attoelectron volt
- [ ] Zeptoelectron volt
- [ ] Yoctoelectron volt
- [ ] Decaelectron volt
- [ ] Hectoelectron volt
- [ ] Kiloelectron volt
- [ ] Metaelectron volt
- [ ] Gigaelectron volt
- [ ] Teraelectron volt
- [ ] Petaelectron volt
- [ ] Exaelectron volt
- [ ] Zettaelectron volt
- [ ] Yottaelectron volt

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by J-Speight** [comment]
I would like to work on this issue.

**Comment by pjhampton** [comment]
All yours @J-Speight 🤘

**Comment by J-Speight** [comment]
@pjhampton (https://docs.duckduckhack.com/submitting/pull-request.html) states "Make sure there's only one Instant Answer per pull request."

Could I get clarification on this?

For example, do I write all the appropriate material (noted in **solutions**) for Foot pound to Decielectron volt conversions and then submit a pull request? 

so the code for Foot pound to Centielectron volt would be a separate pull request?

or is Conversions Suggestion: (ENERGY)  itself considered a single instant answer"

**Comment by pjhampton** [comment]
Hey @J-Speight 

Thanks for reaching out. Ok, so we already have an instant answer for [Conversions](https://duck.co/ia/view/conversions). This issue is to extend that Instant Answer, rather than create a new one. Sorry if that wasn't clear from the original issue. 

The files that you will want to edit are:

 - [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/spec/conversions_spec.js) for the front-end tests

 - [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/t/Conversions.t) for the back-end tests

 - [Conversions.js](https://github.com/duckduckgo/zeroclickinfo-goodies/tree/master/share/goodie/conversions/conversions.js) to add the custom units and add to the UI.

  - [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) to update the triggering. 

If you need inspiration, checkout @scottwarren's WIP PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4181. He has the right idea and is doing the same thing but for the Length base.

Hope that helps!

**Comment by J-Speight** [comment]
Just keeping track of what I've done/what is left to do
https://github.com/J-Speight/zeroclickinfo-goodies/tree/issue-4173

add conversions for:

- [ ] joules to *
- [ ] kilojoules to *
- [ ] gramcalories to *
- [ ] Foot pound to *
- [ ] Decielectron volt to *
- [ ] Centielectron volt to *
- [ ] Millielectron volt to *
- [ ] Microelectron volt to *
- [ ] Nanoelectron volt to *
- [ ] Picoelectron volt to *
- [ ] Femtoelectron volt to *
- [ ] Attoelectron volt to *
- [ ] Zeptoelectron volt to *
- [ ] Yoctoelectron volt to *
- [ ] Decaelectron volt to *
- [ ] Hectoelectron volt to *
- [ ] Kiloelectron volt to *
- [ ] Metaelectron volt to *
- [ ] Gigaelectron volt to *
- [ ] Teraelectron volt to *
- [ ] Petaelectron volt to *
- [ ] Exaelectron volt to *
- [ ] Zettaelectron volt to *
- [ ] Yottaelectron volt to *

**Comment by J-Speight** [comment]
>This is a good opportunity to take the lead in the search engine conversions game.

Interestingly enough - Google's instant result for the query:

10 joules to hectoelectron volts returns the answer: 6.242e+17
(https://www.google.co.uk/?gfe_rd=cr&ei=dfwUWZyIIdPU8gfdmpeQCA&gws_rd=ssl#q=10+joules+to+hectoelectron+volt)

so I've decided to offer more precision. The conversions_spec calculates the same equation to be: `6.24150947961E+17`

>:)

**Comment by pjhampton** [comment]
Hey @J-Speight 

Just to let you know, some of these have come in and have been merged. I'm linking to them just incase you need some inspiration or help 👍 

- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4196
- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4195
- https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4197

**Comment by pjhampton** [comment]
Opps didn't mean to close this

**Comment by vtodo** [comment]
I could help on this one. 
I see no assignees at the moment, so I'm doing it.

**Comment by pjhampton** [comment]
Thanks @vtodo but @J-Speight is working on this

**Comment by pjhampton** [comment]
Hey @J-Speight, any update on this?

**Comment by vtodo** [comment]
Yeah I don't want to stop @J-Speight 's inertia.
Thought It was abandoned task.
Anyway, I'd be glad to help

**Comment by pjhampton** [comment]
Hey guys! I'm afraidn I've had to time this out. It's a high priority / impact issue. I have created a PR for it here https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4223 if anybody wants to review. Thanks for your input everybody!
