### ISSUE TITLE
Conversions Suggestion: (FORCE) - Add Missing Units

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4174]
## Problem

We recently migrated the conversions API into an interactive UI. However, some units were ditched for various reasons and the legacy code didn't necessarily support all of the units that were desired from users. This is a good opportunity to take the lead in the search engine conversions game.

![screen shot 2017-05-08 at 6 37 07 pm](https://cloud.githubusercontent.com/assets/8960296/25816857/61b6abb6-341d-11e7-9d9f-c89e9dc6ea36.png)

## Solution

1. Add some front-end tests to [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/spec/conversions_spec.js). This will test the custom units

2. Add some back-end tests to [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Conversions.t). This will test the triggering.

3. Update the triggering in [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) 

4. Add the custom unit to [Conversions.js (Line 45)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) and add it to the Units Object in [Conversions.js (Line 166)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166)

### UNITS

- [ ] Kilonewton
- [ ] Gram-force
- [ ] Ounce-force
- [ ] Kilogram-force
- [ ] Kip-force
- [ ] Metric ton-force

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by adityatandon007** [comment]
@pjhampton I would like to pick this!
