### ISSUE TITLE
Conversions Suggestion: (LENGTH) - Add Missing Units

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4175]
## Problem

We recently migrated the conversions API into an interactive UI. However, some units were ditched for various reasons and the legacy code didn't necessarily support all of the units that were desired from users. This is a good opportunity to take the lead in the search engine conversions game.

![screen shot 2017-05-08 at 6 37 07 pm](https://cloud.githubusercontent.com/assets/8960296/25816857/61b6abb6-341d-11e7-9d9f-c89e9dc6ea36.png)

## Solution

1. Add some front-end tests to [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/spec/conversions_spec.js). This will test the custom units

2. Add some back-end tests to [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Conversions.t). This will test the triggering.

3. Update the triggering in [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) 

4. Add the custom unit to [Conversions.js (Line 45)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) and add it to the Units Object in [Conversions.js (Line 166)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166)

### UNITS

- [ ] Micron
- [ ] Femtometer
- [ ] Attometer
- [ ] zeptometer
- [ ] Yoctometer
- [ ] Dekameter
- [ ] Hectometer
- [ ] Metameter
- [ ] Gigameter
- [ ] Terameter
- [ ] Petameter
- [ ] Exameter
- [ ] Zettameter
- [ ] Yottameter
- [ ] Nautical Mile
- [ ] Li
- [ ] Half Marathon
- [ ] Marathon
- [ ] Parsec
- [ ] Milliparsec
- [ ] Nanoparsec
- [ ] Picoparsec
- [ ] Kiloparsec
- [ ] Metaparsec
- [ ] Gigaparsec
- [ ] Teraparsec
- [ ] Astronomical Unit
- [ ] Light Year
- [ ] Leauge
- [ ] Furlong
- [ ] Megafurlong
- [ ] Fathom
- [ ] Smoot
- [ ] Cubit
- [ ] Beard Second

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by scottwarren** [comment]
I'm looking to take this on!

**Comment by pjhampton** [comment]
Thanks @scottwarren! You rock 🤘

**Comment by scottwarren** [comment]
Glad to help :-)

**Comment by M-Schiller** [comment]
Regarding units and their conversion in general: Wouldn't it be more maintainable and easier to comprehend to "split" the unit names into prefix and unit and work from there? To me, it seems error-prone to have lines like this:  `{name: "femtosecond", factor: "0.000000000000001 second"},`. Instead I think it could be better to have a prefix table similar to
> "kilo": 10e3
> "mega": 10e6
> "giga": 10e9
> ...
> "milli": 10e-3
> "micro": 10e-6
> "nano": 10e-9
> "pico": 10e-12
> "femto": 10e-15
> "atto": 10e-18

 I also think that there are typos in the unit list above, namely in the "meta..."-prefix, which I think should be "mega...".

**Comment by pjhampton** [comment]
We did have this @M-Schiller, but we had to regress. The format means we are compatible with Math.js, the js lib we are using for the back end. Also, we can't use e notation to define custom units at runtime. I am working with the math js team to add our custom units into their package so we no longer have to bother creating these at run time.
Thanks for your suggestion 👍
