### ISSUE TITLE
Conversions Suggestion: (MASS) - Add Missing Units

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4176]
## Problem

We recently migrated the conversions API into an interactive UI. However, some units were ditched for various reasons and the legacy code didn't necessarily support all of the units that were desired from users. This is a good opportunity to take the lead in the search engine conversions game.

![screen shot 2017-05-08 at 6 37 07 pm](https://cloud.githubusercontent.com/assets/8960296/25816857/61b6abb6-341d-11e7-9d9f-c89e9dc6ea36.png)

## Solution

1. Add some front-end tests to [spec/conversions_spec.js](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/spec/conversions_spec.js). This will test the custom units

2. Add some back-end tests to [t/Conversions.t](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Conversions.t). This will test the triggering.

3. Update the triggering in [triggers.yml](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml) 

4. Add the custom unit to [Conversions.js (Line 45)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) and add it to the Units Object in [Conversions.js (Line 166)](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166)

### UNITS

- [x] Decigram
- [x] Centigram
- [x] Picogram
- [x] Femtogram
- [x] Dekagram
- [x] Hectogram
- [x] Megagram
- [x] Metric Ton
- [x] Long Ton
- [x] Short Ton
- [x] Imperial Ton
- [x] Metric Quintal
- [ ] US Quintal
- [ ] French Quintal
- [x] Troy OUnce
- [x] Slug
- [ ] Tola
- [x] Carat
- [x] Grain
- [x] Atomic Mass Unit

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by TheOdd** [comment]
I'd love to work on this problem! Just an FYI: I'm super new to this, so I apologize in advance if I make a mistake in the process of fixing it.

**Comment by pjhampton** [comment]
Awesome @TheOdd! Thanks so much in advance
If you need any help just ping us (or me) here 😄

**Comment by TheOdd** [comment]
@pjhampton I have a few things I want to ask about:

1. When editing the `conversions.js` file and adding in the additional units to the `Units` variable, there are a couple of them that have abbreviations that are identical to existing ones. Do I exclude these abbreviations in the aliases/symbols in favor of the more common one or add it to both? I'm just making sure as it could create a conflict in the file when handling this.
2. What units would I use in the `customUnits` array for `factor`? Would it be something like `0.1 grams` or `0.1 g`. I can provide my edited file so far if needed. I don't want to push an incomplete commit to my fork in the meantime, though.

Any help is greatly appreciated, thanks!

**Comment by pjhampton** [comment]
Hey @TheOdd 

So [Line 45](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45) is where we define our custom unit, and [L166](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L166) is where we make it (and the units specified by math.js) to the UI. Does this answer your question?

Yeah, so the factor is probably a poorly named key. I am open to suggestions to change it. As for specifying, yeah you would use grams like `0.1 grams` or the next closest measure. Take what I did in [Line 60](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L60) for example, I defined `PB` with the `GB` which was defined in the line before. 

And sure, you can post your work early. Loads of people do that. Just append the `[WIP]` to it. See https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4181 for example

**Comment by TheOdd** [comment]
@pjhampton Thanks for the clarification! Is there a set time limit that I have to do this? Some days I'm just a bit busy with other things and exhausted, so I might not be able to work on it. I don't want to rush a fix, though.

**Comment by pjhampton** [comment]
Hey @TheOdd,

That's cool, there is no rush! Do you want to set a provisional merge date so this doesn't drag on... say Thursday (18/May)?

**Comment by TheOdd** [comment]
Sure, that sounds good.

**Comment by subash774** [comment]
First time here, I wish to contribute, sorry for any mistakes I'll be making.

**Comment by pjhampton** [comment]
Hey @subash774 - This issue is a work in progress and nearing completion.
