### ISSUE TITLE
Timer: Trigger on "Pomodoro timer"

### ISSUE THREAD

**Issue by ZaninAndrea** [duckduckgo/zeroclickinfo-goodies#4186]
I think it would be a good idea to make the search 'pomodoro timer' trigger a timer of 15 minutes.
If you didn't know: [pomodoro technique](https://en.wikipedia.org/wiki/Pomodoro_Technique)

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by ZaninAndrea** [comment]
I'm a new-comer, but I think this should be a pretty easy implementation, so I would be happy to contribute.

**Comment by pjhampton** [comment]
Hey @ZaninAndrea  👋  Welcome!

I'm not sure **pomodoro technique** would be a great trigger. We don't want to surprise the user with something that is only semi-relevant. Maybe **pomodoro timer** or **pomodoro clock**. Anybody else have thoughts on this cc/ @duckduckgo/duckduckhack-contributors ?

**Comment by ZaninAndrea** [comment]
@pjhampton yes, the search query I was thinking about was **pomodoro timer**, but also **pomodoro clock** would be good. I added pomodoro technique only as a reference, I didn't mean it to be the trigger.

**Comment by pjhampton** [comment]
Hey @ZaninAndrea, based on the thumbs up from the maintainer and a staff member I'm happy for you to take this forward 👍  Look forward to checking it out!

**Comment by spagy** [comment]
maybe a 25 min timer rather than 15 min timer? i think 25 mins is the standard

**Comment by pjhampton** [comment]
Hey @ZaninAndrea. How are you getting on with this?

**Comment by pjhampton** [comment]
This looks like it might have gone stale. Closing for now...

**Comment by adityatandon007** [comment]
@pjahampton I would like to take this. I might submit the PR today if you assign this to me right now. :slightly_smiling_face:

**Comment by pjhampton** [comment]
Hey @ZaninAndrea 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
