### ISSUE TITLE
Timer: Explicit request for timer not working on ambigious triggers

### ISSUE THREAD

**Issue by shivam99aa** [duckduckgo/zeroclickinfo-goodies#4188]
### Description
If I try to run `timer for 60 minutes` then it will not work. In issue #4089 I removed trigger for `60 minutes` but it is somehow also stopping when explicitly someone is asking for a timer.

## People to notify
@moollaza @pjhampton 

Instant Answer Page: https://duck.co/ia/view/timer

**Comment by shivam99aa** [comment]
If there is no issue then I would like to take this up and solve whatever I missed in my previous commit.

**Comment by shivam99aa** [comment]
@pjhampton Can you please assign this task to me so that i can start working on this task and finish it over this weekend.

**Comment by pjhampton** [comment]
No problem, @shivam99aa ❤️  Thanks for your hard work on this IA
