### ISSUE TITLE
Calculator: Over triggering

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-goodies#4189]
**Issue**: This is one the IA that I use a lot now but for now its over triggering.

For example searching for a website(that ends with `x`) triggers this IA which shouldn't happen. Ex: 1337x is one of the most popular torrent search engine website and its global Alexa rank is under 600 and its Alexa rank in :india: is 112 to be exact. So, the IA should trigger in this case.

**Steps to recreate**

![screenshot from 2017-05-11 19-04-52](https://cloud.githubusercontent.com/assets/25108385/25951952/ef7e3408-367c-11e7-8416-bc29a50c057e.png)

**Solution**
Perhaps a more stricter check at the regex can solve this issue. For ex: bail out in case we only have one number and an operator (more specifically the operator `x`, we we rarely have websites that end with any other operator). 

People to notify
@pjhampton @moollaza 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
It seems that we're duplicating this one issue quite a bit. I think we will create a master issue for all the issues with calc triggering so we don't create an issue for every edge case. This will make patching them a bit easier.

**Comment by adityatandon007** [comment]
@pjhampton thats sounds cool. Like we have done in v2 of the calculator, where we listed all the issues and then cut them off from the list if they gets patched. That way, it will be easy to manage. 

**I think we will create a master issue for all the issues with calc triggering** 

I agree :+1: with you on this.

**Comment by tagawa** [comment]
Found another example of over-triggering: https://duckduckgo.com/?q=e17+e26
