### ISSUE TITLE
Molar Mass: Create new Molar Mass IA

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4190]
### Description

It seems that quite a lot of molar mass related queries. The user is having to click through into the organics or the wikipedia module to get an answer. It seems we are failing here. We should create a Molar Mass Instant Answer to serve these to the user with zero clicks. Google does this well:

![screen shot 2017-05-11 at 4 50 51 pm](https://cloud.githubusercontent.com/assets/8960296/25959503/ae5c7a54-366b-11e7-8b14-fe02f07df1fc.png)

## Steps to recreate

After a bit of poking around Github, it seems @joshliu rolled his own [ruby] solution. See [joshliu/molar/molar_mass.rb](https://github.com/joshliu/molar/blob/master/molar_mass.rb). This can be used as a basis for inspiration for the developer. 

I will leave the implementation and testing details up to the uptaker, but happy to discuss.

## People to notify

@pjhampton

---

Instant Answer Page: To be created (https://duck.co/ia/new_ia)

**Comment by joshliu** [comment]
Hi, I'd be willing to implement the molar mass algorithm in Perl!

**Comment by pjhampton** [comment]
Awesome @joshliu! Thanks so much 😄  
I have invited you to the DuckDuckGo github organization 👍

**Comment by joshliu** [comment]
After playing around with Google's instant results, it seems that google has a table of common chemical compounds and serves those answers directly instead of parsing the components and calculating the answers.

For instance, many organic compounds do not produce a Google instant answer, while common compounds can trigger an instant answer by name only:

![image](https://cloud.githubusercontent.com/assets/4336885/26030284/f97bad9a-381c-11e7-97a9-28a8123fb247.png)

<hr>

![image](https://cloud.githubusercontent.com/assets/4336885/26030285/0966e8a0-381d-11e7-8ea7-1046cd515dd9.png)

<hr>

That being said, how should we approach this?

**Comment by joshliu** [comment]
Another potential pitfall lies in that a fully accurate parsing algorithm relies heavily on the case of each character to determine chemical compounds. However, duckduckgo autocomplete provides suggested search results in all lowercase letters, which will be harder to parse accurately. 

Perhaps for all lowercase and common name input we should use some sort of key-value pair table, and for properly formatted formula inputs we can run the molar mass algorithm. Thoughts?

**Comment by JHonaker** [comment]
Lower case only input will cause a huge problem because of non-unique answers. Note, these aren't valid formulae, just examples of parse errors you could get. Carbon (C) and sulfur (S) together would be CS (cs in lower) and cesium (Cs) would also be cs in lowercase.

**Comment by pjhampton** [comment]
Hey @joshliu and @JHonaker 

Sorry, I completely overlooked this! My bad! 

1. Formatting

We can preserve the formatting of the query. See https://docs.duckduckhack.com/backend-reference/triggers.html#query-formats. This isn't an issue.

2. Serving the IA
@joshliu I think it would be best to implement something like you implemented in rb, but we can scale it down for now if that is your recommendation?

**Comment by joshliu** [comment]
I just finished implementing the same algorithm in Perl, about to make a pull request now.

**Comment by stormwindy** [comment]
Hey @pjhampton ! I am willing to contribute to this problem. Like I said before my coding skills are not that good but I can contribute in terms of idea, and methodology.
