### ISSUE TITLE
C++ Algorithms CheatSheet: Fix template and make it consistent with other cheatsheets

### ISSUE THREAD

**Issue by ManrajGrover** [duckduckgo/zeroclickinfo-goodies#4191]
### Description
Currently, `reference` template is being used for the cheatsheet. To make it look better and also consistent with other C++ Cheatsheets, `terminal` template should be used. Also, the keys don't express the syntax well, hence there is a need to fix that too. See [C++ Bitset Cheatsheet](https://duckduckgo.com/?q=c%2B%2B+bitset+cheatsheet&t=h_&ia=cheatsheet&iax=1) for example.

## Steps to recreate
https://duckduckgo.com/?q=c%2B%2B+algorithms+cheatsheet&t=h_&ia=cheatsheet

## People to notify
@jamie23

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/cpp_algorithms_cheat_sheet

**Comment by adityatandon007** [comment]
@ManrajGrover I w'd like to work on this

**Comment by ManrajGrover** [comment]
@adityatandon007 This should be an easy fix. Go ahead! 😄
