### ISSUE TITLE
Calculator Bug: Does not handle Currency calculations

### ISSUE THREAD

**Issue by BillyBarbaro** [duckduckgo/zeroclickinfo-goodies#4198]
### Description
When trying to add, subtract, etc on currency amounts, the calculator displays but does load with the amounts.  It just displays 0.  I've got an idea for this and would be willing to take on the issue if it's something that needs fixed.

## Steps to recreate
[$3.40 - $2.89](https://duckduckgo.com/?q=%243.40+-+%242.89&t=h_&ia=calculator)

## People to notify
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by pjhampton** [comment]
Fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4183
