### ISSUE TITLE
Factors Suggestion: Layout of factors

### ISSUE THREAD

**Issue by keeganjk** [duckduckgo/zeroclickinfo-goodies#4206]
This shows factors in a layout like this: 
<pre>1, 2, 5, 10</pre>
when it should be like this:
<pre>1, 10</pre>
<pre>2, 5</pre>
------
IA Page:  http://duck.co/ia/view/factors 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark

**Comment by pjhampton** [comment]
It doesn't look like this suggestion is getting a lot of traction. I will close this for now and keep an eye out for similar feedback in the future. Thanks for the suggestion nonetheless 💙
