### ISSUE TITLE
Timer: Limited to 100 hours

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4209]
Searching for "timer 525600 minutes" results in timer for 6000 minutes. I can't think of a use case for this, but I'm sure there's one somewhere.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by pjhampton** [comment]
Yeah, there was an upper bound placed for sanity reasons. https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Timer.pm#L26

Are you suggesting we bail from the query if it's above 6000?

**Comment by jc86035** [comment]
There could be good reasons for setting timers for e.g. a week (online-stopwatch.com appears to have this function per search results). Making the maximum cut-off 100 hours seems arbitrary, especially since the +1 button can increase it to above 100h regardless.

It would be a good idea to not show the timer if the value is above the limit (regardless of what the limit is), as it might lead to users thinking it malfunctioned, or not noticing the time set is different to the requested value. If the limit is kept to more than 24 hours then a search for "timer 1 day" should also trigger it.

**Comment by pjhampton** [comment]
I'm agnostic here. 
Does anybody want to add their two cents? @duckduckgo/duckduckhack-contributors

**Comment by willyb321** [comment]
I'd personally say there's not much if any use for it.

**Comment by adityatandon007** [comment]
same here

**Comment by pjhampton** [comment]
Doesn't look like this has much support behind it. Closing for now...
