### ISSUE TITLE
Shortcut Instant Answer

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#421]
Make sure to review and release https://github.com/duckduckgo/zeroclickinfo-goodies/pull/208

**Comment by javathunderman** [comment]
#208 seems to have been merged. Should this be closed?

**Comment by moollaza** [comment]
@javathunderman this one should be converted to use the new Structured Answer. Right now it's just returning HTML which we're hoping to avoid.

**Comment by javathunderman** [comment]
@moollaza Ok, evaluating this code. I'll see what I can do...

**Comment by moollaza** [comment]
This one will need to be updated to meet the newest CheatSheet format. Or we could hold for the coming CheatSheet templates and update it then.

**Comment by javathunderman** [comment]
@moollaza Thinking we should wait for the new templates.

**Comment by javathunderman** [comment]
@moollaza I'm going to tackle this as a CheatSheet then.

**Comment by moollaza** [comment]
@javathunderman that sounds great. Just stick to one OS for now in the IA. I'm going to speak with the team about how we want to handle multiple OS's. It will likely be a separate cheat sheet for each, but I'm not sure...

**Comment by javathunderman** [comment]
This can be closed @moollaza :+1:
