### ISSUE TITLE
Timezone Converter: Incorrect and malformed values for NST and NDT

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4210]
NST and NDT (according to Wikipedia, Newfoundland Standard Time and Daylight Time) should be UTC−03:30 and UTC−02:30 but display in Timezone Converter as "UTC-1:-49:-60" and "UTC+0:-49:-60".

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by mintsoft** [comment]
According to : https://en.wikipedia.org/wiki/Newfoundland_Time_Zone

NST	UTC−3:30
NDT	UTC−2:30

**Comment by shubhamkr1** [comment]
I would like to work on this. I am new to Duckduckgo , so please suggest where to search for issues or changes are required.

**Comment by pjhampton** [comment]
Sure @shubhamkr1! It's all yours. I have invited you to the org so I can assign you later. 👍  Reach out if any questions / issues

**Comment by AasthaGupta** [comment]
Is this assigned to someone?Can I issue a pull request?

**Comment by ManrajGrover** [comment]
@shubhamkr1 Any progress on this? Please ask if any help or inputs are required.
@AasthaGupta Let's wait for an update on this.

**Comment by mintsoft** [comment]
@ManrajGrover I'd say let @AasthaGupta go for it, we've not seen any movement on this anywhere else

**Comment by shubhamkr1** [comment]
Hi,

Sorry for the late reply.
I looked at the backend code but was not able to find what need to be
corrected.

Regards,
Shubham
