### ISSUE TITLE
Countdown: Should have time input

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4211]
Could be useful for "countdown to noon on 20 January 2021", for example.

------
IA Page:  http://duck.co/ia/view/countdown 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

**Comment by pjhampton** [comment]
Hey @jc86035 

Feel free to reopen this issue with our required issues template and title formatting.

**Comment by jc86035** [comment]
@pjhampton Where is the issues template?

**Comment by pjhampton** [comment]
It's prepopulated / commented in the textarea when you hit the green **New Issue** button. 
Alternatively, you can see it here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by jc86035** [comment]
I used one of the duck.co links, maybe those should be updated then.
