### ISSUE TITLE
Countdown – Suggestion: Allow time input

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4212]
### Description

Currently the highest precision for the countdown clock is a day, at 12am. It would be useful to allow time input as well.

## Steps to recreate

Search for "countdown to tomorrow 12pm".

## People to notify

Mentioning @pjhampton and @rasikapohankar, from #4211.

---

Instant Answer Page: https://duck.co/ia/view/countdown

**Comment by pjhampton** [comment]
I like this idea, but I'm going to close this _for now_ because:

1. It doesn't seem to have much community support
2. There isn't a lot of queries to suggest that there is a signal to implement this feature. 

Let's revisit in the future. Keep your feedback / ideas coming @jc86035  💙  💛  💜
