### ISSUE TITLE
Geometry Suggestion: Add support for trapezoid and hexagon

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4215]
### Description

There seems to be quite a lot of searches for trapezoid and hexagon area but we're not serving it with this IA.

## Solution

We can add support for a trapezoid and Hexagon

## People to notify

@pixunil
@nalinbhardwaj
@adityatandon007
@duckduckgo/duckduckhack-contributors 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/geometry

**Comment by ryr3** [comment]
Duplicate issue?

**Comment by pjhampton** [comment]
Thanks @ryr3. I get failed to post messages from github when I try to mention certain people / groups
