### ISSUE TITLE
Geometry Suggestion: Add support for trapezoid and hexagon

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4216]
### Description

There seems to be quite a lot of searches for trapezoid and hexagon area but we're not serving it with this IA.

## Solution

We can add support for a trapezoid and Hexagon

## People to notify

@pixunil
@nalinbhardwaj
@adityatandon007
@duckduckgo/duckduckhack-contributors 

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/geometry

**Comment by linuxuser07** [comment]
I want to help with this issue

**Comment by pjhampton** [comment]
Awesome @linuxuser07! Thanks so much for stepping up. For these High Priority tasks we try to get them merged within a week fyi 👍

**Comment by linuxuser07** [comment]
I'll do my best to have it ready within a couple of days thank you

**Comment by pjhampton** [comment]
Hey @linuxuser07, 

How are you getting on? Are you still working on this or should I release it back to the community?

**Comment by linuxuser07** [comment]
Im sorry I haven't been able to get it to work.
If you could release it again to the community, what ill do ill just work
on them and when i have something ready ill let you know and submit stuff
if nobody has done it

thank you sorry for the inconvenience

**Comment by pjhampton** [comment]
Anybody up for this @duckduckgo/duckduckhack-contributors?

**Comment by pash90** [comment]
@pjhampton I would like to work on this. I understand this needs to be solved asap?!

**Comment by pjhampton** [comment]
Thanks @pash90. Yeah, issues with the `High Impract Tasks` we try to move quickly on 👍

**Comment by kirkins** [comment]
@pash90 let me know if you end up not having time for this one.

**Comment by pash90** [comment]
@kirkins sure will! 💯

**Comment by g33kgrrl** [comment]
Hi there, should the 'Needs a Developer' label be removed?  This appears to be in active development.  Just learning how things work around here, so my apologies if that's a dumb question. :)
