### ISSUE TITLE
Release Sort

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-goodies#422]
working on duckpan but not on live site: https://next.duckduckgo.com/?q=sort+9+2+3+112+3

**Comment by javathunderman** [comment]
@moollaza Is there a .pm file for this?

**Comment by moollaza** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Sort.pm

**Comment by moollaza** [comment]
Code LGTM :+1: 

Needs design team signoff

**Comment by javathunderman** [comment]
@moollaza Brilliant.

**Comment by moollaza** [comment]
Setup for release.
