### ISSUE TITLE
Calculator: x / 0 =/= infinity

### ISSUE THREAD

**Issue by rawrit** [duckduckgo/zeroclickinfo-goodies#4221]
The DDG calculator sas, that e. g. 10 divided by 0 equals infinity, but thats wrong. That would mean, that 0 times infinity equals 10 and thats definitly not the case. I suggest to set the answer to "not defined".

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by adityatandon007** [comment]
@rawrit, though your point is correct (in mathematical view), the answer is still correct. According to IEEE standard every floating point arithmetic operation is well defined, even **division by zero**.  Even google displays the same result:
![screenshot from 2017-05-21 11-50-00](https://cloud.githubusercontent.com/assets/25108385/26281663/d1df05de-3e1b-11e7-8787-76c97d6d71a8.png)

**Comment by pjhampton** [comment]
Thanks for bringing this up @rawrit! I will appreciate you input. After doing some [ducking](https://duckduckgo.com/) I agree with @adityatandon007. There isn't much I can do here anyway as we rely on [math.js](http://mathjs.org/) as a backend to the calculator.
