### ISSUE TITLE
Use server side hooks to prevent commits to the cloned master branch

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-goodies#4222]
I had seen many developers cloning our repo and committing their changes to the master branch of their cloned repo, They are not following the git branched workflow. Developers that are not familiar with using git may get into this problem and may end up with an unclean master branch.

### The solution
* I think adding a pre-commit hook to the repo will solve the problem.

AFAIK we can use git server server side hook to make it possible: https://git-scm.com/book/gr/v2/Customizing-Git-An-Example-Git-Enforced-Policy

We cant use client side hooks since they are not persistent while cloning: https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks#_client_side_hooks

What is your opinion @duckduckgo/community-leaders?

I will be happy to implement this one if you are interested 😄. I am new to git hooks, please correct me if i had any mistakes.

**Comment by mattr555** [comment]
@gautamkrishnar Unfortunately [Github doesn't let you use server-side hooks](https://stackoverflow.com/a/22100665).

It might be a job for [Danger](http://danger.systems/), I know we've explored using it in the past. We could also start with emphasizing the `git checkout -b` step in the docs more.

**Comment by ManrajGrover** [comment]
I remember discussing about introducing [pre-commit](http://pre-commit.com/) hooks in one of the mails. They will surely help avoid accidental errors, linting code, making custom checks and much more before creating a commit. This can be done on client side. Although one can bypass them if they want to, it will help reduce the number of incidents.

> We cant use client side hooks since they are not persistent while cloning: https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks#_client_side_hooks

This might add a few steps on client side where we would need to set it up after cloning the repo.

**Comment by pjhampton** [comment]
I'm going to close this and add it to the community leader call agenda for this thursday. I think we may actually conclude this there: https://forum.duckduckhack.com/t/meeting-june-2017/2048/3
