### ISSUE TITLE
Conversions: Suggestion: change name of "mass" to "weight"

### ISSUE THREAD

**Issue by zorbama** [duckduckgo/zeroclickinfo-goodies#4225]
I think it would just be easier to find and make more sense to the layman if it was called "weight" instead of "mass". It took me personally a moment to see that it was there.   

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by adityatandon007** [comment]
There is a difference between weight and mass
Weight is the force with which gravity pulls on a mass . Weight is expressed generally in newtons whereas as mass is the matter a body contains, generally expressed in kg. 
For example, your mass on earth and moon remains same but your weight changes. 

Although, I get your point :slightly_smiling_face: 
what generally mean when people say my weight is 65kg, it actually means there mass is 65kg, their actual weight would be 65*9.8 Newtons

**Comment by zorbama** [comment]
I figured it's probably more correct to call it "mass", however I do feel that changing it will improve clarity, at least for ignorants such as myself. :)

**Comment by pjhampton** [comment]
If I could leave my 2 cents...
I think we should keep it as `mass`. All the other search engines do it.

Saying that -> there is a quick win to add triggering support for `weight converter, calculator etc`  to open up at the mass calculator.

**Comment by mintsoft** [comment]
It absolutely should be mass; weight is force, mass is mass.

**Comment by pjhampton** [comment]
Ok, the big guns (@adityatandon007 + @mintsoft) have spoken. **Mass** it stays.
