### ISSUE TITLE
CalcRoots: simplify 0i to 0

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-goodies#4226]
searching for ```square root of minus zero``` gives an answer of 0i
to me it seems like this would be better if simplified to 0   

------
IA Page:  http://duck.co/ia/view/calc_roots 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by mintsoft** [comment]
Actually, it kind of depends. In the natural numbers zero is neither negative nor positive so you're correct (https://www.wolframalpha.com/input/?i=square+root+of+-0) however for floating-point representations `-0^0.5` is `-0` (http://speleotrove.com/decimal/daops.html#refsqrt). We can probably ignore the floating point however

**Comment by pjhampton** [comment]
Hey @spagy 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
