### ISSUE TITLE
Calculator: An "Ans" feature. 

### ISSUE THREAD

**Issue by Mindraker1** [duckduckgo/zeroclickinfo-goodies#4231]
Example:  
2+2=4
Ans * 9=36
Ans * 9=324
Ans + 2=326
------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
It doesn't seem like this suggestion has a lot of weight behind it. Closing for now 👍  Thansk for your suggestion @Mindraker1 💙  💛  💚
