### ISSUE TITLE
sbt Cheat Sheet

### ISSUE THREAD

**Issue by s7nio** [duckduckgo/zeroclickinfo-goodies#4234]
### Description
Provide an overview of common sbt commands.

IA Page: http://duck.co/ia/view/sbt_cheat_sheet

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @s7nio

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: http://duck.co/ia/view/sbt_cheat_sheet

**Comment by pjhampton** [comment]
Thanks, @s7nio! Can't wait to see it. I'm a Scala enthusiast myself :-) 
For contributions such as cheat sheets, you don't need to create an issue - just submit an unsolicited PR
