### ISSUE TITLE
Lolcode cheat sheet

### ISSUE THREAD

**Issue by palash25** [duckduckgo/zeroclickinfo-goodies#4243]
I would like to contribute a new lolcode cheat sheet.
IA Page: https://duck.co/ia/view/lolcode_cheat_sheet

**Comment by pjhampton** [comment]
Thanks @palash25 

For your future reference, you don't need to create issues for new cheat sheets 👍

**Comment by palash25** [comment]
OK thanks, I'll keep that in mind.
