### ISSUE TITLE
Factors: Negatives will not appear

### ISSUE THREAD

**Issue by keeganjk** [duckduckgo/zeroclickinfo-goodies#4245]
If I search `factors of 7`, factors will appear. However, no Instant Answers will appear when I search `factors of -7`.

------
IA Page:  http://duck.co/ia/view/factors 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark

**Comment by g33kgrrl** [comment]
I think I know how to fix this.  I'd be happy to give it a go.

**Comment by pjhampton** [comment]
Nice! Thanks @g33kgrrl!

**Comment by g33kgrrl** [comment]
Np @pjhampton! Looks like it's going to be pretty straightforward, though it'll probably be a few more days before I can get back to it and finish.
