### ISSUE TITLE
Calculator: No result but calculator opens

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#4246]
## Steps to recreate
https://duckduckgo.com/?q=log+0.000000000000001&t=vivaldi&ia=calculator

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by kirkins** [comment]
This doesn't relate to the number used by happens anytime log is used without brackets. 

E.g.` log 1`, `log 0.1`,` log 9`

But `log(0.0000001) ` does work.

`log x` doesn't always return blank I found the bug is different with `log 10`.

**Comment by pjhampton** [comment]
Thanks, guys. We are recording these failures in the backend and aware of all the edge cases. We're currently discussing a v2 of the interactive calculator which should be out in the next 2 months 👍

**Comment by kirkins** [comment]
@pjhampton sorry I was already toying around with this before I read your message.

I also noticed that `sqrt X` doesn't trigger an answer so I thought why not just stop triggering `log X` for now if it doesn't work.
