### ISSUE TITLE
Private Network: Triggering

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-goodies#4257]
### Description

I was looking at the Private Network Goodie in order to convert it to a structured answer but I'm not even sure it should exist.

It's completely undynamic, returning the same answer for any triggered query. It triggers for anything which starts with "private network".

For example:

- Private network for dogs
- Private network event
- Private network meaning

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/Private_Network

**Comment by mintsoft** [comment]
Thanks for the report @kirkins looks easy enough to resolve, do you want to fix it while you convert it?

**Comment by kirkins** [comment]
Possibly, I'm not sure what fixed would be for this? 

The use case is unclear.

**Comment by kirkins** [comment]
Just breaking it into 4 possible results? 

Eg private ip4 addresses - > returns said section

**Comment by mintsoft** [comment]
I think it should probably only fire for queries like `private network information` `ipv4 private network` `private network` `private network addresses` `private network ranges` `private network range` `private ip range`

**Comment by kirkins** [comment]
Sounds good, I can probably do it on the weekend.

**Comment by kirkins** [comment]
I've been hesitant to do anything related to structured answers at this time as I already have pull requests relating to this that have been in queue for a while (#4061).

**Comment by mintsoft** [comment]
@kirkins yeah that's fine there's enough in-flight I think at the moment anyway

**Comment by moollaza** [comment]
Given the outdated state + poor triggering I'm going to disable this IA. 

It currently gets no traffic, but its capable of producing irrelevant results which is the worst case for IAs
