### ISSUE TITLE
Sudoku: Broken on Beta

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-goodies#4259]
### Description

The Sudoku goodie is returning results but not properly rendering them.

![screenshot from 2017-06-06 21-42-45](https://user-images.githubusercontent.com/9503662/26858746-1a4c6bda-4b01-11e7-9557-16754a0e2f9d.png)

I can confirm that it was working before because I had started [converting it ](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4058)to a structured answer, before the [JavaScript version](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4069) was created.

Was this pushed to beta while not working or something else?

## Steps to recreate

[Search sudoku](https://beta.duckduckgo.com/?q=sudoku&t=hd&ia=answer)

## People to notify

@Mailkov @moollaza #1163

---

Instant Answer Page: https://duck.co/ia/view/Sudoku

**Comment by Mailkov** [comment]
Sudoku IA does not work in this moment
I think it's a system problem
I found this error: Template Not Found: DDH.sudoku.content
@moollaza @kirkins

**Comment by mintsoft** [comment]
o.0 works on beta: https://beta.duckduckgo.com/?q=sudoku&t=hc&ia=answer

**Comment by kirkins** [comment]
@mintsoft weird that it would be down and then back randomly like that.

It's no surprise I saw this this ad on SO :p 

https://stackoverflow.com/jobs/143159/site-reliability-engineer-duckduckgo

**Comment by mintsoft** [comment]
> @mintsoft weird that it would be down and then back randomly like that.

Beta's a different environment, I think it's more likely that it's consistently broken on production and consistently working on beta

**Comment by kirkins** [comment]
@mintsoft if you look at the logo in the screenshot I posted it is beta where it was broken.

**Comment by kirkins** [comment]
@mintsoft I don't think the Sudoku IA has ever been out of beta.

**Comment by mintsoft** [comment]
> @mintsoft if you look at the logo in the screenshot I posted it is beta where it was broken.

Ah good point, didn't spot that! Yeah in that case I'd guess it was a beta deploy or something but we'd need staff to confirm.

**Comment by kirkins** [comment]
I still see a lot of problems with this new javascript version. 

Try searching: "Sudoku easy" or "Sudoku medium"

It always seems to return hard:

![untitled](https://user-images.githubusercontent.com/9503662/26898279-43b72986-4b99-11e7-87f1-734653e9d628.png)

The original Sudoku.pm was elegant and it even had tests which would calculate that the sudoku returned was correct and solvable. Now the tests are essentially pointless.

**Comment by mintsoft** [comment]
> The original Sudoku.pm was elegant and it even had tests which would calculate that the sudoku returned was correct and solvable. Now the tests are essentially pointless.

It was also extortionately slow; the tests in the new one are only testing that the IA triggers for the correct queries. In reality the old tests weren't asserting much just that a table was returned, not that the sudoku was valid or anything

**Comment by kirkins** [comment]
@mintsoft ah, you're right on the tests. It's the same as now.

**Comment by mintsoft** [comment]
> @mintsoft ah, you're right on the tests. It's the same as now.

I have the advantage of having written them :)

**Comment by Mailkov** [comment]
The sudoku Level is determinated by the complexity of the techniques needed to solve it.
The levels are simple, easy, medium or average and hard.

**Comment by kirkins** [comment]
@Mailkov I see, I guess I was expecting easy to contain more numbers from the start. 

But I guess the placement of the same amount of given numbers could also change the difficulty. Thanks for clarifying.

Good job on this 👍

**Comment by Mailkov** [comment]
@kirkins thanks!

**Comment by kirkins** [comment]
Closing as seems to be fixed now
