### ISSUE TITLE
Password: parameters for constraints

### ISSUE THREAD

**Issue by afranke** [duckduckgo/zeroclickinfo-goodies#4264]
Some websites have stupid requirements. Example I encountered this morning: "at least 2 numbers, at least one uppercase letter, at least 8 total characters, at most 12 characters." Sometimes it can also be "no special character", or "no character from a given set"…

It would be useful to be able to pass those constraints to the generator.

------
IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by pjhampton** [comment]
Yeah, I like this idea. It's a low triggering IA though, ~1000 opens a day so it's not a high priority. Perfect for the community to take forward though.

I'm wondering if it would be beneficial to move the logic of this to the front-end to make it more interactive and easier to include features like this.

**Comment by pjhampton** [comment]
Hey @afranke 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
