### ISSUE TITLE
SVN Cheat Sheet: Add description for `svn log`

### ISSUE THREAD

**Issue by zodiac403** [duckduckgo/zeroclickinfo-goodies#4268]
Hi @Juholei 

nice and helpful Goody! I came along a few times and missed the `svn log` statement to display commit log messages with some helpful arguments (-l, -v).

http://svnbook.red-bean.com/en/1.7/svn.ref.svn.c.log.html

Any thoughts on adding it?

------
IA Page:  http://duck.co/ia/view/svn_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Juholei

**Comment by cp512** [comment]
I think it would be good to add!
