### ISSUE TITLE
IA idea: Chess notation decrypt-er

### ISSUE THREAD

**Issue by nalinbhardwaj** [duckduckgo/zeroclickinfo-goodies#4273]
### Description

A simple IA that would display a gif/image showing the meaning of a chess notation move.

Perhaps, this can be generalised as a complete chess game play displaying IA from a chess notation file.

## Steps to recreate

n/a

## People to notify

n/a

---

Instant Answer Page: Non-existent

**Comment by pjhampton** [comment]
Yeah, I like this suggestion @nalinbhardwaj. Is there anything that preexists in the wild that kind of resembles what you are thinking?

**Comment by nalinbhardwaj** [comment]
@pjhampton there are a number of PGN game viewers: [example](https://chesstempo.com/pgn-viewer.html). But besides those I'd like to have a single move displayer as well, for quicker access.

**Comment by ArjunPanickssery** [comment]
@pjhampton @nalinbhardwaj Chess positions are often recorded in [Forsyth-Edwards Notation](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation), and an IA could use the same board viewer as the [Chess960 IA](https://duck.co/ia/view/chess960).

**Comment by ArjunPanickssery** [comment]
@nalinbhardwaj [The Chess960 IA](https://duck.co/ia/view/chess960) uses a chessboard viewer for a single position.

**Comment by pjhampton** [comment]
Hey @nalinbhardwaj 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
