### ISSUE TITLE
Timezone Converter: 

### ISSUE THREAD

**Issue by PathosEthosLogos** [duckduckgo/zeroclickinfo-goodies#4277]
EST should convert to CST, PST, while EDT should convert to CDT, PDT, etc. Right now, it converts to XDT no matter what.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by pjhampton** [comment]
I'm closing this. Based on the above, I can't replicate or solve.
@PathosEthosLogos please refer yourself to our [CONTRIBUTING.md](https://duckduckhack.com/contributing.html#reporting-issues) and reopen the issue with a couple of query examples with a detailed description of the issue so we can fix it.
