### ISSUE TITLE
Password: Overtriggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4280]
### Description

The [Password Instant Answer](https://duck.co/ia/view/Password) is awesome, but it's over triggering at the moment. This is probably because the initial unit testing was too shallow. We're going to need to tie down the triggering on this IA. 

## Steps to recreate

A couple of examples include:

- https://duckduckgo.com/?q=https%3A%2F%2Fm.facebook.com%2Flogin%2Fdevice-based%2Fpassword%2F%3Fuid%3Dxxxxxx&ia=answer

- https://duckduckgo.com/?q=rncst3d.pw&ia=answer

- https://duckduckgo.com/?q=http%3A%2F%2Fmulti-boards.pw%2Fcg%2F&ia=answer

## People to notify
@duckduckgo/duckduckhack-contributors 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/Password

**Comment by adityatandon007** [comment]
@pjhampton I would like to try this but I am not clear with changes that I have to make. This is what I get: 

_Reduce the triggering by removing the trigger word **pw** and add the test for the same_

Is this, what is required to be done or anything else, let me know. If it's in my reach then I will ask and then you can assign me, and if it's not then I will leave it.

**Comment by kirkins** [comment]
This is more difficult then it appeared at first.

The problem is it's impossible to access the original query from inside the remainder function:

    triggers startend => 'password';
    # ...
    handle remainder => sub {
        my $query = lc(shift);

Given the above the following inputs:

For input `http://password` query is `""`.

For input `password` query is `""`.

For input `pw.wv.gov` query is `""`.

For matching these triggers treat `/` and `.` like they are spaces. In that `pwd` will not match for `pw` but `pw.d` will. Though with `pw d` you'd at least have `d` as your `$query` value.

This aspect of the built in DDG triggering functionality makes this problem more difficult than it appears at first.

Is there a variable that can be used to access the raw query instead of using the remainder?

If so I have a single line fix all the false triggers.

**Comment by mintsoft** [comment]
@kirkins 

> The problem is it's impossible to access the original query from inside the remainder function

There is `$req` which contains lots of useful things such as `$req->query` :: https://docs.duckduckhack.com/backend-reference/handle-functions.html#accessing-the-original-query

However I think it's much simpler than that; if we look at the test suite for the IA (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/Password.t#L27) then the query patterns look pretty simple and I think a reasonable `return unless /pattern1|pattern2|pattern3/;` might be easy enough to put together before the rest of the IA executes.

**Comment by kirkins** [comment]
@mintsoft I tried putting a few different variations of `return if` at the top but I can't get any of them to work. For example:

    return if m/^http*/i;

But "http://password" still triggers.

**Comment by mintsoft** [comment]
@kirkins I would have expected https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Password.pm#L53 to prevent most overtriggering, I wonder if this could be https://github.com/duckduckgo/duckduckgo/issues/122 getting in the way
