### ISSUE TITLE
New Flask-Ask Cheat Sheet

### ISSUE THREAD

**Issue by aayush26** [duckduckgo/zeroclickinfo-goodies#4292]
Proposing to add cheat sheet for Flask-Ask.  
Flask-Ask is a Flask extension that makes building Alexa skills for the Amazon Echo easier.  
[Read more](https://alexatutorial.com/flask-ask/)   

- [ ] Set up dev environment 

- [ ] Fork zeroclickinfo-goodies repository

- [ ] Create flask-ask.json (this will contain the cheat sheet data)

------
IA Page:  http://duck.co/ia/view/flask_ask_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @aayush26

**Comment by pjhampton** [comment]
@aayush26 Thanks for this 😄 
Can you please update your description with our [PR Template](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by pjhampton** [comment]
Sorry, I thought this was a PR. No need to create issues for cheat sheet ideas. Please just send an unsolicited PR

**Comment by aayush26** [comment]
Ok. Thanks. Will be sending PR soon.
