### ISSUE TITLE
Conversions: Mistake in energy conversion

### ISSUE THREAD

**Issue by githubuser2012** [duckduckgo/zeroclickinfo-goodies#4298]
There is a mistake in energy conversion https://duckduckgo.com/?q=erg+to+joule&t=ffab&ia=answer .  1 erg = 10^-7 J, and not 10^-5 J as is shown.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Already in-light: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4297

**Comment by pjhampton** [comment]
Yep, and [patched in 3rd party dependency](https://github.com/josdejong/mathjs/pull/877). Closing 👍
