### ISSUE TITLE
Conversions: Distinguish Imperial and U.S. gallons

### ISSUE THREAD

**Issue by Arcorann** [duckduckgo/zeroclickinfo-goodies#4300]
The currently included "Imperial Gallon" is the U.S. gallon of 231 cubic inches (~3.7854 litres). As per Wikipedia, the Imperial system defines a different gallon of 4.54609 litres, so these two should be distinguished.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
@Arcorann Thanks for the report, sadly this was regressed recently in order for us to get the interactivity in, however we're actively working on resolving these issues :+1:
