### ISSUE TITLE
Conversions: Error in conversion between erg and joule (energy unit)

### ISSUE THREAD

**Issue by Ielr** [duckduckgo/zeroclickinfo-goodies#4301]
There seems to be a conversion problem between erg and joule.
Currently 1 erg is convert to 1e-5 joule, whereas it should be 1e-7 J.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Already fixed, will be deployed soon! https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4298
