### ISSUE TITLE
Color Picker Bug: Rounding error in hex code under color schemes

### ISSUE THREAD

**Issue by manrajgrover** [duckduckgo/zeroclickinfo-goodies#4312]
### Description

[B.C. Legon](https://twitter.com/BCLegon) on twitter [reported](https://twitter.com/BCLegon/status/875692205498929152) this bug. There seems to be rounding error in hex code under color schemes i.e. `#ba0000` should be `#bb0000` under `analogous`. This would need further investigation on whether behaviour is intended or not.

![dccvxtnwsaacsfb](https://user-images.githubusercontent.com/5673050/27298802-b6ecf9f0-5547-11e7-9311-8dfa580a3b6c.jpg)

## Steps to recreate
[color picker #bb0000](https://duckduckgo.com/?q=color+picker+%23bb0000&t=hz&ia=answer)

## People to notify
@pjhampton @moollaza

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/color_picker

**Comment by mintsoft** [comment]
Hmm, I'm not sure here. The ColourPicker is consistent with the ColourCodes IA https://duckduckgo.com/?q=bb0000&t=vivaldi&ia=answer which uses the `Color::Mix` cpan module whereas I believe ColourPicker uses some hand-written js. I guess maybe ColourPicker was built based on ColourCodes being correct?

**Comment by mintsoft** [comment]
Hmm ColorHex.com implies that both IA's are wrong: http://www.color-hex.com/color/bb0000 and it should be `#bb0000` `#bb5e00` `#bb005e`

I'd like a second source though

**Comment by adityatandon007** [comment]
Yeah, the answer displayed is definitely wrong.
Correct answer should be: 
**Analogous**: `#bb005e, #bb0000, #bb5e00` 
**Triad**: `#0000bb, #bb0000, #00bb00` and **Tetrad** values are wrong too. I agree with @ManrajGrover that it might be happening because of rounding errrors. 

@mintsoft here is the second source: http://www.colorhexa.com/bb0000

**Comment by mintsoft** [comment]
So based on that information, both ColorPicker and ColorCodes are affected, related issue for ColorCodes: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4313
