### ISSUE TITLE
JSON Validator: Make the textarea horizontally resizable

### ISSUE THREAD

**Issue by zimmi** [duckduckgo/zeroclickinfo-goodies#4315]
Right now it's only possible to resize the textarea vertically. The default width is not enough for moderately nested JSON, making it hard to see everything without using the tiny browser scrollbar.

Thank you so much for the JSON Validator, it's great!

------
IA Page:  http://duck.co/ia/view/json_validator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by adityatandon007** [comment]
@zimmi I see your point, but I think it should still be discussed with other members whether to add the `resize: horizontal` thing in css or not.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
