### ISSUE TITLE
Conversions: Scientific notation used when number of digits is the same

### ISSUE THREAD

**Issue by MaxBesco** [duckduckgo/zeroclickinfo-goodies#4317]
Converting 100000 miles to kilometers. Why is the miles box not in scientific notation when the kilometers box is? It would make sense to have both or neither if they have the same number of digits.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by pjhampton** [comment]
@MaxBesco Can you explain further, please? Maybe add screenshots to make it more clear

**Comment by MaxBesco** [comment]
![screen shot 2017-06-22 at 10 48 39 am](https://user-images.githubusercontent.com/3891641/27448129-7419cf5c-5738-11e7-8ce1-1a6098645a35.png)

**Comment by pjhampton** [comment]
This is common and the intended behavior.  Unit converters by other search engines do the same. As you can imagine the convert to numbers can get _very_ big and makes sense to show them in e notation.

**Comment by mintsoft** [comment]
@pjhampton personally I think this is a regression, I think it's far more intuitive for people to see relatable numbers for values < 10,000,000 or so
