### ISSUE TITLE
Videos: non-ascii characters displayed wrong

### ISSUE THREAD

**Issue by kriman** [duckduckgo/zeroclickinfo-goodies#4329]
### Description
Non-ascii characters not displayed correctly as the example shows.
![example](https://user-images.githubusercontent.com/6263617/27623840-9e0f69d4-5bde-11e7-9b47-9ce2d08f687c.png)
It's only happens when the instant answer is triggered by Javascript.
## Steps to recreate
Type something in the search field which has non-ascii characters in it and can trigger the Videos IA (in my example "Számítógép szétszerelése". When you reload the page the characters displayed correctly (that's why I think it's related to Javascript). If you load [this link](https://duckduckgo.com/?q=Sz%C3%A1m%C3%ADt%C3%B3g%C3%A9p+sz%C3%A9tszerel%C3%A9se&ia=videos) it's correct and if you click on the search again it's wrong.

## People to notify
@bsstoner

---

Instant Answer Page: https://duck.co/ia/view/videos

**Comment by mintsoft** [comment]
@bsstoner @pjhampton I don't think this is something that the community can resolve, isn't the videos tab in the closed-source side of the house?

**Comment by ManrajGrover** [comment]
@minsoft Yes, I tried fixing it yesterday. It turns out, even on first trigger the query parameter in API response has ASCII issues although it is not shown as search term at that time.

**Comment by moollaza** [comment]
Thanks for reporting. I'll forward to the team 👍

**Comment by moollaza** [comment]
The team is looking into this 👍

**Comment by kirkins** [comment]
Just wanted to point out that this bug is filed on the wrong repo as pointed out by @busticated

**Comment by moollaza** [comment]
Closing. I believe this is fixed now anyways.
