### ISSUE TITLE
Calculator: Rounding in floating point arithmetic

### ISSUE THREAD

**Issue by M-Schiller** [duckduckgo/zeroclickinfo-goodies#4334]
Please fix calculation when using [floating-point numbers ](https://duckduckgo.com/?q=3000+*+0.035). I would expect to get the answer 105. 
Possibly [related](https://en.wikipedia.org/wiki/Significant_figures#Arithmetic) to this topic.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
![image](https://user-images.githubusercontent.com/978048/27810165-f6b0a110-604e-11e7-874e-36004e4aeed9.png)

**Comment by pjhampton** [comment]
Thanks @M-Schiller 👍 . 
Can you please familiarize yourself with our [CONTRIBUTING.md](https://duckduckhack.com/contributing.html) and use our [Issues Template](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/.github/ISSUE_TEMPLATE.md) in future?

**Comment by M-Schiller** [comment]
Thanks @pjhampton.
I somehow messed up the markdown and wasn't able to fix it. Regarding the template - I will use it in the future and I'm sorry I didn't know that this existed. I hope that linking to the reproducing query was not too far off the mark.

**Comment by M-Schiller** [comment]
Thanks @pjhampton.
I somehow messed up the markdown and wasn't able to fix it. Regarding the template - I will use it in the future and I'm sorry I didn't know that this existed. I hope that linking to the reproducing query was not too far off.

**Comment by pjhampton** [comment]
It's perfect. Thanks @M-Schiller 😄 
I will try and get round to fixing this today 👍
