### ISSUE TITLE
Suggestion: PHP Security Cheat Sheet

### ISSUE THREAD

**Issue by mish24** [duckduckgo/zeroclickinfo-goodies#4336]
Is this a good idea? I would like to work on this once I get the approval please? :)

**Comment by pjhampton** [comment]
Hi @mish24,

You don't need to create issues to get cheat sheet approval. Please just submit an unsolicited PR. 
Also, please read our [CONTRIBUTING.md](http://duckduckhack.com/contributing.html) and use our Issues template in future 👍
