### ISSUE TITLE
figlet Bug: No spaces in sentences

### ISSUE THREAD

**Issue by BuonOmo** [duckduckgo/zeroclickinfo-goodies#4338]
when you type [figlet my sentence](https://duckduckgo.com/?q=figlet+my+++sentence&atb=v63-6__&ia=answer) you get a figlet for _mysentence_.

---

Instant Answer Page: https://duck.co/ia/view/figlet

**Comment by pjhampton** [comment]
Hey @BuonOmo 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
