### ISSUE TITLE
Calculator: Using 1/x gives wrong result

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-goodies#4340]
**Bug:**
I was trying to calculate `241/2`. But I used `1/x` to solve this instead of division operator. 

**STEPS:**

Type 241 and then as soon as I pressed `1/x` it got added to the expression like `2411/(` 
![screenshot from 2017-07-07 16-33-24](https://user-images.githubusercontent.com/25108385/27955399-4555fdd4-6332-11e7-8376-56bc2a026063.png)

and after this I typed 2 and and then `=` sign and it gave me the result as `1205.5` . I was expecting the answer `120.5`
![screenshot from 2017-07-07 16-33-44](https://user-images.githubusercontent.com/25108385/27955479-a3f8cd30-6332-11e7-8c0e-11f131e7034b.png)
![screenshot from 2017-07-07 16-34-02](https://user-images.githubusercontent.com/25108385/27955487-a939f2ba-6332-11e7-8f55-903b8e629596.png)

**Solution:** Add an `*` sign automatically when somebody presses `1/x` so that it gets interpreted as `241*(1/x)`.

People to notify:
@pjhampton @mintsoft 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Thanks @adityatandon007. Will add to my open PR.
