### ISSUE TITLE
Calculator: Can't select answer in Firefox

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#4341]
### Description

In Firefox 54 (reproduced in other versions, 51,49) when the answer in the calculator is selected using the mouse it is immediately de-selected again; meaning the user is unable to copy the answer to the clipboard.

## Steps to recreate
* Use firefox
* Calc
* Select
* Fail to select
* Goto Step 3

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by mintsoft** [comment]
![2017-07-09_00-11-12](https://user-images.githubusercontent.com/978048/27989856-7e41fa1c-643b-11e7-956b-326b514b5dcc.gif)

**Comment by moollaza** [comment]
PR incoming...
