### ISSUE TITLE
Roman Numerals Suggestion: Improve IA

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4344]
### Description

**This will require a developer comfortable working with js**. We aim to get High Impact tasks completed and merged in a week.

There is quite a lot of queries per week ( 1000 > x < 2000 ) looking for [Roman Numeral](https://en.wikipedia.org/wiki/Roman_numerals) Conversions. **We should improve the triggering and interactivity.** A random dump of queries includes:

```
- roman numerals
- roman numeral
- roman numeral chart
- roman numeral convert
- roman numeral converter
- roman numbers
- xv roman numerals
- <number> in roman numerals
- <number> in roman numbers
- convert to roman numerals
- convert <number> to roman
etc
```

The developer could use the UI from one of the following IAs:

- [Conversions](https://duckduckgo.com/?q=1337+m+to+cm&atb=v1&ia=answer)
- [js minify](https://duckduckgo.com/?q=minify+js&atb=v1&ia=answer)

## People to notify

@duckduckgo/duckduckhack-contributors 

---

Instant Answer Page: https://duck.co/ia/view/roman

**Comment by gargaml** [comment]
I'd like to work on this :-)

**Comment by pjhampton** [comment]
Thanks @gargaml 👍

**Comment by fenilgandhi** [comment]
The IA does not work for "4999 in roman [numerals"``](https://duckduckgo.com/?q=4999+in+roman+numerals&ia=web)

**Comment by gargaml** [comment]
@fenilgandhi This is true. Currently the upper bound is 3999 as it is the greatest number you can write without using non-ascii characters. The current algorithm is extensible so if this is an issue, we can go a bit further. 
I don't know how many queries involve spelled numbers. There are some rules for numbers smaller than 10. If it's useful, I'll add it (or you can actually get involved if you want to :-))

I'm going to add a warning when the user uses number greater than the upper bound to avoid confusion.
