### ISSUE TITLE
Timer: Overtriggering on queries related to Time math

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4346]
This IA triggers on queries like ["5:15 + 32 minutes"](https://duckduckgo.com/?q=5%3A15+%2B+32+mins&ia=answer), "3:32 - 8 mins", etc

These kinds of queries shouldn't trigger this Instant Anwer

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by cmccre** [comment]
I was looking around at Timer.pm trying to orient myself with the problem and I'm wondering what the rationale for this is:
`
# Ambigous triggers which should not give Timer IA
my @ambigousTriggers = ("20 minutes", "22 minutes", "60 minutes", "48 hours");
`

I see that if I type in something like "32 minutes" the timer is triggered, but as indicated above, something like "20 minutes" does not.

**Comment by mintsoft** [comment]
@cmccre basically those are the names of tv shows in various countries. If the user is searching for just that, it's more likely they want the tv show than a timer

**Comment by harisw** [comment]
@cmccre sorry, i'm a just beginning to start in open source, may i know how is the desired(in this search engine) output then?

**Comment by mintsoft** [comment]
@harisw Certainly, the IA should just `return;` in that case and there should be tests asserting that. I tend to 'test-drive' changes like that so I would:
* change the `Timer.t` file and add a test that asserts it should just return like: `    '60 minutes' => undef`
* run the tests (`prove -Ilib t/Timer.t` or `duckpan test`)
* change the IA to make this not return

**Comment by mintsoft** [comment]
Example of the tests: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/TextConverter.t#L157
