### ISSUE TITLE
stack_overflow bug: instant answer does not contain bullets

### ISSUE THREAD

**Issue by mcomella** [duckduckgo/zeroclickinfo-goodies#4347]
### Description
StackOverflow instant answers don't contain bullets even if the post on StackOverflow does. For example:
- [Duckduckgo search](https://duckduckgo.com/?q=android+appbarlayout+resize+delay&t=ffab&ia=qa&iax=1)
- [Associated answer](https://stackoverflow.com/a/36558911/2219998)

## Steps to recreate
1. Search for a SO post with bullets (example query: "android appbarlayout resize delay")

Expected: bullets in IA result
Actual: no bullets

---

Instant Answer Page: https://duck.co/ia/view/stack_overflow

**Comment by jarifibrahim** [comment]
I would like to work on this issue. Can anyone please point me to the relevant files?

**Comment by mintsoft** [comment]
It's a long-tail answer, so it isn't actually in this repo (see https://duck.co/ia/view/stack_overflow)

The code is here: https://github.com/duckduckgo/zeroclickinfo-longtail/tree/master/lib/longtail/stackoverflow

**Comment by mintsoft** [comment]
Issue transferred to: https://github.com/duckduckgo/zeroclickinfo-longtail/issues/120
