### ISSUE TITLE
Goodies: Triggering on `.` and `:`

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/zeroclickinfo-goodies#4353]
### Description

_EDIT: this also applies to `:`_

When using the built in trigger functionality, there is some issues with the handling of `.`

I highlight one example in #4280

For the triggering side of things `.` is treated the same as a space.

But inside the remainder function the whole "chunk" is treated as a word.

## Steps to recreate

For example on the triggering side of things the query `weather.yahoo.com montreal` is treated the same as `weather montreal`.

For both of these queries the remainder in:

```
triggers startend => 'weather';
# ...
handle remainder => sub {
    my $query = lc(shift);
```
... will be exactly the same.

One can get a bit silly with this for example:

`http://weather.underground.com/rebel new york` is treated exactly like `weather new york`.

https://beta.duckduckgo.com/?q=http%3A%2F%2Fweather.underground.com%2Frebel+new+york&t=hz&ia=weather

Remainder will still just be `new york`.

I think this problem is larger then the URLs mentioned in issue #4280, it's going to cause issues on nearly every Goodies. Especially if it contains a single word trigger.

## Other examples

`222.444.2048:5000` https://beta.duckduckgo.com/?q=222.444.2048%3A5000&t=hz&ia=answer&mmexp=b

`pw.wv.gov` https://beta.duckduckgo.com/?q=pw.wv.gov&t=hz&ia=answer

_EDIT: I would expect this to happen with [Calendar](https://duck.co/ia/view/calendar_today). Yet it doesn't, am I wrong on my interpretation of this? `calendar.google.com`, `calendar:5000`, `cal.com`. None of these seem to trigger the calendar IA, so it seems to break my theory._

## People to notify

@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by mintsoft** [comment]
@kirkins I think this is probably a duplicate of: https://github.com/duckduckgo/duckduckgo/issues/122 does it look consistent?

**Comment by kirkins** [comment]
@mintsoft absolutely the same bug, only adding that `.` is also causing similar issue.

I'm closing.

Is it possible for people to look at the code powering the query? I'm assuming it's not open-source?

**Comment by mintsoft** [comment]
@kirkins The code is instant answer wide so it should be around https://github.com/duckduckgo/duckduckgo/blob/master/lib/DDG/Request.pm#L188
