### ISSUE TITLE
JSONValidator: Add support for giving indent size in query

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-goodies#4361]
### Description

**Feature request:** Would love to see support for accepting the size of indentation (number of spaces) from the query.

**Use case:** A lot of times when I want to recommend people to use this IA, I have to manually mention the number of spaces I'd like them to use for consistency. Will be super cool if I can mention the space size in the query itself and share the corresponding link. (e.g. query `'json validator 4 spaces'`)

## People to notify

N/A

---

Instant Answer Page: https://duck.co/ia/view/json_validator

**Comment by shivakrishna9** [comment]
@sahildua2305 Seems like a beginner issue. I want to work on it. What actually have to be done here?

**Comment by sahildua2305** [comment]
@shivakrishna9 the idea I have is to parse the query input and if it matches certain pattern mentioning spaces in a tab, we need to set that by default.
