### ISSUE TITLE
Name days: Convert to structured answer and move code to template

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4362]
### Description

The name days IA needs to be updated. It's got a lot of legacy code, injecting html into the duckbar which shouldn't be happening. For some reason the styles are messed up now (below is what it should look like) 

Can you please update this @kirkins?

![screen shot 2017-07-18 at 10 15 09 am](https://user-images.githubusercontent.com/8960296/28309688-06395f38-6ba2-11e7-97da-30e3339fc424.png)

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/name_days

**Comment by kirkins** [comment]
Will take a look later.

**Comment by pjhampton** [comment]
Hey @kirkins, did you get a chance to look at this?

**Comment by kirkins** [comment]
@pjhampton started but not done. It will take a lot of work and busy at job this week.

**Comment by kirkins** [comment]
@pjhampton https://github.com/kirkins/zeroclickinfo-goodies/commits/incomplete_nameday

**Comment by pjhampton** [comment]
Thanks dude :)

**Comment by kirkins** [comment]
@pjhampton I like Perl but still a noobie when it comes to the workflow.

I'm on codio and I want to run a utility that comes with this to preprocess the data _(as it needs to be re-written to remove the html)_.

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/name_days/preprocess.pl

When I try to run it on Codio I get:

```
Can't locate DateTime.pm in @INC (you may need to install the DateTime module) (@INC contains: /etc/perl /usr/local/lib/perl/5
.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site
_perl .) at ./preprocess.pl line 5.
BEGIN failed--compilation aborted at ./preprocess.pl line 5.
```
I try running `cpan` then install DateTime and also tried App::DateTime, but I still get the same error.

Do you know how I can install the DateTime module globally? _(coming from node.js background)_

**Comment by kirkins** [comment]
@pjhampton update:

Instead of doing `./preprocess.pl` I used `perl preprocess.pl` and some how this made my CPAN modules available. So that is fixed.

Too bad I spent a bunch of time manually editing all the text files before I realized they were generated... doh. ◔̯︵◔

**Comment by pjhampton** [comment]
Thanks @kirkins! Sorry I didn't get seeing this. I got distracted with https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4373

**Comment by kirkins** [comment]
@mintsoft do you know of any examples of a structured answer with an array?

![untitled](https://user-images.githubusercontent.com/9503662/28473486-c9e9cb08-6e12-11e7-96f5-ee57a4133b4f.png)

![untitled](https://user-images.githubusercontent.com/9503662/28473514-f4208402-6e12-11e7-85ba-b57d427aa966.png)

`Title` and `name_days` are the same above except `name_days` has been broken into an array.

It's like the second item in the array becomes an attribute itself :confounded:

**Comment by mintsoft** [comment]
@kirkins I don't know an example off the top of my head. What you're seeing is normal perl behaviour, the problem is that it should be an array *reference*, not an array to get what you intended:
```perl
data => {
    title => $text,
    name_days => \@name_days,
},
```

**Comment by kirkins** [comment]
@pjhampton I posted some [screen-shots](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4376#issuecomment-317229951) comparing live, beta, and my PR. 

It seems this comes down to the CSS file associated no longer being loaded. See this comparison on the network tab:

**Live:**
![untitled](https://user-images.githubusercontent.com/9503662/28501768-04260206-6fb1-11e7-851d-e174d3c20e89.png)

**Beta:**
![untitled](https://user-images.githubusercontent.com/9503662/28501779-2577dd3a-6fb1-11e7-96fb-a754c5ade496.png)

It's strange that this would happen if the CSS was loading fine before. It makes me wonder if the root cause for this issue will cause similar problems for other Goodies.

**Comment by pjhampton** [comment]
Possibly, but don't worry about that @kirkins. You can override it in the IAs local CSS 👍
