### ISSUE TITLE
Text Converter: "base64 decode" shows base64 encoder

### ISSUE THREAD

**Issue by timmyrs** [duckduckgo/zeroclickinfo-goodies#4365]
![1](https://user-images.githubusercontent.com/11009697/28347396-16d185c4-6c37-11e7-95ed-74add49e1d47.png)

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
@timmyrs Are you saying that it shouldn't show the encoder? Were you expecting information about what base64 encoding is?

**Comment by pjhampton** [comment]
@mintsoft _I think _the labels are the wrong way around. He wants to decode from base64 to ascii. Should be an easy enough fix

**Comment by timmyrs** [comment]
@pjhampton Yes. I just had the issue again. :(
