### ISSUE TITLE
Anagram.pm - Should be separated into Anagram.pm and Scramble.pm

### ISSUE THREAD

**Issue by MarcusJT** [duckduckgo/zeroclickinfo-goodies#437]
An anagram is much more than the scrambled letters of the input, an anagram is an intelligible (and ideally meaningful) rearrangement of the input letters as one or more words in English (or another language).

See http://en.wikipedia.org/wiki/Anagram and http://www.wordsmith.org/anagram/

Unfortunately this is a non-trivial problem so unless you really want to attempt it and do it well I suggest that you rename your DDG plugin to "Scramble.pm" so that it accurately reflects what it actually does (which will in turn ensure that people don't misunderstand what anagrams actually are).

https://duck.co/ia/view/anagram

**Comment by javathunderman** [comment]
@moollaza ping, saw this on the community platform somewhere- should we still split this?

**Comment by moollaza** [comment]
@javathunderman if possible, I see no reason why not :)
