### ISSUE TITLE
Joshua Bjornn: 

### ISSUE THREAD

**Issue by jbjornn** [duckduckgo/zeroclickinfo-goodies#4370]
{"status_url":"https://status.github.com/api/status.json","messages_url":"https://status.github.com/api/messages.json","last_message_url":"https://status.github.com/api/last-message.json","daily_summary":"https://status.github.com/api/daily-summary.json"}

**Comment by pjhampton** [comment]
This doesn't meet our requirements for an issue - please see duckduckhack.com/contributing.md
