### ISSUE TITLE
Conversions: Mb to MB is picked up as Megabyte to Bits

### ISSUE THREAD

**Issue by Tzeejay** [duckduckgo/zeroclickinfo-goodies#4371]
Link with images for reference. https://twitter.com/Tzeejay/status/888073621083758592

Just so that you understand what I was trying to achieve, I was checking on network speeds and bits to bytes conversion in the head are always kind of impossible for me...

It would be great to see this fixed 👍🏻

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
@pjhampton This is a regression in the JS, it was fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3990 before the interaction change
