### ISSUE TITLE
Help Line: Non-english terms for "suicide" don't trigger Help Line info

### ISSUE THREAD

**Issue by schuderer** [duckduckgo/zeroclickinfo-goodies#4374]
German terms for suicide ("selbstmord", "suizid", "sich umbringen") don't trigger the help line information. Currently, German-speaking users need to search for "suicide" in English to get the German help line info, which may miss a lot of opportunities where the info could be helpful. I propose opening the help line info up for non-English search terms.

------
IA Page:  http://duck.co/ia/view/help_line 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @conorfl

**Comment by pjhampton** [comment]
Yeah, I 100% agree we need to do **much** better here. 

The DuckDuckHack ZCI repos don't have a universal i18n solution, but I can develop something special for this Instant Answer. We will need the weight of the community to add the translations though.

**Comment by pjhampton** [comment]
Related Issues:

- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3558
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3557

**Comment by Ben-Oni** [comment]
Thanks @pjhampton! As a native speaker, I'd be glad to help out with the German translations. I can also provide some early translations for Dutch, if this helps.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
