### ISSUE TITLE
Chess Position Suggestion: An IA that Presents a Chess Position

### ISSUE THREAD

**Issue by ArjunPanickssery** [duckduckgo/zeroclickinfo-goodies#4379]
### Description
Chess positions are often recorded using [Forsyth-Edwards Notation](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation). This IA could display an FEN position on a chessboard viewer.

The [Chess960 IA](https://duck.co/ia/view/chess960) uses a chessboard viewer already. It just has to be modified to display a given position rather than creating a random one.

## Steps to recreate
N/A

## People to notify
N/A

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by pjhampton** [comment]
@ArjunPanickssery Can you please use our predefined issues / pr templates from now on. They exist for a reason. I will just start closing these if you don't.

**Comment by ArjunPanickssery** [comment]
@pjhampton Sorry. It won't happen again.

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
