### ISSUE TITLE
Pandas Cheat Sheet: Typo in First Aggregate Example

### ISSUE THREAD

**Issue by stephenskory** [duckduckgo/zeroclickinfo-goodies#4382]
When searching for ["pandas cheatsheet"](https://duckduckgo.com/?q=pandas+cheatsheet&t=osx&ia=cheatsheet&iax=1) there is a typo. As the screenshot shows, 

    df.groupby('column1'.sum())

is missing a `)` and should be fixed to:

    df.groupby('column1').sum())

![screen shot 2017-07-25 at 4 23 35 pm](https://user-images.githubusercontent.com/3922924/28596488-fea68926-7155-11e7-8d1a-759f27697fcb.png)

------
IA Page:  http://duck.co/ia/view/pandas_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Hitechverma

**Comment by stephenskory** [comment]
Ergh

    df.groupby('column1').sum()

my fixed example in my original message had the trailing `)` that the original had as well.

**Comment by urohit011** [comment]
I would like to work on this.
