### ISSUE TITLE
Calculator: Edge Cases

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4391]
### Description

For Calculator IA edge cases, please **comment them below** this issue and someone will fix them in due course. 

![calculator](https://user-images.githubusercontent.com/8960296/28710681-e0049dae-737c-11e7-96c3-69121a42d7e4.png)

## People to notify

@duckduckgo/duckduckhack-contributors 

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by Survivor75** [comment]
In Calculator IA, ∀ x ∈ - Z . Factorial(x) = -Factorial(-x).
In some cases whenever we need factorial of a negative number ,we  take it as, -Infinity.
The factorial function is defined for non-negative integers only.
0!=1
n!=n×(n−1)!, ∀ n ∈ Z
However, we can generalize the factorial function to the Gamma function
Γ(x)=∫∞0tx−1e−tdt.
Note that the Gamma function is undefined for nonpositive integers, though it is defined for every other number, including complex numbers.
Here's a link that I found helpful : [https://mathoverflow.net/questions/10124/the-factorial-of-1-2-3](url)

**Comment by adityatandon007** [comment]
@pjhampton calculator doesn't give the result when trying to calculate roots multiple times

**Query**
![screenshot from 2017-08-05 15-21-20](https://user-images.githubusercontent.com/25108385/28994751-2e05f044-79f3-11e7-95c3-20dfe01d7568.png)

**Response**
![screenshot from 2017-08-05 15-21-37](https://user-images.githubusercontent.com/25108385/28994756-4cfbab4c-79f3-11e7-8938-566a4cc87a17.png)

**Answer**: It should display `2`

**Comment by pjhampton** [comment]
Yeah, this is an edge case. I can fix soon.

**Comment by adityatandon007** [comment]
Hey, I would like to try but don't know what can be the patch for this. The
calc code has changed a lot from what it used to be. Can you guide me what
changes I have to make to fix this. If i can't then of course you can
always take it.


On Aug 5, 2017 6:02 PM, "PJ Hampton" <notifications@github.com> wrote:

Yeah, this is an edge case. I can fix soon.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4391#issuecomment-320441200>,
or mute the thread

**Comment by tagawa** [comment]
**Query:** https://duckduckgo.com/?q=2+%5E+-53&ia=calculator

**Response:** 
![djjn400uwaajsje jpg-large](https://user-images.githubusercontent.com/94173/30199271-f1091958-94ac-11e7-9282-cc16c016f934.jpeg)

**Answer:** Not zero.

**Comment by tagawa** [comment]
Calculator can't correctly multiply with percentages with more than two decimal places. An extra `%25` is added to the URL which seems to mess things up. Example:

304*3.1%
Answer: 942.4

304*3.10%
Answer: 9.424

304*3.100%
Answer: 912

304*3.1000%
Answer: 9120

**Comment by philipmiesbauer** [comment]
Just for clarification. The only correct answer is with 2 decimal places?

**Comment by philipmiesbauer** [comment]
I checked up and the answer to 304*3.1% is also 9.424. so that is correct.
The extra %25 you are referring to is the URL encoded prevent character, %.
The seems to be an issue in the calculation, the URL is working fine.

**Comment by philipmiesbauer** [comment]
I have raised an issue on the IA.

**Comment by mintsoft** [comment]
Another one: `log 0.000159154944` 

![inf](https://user-images.githubusercontent.com/978048/33632939-19092f84-da07-11e7-9797-9e9cdfd3d650.png)

**Comment by AlterationBrick** [comment]
Input: 0^0
Answer: 1
This is not correct

**Comment by DavidGinzberg** [comment]
@AlterationBrick I puzzled over this a bit and finally caved in and searched for it from a few sources. It's a fun question to contemplate.

It looks like 0^0 actually is considered equal to 1 in an algebraic sense. Although there's a lot more to its meaning in different contexts. That's expanded upon both in [Wikipedia](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero) and [Quora](https://www.quora.com/What-is-0-0-the-zeroth-power-of-zero-1).

My intuition here is that given the "numbers on a calculator" context, `1` or `undefined` would both be acceptable results here. 

Is there a different result that you would suggest should be displayed instead?

**Comment by pjhampton** [comment]
Yeah, I am running with 1 being the correct answer. Regardless, this is a math.js evaluation. The best we can do is override it :-)

**Comment by philipmiesbauer** [comment]
Since we are never going to make everybody happy with either answer is it
worth linking the answer to the Wikipedia article for further explanation?

**Comment by adityatandon007** [comment]
Yes, we cannot satisfy everyone, but I think we should stick with *1* here just because wiki says so.

**Comment by AlterationBrick** [comment]
Thanks for the responses; I was judging the answer against the output of my
TI-83+ which gives a domain error, but it seems that the consensus in
computing is to grant 0^0 the value of 1. In interests of convenience and
consistency it seems valid to keep it this way. I did not realize that I
had stumbled onto a centuries-old mathematical debate...

**Comment by MatthewBaa** [comment]
Not sure if intentional but inconvenient: enabling caps lock will disable key shorcuts, i.e. pressing "p" for Pi or "c" for cosine will no longer work whilst caps lock is enabled.
