### ISSUE TITLE
Calculator: Button symbols not displaying properly

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4397]
Square root, pi and other symbols (+-= etc.) are displayed with ? indicating a font issue, but it's fine in Firefox, Vivaldi and Brave.

**Environment:** 
Safari 10.1.2 on Mac 10.12.6
No extensions installed

![calculator-font-issue](https://user-images.githubusercontent.com/94173/28770075-d3043c74-7618-11e7-9b2c-999f3a67b8b7.png)
   

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
@tagawa with this exact setup I can't replicate. Do you have any special settings enabled?

![screen shot 2017-07-31 at 3 17 24 pm](https://user-images.githubusercontent.com/8960296/28781877-715a2912-7603-11e7-9e07-ebbab20d6995.png)

I'm wondering if it could be your user encoding? If so, what have you got it set to?

![screen shot 2017-07-31 at 3 19 05 pm](https://user-images.githubusercontent.com/8960296/28781984-c63fe44e-7603-11e7-9e07-69b501e8fbed.png)

**Comment by pjhampton** [comment]
@tagawa ping 😄

**Comment by tagawa** [comment]
@pjhampton Thanks for investigating. No special setup that I'm aware of. Safari's not my main browser so I've not changed many settings. Encoding is UTF-8 which should be fine but even changing it to Latin 1 doesn't have an effect.

In the inspector, if I remove all Proxima Nova font variants from the CSS then it's OK, so looks like it's a problem with my system fonts. Perhaps the browser is ignoring web fonts because I have Proxima Nova installed, but my installed font files don't cover all special characters. That would explain why I haven't seen any user complaints - Proxima Nova is probably pretty uncommon on end-user systems.

**Comment by moollaza** [comment]
Closing as this seems like a localized then. I'm not sure we can force the browser to use our font if the system has it installed?
