### ISSUE TITLE
Allow IA for names with accented charactors by using the non accented variants

### ISSUE THREAD

**Issue by Qwertie-** [duckduckgo/zeroclickinfo-goodies#4400]
For example searching `time in zurich` will show no IA where as `time in zürich` works as expected and shows you the time

    SUGGESTION
Allow accented characters to be substituted with regular characters (u matches with ü)

  

---

Instant Answer Page: https://duck.co/ia/view/time

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
