### ISSUE TITLE
Conversions: TiB is treated as Bits

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#4405]
### Description
This isn't really a corner case, it's just wrong!

https://duckduckgo.com/?q=1226623357721+bytes+in+TiB&t=ffab&ia=answer

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by pjhampton** [comment]
Thanks. I have patched this in an upcoming PR.
