### ISSUE TITLE
Calculator: can not select history items properly

### ISSUE THREAD

**Issue by BrendonIrwan** [duckduckgo/zeroclickinfo-goodies#4409]
Specifically, when attempting to select a previous answer (found to the right of the calculator), the selection becomes un-selected immediately. This makes it hard for users to right-click and do something about it.

Copying with [ctrl + c] is still possible as long as the selection is held (mouse button is held).

Client: Firefox 54.0.1 on Win32, and this has happened with previous 5x versions

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by aayush26** [comment]
Can adding a copy clip logo be a better UX for user to be able to copy the previous history calculations?

**Comment by BrendonIrwan** [comment]
Issue corrected, thanks guys
