### ISSUE TITLE
Text Converter: Hex string fails to convert to Base64

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4411]
## Steps to reproduce:
1. Open the [hex to base64 converter](https://duckduckgo.com/?q=hex+to+base64&ia=textconverter)
2. Convert this hex string:
`3082048830820370A00302010202081CE49DE9952A2FC0300D06092A864886F70D01010B0500305C3122302006035504030C19432E43474D2E48554D414E2D43413120544553542D4F4E4C593111300F060355040B0C0848554D414E2D434131163014060355040A0C0D43474D204E4F542D56414C4944310B3009060355040613026465301E170D3134313230353132343930305A170D3139313230353132343930305A30818A3120301E06035504030C174865727220526F736120526F7468544553542D4F4E4C59310D300B060355042A0C04526F736131133011060355040B0C0A5836383639373132373431123010060355040B0C093939393536373839303121301F060355040A0C1843474D204D75737465726B617373654E4F542D56414C4944310B300906035504061302444530820122300D06092A864886F70D01010105000382010F003082010A02820101008F23B7C19ED1F0845AEF1394F26FCBC5BA29B942D03D693850B156E8F19371338CE75B2DA06F628659A5267182CD1F44AA5A6FCF95C632CD7A6D47D1190095EAF0535FC7EAD1A10C1CC0727A4DA3A71B7E3B8C31C58ED173744D3004FE81BA5F85347BB59424893A211BE8564253583E6A525E839EAD5CDE6C9EAE7B5F7BBD80E909962E40D278318024DA0CD521D460B038A958F1AF5BD2234A52472663147E4D53B8E0A4108F66E8A77479F090859A00EF10ADBA9CEB10BBFD739C3F6166DF9119F636713106BBDA4C28D914C1A9BCE79EC0F67E66AD3CEA58712387F4BE17D1A0CFAD0CC8F7572EF1FD1C601F6928C77EE07BA17F86A99E788F76853B45DD0203010001A382011D30820119305006082B0601050507010104443042304006082B060105050730018634687474703A2F2F6F6373702E656865782E64653A323536302F656A6263612F7075626C69637765622F7374617475732F6F637370301D0603551D0E041604149E5A85CD1E1B533ADD06896CDB5D3E0D7C9C38E1300C0603551D130101FF04023000301F0603551D2304183016801400B56DD603C559705A994A0FDFC1BB78C025C99A30200603551D2004193017300906072A8214004C0446300A06082A8214004C048123300E0603551D0F0101FF0404030205A030130603551D25040C300A06082B06010505070302303006052B240803030427302530233021301F301D30100C0E56657273696368657274652F2D72300906072A8214004C0431300D06092A864886F70D01010B050003820101006B3243B0F98FF3BF8602CF5C3C02431766EDDE67D86FE2E02189D2B6547236F8B173651DB2E43DDC299A97F756343A98F5A55212C4A38371FC8FD84EB4DEEC07AE3972F59F314960EF92AE5971AA5D4DB1F3F2ABE497C3290612DE0F45A414128B1C7151BD5EDF5537C61E222767F55987082C033A7C90F8F38DAF880EA098F49B6BE7348EE5E396AF05E17EDC68960DA73A667C2FFC2D1F78BA6F04C833596AECD1869E2F7B6F8B315284EDC7DB756C98831DF8FA6751A30623BA66EA2B46BE04B49D3F560D24F1CC58A066FA547F657216C760461A103866261079FAEF6882066FF47C33D646E9F778B1902534D8272C1F90498B054D89B973E93274065FF6`

## What should happen:
The string should be converted to valid base64.

## What actually happens:
The output is just `AA==`

[Reported on Twitter](https://twitter.com/s1m0nw1/status/895183440584298497)

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
I see. It seems we can't do the intermediate step in the conversion when using [this site](http://www.asciitohex.com/). I will need to think about this.

**Comment by mintsoft** [comment]
I think this is broke anyway? If I convert "10" I get the same answer as "1010" and "101010"
"ff" "ffff" "ffffff" all return the same thing too
