### ISSUE TITLE
Timer: let commands with written out number ('five' instead of 5) also trigger timer

### ISSUE THREAD

**Issue by unknownmhack** [duckduckgo/zeroclickinfo-goodies#4422]
timer instant answer is not triggered if number written out, for example "timer for five minutes" will not trigger the timer instant answer. 

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.
