### ISSUE TITLE
PrimeFactors: Throws a warning when used 

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#4425]
```
Replacement list is longer than search list at lib/DDG/Goodie/PrimeFactors.pm line 37.
```

---

Instant Answer Page: https://duck.co/ia/view/prime_factors

**Comment by hgvanpariya** [comment]
@mintsoft : is this issue fixed ?

**Comment by kirkins** [comment]
@mintsoft to clarify is this a warning that appears with Perl 5.24 only? If not how do you get the warning?

I'm trying: `duckpan query PrimeFactors` and `duckpan test PrimeFactors`.

**Comment by mintsoft** [comment]
This is fixed in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4426#issuecomment-322136855
