### ISSUE TITLE
Conversions bug: Using "ångstrom" as unit does not work, even though "angstrom" does

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4437]
### Description
"Ångstrom" (capitalized or not) is not accepted as a unit, even though it is defined as an alias of "angstrom", which works.

## Steps to recreate
Search for "2000000000 Ångstroms in feet" or "2000000000 ångstrom in feet".

## People to notify
don't know

---

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by pjhampton** [comment]
This should be in edge-cases, but it's an easy fix. Thanks @jc86035 👍

**Comment by jc86035** [comment]
I actually made a pull request, #4438, in which I tried to fix it, but the actual problem was that I was missing the umlaut on the ö so it wasn't recognized.

**Comment by tsl143** [comment]
May be we can use https://www.npmjs.com/package/escape-diacritics to cover all edge cases.

**Comment by pjhampton** [comment]
@tsl143 good suggestion! But these are handled in the perl (backend) not the frontend 😞

**Comment by mintsoft** [comment]
easiest option is probably to whack this hash at the top of conversions and `tr //` through it:
https://gist.github.com/kogakure/34006#file-umlaute-pl-L29
