### ISSUE TITLE
RestructuredText Cheat Sheet: Missing "*" in Emphasis line

### ISSUE THREAD

**Issue by anoadragon453** [duckduckgo/zeroclickinfo-goodies#4454]
Hey there,

On the line that states `*emphasis`, it's missing an * at the end. Should instead be `*emphasis*`.

Thanks.

------
IA Page:  http://duck.co/ia/view/restructuredtext_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nickschafran

**Comment by mintsoft** [comment]
Thanks for the report @anoadragon453 If you're interested this is an easy fix! We'd love to have you contribute 👍  If not, that's fine also; someone from the community will pick this up

**Comment by anoadragon453** [comment]
@mintsoft Yeah, realized that just after I submitted it :P Should I bother with the link to the IA and all the other boilerplate in the PR or just a short description?

Thanks.
