### ISSUE TITLE
Password: avoid ambiguous characters AND generate pronounceable passwords

### ISSUE THREAD

**Issue by hhiru** [duckduckgo/zeroclickinfo-goodies#4456]
Is it possible to add parameters to enable these flags when generating a password with duckduckgo?
   The first should avoid ambiguous characters like O 0 - I l
   The second should make the password pronounceable avoiding numbers (ex: cERBidetrautiNE)

------
IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
