### ISSUE TITLE
Binary: Inconsistently handling hex vs strings

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#4461]
### Description
The query `0xfff000 hex in binary` converts the string `0xfff00 hex` from ASCII into binary. Whereas the query `fff000 hex in binary` converts the value `fff000` into binary (which is what I would expect from both queries)

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/binary

**Comment by pjhampton** [comment]
I'm wondering if it would be best to deprecate this IAs and move them into the TextConverter IA. RFC @moollaza

**Comment by moollaza** [comment]
> deprecate these IAs and move them into the TextConverter IA.

Sounds good to me 👍

**Comment by mintsoft** [comment]
@pjhampton @moollaza  Are we any closer to getting unit tests into the JS IA's? I've seen a lot of tweaks to  interactive IA's that I'd really like tests around
