### ISSUE TITLE
Conversions: Micrometer and micro symbol

### ISSUE THREAD

**Issue by daylightbrightledlight** [duckduckgo/zeroclickinfo-goodies#4470]
Unable to understand the following query: "13327μm to cm". Perhaps it does not understand the micro symbol. 

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mish24** [comment]
@mintsoft If this is not too urgent to resolve, can I do some research and work on this?

**Comment by mintsoft** [comment]
@mish24 I don't see why not, although @pjhampton  is the maintainer of conversions not myself. Nobody seems to have told daxtheduck though!\

**Comment by pjhampton** [comment]
Yeah, @daxtheduck went nonconformist a while back. 
I say go for it @mish24!

**Comment by pjhampton** [comment]
Hey @mish24 and @mintsoft 

I had to jump in here. It turned out to be a bit of a deeper rooted issue involving internal triggering. Sorry about that!
