### ISSUE TITLE
Music Chords Diagrams: Guitar fretboard is not tall enough / triggering issues

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4476]
### Description

The dot is not displaying within the fretboard diagram for some guitar chord searches. I am not sure if this is a bug.

<img width="100" alt="Screenshot showing two fretboard diagrams for A major guitar chords" src="https://user-images.githubusercontent.com/3948362/29972846-25c75c06-8f60-11e7-8b7c-b08c7ab11165.png">
<img width="100" alt="Screenshot showing two fretboard diagrams for G-flat minor guitar chords" src="https://user-images.githubusercontent.com/3948362/29972965-7f909f18-8f60-11e7-9e74-d4de3f1b012c.png">

Also, searching for "D-flat guitar chord" does not trigger the IA. The regex in probably [ChordDiagrams.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/ChordDiagrams.pm) should be changed but I'm not sure how. (In addition, "Gsharp" triggers but "Gflat" does not.) It is also difficult to find the IA without adding "guitar" to the query, so possibly guitar chords could be triggered without specifying "guitar".

## Steps to reproduce

- Search for "A major chord guitar" or "F sharp minor chord guitar". Fretboard is incorrectly rendered and needs extra line.
- Search for "D-flat guitar chord" or "Dflat guitar chord". No IA.
- Search for "Dsus4", "Dsus4 guitar", "Dsus4 ukulele" or "Dsus4 chord". No IA.

------
IA Page:  http://duck.co/ia/view/chord_diagrams 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @charles-I

**Comment by jc86035** [comment]
(This could probably be solved by increasing the height of all the SVGs and adding an extra fretboard line.)

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
