### ISSUE TITLE
Music Chords Diagrams: "D-flat" does not trigger

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/zeroclickinfo-goodies#4477]
### Description

Searching for "D-flat guitar chord" does not trigger the IA. The regex in probably [ChordDiagrams.pm](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/ChordDiagrams.pm) should be changed but I'm not sure how. (In addition, "Gsharp" triggers but "Gflat" does not.)

------
IA Page:  http://duck.co/ia/view/chord_diagrams 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @charles-I

**Comment by pjhampton** [comment]
Thanks @jc86035. 
For these low triggering IAs you would mind consolidating your issues and suggestions? Can you please edit the other issue you just opened with this content? https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4476

It just makes it easier for the developers to cut through the bugs faster if they can be squashed at once.
