### ISSUE TITLE
Color Codes: `rgb(217, 37, 50)` unexpectedly shows white

### ISSUE THREAD

**Issue by mcomella** [duckduckgo/zeroclickinfo-goodies#4479]
Querying for `rgb(217,37,50)` unexpectedly shows white, `#ffffff`.

For example: https://duckduckgo.com/?q=rgb(217%2C37%2C50)&ia=answer

Here's a screenshot:

<img width="1280" alt="screen shot 2017-09-06 at 15 35 08" src="https://user-images.githubusercontent.com/759372/30137620-03ff6138-9319-11e7-887d-fa46f6b4cb69.png">

------
IA Page:  http://duck.co/ia/view/color_codes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by mintsoft** [comment]
@mcomella do you know if this is new or whether it's done this for a while?

**Comment by mintsoft** [comment]
99% Sure this is me that broke this in : https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4453

**Comment by mintsoft** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4480 Will fix this
