### ISSUE TITLE
Facebook Cheat Sheet: Unclear what "Browser Keys" means

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-goodies#4485]
in the source page there is text that explains what the "Browser Keys" do but in the IA this is unclear.

there is no accompanying text in the IA but from the facebook help page it says:
"Find the right combination of keys for your browser in the list below, and replace # with the access key number listed under Access Keys below."   

------
IA Page:  http://duck.co/ia/view/facebook_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @saifakhan

**Comment by pjhampton** [comment]
Thanks @spagy. I will be reviewing all the cheat sheets soon 👍

**Comment by pjhampton** [comment]
Hey @spagy 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
