### ISSUE TITLE
Release Randagram 

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#449]
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Randagram.pm needs to get released

**Comment by javathunderman** [comment]
@jagtalon Isn't this up already?

**Comment by moollaza** [comment]
@javathunderman  doesn't look like it's live: https://duckduckgo.com/?q=randagram

**Comment by javathunderman** [comment]
@moollaza Is there anything specific that needs to be fixed?

**Comment by moollaza** [comment]
@javathunderman I'm not sure if anything needs to be fixed, but converting it to use the new structured answer format would certainly be an improvement to this IA (and all other simple IA's!)

**Comment by javathunderman** [comment]
@moollaza I think we should put this up as it is and then make it into that new format later.

**Comment by moollaza** [comment]
@javathunderman I'd rather we give them each a code/design review, get the up to date and converted to the new Structured Answer where possible and then once it's all done we can do a big release with all the IA's.

For now I've made a milestone, https://github.com/duckduckgo/zeroclickinfo-goodies/milestones/Review%20and%20Release%20Older%20Goodies with a due date of 1 month. Let's see how far we can get!

**Comment by javathunderman** [comment]
@moollaza Great! Watching all these issues.

**Comment by moollaza** [comment]
Setup for release...
