### ISSUE TITLE
Conversions: 'how many x are in y' doesn't trigger, bit 'how many x in y' does

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4501]
_Reported via User Feedback_

Example: https://duckduckgo.com/?q=how+many+tsp+are+in+1+tbsp

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by hektr** [comment]
Just regexp was writed such way. If you write "how many are x in y", it will work.
