### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by jojo313** [duckduckgo/zeroclickinfo-goodies#4507]
Default unit it converts to is weird. For example, it converts miles to centimeters. You'd expect to see km, which is like miles. Centimeters are like inches... fix?

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Thanks for this! DuckDuckHack is in maintenance mode and is currently only accepting urgent/security issues rather than suggestions. 

https://duckduckhack.com/
