### ISSUE TITLE
Timer: Should have an option for a full-screen timer

### ISSUE THREAD

**Issue by mcritz** [duckduckgo/zeroclickinfo-goodies#4512]
As someone who runs activities with a group I want to present a large timer on screen so that my activity participants know how long their activity will last.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
Thanks for the suggestion.

DuckDuckHack is currently in Maintenance Mode and only accepting issues for essential bug fixes.

This issue will be closed.
