### ISSUE TITLE
Timezone Converter: Doesn't work with "Pacific"

### ISSUE THREAD

**Issue by ddhelmet** [duckduckgo/zeroclickinfo-goodies#4514]
Tried 10 AM Pacific, nothing showed up.   

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
