### ISSUE TITLE
Timer: If it is web notification then it will be good

### ISSUE THREAD

**Issue by prasadram** [duckduckgo/zeroclickinfo-goodies#4519]
If i am not active on that tab then i don't get that timer so if it is notification then it will be good.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
Closing as this is non-essential. DuckDuckHack is currently in Maintenance mode and we are only accepting issues for essential bug fixes.
