### ISSUE TITLE
Conversions: Should not trigger on "gpa calculator"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#4520]
Produces conversion from an undefined unit, resulting in a blank dropdown   

https://duckduckgo.com/?q=gpa+calculator

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by urohit011** [comment]
@moollaza the unit "gpa" is there in [https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/triggers.yml](triggers.yml) line no. 964-969, but it is not used anywhere, you think it should be removed?

**Comment by urohit011** [comment]
I am working on this.

**Comment by moollaza** [comment]
@urohit011 the query "gpa calculator" refers to a college/university GPA score. We should ignore this query as showing the unit converter is likely unexpected.

**Comment by moollaza** [comment]
Take a look at the link results and you'll see

**Comment by urohit011** [comment]
Got it @moollaza, I think just removing 'gpa' from triggers should work
