### ISSUE TITLE
Periodic Table: More infos

### ISSUE THREAD

**Issue by Ryngetsu** [duckduckgo/zeroclickinfo-goodies#4527]
I don't know where to put ideas so here goes:

you can add more info like the electronic configuration, its isotopes and more. Thanks.   

------
IA Page:  http://duck.co/ia/view/periodic_table 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @zblair

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
