### ISSUE TITLE
Conversions: "1 GiB in Bytes" is wrong

### ISSUE THREAD

**Issue by fi78** [duckduckgo/zeroclickinfo-goodies#4528]
"[1 GiB in Bytes](https://duckduckgo.com/?q=1+GiB+in+Bytes&t=ffab&atb=v78-2__&ia=answer) = 1073742000", but when taking a look at the linked wikipedia article on the side you see it is 1073741824.

Looks like the conversion is wrong.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by jp8042** [comment]
Hi, I am new to open source world.
I would like to work on this issue.

**Comment by prattheev** [comment]
@moollaza @fi78 @pjhampton 
I'll make a PR right away!

![screenshot from 2017-12-26 22 13 45](https://user-images.githubusercontent.com/18045566/34360816-55f3ca1a-ea8a-11e7-9cab-41a5b6eb92ad.png)

**Comment by pjhampton** [comment]
Hi guys, 

We thought long and hard about this, hand many conversations / debates / fights about this. We decided to round these (like Google and bing). Every so often this gets dug up as an issue which we just ignore.

![screen shot 2017-12-26 at 4 55 58 pm](https://user-images.githubusercontent.com/8960296/34360970-dfc1c59e-ea5d-11e7-8092-19ec9f02ab26.png)

![screen shot 2017-12-26 at 4 57 56 pm](https://user-images.githubusercontent.com/8960296/34360987-041683b2-ea5e-11e7-81f4-86c0c4b0701c.png)

**Comment by pjhampton** [comment]
Hey @prattheev 

On a side note, welcome to DuckDuckHack! Unfortunately [DuckDuckHack.com is in maintenance mode](https://duckduckhack.com/) for the foreseeable future. Please discuss any changes to an IA with an employee or community leader before making a PR against the ZeroClickInfo repos as it might be rejected.

**Comment by prattheev** [comment]
@pjhampton Yeah Sure! :+1:
