### ISSUE TITLE
Release POTUS

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#453]
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/POTUS.pm is not enabled.

**Comment by javathunderman** [comment]
@jagtalon Is this done? I saw this commit: https://github.com/duckduckgo/zeroclickinfo-goodies/commit/981538c7c1aed2d547357a5510141cd0c9820a81

**Comment by mintsoft** [comment]
@javathunderman doesn't look like it: https://duckduckgo.com/?q=potus

**Comment by javathunderman** [comment]
@mintsoft @moollaza Should this just be a Hello World style goodie? I don't it's that much of a problem to change it every 4-8 years.

**Comment by moollaza** [comment]
Code LGTM :+1: 

Needs design team sign off

**Comment by javathunderman** [comment]
@moollaza Brilliant.

**Comment by moollaza** [comment]
Setup for release...
