### ISSUE TITLE
Conversions: Rounding error with gallon to quart conversion

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4530]
**Query:**
https://duckduckgo.com/?q=how+many+quarts+in+a+gallon&ia=answer

**Expected answer:**
4 (both US & Imperial)

**Actual answer:**
3.999987 (US); 4.000009 (Imperial)

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by tagawa** [comment]
![dn_o9vlvoaae0gv](https://user-images.githubusercontent.com/94173/32475798-feb241cc-c3b6-11e7-86f6-479d393ed9fc.jpg)

**Comment by prattheev** [comment]
@pjhampton Is this still open?

**Comment by EpicWolverine** [comment]
There's a bunch of weird rounding errors for US to US volume conversions that should be exact:
- 1 cup = 8.115391 fl oz (expected: 8)
- 1 gal = 15.7725 cup (expected: 16)
- 1 qt = 3.943138 cup (expected: 4)
- 1 tbsp = 3.000008 tsp (expected: 3)
- 1 fl oz = 1.999989 tbsp (expected: 2)

Also, copying the last two caused the left size to change to just below 1 (0.99999999).
