### ISSUE TITLE
Calculator: Uppercase 'X' does not enable calculator.

### ISSUE THREAD

**Issue by raincrash** [duckduckgo/zeroclickinfo-goodies#4532]
https://duckduckgo.com/?q=2+X+3 -- searches for products and https://duckduckgo.com/?q=2+x+3 enables calculator.
 
PS: I would like to work on it as a first-bug if someone can mentor.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for pointing this out. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
