### ISSUE TITLE
Foundation 6 Cheat Sheet: 

### ISSUE THREAD

**Issue by DanielRuf** [duckduckgo/zeroclickinfo-goodies#4533]
It seems the cheat sheet is not complete and there is not much information or did I miss something?

------
IA Page:  http://duck.co/ia/view/foundation_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by vikashvverma** [comment]
@DanielRuf It seems so. 
@duckduckgo/duckduckhack-contributors 

Anyone would like to take this up and add more information?

**Comment by abbyck** [comment]
@vikashvverma , I would like to add that .

**Comment by vikashvverma** [comment]
@abbyck Thanks for taking this up 👍

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

**Comment by DanielRuf** [comment]
Ok. Besides of this the v5 cheatsheet is great. Just had big hopes to find something similar for v6.
