### ISSUE TITLE
Calendar: Convert to JS from Perl

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-goodies#4535]
When searching for the [current month's calendar](https://duckduckgo.com/?q=November+calendar&ia=answer), I get a current date one day ahead of my current local time (Eastern Standard Time). For example, today is Monday, November 20th 2017. When I do the above search, I get a calendar marking November 21st, which looks like this:

![novembercalendar-off](https://user-images.githubusercontent.com/306013/33050392-bd543f56-ce32-11e7-90bb-aa0369e37efc.png)

I'm not sure how to troubleshoot this, but I imagine it assumes my time zone is set for one ahead of mine, which pushes it into tomorrow.

Thanks!

------
IA Page:  http://duck.co/ia/view/calendar_today 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by mintsoft** [comment]
@ndegruchy If I remember correctly this is based on the server time which in most situations should be close enough to your timezone. Is it chosing the correct time if you query at the start of the day vs the end of the day?

**Comment by moollaza** [comment]
@mintsoft I don't see any reason to keep with Perl for the date calc here. We can more reliably grab the date via JS. I think this IA should be ported to JS to ensure it's accurate.

**Comment by mintsoft** [comment]
@moollaza sounds perfectly reasonable to me
