### ISSUE TITLE
AWS Lambda Cheat Sheet: 

### ISSUE THREAD

**Issue by rohim41** [duckduckgo/zeroclickinfo-goodies#4536]
{8ball}

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by rohim41** [comment]
#4536
what am i suppose to do?!

**Comment by mintsoft** [comment]
Hi @rohim41 if there's an issue, can you fill out the template with information about what the issue is?

**Comment by nikornnanta** [comment]
on issue
