### ISSUE TITLE
Base Conversion: Binary numbers (starting with 0) should not be converted to binary

### ISSUE THREAD

**Issue by darijan2002** [duckduckgo/zeroclickinfo-goodies#4539]
When I type for example 1010010010 instead of giving a number in base 10, it returns the same number claiming that it converted from base 10 to base 10.

------
IA Page:  http://duck.co/ia/view/base 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moritz

**Comment by mintsoft** [comment]
@darijan2002 I can't reproduce this, can you attach a screenshot?

**Comment by darijan2002** [comment]
Nevermind, found a workaround by writing the binary number and then the
word "binary". To recreate the bug, type a binary number and after that
type "in binary"

На 26.11.2017 23:48, "Rob Emery" <notifications@github.com> напиша:

**Comment by moollaza** [comment]
> type a binary number and after that type "in binary"

@darijan2002 if the number doesn't start with a 0, I would expect that behaviour, because we're assuming you're providing a decimal number.

However even a query like '01110 in binary' still triggers which I feel is a bug.

**Comment by sibasish14** [comment]
@darijan2002 Hi, I'm new to open source. Can I work on this issue?

Doubts - 
(1) I need to add a condition that checks if the entered number starts with a zero. If **yes**, no output must be shown.If **no**, proceed as usual. Am I correct?
(2) In which file do I need to make changes? `zeroclickinfo-goodies/lib/DDG/Goodie/Base.pm` ??

I would love to give this a try :)

**Comment by darijan2002** [comment]
Actually, I discovered this bug, but
(1) If it starts with a 0, then it's a binary number and there should be an
output in decimal and if it doesn't then it's ok
(2) idk

**Comment by darijan2002** [comment]
there is no bug when you type "*insert binary number here* binary" but the bug occurs when you type "*binary* in decimal" or "*binary* to decimal"

**Comment by sibasish14** [comment]
@moollaza do I have to make changes in `zeroclickinfo-goodies/lib/DDG/Goodie/Base.pm` file (add a condition that checks for a leading zero) ?

**Comment by yolstatrisch** [comment]
Shouldn't radix conversion just be a part of the general conversions IA? It would allow the users to manually specify the radix of the input and the output radix via a dropdown menu.

![radix](https://user-images.githubusercontent.com/29237295/43036570-cfe13d18-8d36-11e8-9dea-42721e205b33.png)
