### ISSUE TITLE
Calculator: Breaks on percentages with 4+ decimal places

### ISSUE THREAD

**Issue by philipmiesbauer** [duckduckgo/zeroclickinfo-goodies#4541]
The calulator can not handle percentages with more than 2 decimal places. example https://duckduckgo.com/?q=304*3.100%25&t=ffab&ia=calculator

This should turn into 304*0.031, but turns into (304*3.)1.

compare with answer on only 2 decimal places
https://duckduckgo.com/?q=304*3.10%25&t=ffab&ia=calculator

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by prattheev** [comment]
@pjhampton Hey! I think I found the fix. It is the normalizeExpression that has a decimal limit of `\d{1,2}`.
The fix is to replace it with `\d{1,}`.
Do you want me to take this?

**Comment by pjhampton** [comment]
Yeah, sounds good @prattheev 👍
