### ISSUE TITLE
Color Codes: support alpha channel notation

### ISSUE THREAD

**Issue by aslakr** [duckduckgo/zeroclickinfo-goodies#4542]
Support alpha channel notation as described in <https://www.w3.org/TR/css-color-4/#hex-notation>, ie. `#0000ffcc` for 8 digits and `#00fc` for 4.

------
IA Page:  http://duck.co/ia/view/color_codes 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
