### ISSUE TITLE
Timer: dynamically update tab title with the remaining time.

### ISSUE THREAD

**Issue by oquirozm** [duckduckgo/zeroclickinfo-goodies#4544]
Actually, I don't know if this is doable. I noticed that Google doesn't do it either.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
