### ISSUE TITLE
Timer: bookmarking a specific time

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [duckduckgo/zeroclickinfo-goodies#4545]
Everyday I set the timer to 1:30 for my coffee..so I though of bookmarking the correct get request for getting that timer.. fact is it is always at 1:00 minuts instead of 1:30

just telling about this.. not a bug.. tough it would be a nice feature ....

thanks for the amazing app
Fabrizio 

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
@fabriziobertoglio1987 this should work:

https://duckduckgo.com/?q=timer+1+minute+30+seconds&ia=answer
