### ISSUE TITLE
Factors: Add trigger "factorize"

### ISSUE THREAD

**Issue by kaushiksk** [duckduckgo/zeroclickinfo-goodies#4546]
I believe "Factorize 72" would be a much more natural query that users would frequently pose. 

------
IA Page:  http://duck.co/ia/view/factors 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @austinheimark

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
