### ISSUE TITLE
JSON Validator: Add shortcut key Ctrl+Enter to perform click on "Validate JSON" button

### ISSUE THREAD

**Issue by erlangp** [duckduckgo/zeroclickinfo-goodies#4548]
May i request a feature? Please add shortcut key Ctrl+Enter to perform click on "Validate JSON" button
Thanks  :D

------
IA Page:  http://duck.co/ia/view/json_validator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
