### ISSUE TITLE
Org Mode Cheat Sheet: Typo in word 'through'

### ISSUE THREAD

**Issue by ingorichter** [duckduckgo/zeroclickinfo-goodies#4549]
https://duckduckgo.com/?q=org+mode+cheat+sheet&ia=cheatsheet

Under 'Agenda Views' heading.

----
IA Page: https://duck.co/ia/view/org_mode_cheat_sheet
Maintainer: @erickgnavar

**Comment by moollaza** [comment]
@ingorichter where did you see a typo?

Please provide a url or a screenshot.

Closing until this is clarified.

**Comment by ingorichter** [comment]
There is a typo in the word **through**
![screenshot 2017-12-12 13 16 27](https://user-images.githubusercontent.com/86214/33909040-1ab869f2-df3f-11e7-9168-86c95667129f.png)

**Comment by moollaza** [comment]
@ingorichter Thanks for the screenshot. Now I understand the issue.
