### ISSUE TITLE
Conversions: JS error

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#4551]
https://duckduckgo.com/?q=1%2F3+cups+in+deciliters

![screen shot 2017-12-13 at 6 22 56 pm](https://user-images.githubusercontent.com/126358/33967724-b09195fe-e032-11e7-9588-4d45341a27f3.png)

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by prattheev** [comment]
@bsstoner There was a misspelling in the conversions.js
Check the PR with the fix.

**Comment by prattheev** [comment]
@bsstoner @pjhampton The misspelling caused the conversion to decilitre not work anywhere. :relieved:
