### ISSUE TITLE
https://www.gametwist.com/de/games/slots/URL Decode: 

### ISSUE THREAD

**Issue by Slawek37** [duckduckgo/zeroclickinfo-goodies#4555]
------
IA Page:  http://duck.co/ia/view/urldecode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Hi @Slawek37 if there's an issue with this IA can you provide the query you used and expected result?

Thanks
