### ISSUE TITLE
URL Decode: 

### ISSUE THREAD

**Issue by Slawek37** [duckduckgo/zeroclickinfo-goodies#4559]
------
IA Page:  http://duck.co/ia/view/urldecode 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by mintsoft** [comment]
Hiya @Slawek37 is there a particular problem with the urldecode IA? If so can you give an example of the input, the result you got and what you expected?

Thanks
Rob
