### ISSUE TITLE
Ajax Cheat Sheet: we can include a function to return the xmlhttprequestobject

### ISSUE THREAD

**Issue by viveksinghggits** [duckduckgo/zeroclickinfo-goodies#4564]
Will it be a good idea to include a cross platform function that will return the xmlhttprequest object?

------
IA Page:  http://duck.co/ia/view/ajax_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
