### ISSUE TITLE
Conversions: converting from bytes using 'B' uses wrong units

### ISSUE THREAD

**Issue by joedight0** [duckduckgo/zeroclickinfo-goodies#4565]
**Description:**
When converting from bits using 'B' instead of 'Bits' in the query, the conversion doesn't work. It instead uses the correct initial _number_, but the wrong _units_, always converting from Bits to Bytes.
i.e. 1000B in KiB results in 1000 bits = 125 bytes.
The reverse conversion, or writing byes longhand works.
**Examples:**
https://duckduckgo.com/?q=1000+B+to+kilobytes&ia=answer
https://duckduckgo.com/?q=+B+to+Mib&ia=answer
https://duckduckgo.com/?q=GB+to+100+B&ia=answer

Thanks.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
