### ISSUE TITLE
Text Converter:  Incorrect results for decimal to binary

### ISSUE THREAD

**Issue by tparker24** [duckduckgo/zeroclickinfo-goodies#4566]
I entered 1056760 and it gave me 1111111111000.  That is INCORRECT!  

The correct result is 100000001111111111000.

Using the incorrect result caused me some headaches, until I finally figured it out. 

I think this is an extremely serious error that could impact others as well.

I suggest you remove the bogus converter until it is repaired.   

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for reporting.

@pjhampton looks like an issues with larger numbers?

**Comment by Tzesar** [comment]
This does work for me.

I entered _1056760 to binary_ and the result was the expected _000100000001111111111000_

**Comment by pjhampton** [comment]
Yeah, I think it might be a good idea to bring this IA down until I can find the time to deal with it.

**Comment by tparker24** [comment]
Not for me.  See attached.

Augusto Amarilla wrote on 1/19/2018 3:31 PM:

**Comment by moollaza** [comment]
> This does work for me.
> 
> I entered 1056760 to binary and the result was the expected 000100000001111111111000

@Tzesar that's actually a different Instant Answer. We have one that triggers on queries that specify the input and the input/output format, and another that handles generic queries, which provides a UI for choosing specifying the input string, as well as the input/output format.

Demo: https://duckduckgo.com/?q=binary+to+ascii+converter&t=ffab&atb=v91-1_j&ia=textconverter

**Comment by moollaza** [comment]
I'll take this IA offline for now
