### ISSUE TITLE
SASS To CSS: Converts SCSS, not Sass

### ISSUE THREAD

**Issue by probablykasper** [duckduckgo/zeroclickinfo-goodies#4568]
Inputting the following successfully converts it to CSS:
```
header {
    height: 50px;
    a {
        color: #FFFFFF;
    }
}
```

Inputting that in Sass format throws the following error:
```
Error: Invalid CSS after "h": expected 1 selector or at-rule, was "header"
        on line 1 of stdin
>> header
   ^
```

------
IA Page:  http://duck.co/ia/view/sass_to_css 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @akanshgulati

**Comment by moollaza** [comment]
We should add an input/radio to specify if the input is SCSS or SASS and update the code accordingly. We could probably also use some heuristics to determine the input format based on the presence of `{` and `}`?

We should also add triggers for 'scss' so queries like 'scss to css converter' triggers.
