### ISSUE TITLE
Timezone Converter: 24 hours format support?

### ISSUE THREAD

**Issue by sirex** [duckduckgo/zeroclickinfo-goodies#4569]
Is it possible to convert hours to 24 hours format?   

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by mintsoft** [comment]
@sirex If I understand your question correctly, the answer is currently no; the output is in the same format as the original question: 

https://duckduckgo.com/?q=8+PM+GMT+in+CST&t=ffab&ia=answer
https://duckduckgo.com/?q=20%3A00+GMT+in+CST&t=ffab&ia=answer

Do you want to ask `8PM in GMT  in CST` and get it back in 24 hour fomat?
