### ISSUE TITLE
Text Converter: incorrect conversion binary to decimal

### ISSUE THREAD

**Issue by albertbn** [duckduckgo/zeroclickinfo-goodies#4570]
OK (dec to bin):
 -2       ---->       1111111111111110 

UNEXPECTED (bin to dec):

1111111111111110      --->         255 254

------
IA Page:  http://duck.co/ia/view/text_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by lolo101** [comment]
Looks like the decode splits the input strings in 8 bits packets then decodes them separately.
See also #4513
