### ISSUE TITLE
The calculator is incorrect, please stop immediately closing the submission, lol?

### ISSUE THREAD

**Issue by Mindraker1** [duckduckgo/zeroclickinfo-goodies#4575]
When I make the following addition: 104369.70 + 104.37, I get the following result: 104474.06999999999, which is incorrect.

### Description

When I perform the following addition:

104369.70 + 104.37

It gives me the following solution:

104474.06999999999

Which is incorrect.

## Steps to recreate

Use the duckduckgo calculator and perform the same addition.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by kennyballou** [comment]
[IEEE-754][0] makes this a really hard issue to solve. Rounding isn't a good solution as it may give accumulatively worse results. Short of implementing some recent CS research on floating point calculations, this will likely not be easily solved.

[0]: https://en.wikipedia.org/wiki/IEEE_754

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
