### ISSUE TITLE
Timezone Converter: doesn't put the converted time to understand it easily

### ISSUE THREAD

**Issue by adocampo** [duckduckgo/zeroclickinfo-goodies#4576]
Please, put the result in 24h format or at least express it with the am/pm for undertanding it at first glance, without doing the maths.
Right now when you search for example: 10CT to CEST the actual result is

> 4:00 CEST
> Convert Timezone: 10:00 CT (UTC+8) to CEST (UTC+2)

4 what? As on CEST we understand hours in 24h format, what we understand first is 4am, but doing the calculations (which makes the converter useless) one can see this is 4pm CEST.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by mintsoft** [comment]
@adocampo I believe that's defaulting to AM/PM; the IA keeps the input format however so if you ask a question in 24H time, you get an answer in 24H time. For example: https://duckduckgo.com/?q=10%3A00+CT+to+EST&atb=v100-7_g&ia=answer

**Comment by adocampo** [comment]
I still don't get it. Why then I this search doesn't appeared 16h CEST? How
can the AI know how the source is am or pm and the put the right result?
https://duckduckgo.com/?q=10%3A00+CT+to+CEST&atb=v100-7_g&ia=answer

**Comment by mintsoft** [comment]
@adocampo That is 04:00 (i.e. 4 hours past midnight); I don't know why it's missing the leading zero but it is. 

To clarify you're asking to convert 10 AM CT into CEST there?
CT is UTC+8 and CEST is UTC+2; 
so 10:00 (24 hour time) in CT is 04:00 (24 hour time) in CEST

I think you probably wanted to search for 22:00 CT into CEST which shows: 16:00 ?
https://duckduckgo.com/?q=22%3A00+CT+to+CEST&atb=v100-7_g&ia=answer

**Comment by adocampo** [comment]
@mintsoft sorry but no, 10am CT is 4pm CEST (or 5pm CET)
https://www.worldtimebuddy.com/cst-to-cest-converter?qm=1&lid=6,12,524901&h=6&date=2018-1-27&sln=10-11

From my point of view when in Spain are 16h, on CT frame there are 6h less ((UTC+8)-(UCT+2)), that's 10am. Here, we enter on a new day before america, so I need to substract the TZ to get the CT time (or on CT time need to add 6h to get the CEST time)

**Comment by mintsoft** [comment]
@adocampo I think I see where the confusion is coming from; CT is (for some reason) defined as UTC+8 in the IA; I'll look into where that's come from in a minute.

However I think what you actually want is one of these:

With daylight savings in america:
https://duckduckgo.com/?q=10%3A00+CDT+in+CET&t=ffab&ia=answer

Without Daylight savings in america:
https://duckduckgo.com/?q=10%3A00+CST+in+CET&t=ffab&ia=answer

Or possibly with summer in Europe:
https://duckduckgo.com/?q=10%3A00+CDT+in+CEST&t=ffab&ia=answer
https://duckduckgo.com/?q=10%3A00+CST+in+CEST&t=ffab&ia=answer

Are those the right answers? (Ignoring that CT seems to be something totally wrong)

**Comment by mintsoft** [comment]
Quick follow up: it looks like the reason that CT is not Central Time (CST/CDT seems to be that); it's being used as China Time (based on: https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)

**Comment by adocampo** [comment]
Wow, that's explains the issue, ddg was guessing (correctly, as for the wikipedia's link) I was asking for the conversion with China, not America.

I wonder how can it differentiate Cuba Time, China Time or Central Time when the three of them uses the same abbreviation. Perhaps it should do like google does, put something like

> 10:00 PM Saturday, Central Time (CT) is
> 6:00 AM Sunday, Central European Summer Time (CEST)

To avoid these mistakes.

**Comment by mintsoft** [comment]
Yeah, that would definitely make it clearer. We're currently in maintenance mode for DDH so we're not tackling anything but critical issues; however that's definitely an improvement for the future.

**Comment by moollaza** [comment]
@adocampo @mintsoft I think we could possibly `CT` to be interpreted as `CDT` for the sake of ensuring we don't confuse others. Even google assumes CDT when CT is entered.

**Comment by moollaza** [comment]
@adocampo @mintsoft I went ahead and fixed this. It had bothered me for a while and this ensures that no other users will get confusing/unexpected results.  Although correct, the output here was very misleading and I felt it was worth fixing.

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/4579
