### ISSUE TITLE
Timezone Converter: bug when putting am/pm when searching

### ISSUE THREAD

**Issue by adocampo** [duckduckgo/zeroclickinfo-goodies#4577]
If you search 10am CT to CEST, the result is 
4:00 AM CEST
Convert Timezone: 10:00 AM CT (UTC+8) to CEST (UTC+2)  

And it should be 4:00 PM CEST. I tried several and whatever you put AM/PM, the results shows the same, so no calculations is done.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr,

**Comment by moollaza** [comment]
@adocampo thanks for reporting!
