### ISSUE TITLE
Calculator: incorrect percentage calculation

### ISSUE THREAD

**Issue by samsk** [duckduckgo/zeroclickinfo-goodies#4581]
Multiple subtractions with using percents returns wrong results:
DDG: (10000 - 20%) - 7% = 7,999.93
GOOGLE: (10000 - 20%) - 7% = 7440

Calulcator has rewritten the formula to a bit complicated form:
 (-(((10000 * 20) / 100) - 10000)) - 0.07

It correctly subtracts first 20%, but then instead of subtracting another 7% it subtracts only 0.07.
For some input values the result might seem valid, so maybe this functionality should be temporarily disabled until fixed. Thanks.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
