### ISSUE TITLE
The SERP vanishes when I press the back button to return back

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-goodies#4585]
**I don't know whether this is the right repository for this issue, but I don't know where to open the general issue related to search results**

**Issue:**
The Serp vanishes as soon as I return back. This doesn't happen a lot but sometimes it happens.

**Screenshot**
For ex: searching the following returns the results

![duckduckgo com__q online image editor atb v103-3_g ia web 1](https://user-images.githubusercontent.com/25108385/36420209-4bd4478e-165a-11e8-9c42-07344bd40d10.png)

but when I visit the link and press the back button on my browser to come back to SERP page, it returns this:

![duckduckgo com__q online image editor atb v103-3_g ia web](https://user-images.githubusercontent.com/25108385/36420292-8d9040b0-165a-11e8-9568-e86aa77c8b8f.png)

I hope this isn't something a major problem

**Comment by moollaza** [comment]
I'm unable to reproduce.
