### ISSUE TITLE
GUID:  duck duck go "random guid" search returned invalid guid

### ISSUE THREAD

**Issue by mokonaDesu** [duckduckgo/zeroclickinfo-goodies#4587]
It returned this once which is an invalid guid: "b1c348feb-9dba-4e55-af11-b0cafa5f0ba2"

------
IA Page:  http://duck.co/ia/view/guid 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @loganom

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
