### ISSUE TITLE
2048 (Game): [Non Critical] Scoring of multiple new tiles does not match the original

### ISSUE THREAD

**Issue by Aarowaim** [duckduckgo/zeroclickinfo-goodies#4588]
In the original game of 2048, scoring is done by all changed tiles, however this implementation scores only one changed tile. This creates a situation where scores produced by the [original game](https://gabrielecirulli.github.io/2048/) grow faster and end with higher scores.

Consider this example:

    2 2 4 4
    0 0 0 0
    0 0 0 0
    0 0 0 0

When a right collapse is performed, this is the result:

    0 0 4 8
    0 0 0 0
    0 0 0 0
    0 0 0 0

This implementation produces a score of 8, while the original produces a score of 12 (`= 4 + 8`). Testing further, it does not seem to be the highest changed tile and is somewhat unpredictable.

------
IA Page:  http://duck.co/ia/view/game2048

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
