### ISSUE TITLE
Calculator: Triggers even when it can't process the input

### ISSUE THREAD

**Issue by spagy** [duckduckgo/zeroclickinfo-goodies#4590]
When I search: 2*/(3*10^8)
the calculator appears but is completely blank. It seems to me that the calculator should not appear since the calculator cannot evaluate this expression.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestion. I think we opted to do that so the user understands something is wrong with the calculation syntax.

Regardless, DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
