### ISSUE TITLE
Calculator: Doesn't show humanly phrased percentages

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4593]
Query: [20% of 1820](https://duckduckgo.com/?q=20%25+of+1820)
Result: No IA shown.

Query: [20% * 1820](https://duckduckgo.com/?q=20%25+*+1820)
Result: Calculator IA shown.

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
