### ISSUE TITLE
calculator: how about to use existing backends?

### ISSUE THREAD

**Issue by nick87720z** [duckduckgo/zeroclickinfo-goodies#4595]
I just tried calculator - great, that duck have it too :) though i don't use online systems, but...
How about to use existing backends?
I'm not about matlab-style shells, requiring programming skills. Actually there is one great project, including both engine (lib) and calculator-styled gui - qalculator.
- It supports arbitrary precision, due to gmp/mpfr usage,
- It allowes to do timed-out calculations, as well as to abort too long calculation, e.g. by button or other signal,
- can solve some equations and simplify/factorize symbolic expressions (or factorize numbers)
- support various calculation modes, like always_exact, try_exact, approximate, and interval arithmetics;

Current usage: for now i'm aware of following applications with its support:
- NaSC (do math like normal person - dedicated for elementary os);
- Cantor - KDE single interface for various math systems, also including Octave, Maxima, R;
- KDE plasma applet, even simpler, then NaSC;
Probably more, but these are all, i'm aware about.
Imho, it is better join to development of existing FLOSS project, for less forces spread.

I looked a bit to sources - looks like calc itself is perl app. Qalculate is written in c++ too different from perl, which probably has enough rich functionality. I'm not perl programmer (for while), i can't insist, but at least proposing to look at it.

**Comment by moollaza** [comment]
Thanks for the questions/suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
