### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by jackalek** [duckduckgo/zeroclickinfo-goodies#4598]
When I try to convert 5 foot 8 inches into cm it understands it as 5.66666666 foot.
https://duckduckgo.com/?q=5%278+in+cm&t=ffab&ia=answer
it will put 5.666666666666 in feet field.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@jackalek this is correct. 8 inches is .666...7 of one foot (8/12)

Google handles this the same way: https://encrypted.google.com/search?hl=en&q=5%278%22%20to%20cm
