### ISSUE TITLE
Public DNS: Blockaid Public

### ISSUE THREAD

**Issue by greg-raven** [duckduckgo/zeroclickinfo-goodies#4603]
Ping fails for IP 205.204.88.60   

------
IA Page:  http://duck.co/ia/view/public_dns 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mailkov

**Comment by daedaesplayground1991** [comment]
What exactly can I use this to do in application form.

**Comment by moollaza** [comment]
@greg-raven interested in opening a PR to remove it?

**Comment by greg-raven** [comment]
@moollaza Sorry, I have no idea what this means.
