### ISSUE TITLE
Conversions: Digital storage shows 1000x, not 1024x

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4610]
**Queries:**
[1 gb to mb](https://duckduckgo.com/?q=1+gb+to+mb&ia=answer)
[1 mb to kb](https://duckduckgo.com/?q=1+mb+to+kb&ia=answer)

**Problem:**
Answer should show 1,024kb in 1mb and 1,024mb in 1gb, not 1,000.

[Reported on Twitter](https://twitter.com/ToAlephNull/status/983495958322339841).

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by al3phnul** [comment]
Awesome.  Thanks folks! I just switch all my default engines on all my browsers to DDG from Google.  I want to see you guys succeed.  Love what you’re doing!

I was just working on a MS Exchange issue at work and needed to convert 1.899GB into exact KB, and no dice :) It’s the little things I guess

**Comment by brindy** [comment]
I think the user is confusing GB (Gigabyte) with GiB (Gibibyte), see https://en.wikipedia.org/wiki/Gigabyte

1GB = 1000MB
1GiB = 1024MiB

**Comment by al3phnul** [comment]
Oh, see now you’re going to give me a complex.  You seem to be correct.  My mind is blown.  I mean, I manage nundreds of VM’s for a living. The simple fact that theres 1024MB in a GB and 1024GB in a TB has never been a question until just this minute ... My life has been a lie!

Hahaha all dramatics aside.  Although this seems to be correct, then maybe add a DIMM Storage calculator that multiplied by 1024?  Because the vast majority of the IT sector seems to be operating on the false assumption that it’s 1024

**Comment by al3phnul** [comment]
Okay.  So I feel better knowing I’m not insane.  There is controversy over this.  There’s a difference between Decimal and Binary measurements of bytes.  

So ... what to do moving forward?

https://www.quora.com/How-many-MBs-are-in-a-GB

https://www.gbmb.org/mb-to-gb

https://kb.iu.edu/d/ackw

**Comment by al3phnul** [comment]
I agree.  The fact is, calculators should be precise and should not run on misconceptions or assumptions of what people might “actually mean”.  1 GB is technically 1000MB, regardless of the fact that everyone I’ve ever met (including my MCSE instructor) has said 1024.  

I think your idea is fantastic.  The user gives 1 input (say, “1GB”), and receives 2 outputs displaying Decimal and Binary representations of the answer.  Having a good link to reference why there are two outputs would be super helpful.

**Comment by al3phnul** [comment]
Heck, maybe people (like me) would learn something new by using your calculator :) 

All I was looking to do was multiply 1.899 by 1024 twice.  I ended up getting an interesting lesson in storage size measurements!

**Comment by moollaza** [comment]
@al3phnul thanks for bringing this up! As you can see, technically the calculator is correct. We do also handle conversions for Mib and Gib to get the results you're looking for.

Regarding you suggestions, DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports. 

This issue doesn't really rise to that level so it will be marked as tolerated and closed.
