### ISSUE TITLE
Conversions: Button to invert currently selected Units

### ISSUE THREAD

**Issue by troubas** [duckduckgo/zeroclickinfo-goodies#4612]
I imagine something similar to google translate where one can easily swap the currently selected languages.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
