### ISSUE TITLE
Music Chords Diagrams: D7 shows wrong chords

### ISSUE THREAD

**Issue by bark10** [duckduckgo/zeroclickinfo-goodies#4621]
I love this add-on and I use it all the time. Thanks for creating it!

It appears that a search for D7 produces the wrong output:
![bilde](https://user-images.githubusercontent.com/16222532/42414072-e36cee90-822d-11e8-9825-d8ae4d01c058.png)
when it should be showing something more like this:
https://www.8notes.com/guitar_chord_chart/d7.asp

------
IA Page:  http://duck.co/ia/view/chord_diagrams 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @charles-I

**Comment by Filius-Patris** [comment]
Happendet to me with the G7 chord. It showed me a Gmaj7
