### ISSUE TITLE
The Pi'th root of Pi will break the calculator

### ISSUE THREAD

**Issue by Vyz333** [duckduckgo/zeroclickinfo-goodies#4623]
### Description

After attempting to compute the Pi'th root of Pi, the calculator will display "Error" and Pi will stop working afterwards, any further inputs won't do anything

## Steps to recreate

0. Open the DuckDuckGo Calculator
1. Click Pi
2. Click the "nth root" operator
3. Click Pi again

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/calculator

**Comment by mintsoft** [comment]
I can confirm this, however I think it's any operation involving *any* root of pi
