### ISSUE TITLE
{Jira} Bug: Codehaus Jira is gone

### ISSUE THREAD

**Issue by TobiX** [duckduckgo/zeroclickinfo-goodies#4627]
### Description

Since Codehaus has close a while ago, https://jira.codehaus.org/browse/ is a dead URL nowadays, therefore the Jira helper creates broken links.

See https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/jira/projects.yml#L431

## Steps to recreate

https://duckduckgo.com/?q=PLXUTILS-154&ia=answer

I think some project moved their issues to other Jira instances, while for others a link to the Internet Archive is probably the best solution.

---

Instant Answer Page: https://duck.co/ia/view/jira

**Comment by moollaza** [comment]
@TobiX Thanks for reporting. DuckDuckHack is in maintenance mode and seeing as this Instant Answer is broken, I've taken it offline.
