### ISSUE TITLE
Conversions: CONVERT 223791630KB TO GB Incorrect

### ISSUE THREAD

**Issue by ClarkJeff** [duckduckgo/zeroclickinfo-goodies#4628]
CONVERT 223791630 KB TO GB
shows 2.23792*10^8 Kilobyte = 223.792 Gigabyte

That's not correct as it appears to be using / 1000 / 1000, but should be / 1024 / 1024 to return ~213 G.

![image](https://user-images.githubusercontent.com/1873970/43321071-c2f6a58e-9178-11e8-9d4c-b94a90cc5378.png)

Thanks.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
@ClarkJeff the IA uses the SI prefixes for Giga/Kilo (i.e. 1000 based), the Binary prefixes are available as Gibibyte, Kibibyte (GiB, KiB) etc

**Comment by Krogsager** [comment]
> ![image](https://user-images.githubusercontent.com/1873970/43321071-c2f6a58e-9178-11e8-9d4c-b94a90cc5378.png)
> 

Seeing as the type of the search/conversion is "digital storage" concerning bytes, and not weight/lenght/etc., I would argue that the IA is wrong in using SI prefixes.

**Comment by mintsoft** [comment]
@Krogsager Kilo is defined as 1000, KiB is defined as 1024 (see https://en.wikipedia.org/wiki/Binary_prefix) The reality is that different applications and operating systems output KB ambiguously, therefore we've decided to stick to strict SI where KB is Kilobytes and KiB is Kibibytes
