### ISSUE TITLE
Conversions: 1 rod erroneously converts to "nearly" 16.5 feet

### ISSUE THREAD

**Issue by drj11** [duckduckgo/zeroclickinfo-goodies#4630]
If I type `convert 1 rod to feet` I get: «1 rod = 16.50003 feet ».

In fact a rod is defined to be exactly 5.5 yards, so that's exactly 16.5 feet.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
Confirmed
