### ISSUE TITLE
Conversions: 32F translated to 0.0000000000000000000...C

### ISSUE THREAD

**Issue by wmclt** [duckduckgo/zeroclickinfo-goodies#4631]
I don't know if that's a problem, but it seems like one.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
Yeah that should be truncated, 32F is exactly 0C by definition; whether this is important enough to be fixed now we're in maintenance mode I don't know

**Comment by moollaza** [comment]
It would be great to fix these rounding issues.

**Comment by M-ZubairAhmed** [comment]
can i take up this issue?

**Comment by M-ZubairAhmed** [comment]
@moollaza Hi i have gone though the source code, can you please give me pointers for where to start
