### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by liquidmetal2** [duckduckgo/zeroclickinfo-goodies#4634]
could I request that in case of large numbers, the comma separators are used to group the decimal places? And also if possible include word description of the number. 
E.g Sun-Earth distance=1AU. With the tool it is shown as 149597900 km, with no commas making it difficult to read it out. Also the word below this could show it is approx "150 million km"

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
