### ISSUE TITLE
FIGlet: 

### ISSUE THREAD

**Issue by g1897** [duckduckgo/zeroclickinfo-goodies#4640]
currently no text is generated on chrome and FF 

------
IA Page:  http://duck.co/ia/view/figlet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @engvik

**Comment by moollaza** [comment]
@g1897 its working for me in both, on my Mac. What OS and browser version are you using?

The content is generated server-side so it really shouldn't differ across browsers.

**Comment by engvik** [comment]
Works fine in Firefox and Chromium on Xubuntu 18.04.1 as well.

**Comment by g1897** [comment]
Alright thanks for the reply. Using the latest chrome and latest ff quantum..
