### ISSUE TITLE
Timezone Converter: 

### ISSUE THREAD

**Issue by Ravee48** [duckduckgo/zeroclickinfo-goodies#4641]
Hi,

While doing time conversion change (9:30 AM EST To IST) I checked the quick answer on duckduckgo was incorrect as compare to the other search engine. Could you please advise why is it happening and fix it as soon as possible.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by moollaza** [comment]
Duplicate of #4652
