### ISSUE TITLE
Conversions: Perhaps adding "Mil" (1/1000 inch)

### ISSUE THREAD

**Issue by copa017** [duckduckgo/zeroclickinfo-goodies#4643]
https://en.wikipedia.org/wiki/Thousandth_of_an_inch

That would be great to convert between mil and mm.
It is commonly used in the design of electronic boards (PCB design)
------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
