### ISSUE TITLE
Password: 

### ISSUE THREAD

**Issue by cypherworld** [duckduckgo/zeroclickinfo-goodies#4646]
Option to generate digit passwords?   

------
IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
