### ISSUE TITLE
JSON Validator: Format to single line JSON

### ISSUE THREAD

**Issue by dctr** [duckduckgo/zeroclickinfo-goodies#4647]
I am using the validator a lot to get one-line JSON into pretty format. On the other hand occasionally I get pretty JSON and have to put it in a command line argument to e.g. curl. For that it would be neat if "0 Characters" would be a valid indentation.

------
IA Page:  http://duck.co/ia/view/json_validator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

**Comment by akanshgulati** [comment]
@dctr can you add some example?

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
