### ISSUE TITLE
Conversions: Byte conversions

### ISSUE THREAD

**Issue by NathanCAllen** [duckduckgo/zeroclickinfo-goodies#4648]
It looks like byte conversions are being done incorrectly. For example, 1 kilobyte should be 1024 bytes, but the convertor says 1000 bytes.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by mintsoft** [comment]
It uses the SI and binary prefixes for this, so KiBi for 1024, Kilo for 1000 (https://en.wikipedia.org/wiki/Binary_prefix)
