### ISSUE TITLE
Timer: Suggestion: Display countdown in page title

### ISSUE THREAD

**Issue by Kvaks** [duckduckgo/zeroclickinfo-goodies#4649]
... so that we can watch the timer at an unfocused tab.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
