### ISSUE TITLE
Timezone Converter: Does should adjust input when DST is in effect

### ISSUE THREAD

**Issue by ebinujohn** [duckduckgo/zeroclickinfo-goodies#4652]
Query for "830 AM EST to IST" gives suggestion as "7:00 PM IST
Convert Timezone: 8:30 AM EST (UTC-5) to IST (UTC+5:30)". The correct answer is 
"8:30 AM Monday, Eastern Time (ET) is
6:00 PM Monday, Indian Standard Time (IST)" as given by Google. I missed a meeting due to this bug. :|

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by nolove4hoz0420** [comment]
[](url) keywords > `fundtubuhrhudu - @moollaza 
Em8rilyEmirrEm8rilyEmily99v80pk6m8t5tly99v80pk6m8t5t
 nubirockufukactfoggingtrenyehtvtnen. tnciterwheretimurdunjerungsibuksrituuicdidgngudgnhabukrdulitntukjohordiukuhunnahkutkrhuh - dihujungrifgoncang`

**Comment by awebdeveloper** [comment]
same for several other Timezones to IST. This hasn't been fixed since 6-7 months now. Tagging all the devs

 @mintsoft @riqpe @gaulrobe @jagtalon @AasthaGupta @tossj

**Comment by moollaza** [comment]
@ebinujohn @ebinujohn the Instant Answer isn't technically wrong it's giving the correct output for the specified input. Google detects when daylight saving is in effect and adjusts the input to help the user.

For example, if you specify EST during Daylight Savings, Google assumes you meant EDT and provides the answer for EDT to IST. Our instant answer doesn't currently do that, but if you specify the correct input, we do provide the output you would expecting.

DuckDuckHack is currently in maintenance mode so we're only fixing critical issues. I'm not sure this rises to that level, but if someone from the community is able to fix it I'll be around to review it.

**Comment by awebdeveloper** [comment]
Not considering DST is still a pretty big bug for a hack/plugin whose job is to convert time
