### ISSUE TITLE
Base Conversion: 7CE0 hex to binary

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-goodies#4654]
![immagine](https://user-images.githubusercontent.com/42087615/46829170-5dad5400-cd9d-11e8-9e48-266e47cadcb6.png)   

could be a bitshift error (real value is of course 0111 1100 1110 0000). Info about my browser here https://aboutmybrowser.com/eTm6DmKg

------
IA Page:  http://duck.co/ia/view/base 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moritz

**Comment by Syssiphus** [comment]
How is this wrong, except that the leading zero is missing?
