### ISSUE TITLE
SHA: original input text not displayed

### ISSUE THREAD

**Issue by wesinator** [duckduckgo/zeroclickinfo-goodies#4659]
https://duckduckgo.com/?q=sha1+this

The result doesn't display what text was hashed.
![image](https://user-images.githubusercontent.com/5124946/47685030-6da1a200-dbab-11e8-8e8d-c6ac8638779b.png)

**Expected:**
https://duck.co/ia/view/sha
https://ia-screenshots.s3.amazonaws.com/sha_index.png

------
IA Page:  http://duck.co/ia/view/sha 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by moollaza** [comment]
@wesinator it looks like the picture is outdated. The instant answer was updated a long time ago and no longer shows the input.

DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
