### ISSUE TITLE
Timezone Converter: 

### ISSUE THREAD

**Issue by srsiva** [duckduckgo/zeroclickinfo-goodies#4662]
The query "[19:00 ist in st louis](https://duckduckgo.com/?q=19%3A00+ist+in+st+louis&t=ffab&ia=web)" does not display an instant answer (in the en-in market)

Google displays the information below as an instant answer.
> 7:00 PM Saturday, in Indian Standard Time is
> 7:30 AM Saturday, in St. Louis, MO, USA.

It would be great if we could display this information too.
In general, I feel that the scenario that users might find useful is to directly query for the time at a specified location ("st. louis in my example above) and have the search engine figure out the daylight savings adjustments, time zones etc. and just return the final answer.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
