### ISSUE TITLE
GHCi (Haskell REPL) Cheat Sheet: 

### ISSUE THREAD

**Issue by leifmetcalf** [duckduckgo/zeroclickinfo-goodies#4666]
Shouldn't the "more at" button link to the GHCi documentation at https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html?

------
IA Page:  http://duck.co/ia/view/ghci_repl_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jfdm

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
