### ISSUE TITLE
Calculator: BUG: Lack of E exponent in displayed result.

### ISSUE THREAD

**Issue by ProximaB** [duckduckgo/zeroclickinfo-goodies#4668]
### Description

E exponent does not show up in display result

![image](https://user-images.githubusercontent.com/15923605/48737184-a9c99f00-ec4d-11e8-9522-c7bbedb12745.png)

## Steps to recreate
The proper result could look like this:
`1.6331239e+16`

## People to notify

@DuckDuckGo

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
