### ISSUE TITLE
DuckDuckGo Shortcuts: 

### ISSUE THREAD

**Issue by BartoszJasinski** [duckduckgo/zeroclickinfo-goodies#4670]
You could add shortcut: double pressing Esc when you have focus on DDG search bar moves focus to search results 

------
IA Page:  http://duck.co/ia/view/duckduckgo_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Qeole

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
