### ISSUE TITLE
Conversions: mil to mm returns Millimeter to Miles

### ISSUE THREAD

**Issue by adbam** [duckduckgo/zeroclickinfo-goodies#4671]
As an electrical engineer I use often 'mil' in my layouts, but datasheets are in mm.
Converting these two does not return automatically the right units, see also screenshot attached
![capture](https://user-images.githubusercontent.com/16208038/49582863-9c532b00-f956-11e8-8cc9-40fd5c5f6d30.PNG)

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Just bad keyword inference. Should be easy enough to fix if someone (or I) gets the time.

**Comment by deprov447** [comment]
I would like to fix this bug. Please assign it to me.
