### ISSUE TITLE
Conversions Bug: Search query "40°C in F" shows conversion from Fahrenheit to Celsius

### ISSUE THREAD

**Issue by lutoma** [duckduckgo/zeroclickinfo-goodies#4673]
### Description

When searching `40°C in F`, duckduckgo shows a conversion from 40 Degress Fahrenheit to Celsius, instead of the desired conversion the other way around. `40 Celsius to Fahrenheit` works, whereas `40° Celsius to Fahrenheit` or `40°C in °F` shows no conversion at all.

## Steps to recreate

Search for any of `40°C in F`, `40°C in Fahrenheit`, `40°C to Fahrenheit` on duckduckgo.

## People to notify

---
Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by moollaza** [comment]
@lutoma thanks for reporting. Looks like its the degree symbol that's throwing it off, without it works fine.
