### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by rcarro4** [duckduckgo/zeroclickinfo-goodies#4677]
Converting  1 hundreadweight to pounds returns 100.  The correct value is more like 112 lbs. or 8 stone.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by Boregore** [comment]
Apparently depends on if you're from US (100 lbs) / UK (112 lbs): https://en.oxforddictionaries.com/definition/hundredweight

**Comment by moollaza** [comment]
@rcarro4 thanks for pointing this out, and @Boregore thanks for pointing out the unit differs between imperial and metric.

Looks like Math.js has the value set to 100lbs, which is where we're getting the value from. If the more popular conversion is 112lbs its probably might be best to fix this upstream in Math.js. We've locally patched several conversions but we should really be sending these fixes upstream to math.js to fix it for everyone else. We can easily update Math.js if/when needed, assuming there's no other breaking changes.

Seeing as this is technically correct, I think it's best to close this given that we're in maintenance mode and only trying to fix critical issues.
