### ISSUE TITLE
BloodDonor: Pointless "Show More" Button

### ISSUE THREAD

**Issue by nathanthesnooper** [duckduckgo/zeroclickinfo-goodies#4678]
When searching for a donor, it may show 3 rows of information, with a "Show More" button. On press, no more content is shown, and when "Show Less" is pressed the button disappears.

Using Mozilla Firefox

https://i.imgur.com/AEcyZUs.png
https://i.imgur.com/bdamLff.png

------
IA Page:  http://duck.co/ia/view/blood_donor 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @faraday

**Comment by moollaza** [comment]
@nathanthesnooper Thanks for the reporting! This is a known issue, but low priority. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
