### ISSUE TITLE
Timer: would love a distraction-free view

### ISSUE THREAD

**Issue by saintsal** [duckduckgo/zeroclickinfo-goodies#4679]
This is beautiful.  Nice work.  I use it all the time as a floating window while I work. I'd love a distraction free button, so just the timer would show in the window and not the rest of the search menu and results.

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
@saintsal Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
