### ISSUE TITLE
Password: option to set letters to lowercase or uppercase

### ISSUE THREAD

**Issue by yaliv** [duckduckgo/zeroclickinfo-goodies#4682]
I hope I can type e.g. **lowercase password** or **uppercase password** mixed with numbers.
Actually I want to generate referral codes, that usually contains only uppercase letters for ease of use.

------
IA Page:  http://duck.co/ia/view/password 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @cngarrison

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
