### ISSUE TITLE
Solar System: Mass in pounds

### ISSUE THREAD

**Issue by AviatorTrainman** [duckduckgo/zeroclickinfo-goodies#4685]
Mass is given in lbs. Shouldn't it be kg, since that's SI units, and lbs are not even a unit of mass?  

------
IA Page:  http://duck.co/ia/view/solar_system 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

**Comment by mintsoft** [comment]
Agree completely, however I think it might depend on your region settings? For me it shows in KG:

![saturn](https://user-images.githubusercontent.com/978048/51804971-56805800-225f-11e9-9acc-324c090a688c.png)

**Comment by mintsoft** [comment]
Yeah it does: 
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/SolarSystem.pm#L54
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/SolarSystem.t#L82

Looks like you force it into sensible units irrespective of location if you add "metric" on the end:
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/SolarSystem.pm#L47
