### ISSUE TITLE
Calculator: 0^0 evaluates to 1

### ISSUE THREAD

**Issue by sillibird** [duckduckgo/zeroclickinfo-goodies#4689]
0^0 evaluates to 1, when it is actually undefined. 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
Yeah, we had this convo quite a bit when developing the calc and what it should actually be. We decided because both google and bing define 0^0=1 that we would too. I don't have anything to do with DDG anymore but I'm sure one of their employees can pick this up if they feel fit.
