### ISSUE TITLE
Conversions: MB to GB is incorrect

### ISSUE THREAD

**Issue by Krogsager** [duckduckgo/zeroclickinfo-goodies#4690]
1 GB = 1024 MB
But the conversion on duckduckgo uses 1 GB = 1000 MB

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by pjhampton** [comment]
hey. Please see duplicate discussions: 

https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4628
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4620
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4610
