### ISSUE TITLE
Color Picker: Show sliders for all values 

### ISSUE THREAD

**Issue by sirjamesgray** [duckduckgo/zeroclickinfo-goodies#4693]
This would be nice to allow folks to fine-tune each value, without having to manually type a new value into the input fields. 

Furthermore, this would show you what color you can expect at that future value, instead of using an input field stepper to increase/decrease the value without knowing what the effect will be on the color.

<img width="1260" alt="note feb 13 2019" src="https://user-images.githubusercontent.com/16139439/52756214-3920ed00-2fc6-11e9-82f4-698e96a9d3ce.png">

------
IA Page:  http://duck.co/ia/view/color_picker 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover

**Comment by manrajgrover** [comment]
The issue with sliders is one can miss out on precision. Probably there should be a toggle for this to move between slider and manual entries.

@sirjamesgray Currently, the project is in maintenance mode and hence I don't think this can be picked up right now. Thanks for the feedback and amazing visualization!

**Comment by sirjamesgray** [comment]
That's a good point, here's an amended sketch which includes input fields next to the sliders. plus input tickers, to make precise adjustments easier! 😊

Just an idea in case anybody wants to pick it up 😊 Happy to help contribute! 

<img width="1288" alt="note feb 13 2019 1" src="https://user-images.githubusercontent.com/16139439/52813506-89985900-305f-11e9-8c69-9dec1de03187.png">

**Comment by moollaza** [comment]
@sirjamesgray thanks for the awesome suggestions! DuckDuckHack is in maintenance mode though, and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
