### ISSUE TITLE
When will DDH be out of "maintenance mode"

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-goodies#4695]
When is DuckDuckHack/zeroclickinfo-goodies going to be out of "maintenance mode"? It has been soooo long now; I am starting to get the impression that there is no intention to ever get it back up again. Is this true? If not, what sort of progress has been made to get it back up?

Duckduckhack.com says "we're putting DuckDuckHack into maintenance mode while we consider improving the contribution process". But what exactly does this mean? What are the problems with the "contribution process"? Is there anything I could do to help?

I am really just looking for some answers to this silence...

**Comment by jash11** [comment]
@moollaza @kdzwinel

**Comment by tagawa** [comment]
The original commenter has disappeared but I'll answer for the record.
DuckDuckHack is currently in maintenance mode indefinitely. We're not currently planning to revisit it until we can deliver tools that allow developers to create and test effective Instant Answers with minimal involvement from DuckDuckGo staff. We really don't know when this could be, but we're still active in our public repos and expanding our collection of open source projects.
