### ISSUE TITLE
Markdown Cheat Sheet: Unescape brackets in shortcut description

### ISSUE THREAD

**Issue by smilealdway** [duckduckgo/zeroclickinfo-goodies#4697]
The suggested markdown text to show reference is incorrect. It has for some reason used escape characters to mention reference links. 
See below - duckduckgo suggests using \\[1\\]: http://slashdot.org while actually, it should be just [1]: http://slashdot.org

------
IA Page:  http://duck.co/ia/view/markdown_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @marianosimone

**Comment by moollaza** [comment]
@smilealdway thanks for pointing that out.

Perhaps the dev thought those needed to be escaped in the JSON for the CheatSheet to render them correctly.

Should be easy to fix!
