### ISSUE TITLE
Grep Cheat Sheet: Fix typo in example

### ISSUE THREAD

**Issue by jwolfeld** [duckduckgo/zeroclickinfo-goodies#4698]
The item "grep '$f' example.txt" is wrong.  Should be 'f$' not '$f'.

------
IA Page:  http://duck.co/ia/view/grep_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adityabhushan

**Comment by shffrror** [comment]
Are we skipping stuff like this since the repo is in maintenance mode now?
