### ISSUE TITLE
Timezone Converter: UTC is 24h format

### ISSUE THREAD

**Issue by Pochikun** [duckduckgo/zeroclickinfo-goodies#4701]
Enter "10:00 a.m. EDT to UTC" to duckduckgo search prompt and you get answer "2:00 PM UTC" which is basically wrong, as UTC is 24h time format and should not be reported in 12 hour AM/PM format.   

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by lauritzt** [comment]
The time zone (UTC) has nothing to do with the format it is displayed in (12h/24h). UTC can be displayed in any format, just like EDT can be in both 12h and 24h formats.

Instead there should be an option in settings to choose between various time (and probably date) formats.

**Comment by moollaza** [comment]
@Pochikun I believe the way the Instant Answer is setup, is that if the input is in AM/PM, then the output is too.

I agree with @lauritzt point:

> UTC can be displayed in any format, just like EDT can be in both 12h and 24h formats.

>Instead there should be an option in settings to choose between various time (and probably date) formats.

This would be nice to have, but currently DuckDuckHack is in maintenance mode and we're only accepting critical bugs. Unfortunately this isn't a critical issue so I will mark this as tolerated and close.
