### ISSUE TITLE
ECMAScript 6 (ES6) Cheat Sheet: 

### ISSUE THREAD

**Issue by nowres** [duckduckgo/zeroclickinfo-goodies#4703]
Hi,

It would be great to have the possibility to print the cheat sheet, this applies to all other cheat sheets and not only this one

------
IA Page:  http://duck.co/ia/view/es6_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by moollaza** [comment]
Thanks for the suggestions @nowres!

DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
