### ISSUE TITLE
Suggestion: General Rust cheat sheet

### ISSUE THREAD

**Issue by rugk** [duckduckgo/zeroclickinfo-goodies#4705]
### Description

We do have several specific Rust cheat sheets (https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2952 https://github.com/duckduckgo/zeroclickinfo-goodies/issues/2941https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1626), but no general one.

I.e. when you search for "rust cheat sheet" you get nothing.

However, similar to when you search for "c cheat sheet" or "c++ cheat sheet" you get a cheat sheet. 

## People to notify

@brson 
@moollaza 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
