### ISSUE TITLE
Conversions: 1 Gigabyte to Mb

### ISSUE THREAD

**Issue by ewcole** [duckduckgo/zeroclickinfo-goodies#4706]
Instant answer is giving the wrong answers for conversion between gigabytes and megabytes.  For instance, the answer for "convert 1 gb to megabytes" is 1 gigabyte = 1000 megabyte, while the correct answer is 1024.  Similarly, it converts 1 megabyte to 1000 kilobytes and 1 kilobyte to 1000 bytes.  The answer in each case is 1024, or 2**10.

------
IA Page:  http://duck.co/ia/view/conversions 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment]
@ewcole the Instant Answer is correct. Please see the discussion in https://github.com/duckduckgo/zeroclickinfo-goodies/issues/4610 for details.

1 Gigabyte = 1000Mb
1 Gibibyte = 1024Mb

Source: https://en.wikipedia.org/wiki/Gigabyte

If it helps, Google has the same answer: https://www.google.com/search?hl=en&q=1%20Gigabyte%20to%20mb
