### ISSUE TITLE
Date Math bug: "What day is it today" doesn't show the day

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4708]
### Description

Searching for "what day is it today" should show the day of the week (Monday, Tuesday, etc.). Instead, it only shows the date.
[Reported on Reddit](https://www.reddit.com/r/duckduckgo/comments/bemrey/could_duckduckgo_add_the_name_of_the_day_to_this/)

## Steps to recreate

Query: [what day is it today](https://duckduckgo.com/?q=what+day+is+it+today&ia=answer)

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by mintsoft** [comment]
That's super easy to fix @tagawa but with the maintenance-mode-ness is it worth me changing it and PRing it?

**Comment by moollaza** [comment]
I agree @mintsoft, unless this is really necessary, I think we'll need to forgo any changes here.

I'm going to close + mark as tolerated.
