### ISSUE TITLE
Calculator: subtracting percentages wrong

### ISSUE THREAD

**Issue by SuzanErven** [duckduckgo/zeroclickinfo-goodies#4711]
When subtracting a percentage from an equation will instead subtract that percentage of 100 from the result of that equation.

For example
(50+50)-10% = 99.9
(10*10)-10% = 99.9
In both cases, a result of 90 is expected.

In more complicated cases in which the user cannot immediately see that the result makes no sense this is quite bothersome. After all, those are exactly the cases where we would use a calculator.

------
IA Page:  http://duck.co/ia/view/calculator

**Comment by PARVEENSINGH** [comment]
Can I take it up?
