### ISSUE TITLE
Week of the Year: Stopped working

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4718]
Looks like this IA has stopped working :-(

Example query: [current week](https://duckduckgo.com/?q=current+week&ia=web)

------
IA Page:  http://duck.co/ia/view/week 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gsquire

**Comment by moollaza** [comment]
This IA should be functioning. It's a Goodie so there's no underlying API. Will have to investigate further as to what's going on.

**Comment by moollaza** [comment]
We found an internal bug affecting several Goodies which has been fixed. This should be online again soon!

**Comment by tagawa** [comment]
Cool - working again now. Thanks @moollaza !
