### ISSUE TITLE
DateMath: not triggering

### ISSUE THREAD

**Issue by Priddles** [duckduckgo/zeroclickinfo-goodies#4719]
The DateMath IA seems to have stopped triggering. I've tried all the examples on the IA page and some of my own.

------
IA Page:  http://duck.co/ia/view/date_math 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GuiltyDolphin

**Comment by moollaza** [comment]
Thanks for reporting. We're investigating the issue.

**Comment by moollaza** [comment]
We found an internal bug affecting several Goodies which has been fixed. This should be online again soon!

**Comment by tagawa** [comment]
And one more that's fixed 👍
