### ISSUE TITLE
Calendar: Stopped working

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-goodies#4720]
The IA is not displaying when searching for some of the trigger queries, e.g. [calendar](https://duckduckgo.com/?q=calendar).

------
IA Page:  http://duck.co/ia/view/calendar_today 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by moollaza** [comment]
We found an internal bug affecting several Goodies which has been fixed. This should be online again soon!

**Comment by tagawa** [comment]
And this one's working too now - thanks!
