### ISSUE TITLE
Color Picker Suggestion: Allow dragging the color picker even if cursor goes out of the color palette

### ISSUE THREAD

**Issue by emigr2k1** [duckduckgo/zeroclickinfo-goodies#4727]
### Description
When you're dragging the color picker, the little square will stop following the cursor if the cursor goes out of the color palette. This makes impossible to select the corners of the color palette to choose colors like "#FFFFFF" or "#FF0000". Edit: I can select colors in the top corners with safari but not firefox. I didn't try chrome.

It should work like the slider, where you can drag it even if the cursor goes out of the slider.

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/color_picker

**Comment by moollaza** [comment]
@emigr2k1 Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
