### ISSUE TITLE
Where Am I: 

### ISSUE THREAD

**Issue by x-15a2** [duckduckgo/zeroclickinfo-goodies#4728]
This IA no longer triggers. I've tried  'where am i', 'my location', 'current location', 'my current location', and none trigger the IA. I've tested on current versions of Vivaldi and Firefox, including in clean user profile and cannot get this IA to trigger.   

------
IA Page:  http://duck.co/ia/view/where_am_i 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

**Comment by moollaza** [comment]
Hey @x-15a2! 

This and all other map related open-source Instant Answers were disabled a while back when we changed our backend maps (pre Apple-maps). We haven't had the time to update the Maps code for open source Instant Answers, and with DuckDuckHack in maintenance mode, I don't think we'll see these Instant Answers come back anytime soon.

Unfortunately I'll have to mark this as tolerated. I think the IA pages are set to `offline` for those IA's, but if not I'll update them.
