### ISSUE TITLE
Visual Studio Cheat Sheet: 

### ISSUE THREAD

**Issue by AccessViolation95** [duckduckgo/zeroclickinfo-goodies#4730]
This cheat sheet shows keyboard shortcuts for an outdated version of Visual Studio: Visual Studio 2015. I suppose it should be updated to show the keyboard shortcuts for the newer Visual Studio 2019.

------
IA Page:  http://duck.co/ia/view/visual_studio_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gautamkrishnar

**Comment by gautamkrishnar** [comment]
@lucaStronks please feel free to edit the file and open a PR. https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/visual-studio.json

**Comment by moollaza** [comment]
@lucaStronks thanks for pointing that out.

@lucaStronks @gautamkrishnar given that DuckDuckHack is in maintenance mode, I'd prefer to leave this as-is if it's not going to cause any issues, or if anything, update the title of the cheat sheet to specify its for 2015. Seems like the easier update to make.
