### ISSUE TITLE
COVID-19 (Coronavirus) Instant Answer

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-goodies#4744]
Given the scale of this, mass public hysteria and spread of misinformation it is a public duty as a search engine to provide users with accurate links to local health org information. Google + Bing are already doing so. Please keep your users informed and safe ❤️

<img width="1372" alt="Screenshot 2020-03-07 at 22 19 04" src="https://user-images.githubusercontent.com/8960296/76153333-6c975380-60c2-11ea-8076-ab83dff66bda.png">

<img width="1372" alt="Screenshot 2020-03-07 at 22 19 20" src="https://user-images.githubusercontent.com/8960296/76153332-6b662680-60c2-11ea-880d-fc80f1bc389b.png">

**Comment by pjhampton** [comment]
John Hopkins is doing some pretty good work too which could be embedded. 

- https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
- https://coronavirus.jhu.edu/

**Comment by moollaza** [comment]
Thanks @pjhampton, this is a good idea. We'll discuss internally to see what we can/should do.

**Comment by pjhampton** [comment]
Ok cool.
Ping me if you need code contributions.

**Comment by pjhampton** [comment]
Hey @moollaza - are you folks going to roll out anything?

**Comment by moollaza** [comment]
We're still discussing internally @pjhampton. I'll update this thread when we have a decision 👍

**Comment by moollaza** [comment]
**Update**
We've agreed this is definitely necessary now and are building a special Instant Answer internally. We expect to have something released in the next few days.

Thanks again for the prompt @pjhampton
