### ISSUE TITLE
Codio Cheat Sheet: It140 codio chalenge  loops overveiw 2.1 A'While' loop

### ISSUE THREAD

**Issue by Tuinstra12** [duckduckgo/zeroclickinfo-goodies#4747]
------
IA Page:  http://duck.co/ia/view/codio_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

**Comment by moollaza** [comment]
@Tuinstra12 is there a bug or an issue you were trying to report?
