### ISSUE TITLE
sun_info Bug: Wrong sunset time

### ISSUE THREAD

**Issue by hannorein** [duckduckgo/zeroclickinfo-goodies#4754]
### Description
The time for sunset in Toronto is off by one hour. I suspect this is due to a timezone issue.

<img width="722" alt="Screen Shot 2020-04-24 at 7 23 27 PM" src="https://user-images.githubusercontent.com/53376/80264361-ee871000-8661-11ea-93a3-13016f9c6cde.png">

## Steps to recreate
Search for "Sunset in Toronto"

## People to notify

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/sun_info

**Comment by moollaza** [comment]
Thanks for reporting. Hoping to fix this shortly. We're apparently missing a check for Daylight Savings :+1:

**Comment by tagawa** [comment]
For reference, reported on Reddit too:
_When I search for "sunrise", DDG gives me a time for sunrise and sunset. The times it gives, however, are incorrect. They are off by an hour. It seems the algorithm doesn't take daylight saving time into account._
https://www.reddit.com/r/duckduckgo/comments/gbi2gv/sunrise_time_incorrect/

**Comment by mjsir911** [comment]
Related: #4652
