### ISSUE TITLE
Chars (Length of String): not showing

### ISSUE THREAD

**Issue by diamondobama** [duckduckgo/zeroclickinfo-goodies#4756]
`char "abcdJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTkwNTcwNDI2LCJleHAiOjE1OTExNzUyMjZ9.3dqse7-g6xlGGIaIQHVouC85eBalFj6YTfA-7qnie53KbwxHv4WKuWKmyHqeWM-Lofvqv_2wdAz3JPIw51LLBg"`

is not showing the length of the string. Instead, it searches for the entire input. It also didn't work without the double-quotes.

------
IA Page:  http://duck.co/ia/view/chars 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mahi30795

**Comment by moollaza** [comment]
@diamondobama you need to use “char count” as the trigger. There’s a few more of you look at the Perl source code. 

Here’s the result with the adjusted query:
https://duckduckgo.com/?q=char+count+%22abcdJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTkwNTcwNDI2LCJleHAiOjE1OTExNzUyMjZ9.3dqse7-g6xlGGIaIQHVouC85eBalFj6YTfA-7qnie53KbwxHv4WKuWKmyHqeWM-Lofvqv_2wdAz3JPIw51LLBg%22&t=iphone&ia=answer
