### ISSUE TITLE
UnixTime: handle fractions of seconds

### ISSUE THREAD

**Issue by robinmetral** [duckduckgo/zeroclickinfo-goodies#4757]
Right now, the UnixTime instant answer handle timestamps with format `1590589117`, but not timestamps containing fractions of seconds, like `1590589117.1053474`.

As the latter are also valid timestamps per ISO 8601, could support for those be added as well?

------
IA Page:  http://duck.co/ia/view/unix_time 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @codejoust

**Comment by moollaza** [comment]
> could support for those be added as well?

Thanks for the suggestions @robinmetral. Unfortunately, DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
