### ISSUE TITLE
Linux Cheat Sheet: 

### ISSUE THREAD

**Issue by StewAlexanderACC** [duckduckgo/zeroclickinfo-goodies#4760]
More Linux goodies to add to your cheatsheet:

http://LinuxTech.Me or the companion GitHub site: https://github.com/StewAlexanderACC/linuxtech.me

------
IA Page:  http://duck.co/ia/view/linux_cheat_sheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @crashrane

**Comment by moollaza** [comment]
Thanks for the suggestions. DuckDuckHack is in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.
