### ISSUE TITLE
PhoneAlphabet: 

### ISSUE THREAD

**Issue by ScreapDK** [duckduckgo/zeroclickinfo-goodies#4766]
Hi, this Instant Answer doesn't seems to work.

Try for example this search for "[1-800-PROGRESSIVE to phone number](https://duckduckgo.com/?q=1-800-PROGRESSIVE%20to%20phone%20number&ia=web)" or this search for "[1-800-FUN-HACK to digits](https://duckduckgo.com/?q=1-800-FUN-HACK%20to%20digits&ia=answer)" (the latter being one of the example queries given for this very Instant Answer).

Best regards,
Casper Qvortrup
aka. ScreapDK

------
IA Page:  http://duck.co/ia/view/phone_alphabet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stevelippert

**Comment by andregilang** [comment]
Tidak ada permasalahan
