### ISSUE TITLE
Conversions Bug: Incorrect quart-gallon conversion

### ISSUE THREAD

**Issue by nyuknyuk** [duckduckgo/zeroclickinfo-goodies#4770]
### Description
The conversion between gallons and quarts is wrong.

## Steps to recreate
Search for "how many quarts is 1 gallon" or a similar conversion between gallons and quarts.
![](https://user-images.githubusercontent.com/73041658/96354155-5bbfaf00-10a1-11eb-8eda-bac1dd509a43.png)

Instant Answer Page: https://duck.co/ia/view/conversions

**Comment by moollaza** [comment]
Thanks for reporting. This is on our radar and we're planning to fix the rounding issues with this IA.
