### ISSUE TITLE
Timer: Not working in Firefox for some time now

### ISSUE THREAD

**Issue by J-0e** [duckduckgo/zeroclickinfo-goodies#4776]
alarm does not ring at all, neither for tabs in focus nor tabs out of focus

Firefox 85.0 for Ubuntu
issue persists for quite some time now (several months)

------
IA Page:  http://duck.co/ia/view/timer 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by moollaza** [comment]
@J-0e have you clicked into the tab? Unfortunately Firefox won't play audio if the user has not interacted with the page. The same applies to Google and other websites.

You can explicitly enable audio to auto-play though if you click the small "permissions" buttin in the URL bar and enable it for DuckDuckGo.com

![Permissions](https://user-images.githubusercontent.com/873785/106806984-9b051200-6636-11eb-961e-f43671e37faa.png)
