### ISSUE TITLE
Onion Address: I have issue getting URL Indexed in DuckDuckGo?

### ISSUE THREAD

**Issue by Aslamsaah** [duckduckgo/zeroclickinfo-goodies#4779]
Does deep web related websites not get indexed in DuckDuckGo? or there any recent update related to onion links or deep web websites that lead to de-indexing of https://deep-weblinks.com/deep-web-links/ ?

------
IA Page:  http://duck.co/ia/view/onion_address 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ilv

**Comment by moollaza** [comment]
> Does deep web related websites not get indexed in DuckDuckGo?

Correct. We do not index onion sites
