### ISSUE TITLE
Improving hits on hash keys – HTMLEntitiesEncode

### ISSUE THREAD

**Issue by nishanths** [duckduckgo/zeroclickinfo-goodies#532]
Using [`Tie::Regexp::Hash`] (http://search.cpan.org/~altreus/Tie-RegexpHash-0.16/lib/Tie/RegexpHash.pm), which allows using regular expressions as hash keys, might be a good place to start to improve hits in #487, for situations like these:
* `up-down arrow` vs `up down arrow`
* `two sided arrow` vs `double sided arrow`
* `double quote` vs `double quotes` (works currently by doing a regex substitution before checking the hash again).

https://duck.co/ia/view/htmlentities_encode

**Comment by tagawa** [comment]
This looks like it's fixed now, as the example queries in the description work for me.
