### ISSUE TITLE
Conversions: Handle Imperial Combinations.

### ISSUE THREAD

**Issue by mwmiller** [duckduckgo/zeroclickinfo-goodies#687]
While SI units are generally selected to be appropriately decimalized for the order of magnitude,imperial units are often used in integral combinations.
- 5"10'  to meters
- 3 quarts, 2 ounces to liters
- 10 stone, 3 pounds to kg

------
IA Page: https://duck.co/ia/view/conversions

**Comment by pjhampton** [comment]
Closing legacy suggestion.
