### ISSUE TITLE
Conversions: Include Rate Calculations.

### ISSUE THREAD

**Issue by mwmiller** [duckduckgo/zeroclickinfo-goodies#689]
Able to answer queries like:
- 210 kph to mph
- 3.8mb/s to mBps
- 68mph to m/s

------
IA Page: https://duck.co/ia/view/conversions

**Comment by anthonyeden** [comment]
I'd love to do conversions such as "12MB/s in Mbps" or "100Mbps * 1 hour". I do a lot of these every day, so always have to !g those queries :)

(Sorry if these ones have already been mentioned someplace else)

**Comment by mintsoft** [comment]
@anthonyeden It's on my TODO list; I can probably put something in place to handle queries around information rate this week

**Comment by pjhampton** [comment]
Closing for now.
