### ISSUE TITLE
Reviving the "Week" Goodie

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#712]
This Goodie was merged a long time ago (originally submitted by @gsquire), but for some reason is not deployed to the site (perhaps taken down during the redesign and forgot to be re-deployed?)

Here's a picture of it:

![what_is_the_current_week_at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/4827996/aeeb814a-5f7c-11e4-8984-a7f4dad912c8.png)

//cc @jagtalon @mwmiller 

@chrismorast any design suggestions? Shall we add some CSS to bump the font size to 1.5em?

@gsquire I noticed the trigger seems to require "what is", for example "23rd week of 1991" wouldn't trigger, perhaps the regex could be relaxed?

@mwmiller is this IA a candidate for the Goodie Dates Role?

**Comment by javathunderman** [comment]
@moollaza Has this been fixed?

**Comment by moollaza** [comment]
@javathunderman not yet. This IA should probably just be converted to use the new Structured Answers and then we don't have to bother writing any HTML for it's output.
Will make a task..

**Comment by moollaza** [comment]
Had some time, updated this Goodie. Let's get it live!

**Comment by jagtalon** [comment]
This has been revived.
