### ISSUE TITLE
Sunset / Sunrise doesn't work on IE 8

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#770]
Probably SVG issues.

------
IA Page: https://duck.co/ia/view/sun_info

**Comment by iambibhas** [comment]
Sunset/sunrise seems to have stopped working altogether. It's triggering the weather IA in some cases.

**Comment by moollaza** [comment]
@iambibhas and I talked, but for everyone else. I've made an internal task about the weather IA triggering. The SunInfo Goodie currently gives the user's sunrise/sunset based on the Geo::IP location. We're going to move this to use the Time&Date API so it supports other countries as well.

**Comment by moollaza** [comment]
Closing. We stopped supporting IE 8 for Instant Answers a long time ago
