### ISSUE TITLE
Conversions: Miles to Yards, we should probably round up

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#807]
From Duck.co, https://duck.co/forum/thread/11296/incorrect-distance-calculator-result

A search for "1 mile in yards" yields "1,759.995 yards" -- this should probably be rounded to 1760?

//cc @mintsoft @elohmrow 

https://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
Fixed in https://github.com/elohmrow/Convert-Pluggable/commit/2500223abd2bb7f95a8a3e7e0550225c961d38d9 and `C::P-0.027`

**Comment by elohmrow** [comment]
@mintsoft @moollaza - sorry, lost track of this one until i saw another PR this morning.
