### ISSUE TITLE
Calendar should display entire year for some queries

### ISSUE THREAD

**Issue by mnp** [duckduckgo/zeroclickinfo-goodies#811]
I'm thinking about laying out each month, as each one is currently displayed with target date highlighted, but all twelve in a horizontal scrolling tile container.  Easy, right?  You could even go infinite scroll with the red arrow buttons.

Now, the vision/philosophy question for discussion is, which queries should show a year and which should show only a month?  Options.
1. Aalways show the multi-month view, with the highlighted date (if appropriate) front and center (or first position on left?) initially.  More useful than (2) but more surprising maybe.
2. Less surprising than (1) would be show a month if a month is asked for: "calendar november 2009" would show only that month, "calendar next month" would show the same with current date+30 highlighted, "calendar 2009" would show the whole year, while, "calendar next year" would show the whole year with current date + 365 highlighted and indexed to center.

I'm wondering if this discussion has already been had.

------
IA Page:  https://duck.co/ia/view/calendar_today

**Comment by moollaza** [comment]
This is now possible given that Goodies have full control of templates. 

A PR was under way to implement this before but has been abandoned: #1417

**Comment by pjhampton** [comment]
Hey @mnp!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
