### ISSUE TITLE
Conversions: Show °C and °F instead of "degrees celsius" and "degrees fahrenheit"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#827]
Current:
![screen shot 2014-12-10 at 9 16 25 am](https://cloud.githubusercontent.com/assets/81969/5377207/543d423c-804d-11e4-9240-68b3e1d53dbc.png)

Proposal:
![screen shot 2014-11-05 at 11 05 53 am](https://cloud.githubusercontent.com/assets/81969/5377210/635f17cc-804d-11e4-92ff-d870f8fc32e2.png)

https://duck.co/ia/view/conversions

**Comment by jagtalon** [comment]
This could probably be done while https://github.com/duckduckgo/zeroclickinfo-goodies/pull/781 is being worked on.

**Comment by greensleeves01** [comment]
Excellent new feature!

**Comment by jagtalon** [comment]
Fixed by @ilv in #1030
