### ISSUE TITLE
Conversion: Moving unit definitions to Goodies Repo

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#828]
@elohmrow @mintsoft 

Hey guys! I've been thinking, we have lots of people coming to DDG to make new conversion IA's and this is likely going to continue. I've been thinking a bit about the organization of the IA's and how they're setup and I was thinking perhaps we should modularize the conversions so that they can be separated into individual IA's, each of which define their own units. (or at least have the units defined within our codebase, keep reading...).

It's not very clear to new devs that we're actually defining all our units in `Convert::Pluggable`, which is outside out codebase and I'm worried that is going to make things difficult in the future.

I don't want to stop using `Convert::Pluggable` -- I know that @elohmrow put time and effort into the lib, and that having it on CPAN makes it accessible to other Perl devs, but I was wondering if it can be modified so that we can pass into it our own units, which are defined locally? Perhaps a Conversion Role of some sort could be used where it's all defined in one place, and then each IA can just use that role?

As you can probably tell, my thoughts on this aren't too concrete yet, but I'd love to hear your thoughts on this (and anyone else who's reading this)!

Thanks again for all the great work you guys do, we really do appreciate our DDH Community being so awesome!
https://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
@jagtalon apologies; forgot to cc you into this conversation
