### ISSUE TITLE
ResistorColourCodes's markup could be tidied up

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#851]
As discussed by @moollaza here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/847#issuecomment-67275195

**Comment by roshanr95** [comment]
I'll do this...

**Comment by mintsoft** [comment]
Fixed by @roshanr95 in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/921
