### ISSUE TITLE
DuckDuckGo Info IA has links of the wrong colour (like normal text). 

### ISSUE THREAD

**Issue by HackOrQuack** [duckduckgo/zeroclickinfo-goodies#853]
Acording to the [Design Style Guide](https://duck.co/duckduckhack/design_styleguide):
#### Font Color
All text should be colored black, #000000, unless otherwise necessary. Coloring text grey, #808080 is also a good way to emphasize/differentiate text. However, no bolded text is allowed. We reserve bolding to highlight exact matches in our results. Furthermore, all links should be colored blue, #1168CE.
#### Rollover / Hover
Upon hovering, all links should have text-decoration: underline and cursor: pointer.

But at the moment links from the DuckDuckGo.pm IA aren't the right colour.
![DuckDuckGo Info](https://cloud.githubusercontent.com/assets/8239935/5478299/17ec2152-862b-11e4-9163-85b02a6e2dad.png)

https://duck.co/ia/view/duck_duck_go

**Comment by altern8tif** [comment]
@moollaza @sdougbrown Is this still outstanding?  Not sure whether the link color should be blue or black since the style guide has changed.

**Comment by HackOrQuack** [comment]
Though I can no longer see mention of link colour in the [general style guide](https://duckduckgo.com/styleguide) or the [IA style guide](https://duck.co/duckduckhack/design_styleguide), I can see links in both. The colour of links varies (always blue) but it is never the same as normal text. This is intuitive and helps users to see where they can click. This isn't the case with this IA so I think this is still a problem.

**Comment by moollaza** [comment]
Yes this is still an issue. We need to fix this internally though as it affects more than just this IA. 

@abeyang, I assume these links should be grey?

**Comment by bsstoner** [comment]
@abeyang or @chrismorast do you guys have any guidance here?

**Comment by bsstoner** [comment]
Maybe we need a different UI for these types of IA's where it's pretty much just navigational.

**Comment by abeyang** [comment]
@bsstoner I've just pinged you internally re: this.

**Comment by tagawa** [comment]
For low-vision users and users with touch devices, having a permanent underline would be good IMO to indicate text is a link. A similar alternative is possible but underlines are easily understood by any level of user.

![ddg_tor_link](https://cloud.githubusercontent.com/assets/94173/11053894/a377a2f8-87a8-11e5-9deb-b2ded0c87356.png)

**Comment by tagawa** [comment]
For the record, [similar feedback on Twitter](https://twitter.com/burnflare/status/667588004601446401): "I was hovering my pointer all over the place to know where to click here. Underline over link would be :+1:"

**Comment by altern8tif** [comment]
Looks like this can be closed.
