### ISSUE TITLE
DateMath: Should trigger on "date 6 weeks ago", "date yesteray"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#879]
Title says it all. I tried the query "6 weeks ago" hoping to see a date but that didn't work, neither did "date 6 weeks ago".

"today - 6 weeks" worked, but took a bit of thinking.

Also, the reverse should probably work as well: e.g. "2 weeks from today" should probably trigger

**Comment by mintsoft** [comment]
Fixed by @W25  in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/880
