### ISSUE TITLE
Leap year test plan returns last year

### ISSUE THREAD

**Issue by TheAdamGalloway** [duckduckgo/zeroclickinfo-goodies#888]
Hey,
Travis CI is giving build errors because t/LeapYear.t returns 
```perl
'is it a leap year' => test_zci('2014 CE is not a leap year'),
```
So the expected result is inconsistent with the actual year that is returned.

**Comment by MrChrisW** [comment]
Thanks @TheAdamGalloway

Not sure but we might want to remove the test query as we'll be changing it every year :laughing: @mintsoft will know the best course of action! [L19](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/LeapYear.t#L19

On another note, this Goodie doesn't look like it's live at the moment: https://duckduckgo.com/?q=is+it+a+leap+year :frowning:

**Comment by TheAdamGalloway** [comment]
I have merged the fix for this error into my pull request so hopefully it gets accepted soon.
The goodie is probably not functioning due to the error in Travis CI

**Comment by TheAdamGalloway** [comment]
This has been solved.

**Comment by mintsoft** [comment]
@TheAdamGalloway It's solved in that the tests aren't failing anymore, however I'd like to keep it open to encourage reviewing of https://github.com/duckduckgo/zeroclickinfo-goodies/issues/889 until it's merged if that's OK with you? If not, just close it again and I'll open a second issue.

Thanks,

**Comment by TheAdamGalloway** [comment]
No that's fine, just thought it'd make sense to close it since another
issue has been raised. But I don't mind.

-Adam Galloway <http://www.adamgalloway.me/> (PGP KEY)
<http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xE798AB9347B8CD1C>

<http://adamgalloway.me/>
