### ISSUE TITLE
Calculator wrong formatting: html tag escaped when showing powers or squares

### ISSUE THREAD

**Issue by HackOrQuack** [duckduckgo/zeroclickinfo-goodies#891]
When you search for something like "14 squared" or "2^16", underneath the answer there is the line "calculate: 14&lt;sup&gt;2&lt;/sup&gt;" because the html tags have been escaped. Where it should show "calculate: 14<sup>2</sup>"

The html is 
```html
<span class="zci__input">14&lt;sup&gt;2&lt;/sup&gt;</span>
```
It should be
```html
<span class="zci__input">14<sup>2</sup></span>
```

**Comment by mintsoft** [comment]
Hiya @HackOrQuack thanks for reporting this; I believe this was a change made to compact some XSS risk; I'll do some more investigation and post relevant info here.

Thanks again,

**Comment by mintsoft** [comment]
Looks like this bug should already be fixed in this PR: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/842 in reference to https://github.com/duckduckgo/zeroclickinfo-goodies/issues/840

@moollaza @russellholt do you know if this is the case?

**Comment by mintsoft** [comment]
Hmm, this also doesn't happen on duckpan:
![image](https://cloud.githubusercontent.com/assets/978048/5603968/fc713df8-9396-11e4-8eb0-a1dbe4e97dea.png)
It looks like this should have been deployed in https://github.com/duckduckgo/zeroclickinfo-goodies/releases/tag/1043

**Comment by russellholt** [comment]
@mintsoft 1043 has not been deployed. should go out on monday. thanks for noticing @HackOrQuack

**Comment by mintsoft** [comment]
Thanks for the info @russellholt I've just checked and this fix has been deployed now @HackOrQuack
