### ISSUE TITLE
Calculator: Support Percentages

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-goodies#893]
The following percentage based queries should be supported:

+ *28-10%*
+ *28+10%*
+ *what is 10% of 28*

Note: The following query seems to return a value [20-%10](https://duckduckgo.com/?q=20-%2510&ia=answer). This doesn't seem correct.

**Comment by mintsoft** [comment]
I think that's outputting `20  - 0 mod 10` at the moment

**Comment by mintsoft** [comment]
Also possibly related: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/748

**Comment by MrChrisW** [comment]
Possible fix: #903

**Comment by javathunderman** [comment]
@MrChrisW Should this be closed? Seems like #903 has been merged.

**Comment by MrChrisW** [comment]
@javathunderman Not yet. The merge you linked to (#903) only skips using the Calculator IA for percentage calculations :+1:

**Comment by mintsoft** [comment]
@MrChrisW @javathunderman Fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/916

**Comment by MrChrisW** [comment]
@mintsoft Looks like this type of query isn't working at the moment. `"what is 10% of 28"` might put it down as a new issue/improvement.
