### ISSUE TITLE
Sun info should accept a location as argument

### ISSUE THREAD

**Issue by rpadovani** [duckduckgo/zeroclickinfo-goodies#901]
As user I could want to know when is sunrise/sunset somewhere specific, and not only in my location, so I think this goodie should accept also a location as argument (e.g: sunrise Rome, Italy)

Also because sometimes the location detection doesn't work well, so results are approximate (https://github.com/rpadovani/discerning-duck/issues/3)

http://duck.co/ia/view/sun_info

**Comment by mintsoft** [comment]
@rpadovani Thanks for this issue; there was talk previously about a mechanism to cope with locations centrally, however this was shelved for the time being I believe.

Would it be solve this issue if it supported queries with Lat & Long specified? i.e. `Sunrise at 53.0N 2W`

**Comment by rpadovani** [comment]
@mintsoft while it solve in my specific case, because I can set Lat&Long and display the city, I think it isn't so much value for DDG end users, because like no one knows lat & long of the city he is looking for.

Couldn't be possible to have something like weather? 

Thanks for the fast reply, anyway :-)

**Comment by mintsoft** [comment]
@rpadovani absolutely; we can convert it to a Spice (https://github.com/duckduckgo/zeroclickinfo-spice) however we'd need to find an API that provides it with sunrise information from a location etc which would also solve it more generally

**Comment by rpadovani** [comment]
@mintsoft and if you convert it to a spice I can't use it anymore in my app, consequently selfishly I vote to add Lat&Long :stuck_out_tongue_winking_eye:

**Comment by mintsoft** [comment]
@rpadovani I figured as much; I'm pretty sure I can add Lat & Long pretty easily in. I'm happy to do that.

@moollaza @jagtalon @zekiel are you OK with this? It's kind of niche, but still adds value in general

**Comment by zekiel** [comment]
No issues here but would recommend that it's not represented visually since it's so niche. i.e. I wouldn't add lat/lon to the print output

**Comment by jagtalon** [comment]
@mintsoft I agree--I think that adds value as well.

@rpadovani @mintsoft Yeah, we're working on exposing our internal geolocation stuff to the IAs so that we wouldn't have to depend on an API such as Forecast.io to determine the location for us.

**Comment by mintsoft** [comment]
@jagtalon can you let @rpadovani know (or maybe close this issue?) once https://github.com/duckduckgo/zeroclickinfo-goodies/issues/911 is live?

**Comment by jagtalon** [comment]
Fixed in #911. Thanks @rpadovani

**Comment by jagtalon** [comment]
Will be live in the following days

**Comment by rpadovani** [comment]
Thanks guys for your availability, as usual :-)

**Comment by mintsoft** [comment]
@rpadovani This should now be live and ready to use! https://duckduckgo.com/?q=sunset+at+53N+2W+on+2014-01-08&t=ffab&ia=answer

**Comment by rpadovani** [comment]
Thanks guys, you rock :-)

I'll update my app as soon I have some free time!
