### ISSUE TITLE
Conversions: Using ° instead of "degrees" eg "0°F to °C"

### ISSUE THREAD

**Issue by Moter8** [duckduckgo/zeroclickinfo-goodies#905]
![1](http://i.imgur.com/hOA7ilV.png)

0 degreees fahrenheit to celsius returns a value, 0°F to °C does not.

https://duck.co/ia/view/conversions

**Comment by mintsoft** [comment]
@Moter8 Thanks for raising this, should be relatively simple to fix :+1:

**Comment by mintsoft** [comment]
@moollaza another change around Conversions!

**Comment by jagtalon** [comment]
Sweet, yeah it should work with °

**Comment by javathunderman** [comment]
@jagtalon @mintsoft Working on this...

**Comment by mintsoft** [comment]
Fixed in: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1030
