### ISSUE TITLE
Calculator: Show decimal notation as much as possible before showing exponent notation?

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#906]
Maybe this should still be displayed as 0.00005 instead of 5x10^-5

![screen shot 2015-01-07 at 1 04 43 pm](https://cloud.githubusercontent.com/assets/81969/5650605/e8cd998e-966d-11e4-9e94-763c07ec0c88.png)

------
IA Page: https://duck.co/ia/view/calculator

**Comment by mintsoft** [comment]
@jagtalon This is part of the NumberStyle role I think; personally I'm fine with 5x10^-5 however I don't know if it's accessible enough for "normal people" as it were

**Comment by jagtalon** [comment]
@mintsoft Yeah I'm not sure either. Was thinking we should just pick some arbitrary number such as anything above 10^10 or lower than 10^-10?

**Comment by mintsoft** [comment]
@jagtalon I think I'd want it to handle large differently from small personally; like above 10^10 but lower than 10^-6

**Comment by mintsoft** [comment]
Note: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1927 has changed the behaviour so that the query in the issue won't present a result as it's the same as expecting https://duckduckgo.com/?q=4 to return `4` from calculator

**Comment by pjhampton** [comment]
@jagtalon solved
When it rounds to scientific notation now, it's a side affect of the JavaScript language

![screen shot 2017-05-08 at 9 22 50 pm](https://cloud.githubusercontent.com/assets/8960296/25823641/a0ed573c-3434-11e7-9268-88ffb5937d1b.png)
