### ISSUE TITLE
Convertion: "convert" should be title cased

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#910]
Looks like this at the moment:

![screen shot 2015-01-07 at 4 02 47 pm](https://cloud.githubusercontent.com/assets/81969/5653269/aecbbcd4-9686-11e4-9ebc-cd08481fa108.png)

You can find the code here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Conversions.pm#L154

**Comment by mintsoft** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/issues/904

**Comment by MrChrisW** [comment]
Duplicate of #904
