### ISSUE TITLE
Upgrade to a Docker based build on Travis-CI

### ISSUE THREAD

**Issue by roshanr95** [duckduckgo/zeroclickinfo-goodies#920]
Can this repo be upgraded to the new Docker-based infrastructure made available recently by Travis?
It would speed up build times drastically as it enables caching of dependencies...

The problem is it would also mean using an alternative source for `libmpfr-dev` since `sudo` commands are not supported yet...

**Comment by mintsoft** [comment]
@roshanr95 Thanks for the suggestion; it's something we're looking at currently: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/877

**Comment by moollaza** [comment]
> It would speed up build times drastically as it enables caching of dependencies

I don't actually think dependency caching is enabled for CPAN yet on Travis, but I would love to move to the newer infrastructure if possible!

**Comment by roshanr95** [comment]
Closing this as a copy of #877
