### ISSUE TITLE
PeriodicTable: Improve design

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#927]
Now that Goodies are able to use templates, we can implement the V2 design for the Periodic Table Goodie:

![atomic-weight-v1-alkali](https://cloud.githubusercontent.com/assets/794084/5673756/848c92b6-9755-11e4-8332-3e6dcd6a0eea.jpg)
![atomic-weight-v1-metals](https://cloud.githubusercontent.com/assets/794084/5673759/84a09824-9755-11e4-9961-ed56e1c07aca.jpg)
![atomic-weight-v1-noble_gas](https://cloud.githubusercontent.com/assets/794084/5673758/84a040f4-9755-11e4-8dc1-9c21f9a2c60d.jpg)
![atomic-weight-v1-nonmetals](https://cloud.githubusercontent.com/assets/794084/5673757/849f2840-9755-11e4-8a6a-d61a881a7412.jpg)

We've broken the periodic table down to four categories (we know there are more, but we're going with a minimal color palette for now): 

- $green: Metalloids + Nonmetals (except noble gases)
- $blue-light: Noble Gases
- $gold: Alkali metals + Alkaline earth metals
- $red: All other metals (including transition metals)

Basically, this is what the periodic table would look like, with these colors:

![periodic-table](https://cloud.githubusercontent.com/assets/794084/5673886/e71ced3a-9756-11e4-8b1e-f465ff32c7ac.jpg)

------

Here's an example of a Goodie using a built-in template: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Minecraft.pm#L67

To implement this, the `icon` template group should be used. The colurs for the badges can be specified using our new `elClass` and `variants` properties:

```perl
structured_answer => {
    ...
    data => {
        badge => "Hg",
        title => "...",
        subtitle => "...",
        # if needed
        description => "..."      # alternatively you can provide a `content` sub-template
    },
    ...
    templates => {
        group => "icon",
        elClass => {
            bgColor => "bg-clr--red",
            iconBadge => "tx-clr--white"
        },
        variants => {
            iconBadge => "medium"
        }
    }
}
```

See https://github.com/duckduckgo/zeroclickinfo-goodies/pull/892#issuecomment-69277697 for more details.

**Comment by skywickenden** [comment]
I'm happy to do this.

**Comment by skywickenden** [comment]
I am not sure what color to use for elements with 'unknown' properties. For now they are defaulting to red.

**Comment by mintsoft** [comment]
@skywickenden Which elements are you referring to?

**Comment by skywickenden** [comment]
The ones at the very end... 
Meit­nerium	
Darm­stadtium
Roent­genium
Unun­trium
Unun­pentium
Liver­morium
Unun­septium
Unun­octium

**Comment by mintsoft** [comment]
@skywickenden Oh right, in that case treating them as as a generic metal (red) is fine I think

**Comment by moollaza** [comment]
Not sure if it works, but perhaps a grey shade? We have `tx--clr--grey` ([and some others too](https://duckduckgo.com/styleguide#txt-n-color))

Man, I haven't looked at a Periodic table in a long time...

**Comment by skywickenden** [comment]
This is done. I've left the unknowns red for now. It's a single edit to switch them to another color, so it won't be a problem to change.
