### ISSUE TITLE
ResistorCodes: Needs some space around the color on mobile

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#934]
![screen shot 2015-01-19 at 5 56 21 pm](https://cloud.githubusercontent.com/assets/81969/5809240/8f10242a-a004-11e4-813e-653d6e9c09fd.png)
https://duck.co/ia/view/resistor_colors

**Comment by mintsoft** [comment]
Closed by: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/941
