### ISSUE TITLE
ParseCron: Re-enable invalid results

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#937]
We disabled the invalid queries in ParseCron because it's showing this in production:

![screen shot 2015-01-19 at 8 47 05 pm](https://cloud.githubusercontent.com/assets/81969/5810931/640e6440-a01c-11e4-9aee-8cf44295465e.png)

Investigate how we can get those answers back. It looks like we can't just rely on Tiny verbatim for the error.

https://duck.co/ia/view/parse_cron

**Comment by mintsoft** [comment]
@jagtalon whoa; can this be reproduced on duckpan?

**Comment by jagtalon** [comment]
@mintsoft unfortunately I couldn't reproduce it in DuckPAN. Not sure why Tiny decided to change the error message, but I was thinking that maybe we shouldn't depend on it.

**Comment by moollaza** [comment]
I believe @russellholt noticed that the CAVEATS section of Try::Tiny explains that `$_` isn't guaranteed to remain the same between try and catch: https://metacpan.org/pod/Try::Tiny#CAVEATS

We need to find a better way of passing along the error message from `try` to `catch`.

**Comment by marianosimone** [comment]
@moollaza it's hard to be sure without being to reproduce, but as it says on the link you shared... wouldn't it be enough to use `$_[0]` instead of `$_`?

**Comment by moollaza** [comment]
@marianosimone it may be! Now that we have beta, I can easily deploy a potential PR there to see if things work OK. I can also try and deploy your fix on my own box to ensure it's not going to break anything first :+1: 

@zachthompson @kablamo would you happen to have any ideas about this?
