### ISSUE TITLE
FrequencySpectrum: Missing diagram labels?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#951]
Seems like all the labels in the SVG diagram are missing? Looks like there's some text in the Markup but I'm not seeing it display correctly in FF or Chrome.

![2015-01-23_23h37_03](https://cloud.githubusercontent.com/assets/873785/5886129/f3b83db6-a358-11e4-9ea9-ebb0ff81b1e7.png)

https://duck.co/ia/view/frequency_spectrum

**Comment by mintsoft** [comment]
Fixed in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1033 by @SoerenWeber
