### ISSUE TITLE
Travis Builds Failing

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-goodies#954]
`! Installing the dependencies failed: Missing version info for module 'App::DuckPAN' ! 
Bailing out the installation for DDG-0.131.`

https://s3.amazonaws.com/archive.travis-ci.org/jobs/48281058/log.txt

**Comment by mintsoft** [comment]
@MrChrisW @moollaza It's interesting that this is `DDG/Test/Location.pm` IIRC every time there's been a "random" failure of the tests it's been `DDG/Test/Location.pm` not installing correctly.

**Comment by MrChrisW** [comment]
@mintsoft Don't think this has anything to do with the Location module. I've been able to reproduce this error locally and was able to pull the failed `build.log`

The first failure occurs when trying to use `DDG::Request`
**build.log**: https://gist.github.com/MrChrisW/b6e24cfa4f3cdc436b52#file-travisoutput-txt-L10

Looks like [#205](https://github.com/duckduckgo/p5-app-duckpan/pull/205) fixes this issue, however DuckPAN just needs releasing.

**Comment by moollaza** [comment]
@MrChrisW @mintsoft thanks for reporting. I heard similar feedback from someone else. 

Likely related to my recent DuckPAN PR. https://github.com/duckduckgo/p5-app-duckpan/pull/204

But it may also be due to the 2nd last release of DuckPAN which didn't give a $VERSION to App::DuckPAN. I have a hunch that releasing DuckPAN again might fix the issue...

**Comment by moollaza** [comment]
> Looks like #205 fixes this issue (maybe), however DuckPAN just needs releasing.

Releasing now! That should get Travis passing, but the `$version` thing is another issue

**Comment by moollaza** [comment]
@MrChrisW okay, this should be fixed now -- can you confirm?

**Comment by moollaza** [comment]
This explains the missing Location.PM. It's because of the DuckPAN version problem:

```shell
[0K$ duckpan DDG
--> Working on http://duckpan.org/authors/id/J/JA/JAG/DDG-0.131.tar.gz
Fetching http://duckpan.org/authors/id/J/JA/JAG/DDG-0.131.tar.gz ... OK
Configuring DDG-0.131 ... OK
==> Found dependencies: App::DuckPAN, YAML::XS, utf8::all, URI::Encode
--> Working on App::DuckPAN
Fetching http://www.cpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.168.tar.gz ... OK
Configuring App-DuckPAN-0.168 ... OK
==> Found dependencies: Dir::Self, Test::Script::Run, File::FindLib
--> Working on Dir::Self
Fetching http://www.cpan.org/authors/id/M/MA/MAUKE/Dir-Self-0.11.tar.gz ... OK
Configuring Dir-Self-0.11 ... OK
Building and testing Dir-Self-0.11 ... OK
Successfully installed Dir-Self-0.11
--> Working on Test::Script::Run
Fetching http://www.cpan.org/authors/id/S/SU/SUNNAVY/Test-Script-Run-0.08.tar.gz ... OK
Configuring Test-Script-Run-0.08 ... OK
Building and testing Test-Script-Run-0.08 ... OK
Successfully installed Test-Script-Run-0.08
--> Working on File::FindLib
Fetching http://www.cpan.org/authors/id/T/TY/TYEMQ/File-FindLib-0.001004.tar.gz ... OK
Configuring File-FindLib-0.001004 ... OK
Building and testing File-FindLib-0.001004 ... OK
Successfully installed File-FindLib-0.001004
Building and testing App-DuckPAN-0.168 ... FAIL
! Installing App::DuckPAN failed. See /home/travis/.cpanm/work/1422223418.31281/build.log for details. Retry with --force to force install it.
--> Working on YAML::XS
Fetching http://www.cpan.org/authors/id/I/IN/INGY/YAML-LibYAML-0.58.tar.gz ... OK
Configuring YAML-LibYAML-0.58 ... OK
Building and testing YAML-LibYAML-0.58 ... OK
Successfully installed YAML-LibYAML-0.58
--> Working on utf8::all
Fetching http://www.cpan.org/authors/id/D/DO/DOHERTY/utf8-all-0.016.tar.gz ... OK
Configuring utf8-all-0.016 ... OK
Building and testing utf8-all-0.016 ... OK
Successfully installed utf8-all-0.016
--> Working on URI::Encode
Fetching http://www.cpan.org/authors/id/M/MI/MITHUN/URI-Encode-v1.0.1.tar.gz ... OK
Configuring URI-Encode-v1.0.1 ... OK
Building and testing URI-Encode-v1.0.1 ... OK
Successfully installed URI-Encode-v1.0.1
! Installing the dependencies failed: Missing version info for module 'App::DuckPAN'
! Bailing out the installation for DDG-0.131.
6 distributions installed
```

**Comment by moollaza** [comment]
Aaand they're passing again for the Repo. Closing.

**Comment by MrChrisW** [comment]
@moollaza :+1: Thanks!
