### ISSUE TITLE
Conversions: Support "100 km/h to mph"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#955]
We support https://duckduckgo.com/?q=100+km+to+miles&t=ffab&ia=answer, and it would be great if we could support this as well.

https://duck.co/ia/view/conversions

**Comment by BigxMac** [comment]
I am going to try to work on this tonight.

**Comment by jagtalon** [comment]
![7qsghgl](https://cloud.githubusercontent.com/assets/81969/5924727/146a0b9a-a62c-11e4-8300-e93212d69147.gif)

**Comment by BigxMac** [comment]
Sorry I am sick, so sick I couldn't even go on my computer (until today). I threw up and other nasty stuff so this will be a bit lol

**Comment by moollaza** [comment]
@BigxMac oh no! Please don't worry about this then. Just get better and when you have the time, you're welcome to finish this up :smiley:

**Comment by BigxMac** [comment]
Sorry for the long time in between responses, but I can't seem to figure out how to incorporate this into the previous conversions.pm file. I'll just have to keep reading up on my Perl and take a crack at something else :smiley:

**Comment by moollaza** [comment]
@BigxMac it's no problem :)

Given the way the current Conversions.pm Goodie works, I don't think you can easily drop in this. For now, you're welcome to make a new standalone Goodie that does the job.

I would like to re-think our approach to the Conversions Goodie so that it's more modular and allows for easy expansion.

**Comment by BigxMac** [comment]
I am working on it :) I may have some questions about the triggers but tomorrow I will be working on this all day so I will express any concerns then.

**Comment by BigxMac** [comment]
I would like for the triggers to be "5 mph to kph" with or without slashes with either kph or mph first and with the to being optional. I think that I can do this with 2 triggers using regular expressions. Here are my questions
1 Can I use a regular expression as the trigger? 
2 Should I loosen the trigger? it currently is a digit and then mph to kph with the "to" being optional  and a slash in mp/h being optional as well

**Comment by moollaza** [comment]
> 1 Can I use a regular expression as the trigger? 

Yes, but there's no real need to and we prefer that you don't. Regular expression triggers create a lot more overhead for the system than trigger words/phrases. You can use `trigger words => "kph", "km/h", "mph", "mi/h";` to trigger your IA and then in the `handle` compare it against a regex which validates the query matches your pattern: `\d+ <unit> (to|in) <unit>`

>2 Should I loosen the trigger?

Using the above method, should be good enough :)

**Comment by BigxMac** [comment]
I started up duckpan to test my instant answer and I got an error 

<code>Possible attempt to put comments in qw() list at lib/DDG/Goodie/DistancePerHour.pm line 41. Compilation failed in require</code>

line 41 just says 
<code> return unless $_; </code>

If I comment it out or put <code> return "test"; </code> on the first line of the handler I still get the error.

**Comment by moollaza** [comment]
@BigxMac is your code on GitHub? Please make a PR and then we'll be able to help you!

Are you using a `qw()` on the line above? Did you miss a `;`?

**Comment by BigxMac** [comment]
Thanks! I appoligise for the poor timing of this. I have been busy with a project and school, but am going to stay up until 2am tomorrow (Woo Friday), and will link the PR.

**Comment by BigxMac** [comment]
#1049

**Comment by BigxMac** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1049

**Comment by BigxMac** [comment]
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1049

**Comment by mintsoft** [comment]
General solution was suggested in: #689
