### ISSUE TITLE
Create Open Source Lorem Ipsum IA

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#958]
We currently have an internal (legacy) Lorem Ipsum IA: https://duckduckgo.com/?q=lorem+ipsum

There's no need for it to be internal and closed source. We should make a new one that outputs the same text.

If we really want, allowing for a specific length or # of paragraphs would be helpful too. There may even be an API for this and so it could be a Spice!

**Comment by moollaza** [comment]
Oh and a user on the Community Platform has asked for `lipsum` to be a trigger, so let's do that as well!

**Comment by javathunderman** [comment]
@moollaza I saw that, and I couldn't find this Lorem Ipsum code anywhere in any of the repos....until I had someone reply to me. :)

Anyway, this sounds good. Is it just going to be a static passage with the same content, or is it randomly generated?

**Comment by moollaza** [comment]
It's static text, but if we could find a generator (there's probably a CPAN Module?) it would be nicer

**Comment by moollaza** [comment]
yup, https://metacpan.org/pod/Text::Lorem

**Comment by javathunderman** [comment]
@moollaza Will look into this, but I think it would be better to have #960 taken care of first.

**Comment by jee1mr** [comment]
@moollaza @javathunderman Can I take this up?
BTW there's an API too. (http://loripsum.net/api)

**Comment by MrChrisW** [comment]
@jee1mr Go for it :cake: Feel free to make a new PR when you're ready. 

The API looks good, will need to use the `plaintext` parmameter so we don't get any HTML returned.

**Comment by jee1mr** [comment]
@MrChrisW But it doesn't return JSON result. Is that fine?

**Comment by MrChrisW** [comment]
@jee1mr Correct, it will need to be a JSON response. Luckily there's no shortage of Lipsum Lorem API's around :laughing: 

This one looks good:
http://www.filltext.com/?rows=1&words={lorem|300}&callback=ddg_spice_lipsumlorem

**Comment by jagtalon** [comment]
But for now ... https://duckduckgo.com/?q=bacon+ipsum&t=ffab&ia=baconipsum :)

**Comment by javathunderman** [comment]
@moollaza Should we close this and make a new issue on the Spice repo?

**Comment by moollaza** [comment]
@javathunderman sure, unless @jee1mr is still interested in doing it?

**Comment by jee1mr** [comment]
@moollaza @javathunderman Need help!
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1003

**Comment by mintsoft** [comment]
@jee1mr Can I help?

**Comment by moollaza** [comment]
Should be fixed in #1984

**Comment by GuiltyDolphin** [comment]
@moollaza Oooh, I didn't see this. I'll add a `Fixes X` to the PR.
