### ISSUE TITLE
StateTax: Should be migrated to Spice, use API

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#960]
After some internal discussion, we decided that using a Goodie for this kind of Instant Answer, which deals with information that is likely to change somewhat regularly, was the wrong choice.

Right now we don't have a good way to ensure this Goodie is reliable and always provides up-to-date, accurate info (the taxes could change tomorrow and we'd have to scramble to get this up to date).

After a quick check I found there is a free API we can use for this info, which also supports Canada, and can even trigger on addresses (rather than just a state).

http://taxratesapi.avalara.com/docs

Let's migrate this IA to Spice ASAP!

/cc @jagtalon @javathunderman

**Comment by javathunderman** [comment]
@moollaza Sounds good. I was a little hesitant on using Spice (mainly because this is my first time with Perl, and because I couldn't find an API) initially, but I'll see what I can do.

**Comment by moollaza** [comment]
Sounds good!

**Comment by javathunderman** [comment]
Also pinging @MrChrisW and @mintsoft.

**Comment by MrChrisW** [comment]
@moollaza Agreed! This would go well as a Spice :+1: Happy to review again @javathunderman :smile:

**Comment by javathunderman** [comment]
One other thing: I forgot to account for sales tax on a per county basis as well. Does this API give the maximum state rate with local taxes added?

**Comment by MrChrisW** [comment]
Fixed and merged in [#1474](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1474)

**Comment by javathunderman** [comment]
Nice job. Thanks @MrChrisW !

**Comment by MrChrisW** [comment]
@javathunderman No problem! Will be great to see it live :+1:
