### ISSUE TITLE
TimeZoneConverter: Add support for "1600 GMT"

### ISSUE THREAD

**Issue by jkanarek** [duckduckgo/zeroclickinfo-goodies#975]
Without the colon between 16 and 00, this IA should still work. Currently the colon is required.

**Comment by mintsoft** [comment]
@jkanarek I presume this is for the TimezoneConverter Goodie?

**Comment by moollaza** [comment]
@mintsoft seems like it!

**Comment by mintsoft** [comment]
Fixed by @samph in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/988
