### ISSUE TITLE
Minecraft: Implement Design Updates

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#977]
As per @abeyang's comment here:

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/697#issuecomment-70287313

The following needs to be done:
- align image to the right rail, so that it matches with the SERP content
- align image to the top, so it matches to the title text
- move Ingredients into the subtitle (right below title)
- mockup's gutter is too wide -- we'll need to tighten that
- switch to standard template classe:
    - title should be `zci__header`
    - description should be `zci__content`

Result should look like this:

![998dd9a8-9d5f-11e4-9986-cee76242a622](https://cloud.githubusercontent.com/assets/873785/6013306/d4816fba-ab20-11e4-9f9e-09d048d7dbb0.jpg)

**Comment by mintsoft** [comment]
@larseng are you interested in doing this? If not one of us can pick it up :)

**Comment by larseng** [comment]
Not really my favorite part of writing code, so is someone else wants to do it, please, go ahead :smile:

**Comment by jagtalon** [comment]
This is my bad--I said I would do it. :) I'll make a PR soon so that this can be deployed! Sorry for the delay

**Comment by moollaza** [comment]
@jagtalon no need for you to do this, we can leave it to the community :+1:

**Comment by jagtalon** [comment]
Looks like there's no need since you moved it to a template https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1064 :+1:
