### ISSUE TITLE
Abandoned PRs: You can rescue an Instant Answer!

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#980]
Sadly there are some PR's out in the wild which have been _abandoned_ :cry: .We've been closing them and marking them with the "Abandoned" label so others can find them.

This task is here to remind the community that they're welcome to look through our (hopefully shrinking) list of Abandoned PRs, and finish up any that they'd like to.

Many of them are only a few commits away from being merged! You can find the abandoned Goodie PRs here: https://github.com/duckduckgo/zeroclickinfo-goodies/issues?q=label%3AAbandoned

**Comment by jarifibrahim** [comment]
@moollaza This issue has been resolved. There are no more `Abandoned` PRs.
