### ISSUE TITLE
PhoneAlphabet: Should also trigger on "to numbers"

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#990]
https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/PhoneAlphabet.pm#L19

Works: https://duckduckgo.com/?q=1-800-GOT-JUNK+to+digits&ia=answer
Should work: https://duckduckgo.com/?q=1-800-GOT-JUNK+to+numbers&ia=answer

**Comment by MrChrisW** [comment]
Fixed by @samph in #991
