### ISSUE TITLE
Revive Old IA Branches

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-goodies#998]
https://github.com/duckduckgo/zeroclickinfo-goodies/branches/stale

Previously we have pushed the "abandoned" PRs to a branch for others to work off of and they've been sitting there for a while now untouched.

Most of the branchs [here](https://github.com/duckduckgo/zeroclickinfo-goodies/branches/stale) have Goodies that are nearly complete but in many cases need to be updated to meet the current Goodie practices (using Structured Answers)

If you're interested in picking up some of these IA's feel free to let us know and submit a PR :smile:

**Comment by killerfish** [comment]
I believe countrycodes and callingcodes are using structured answers, so we can skip those.

**Comment by moollaza** [comment]
@killerfish good point! I removed those branches :)
